### ISSUE TITLE
Missing Feature : No Support for Default Compiler Flags in Compiler Config

### ISSUE THREAD

**Issue by xjrc** [LLNL/spack#1006]
After looking over PR #360 and its documentation in PR #989 more carefully, I found that the intended feature for specifying compiler flags in the `compilers.yaml` file is missing.  I was able to verify this by having something like the following in my `compilers.yaml` file:

```
compilers:
  chaos_5_x86_64_ib:
    gcc@4.7.2:
      ...
      cflags: -fPIC
      cppflags: -fPIC
      cxxflags: -fPIC
```

This inclusion caused an 'additional properties are not allowed ('cppflags', 'cxxflags', 'cflags' were unexpected)' error to occur when I attempted to install packages with this compiler.
