### ISSUE TITLE
spack reindex : breaks information on explicit

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#1050]
Reproducible by : 
```
$ spack install m4
```
At this point the file `opt/spack/.spack-db/index.yaml` looks like : 
```yaml
database:
  installs:
    ev7o3dbqvwzojhesg3bvv5rv4oy27nzk:
      explicit: false
      installed: true
      path: /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-4.8/libsigsegv-2.10-ev7o3dbqvwzojhesg3bvv5rv4oy27nzk
      ref_count: 1
      spec:
        libsigsegv:
          arch: linux-x86_64
          compiler:
            name: gcc
            version: '4.8'
          dependencies: {}
          namespace: builtin
          parameters:
            cflags: []
            cppflags: []
            cxxflags: []
            fflags: []
            ldflags: []
            ldlibs: []
          version: '2.10'
    iubkayqswvtjdvnzc2xgs7lphsuybetv:
      explicit: true
      installed: true
      path: /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-4.8/m4-1.4.17-iubkayqswvtjdvnzc2xgs7lphsuybetv
      ref_count: 0
      spec:
        m4:
          arch: linux-x86_64
          compiler:
            name: gcc
            version: '4.8'
          dependencies:
            libsigsegv: ev7o3dbqvwzojhesg3bvv5rv4oy27nzk
          namespace: builtin
          parameters:
            cflags: []
            cppflags: []
            cxxflags: []
            fflags: []
            ldflags: []
            ldlibs: []
            sigsegv: true
          version: 1.4.17
  version: 0.9.1
```
After giving : 
```
$ spack reindex
```
everything is set to `explicit=false` : 
```yaml
database:
  installs:
    ev7o3dbqvwzojhesg3bvv5rv4oy27nzk:
      explicit: false
      installed: true
      path: /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-4.8/libsigsegv-2.10-ev7o3dbqvwzojhesg3bvv5rv4oy27nzk
      ref_count: 1
      spec:
        libsigsegv:
          arch: linux-x86_64
          compiler:
            name: gcc
            version: '4.8'
          dependencies: {}
          namespace: builtin
          parameters:
            cflags: &id001 []
            cppflags: &id002 []
            cxxflags: &id003 []
            fflags: &id004 []
            ldflags: &id005 []
            ldlibs: &id006 []
          version: '2.10'
    iubkayqswvtjdvnzc2xgs7lphsuybetv:
      explicit: false
      installed: true
      path: /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-4.8/m4-1.4.17-iubkayqswvtjdvnzc2xgs7lphsuybetv
      ref_count: 0
      spec:
        m4:
          arch: linux-x86_64
          compiler:
            name: gcc
            version: '4.8'
          dependencies:
            libsigsegv: ev7o3dbqvwzojhesg3bvv5rv4oy27nzk
          namespace: builtin
          parameters:
            cflags: *id001
            cppflags: *id002
            cxxflags: *id003
            fflags: *id004
            ldflags: *id005
            ldlibs: *id006
            sigsegv: true
          version: 1.4.17
  version: 0.9.1
```
