### ISSUE TITLE
[proposal]: Add custom paths/settings to environment modules

### ISSUE THREAD

**Issue by mwilliammyers** [LLNL/spack#1109]
I think you can already add custom paths eg. export `PYTHONHOME` to a generated environment module using [this](http://software.llnl.gov/spack/basic_usage.html#override-package-api) method in `package.py` but it would be nice to be able to not have to modify the `package.py` file or override it with another local package.

I am thinking something like this for the `modules.yaml` config:
```yaml
modules:
  ...
  jdk:
    set_env:
      - JAVA_HOME: $prefix
  foo:
    prepend_path:
      - BAR: $prefix.lib
    append_path:
      - BAZ: $prefix.include
```
Where you can reference any of the prefix attribute variables listed [here](http://software.llnl.gov/spack/packaging_guide.html#id12).

**Comment by tgamblin** [comment]
I like it!

**Comment by alalazo** [comment]
Can I suggest : 
```yaml
modules:
  ...
  jdk:
    set_env:
      - JAVA_HOME: {prefix}
  foo:
    prepend_path:
      - BAR: {prefix.lib}
    append_path:
      - BAZ: {prefix.include}
```
in that way you may use python string formatting capabilities out of the box :smile:

**Comment by alalazo** [comment]
@mwilliammyers I have received a bunch of user feedback for our modules and I'll need to generate something like what you propose, with the only difference that I'll need to permit some token expansion also on the keys, e.g. : 
```yaml
modules:
    prefix_inspections:
      '':
      - '{name}_ROOT'
    tcl:
      all:
        environment:
          set:
            '{name}_FOO': '{ver}'
```
Did you start already working on this? In case, would it make sense to you to work together in #1135 ? @tgamblin ?
