### ISSUE TITLE
Don't use /tmp for staging

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1161]
I have encountered many HPC systems where the `/tmp` directory is not large enough to hold a complete build tree. I then have to manually create symbolic links to work around this. On many HPC systems there are multiple front ends, and when I log in the next time, I might end up on a different login node, and I then have to create another symbolic link.

I think Spack should, by default, use `var/spack` directly as staging directory, and not use `/tmp`.

Also, there should be a configuration mechanism to choose this on a per-system basis, similar to the default value for `make -jN`. Spack should also have the "right" settings built in for "the usual systems", i.e. the commonly used HPC systems available to open research.

**Comment by davydden** [comment]
see https://github.com/LLNL/spack/issues/1137#issuecomment-229290024

**Comment by alalazo** [comment]
This is now configurable through `config.yaml`:
```yaml
config:
  # Temporary locations Spack can try to use for builds.
  #
  # Spack will use the first one it finds that exists and is writable.
  # You can use $tempdir to refer to the system default temp directory
  # (as returned by tempfile.gettempdir()).
  #
  # A value of $spack/var/spack/stage indicates that Spack should run
  # builds directly inside its install directory without staging them in
  # temporary space.
  #
  # The build stage can be purged with `spack purge --stage`.
  build_stage:
    - $tempdir
    - /nfs/tmp2/$user
    - $spack/var/spack/stage

```
