### ISSUE TITLE
There is no option to specify preferred variants.

### ISSUE THREAD

**Issue by paulhopkins** [LLNL/spack#1196]
The manual states that preferred variants can be added to the packages.yaml file:

http://software.llnl.gov/spack/configuration.html#concretization-preferences
> Spack can be configured to prefer certain compilers, package versions, depends_on, and **variants** during concretization. 

but later on it says the only options are "compiler, version, or providers", and there is no mention of variants in the config schema for packages.

I propose that users may select preferred variants to be used either for direct or indirect installation using the following example:

```
packages:
  python:
    variants: ['+ucs4']
  octave:
    variants: ['+fftw', '+curl', '+qt']
```

These preferences are only used if they do not conflict with a variant required by the dependency tree, or specified by the user.
