### ISSUE TITLE
discourage setting external packages to /usr

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1224]
I think Spack should produce a warning (or forbid?) setting external packages to `/usr` and alike as this can easily break other packages.

I was building `petsc+mpi%gcc` on macOS. Since `python` currently fails to build with `gcc` on macOS I tried to use system's python via
```
  python:
    version: [2.7.10]
    paths:
      python@2.7.10: /usr
    buildable: False
```
This however lead to some cryptic errors during `configure` stage of `petsc` with `C++ error! MPI_Finalize() could not be located!`. I am not sure what was a problem (petsc's `configure.log` is not easy to read), I can only speculate that bringing `/usr/bin` in path (from external package) confused `petsc` with system's `cc` and somehow made Spack's `openmpi` nonfunctional. In this particular instance a workaround was to install `petsc%gcc` with `^python%clang`.
