### ISSUE TITLE
Cannot choose Atlas to provide BLAS

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1375]
This fails:

```
$ spack install py-numpy %clang@7.3.0-apple ^atlas
==> Error: py-numpy does not depend on atlas
```

`py-numpy` depends on both `blas` and `lapack`, thus choosing `atlas` to provide these should work.

**Comment by tgamblin** [comment]
Workaround: `spack install py-numpy %clang@7.30-apple +blas +lapack ^atlas`

We're working on making the concretizer smarter.

**Comment by adamjstewart** [comment]
By the way, if you want to always build with Atlas, you can do the following. Run `spack config edit packages` and add:
```
packages:
  all:
    providers:
      blas: [atlas]
      lapack: [atlas]
```
This changes the default to be Atlas.
