### ISSUE TITLE
packages.yaml ValueError: openmpi@1.10.3%gcc@6.1.1 is not in list

### ISSUE THREAD

**Issue by Exteris** [LLNL/spack#1411]
Hi,

I'm trying to use the system-wide version of openmpi, using a packages.yaml file such as:

``` yaml
packages:
  openmpi:
    paths:
      openmpi@1.10.3%gcc@6.1.1: /usr
    buildable: False
```

or

``` yaml
packages:
  openmpi:
    paths:
      openmpi@1.10.3%gcc@6.1.1  arch=linux--x86_64: /usr
    buildable: False
```

but I get a ValueError. Is this related to wrong detection of my system name, and can I override this detection somehow?
