### ISSUE TITLE
Installation issue: diffutils

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#16162]
* This failure seems to be related to a new virtual dependency, _iconv_
  * The dependency was changed on March 28, 2020 in PR #15437 by @iarspider 
* Previously, _diffutils_ linked to _libiconv_ directly.
* Possibly the same issue as #16035

### Steps to reproduce the issue

```console
$ spack spec diffutils % gcc@4.8.5

Concretized
--------------------------------
==> Error: Package 'iconv' not found.
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.14.2-710-f973305
* **Python:** 2.7.5
* **Platform:** linux-rhel7-sandybridge
```

* No maintainer listed.
* No build logs, fails at spec

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files --> NA
- [x] I have searched the issues of this repo and believe this is not a duplicate --> Maybe the same as #16035

**Comment by adamjstewart** [comment]
Weird, I'm not able to reproduce this issue. What does `spack providers iconv` return for you?

**Comment by KineticTheory** [comment]
> Weird, I'm not able to reproduce this issue. What does `spack providers iconv` return for you?

```console
% spack providers iconv
==> Error: non-virtual specs cannot be part of the query [iconv]
Virtual packages:
    D     elf       glx     jpeg            mpe           pil        szip
    awk   fftw-api  golang  lapack          mpi           pkgconfig  tbb
    blas  gl        ipp     mariadb-client  mysql-client  scalapack  unwind
    daal  glu       java    mkl             opencl        sycl
```

* `$SPACK_ROOT/etc/spack/defaults/packages.yaml` has `iconv: [libiconv]` under `all: providers:`
* I've also deleted `$HOME/.spack` to make sure that doesn't cause issues. I have no custom config files in `$SPACK_ROOT/etc/spack` except for `compilers.yaml`.

```yaml
compilers:
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: rhel7
    target: x86_64
    modules: []
    environment:
      unset: []
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8.5
```
