### ISSUE TITLE
'install_missing_compilers' Detected uninstalled dependency error

### ISSUE THREAD

**Issue by nicholas-sly** [LLNL/spack#16244]
Spack errors on 'detected uninstalled dependency' error when trying to reinstall a stack where an external package was registered as having been built with a given compiler and the `package.py` file for that compiler changed since the previous build.

### Steps to reproduce the issue
1. Specify a dependency of a package to use an external package (e.g. Slurm or pkg-config%pgi).
2. Install a stack the installs the compiler as well as a dependency of the above external package.
3. Uninstall all packages from the stack
4. Modify the compiler's `package.py` file
5. Reinstall the stack

### Example Error Message
```
==> Error: Detected uninstalled dependencies for pkg-config: {'pgi'}
==> Error: Cannot proceed with pkg-config: 1 uninstalled dependency: pgi
```

### Information on your system

```
-bash-4.2$ spack debug report
* **Spack:** 0.14.2-700-395e91d
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
```

Example external package specifications used.
```
    slurm:
      paths:
        slurm@19.05.5: /usr
      buildable: false
      version: []
      target: []
      compiler: []
      modules: {}
      providers: {}
    pkg-config:
      paths:
        pkg-config@0.27.1.system%pgi@19.10: /usr/bin
      buildable: true
      version: []
      target: []
      compiler: []
      modules: {}
      providers: {}
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output
