### ISSUE TITLE
Installation issue: py-plotly should not fix all versions of dependencies

### ISSUE THREAD

**Issue by omsai** [LLNL/spack#16544]
### Steps to reproduce the issue

The plotly package incorrectly uses one and only one version of it's dependencies specified in upstream's requirements.txt instead of specifying a minimum version like upstream's setup.py:
https://github.com/plotly/plotly.py/blob/v2.2.0/setup.py#L49

This is is introducing a circular dependency in my trying to use a fewer version of py-deeptools@3.4.1 which has a bugfix my labmate needs.  I can't install a newer version of py-requests because py-plotly use a conflicting

```console
$ spack spec py-deeptools
Input spec
--------------------------------
py-deeptools

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    py-requests@2.5.0:
        ^py-setuptools@24.3:
            ^python@2.7:2.8,3.5:
                ^pkgconfig@0.9.0:


while trying to concretize the partial spec:

    py-plotly@2.0.0:
        ^py-setuptools@24.3:
            ^python@2.7:2.8,3.5:
                ^pkgconfig@0.9.0:


py-plotly requires py-requests version 2.3.0, but spec asked for 2.5.0:
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.14.2
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-zen
```

```yaml
# /etc/spack/packages.yaml 
packages:
  all:
    permissions:
      write: group
      group: users
  r:
    paths:
      r@3.6.1: /usr/bin
    buildable: false
  # py-deeptools:
  #   providers:
  #     'python@3'
```

```yaml
# /etc/spack/repos.yaml 
repos:
- /var/spack/repos/corelab
- $spack/var/spack/repos/builtin
```

```yaml
# /etc/spack/mirrors.yaml 
mirrors:
  local: file:///var/spack/mirror
```

```console
$ tree -F /var/spack/mirror/
/var/spack/mirror/
├── jdk/
│   ├── jdk-11.0.4_10.tar.gz -> jdk-11.0.4_linux-x64_bin.tar.gz
│   └── jdk-11.0.4_linux-x64_bin.tar.gz
└── trf/
    └── trf409.linux64

2 directories, 3 files
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
