### ISSUE TITLE
Unable to install curl@7.50.1%intel@16.0.3 via spack

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#1669]
I'm looking for advice on how to debug this issue.  Spack fails to build curl@7.50.1 with intel@16.0.3 for me:

```
$ spack install --dirty curl
...
==> Building curl
==> Error: Command exited with status 2:
See build log for details:
  /tmp/$USER/spack-stage/spack-stage-FuILeT/curl-7.50.1/spack-build.out

$SPACK_ROOT/var/spack/repos/builtin/packages/curl/package.py:52, in install:
     47       def install(self, spec, prefix):
     48           configure('--prefix=%s' % prefix,
     49                     '--with-zlib=%s' % spec['zlib'].prefix,
     50                     '--with-ssl=%s' % spec['openssl'].prefix)
     51   
  >> 52           make()
     53           make("install")
$ cat /tmp/$USER/spack-stage/spack-stage-FuILeT/curl-7.50.1/spack-build.out
...
  CCLD     curl
icc: error #10236: File not found:  '../lib/.libs/libcurl.so'
$ ls -l lib/.libs/libcurl.so*
lib/.libs/libcurl.so -> libcurl.so.4.4.0
# libcurl.so.4.4.0 is missing
```

However, I can configure and build curl w/o issue if I do so outside of spack:

```
$ head -n 1 /tmp/$USER/spack-stage/spack-stage-FuILeT/curl-7.50.1/spack-build.out # find the configure command and use it below
$ cd /scratch; tar -xvf $SPACK_MIRROR/curl/curl-7.50.1.tar.bz2
$ cd curl-7.50.1
$ ./configure '--prefix=$SPACK_ROOT/opt/spack/linux-redhat6-x86_64/intel-16.0.3/curl-7.50.1-rouubmwgpgtod6zsmlcnhdfwsflmdlek' '--with-zlib=$SPACK_ROOT/opt/spack/linux-redhat6-x86_64/intel-16.0.3/zlib-1.2.8-j27etskpawg5lrge6wovazubcsgk4jba' '--with-ssl=$SPACK_ROOT/opt/spack/linux-redhat6-x86_64/intel-16.0.3/openssl-1.0.2h-a5obyxw6ju5vq5qpb3vunuz6sgm2anob'
$ make -j 12
$  ls -l lib/.libs/libcurl.so*
lib/.libs/libcurl.so -> libcurl.so.4.4.0*
lib/.libs/libcurl.so.4 -> libcurl.so.4.4.0*
lib/.libs/libcurl.so.4.4.0*
```

How do I debug this spack failure?

**Comment by tgamblin** [comment]
Is the external build using icc?  Did you see if the Spack build works for gcc?

**Comment by KineticTheory** [comment]
The external build is using icc (`$CC` is set to the full path of icc and there are compile warnings about deprecated flags that are issued from icc).  `spack install curl%gcc@4.4.7` works w/o issue.

**Comment by KineticTheory** [comment]
I'm seeing these same errors with other packages that build with autotools (libtool, curl, netcdf). The failure is always about a missing library in the `.libs` directory where a bad symlinks exist.

All of these builds worked with an older version of spack.  @tgamblin mentioned in #638 that spack should now be able to build NetCDF with Intel compilers.  Maybe there was update in that set of changes to is breaking my builds. Thoughts?

Additionally, these tools build fine outside of spack with Intel.  They also work when I use the GNU compilers from within spack.

**Comment by tgamblin** [comment]
Do you know which version used to work?

**Comment by KineticTheory** [comment]
* `curl@7.46.0%intel@16.0.3` still works on our Toss2 machines.
* `spack install --dirty curl@7.47.1%intel@15.0.5` works but `spack install -v --dirty curl@7.47.1%intel@16.0.3` fails. Maybe there is something wrong with the intel@16.0.3 environment (via modulefile) on our Toss2 machines.

**Comment by lee218llnl** [comment]
@KineticTheory FWIW, it builds OK here at LLNL on a TOSS 2 system. We do have some local config files for the compilers, though, that add rpaths, which may be part of the difference. Can you attach your spack-build.out? I can compare it to mine.

**Comment by KineticTheory** [comment]
@lee218llnl As it turns, out I'm getting the same error for libtool and I have attached the log files for this package.  

I was thinking that the build error for curl might be caused by using older versions of the autotools and I hacked in a 'build' dependency in curl/package.yml to pick up spack provided libtool. This is when I found that libtools (and a few other packages are failing in an identical way).

[spack-build.out.txt](https://github.com/LLNL/spack/files/453536/spack-build.out.txt)
[spack-build.env.txt](https://github.com/LLNL/spack/files/453537/spack-build.env.txt)

**Comment by lee218llnl** [comment]
I did a diff of your build and mine. Yours is failing to build libtool and one thing that stands out in the configure output of your build is:

checking if the linker (/yellow/usr/projects/draco/vendors/spack.ml.20160829/lib/spack/env/ld) is GNU ld... no

versus mine:

checking if the linker (/nfs/tmp2/lee218/spack/lib/spack/env/ld) is GNU ld... yes

I'm not sure if this is the root cause, but do you have ld wrappers for the Intel 16 compiler that you don't have for the 15 compiler?

Also, I don't see the build commands being executed in your output file. Here's what I see in mine:

config.status: executing depfiles commands
config.status: executing libtool commands
==> 'make' '-j32'
  GEN      libtoolize
make  all-recursive
make[1]: Entering directory `/tmp/lee218/spack-stage/spack-stage-ZB40cc/libtool-2.4.6'
Making all in .
make[2]: Entering directory `/tmp/lee218/spack-stage/spack-stage-ZB40cc/libtool-2.4.6'
  CC       libltdl/lt__strl.lo
  CC       libltdl/loaders/libltdl_libltdl_la-preopen.lo
  CC       libltdl/loaders/dlopen.lo
  CC       libltdl/libltdl_libltdl_la-lt__alloc.lo
  CC       libltdl/libltdl_libltdl_la-lt_dlloader.lo
  CC       libltdl/libltdl_libltdl_la-slist.lo
  CC       libltdl/libltdl_libltdl_la-lt_error.lo
  CC       libltdl/libltdl_libltdl_la-ltdl.lo
  CCLD     libltdl/dlopen.la
  CCLD     libltdl/libltdl.la
make[2]: Leaving directory `/tmp/lee218/spack-stage/spack-stage-ZB40cc/libtool-2.4.6'
make[1]: Leaving directory `/tmp/lee218/spack-stage/spack-stage-ZB40cc/libtool-2.4.6'
==> 'make' '-j32' 'install'

**Comment by KineticTheory** [comment]
@lee218llnl There are no wrappers for ld on this machine.  In fact if I run configure in the staging directory (outside of spack), I see:

```
checking for ld used by /usr/projects/hpcsoft/toss2/common/intel-clusterstudio/2016.3.067/compilers_and_libraries_2016/linux/bin/intel64/icc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
```

Here's a copy of spack-build.out from today's attempt (fresh git clone of spack):
[spack-build.out.txt](https://github.com/LLNL/spack/files/462834/spack-build.out.txt)
I'm not sure why there would be missing commands from the previous file.

**Comment by KineticTheory** [comment]
@lee218llnl I think I just found the problem. My `compilers.yaml` has this entry:

```
- compiler:
    modules:
      - intel/16.0.3
    operating_system: redhat6
    paths:
      cc: /yellow/usr/projects/hpcsoft/toss2/common/intel-clusterstudio/2016.3.067/compilers_and_libraries_2016/linux/bin/intel64/icc
      cxx: /yellow/usr/projects/hpcsoft/toss2/common/intel-clusterstudio/2016.3.067/compilers_and_libraries_2016/linux/bin/intel64/icpc
      f77: /yellow/usr/projects/hpcsoft/toss2/common/intel-clusterstudio/2016.3.067/compilers_and_libraries_2016/linux/bin/intel64/ifort
      fc: /yellow/usr/projects/hpcsoft/toss2/common/intel-clusterstudio/2016.3.067/compilers_and_libraries_2016/linux/bin/intel64/ifort
    ldflags: -Wl,-rpath,/usr/projects/hpcsoft/toss2/common/intel-clusterstudio/2016.3.067/compilers_and_libraries_2016/linux/lib/intel64
    spec: intel@16.0.3
```

I don't remember exactly why I added the `ldflags` option, but commenting this line out allows libtool to build. I'm going to start rebuilding my vendor stack to remind myself why the `ldflags` entry was needed (if at all). I think this has something to do with missing rpaths and the use of `--dirty` to allow intel/16.0.3 to work with MPI compile wrappers (ones that need `CXX=mpicxx`).
