### ISSUE TITLE
Add ability to toggle default state of Buildable

### ISSUE THREAD

**Issue by white238** [LLNL/spack#16734]
Add ability to change the default state of Buildable to False instead of True.

### Rationale

Unless you are careful and lock down your dependencies, Spack builds far too many packages (perl, tar, etc).  Users who are unfamiliar with the problem often waste hours thinking that a 2 hour library build is normal when it should be < 10 minutes. It would be nice to be able to provide a list of packages I want Spack to build instead of the opposite which is turning off the ones I don't want it to build.

### Description

```
packages:
   all:
    buildable: False
  axom:
    buildable: True
  conduit:
    buildable: True

```
