### ISSUE TITLE
build dependencies are loading in environment module files

### ISSUE THREAD

**Issue by glennpj** [LLNL/spack#1681]
I have the following in my `modules.yaml` file:
```
modules:
  tcl:
    naming_scheme: '{name}/{version}-{compiler.name}-{compiler.version}'
    all:
      autoload: 'direct'
```
When loading a module all `build` dependencies are loaded as well. This is not a huge issue but I think the desired behavior is to _not_ load build-only dependencies.
