### ISSUE TITLE
"exclude" semantic bug with non-boolean variants in spec matrices

### ISSUE THREAD

**Issue by raovgarimella** [LLNL/spack#16841]
I tried to create a spec matrix for testing variants of a package and excluding some incompatible variant combinations. Unfortunately, it did not work.

### Steps to reproduce the issue

I created a ```spec.yaml``` file in a new directory

```
spack:
  # add package specs to the `specs` list
  specs:
    - matrix:
       - [mstk]
       - [+parallel]
       - [partitioner=none, partitoner=all, partitioner=zoltan, partitioner=metis]
      exclude:
       - '+parallel partitioner=none'
  view: False
```
and ran
```spack concretize -f```

### Error Message

I was expecting the following options to be concretized
```
mstk+parallel partitioner=all
mstk+parallel partitioner=zoltan
mstk+parallel partitioner=metis
```
Instead, spack did not exclude the ```+parallel partitioner=none``` option and tried to concretize it which naturally resulted in a conflict and an error

### Information on your system
* **Spack:** 0.14.2-1252-2fa5a05dc
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-skylake

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output
