### ISSUE TITLE
Provide an Ansible Spack module

### ISSUE THREAD

**Issue by aphecetche** [LLNL/spack#16843]
Would love to see an Ansible module that would let me install packages with Spack

### Rationale

To install my dev machines (mainly laptops and virtual vms) I've setup years ago some Ansible playbooks. So far the packages I'm installing that way are done with either the specific platform package managers (e.g. brew on Mac, apt on ubuntu, etc...) leading to a lot of distribution specific yml files or from source with "custom" recipes. Would be better to leverage Spack power here.

### Description

Typical usage would be to replace things like : 

```
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - curl
    - bzip2
```
by : 

```
- name: install required packages
  spack:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - curl
    - bzip2
```

### Additional information

While an Ansible module is not strictly required (I'm currently setting up a custom role instead) it would be much more convenient.  

### General information

- [X] I have run `spack --version` and reported the version of Spack
~/github.com/aphecetche/ansible [asdf-to-spack] $ spack --version
0.14.2
- [X] I have searched the issues of this repo and believe this is not a duplicate
have searched also more widely for "ansible spack module" (and first mainly got hits concerning ... Spark ;-) )
