### ISSUE TITLE
Broken Compatibility with Cray CN16 Systems

### ISSUE THREAD

**Issue by rspavel** [LLNL/spack#17123]
Identified issues with semi-recent (post spack v0.14.2) changes to how spack detects compilers and environment variables on Cray XC40 machines running CN16 . Specifically tested on LANL's Trinitite and Trinity with NERSC's Cori (CN17) used as a control. Regardless of spec and compilers.yaml, Spack maps Cray's compiler wrappers to the system compiler of ```gcc@4.8.5``` 

### Steps to reproduce the issue

```console
$ spack compiler find
$  spack install comd~mpi%gcc@9.2.0
```

### Error Message

On XC40 with haswell+knl compute nodes running CN16  (Trinitite)
```console
$ spack compiler find
$  spack install comd~mpi%gcc@9.2.0
==> 19586: Installing comd
(...)
  >> 114    cmdLineParser.c:1:0: error: bad value (haswell) for -mtune= switch
  >> 115    mycommand.c:1:0: error: bad value (haswell) for -march= switch
```

And On XC40 with haswell+knl compute nodes running CN17 (Cori) installation succeeds

### Information on your system

Error manifests with 

```
 spack debug report
* **Spack:** 0.14.2-1312-3347ef2de
* **Python:** 3.4.10
* **Platform:** cray-sles12-haswell
```

Able to have successful building (barring usual issues with cray platforms) using release ```v0.14.2``` under which debug does not have a report command. Have not further bisected commits in interim yet.

### Additional information

- [x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Can you post your `compilers.yaml` (probably in `~/.spack/cray/`)?

The most recent change to how Spack handles Cray was #16593. Maybe you can try reverting that commit locally and see if it solves the issue for you? @becker33 may want to take a look at this issue.

**Comment by rspavel** [comment]
```compilers.yaml``` generated on ```3347ef2de4e08374750eb68f750800c1854d595f```

```
compilers:
- compiler:
    extra_rpaths: []
    environment:
      unset: []
    modules:
    - PrgEnv-intel
    - intel/15.0.5
    target: any
    flags: {}
    spec: intel@15.0.5
    operating_system: cnl6
    paths:
      f77: ftn
      fc: ftn
      cxx: CC
      cc: cc
...
- compiler:
    extra_rpaths: []
    environment: {}
    modules:
    - PrgEnv-gnu
    - gcc/9.2.0
    target: any
    flags: {}
    spec: gcc@9.2.0
    operating_system: cnl6
    paths:
      f77: ftn
      fc: ftn
      cxx: CC
      cc: cc
```

And generated with ```7a68a4d8513cd6105ee21bedfe04664c292d1e7d``` (tag ```v0.14.2```)

```
compilers:
- compiler:
    spec: gcc@4.9.3
    operating_system: cnl6
    extra_rpaths: []
    environment:
      unset: []
    target: any
    flags: {}
    paths:
      f77: ftn
      fc: ftn
      cxx: CC
      cc: cc
    modules:
    - PrgEnv-gnu
    - gcc/4.9.3
...
- compiler:
    spec: gcc@9.2.0
    operating_system: cnl6
    extra_rpaths: []
    environment: {}
    target: any
    flags: {}
    paths:
      f77: ftn
      fc: ftn
      cxx: CC
      cc: cc
    modules:
    - PrgEnv-gnu
    - gcc/9.2.0
```


And it looks like the version of spack I had pulled on trinitite predates that PR but verified same behavior with latest HEAD of ```eb5f1886b78a2b79c9fb5748addaad69c1a56591```
