### ISSUE TITLE
Pipelines: Allow users to provide their own scripts

### ISSUE THREAD

**Issue by scottwittenburg** [LLNL/spack#17164]
Many users attempting to leverage the `spack ci` command and auto-generated pipelines have asked for ways to customize the generated build jobs.  This proposal aims to satisfy that goal, and to solve the issue #17119 aimed to solve (unsuccessfully).  Therefore this proposal supersedes #17119.

At a high level, the proposal is for `spack ci generate` to stop generating any `before_script` or `after_script`, and only generate a `script` if the user didn't provide one.  Users will be able to provide their own versions of these fields via the `gitlab-ci` section in the `spack.yaml`.  If users want to supply their own `script`, they just need to be sure it arranges to be sitting at the root of the environment repository when it runs, and that at some point it calls `spack ci rebuild`.  If users do not supply their own `script`, then the following will be generated for them:

```
    script:
        - spack ci rebuild
```

### Rationale

The `spack ci` command only provided `before_script` and `after_script` for one purpose, to assist users in obtaining the version of spack they desired their ci rebuild jobs to use.  Due to the dynamic nature of pipeline generation, this required users to: 

1. provide CI environment variables identifying the spack repository and version (branch, tag, SHA), 
1. use those variables to clone spack, e.g. in the `before_script` of the pipeline generation job,
1. pass those variables along to `spack ci generate` using the `--spack-repo` and `--spack-ref` command line arguments

at which point, spack would then generate jobs with a `before_script` which fixed the location of the cloned spack at the root of the environment repository.  To make this concrete, here's an example pipeline generation job which depends on a custom spack version.  The variables `SPACK_REPO` and `SPACK_REF` could be provided by the user via the CI variables interface in gitlab, or passed in via an upstream pipeline trigger, etc:

```yaml
generate-pipeline:
  stage: generate
  before_script:
    - git clone ${SPACK_REPO} --branch ${SPACK_REF}
    - . "./spack/share/spack/setup-env.sh"
  script:
    - spack -d ci generate
      --spack-repo ${SPACK_REPO}
      --spack-ref ${SPACK_REF}
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  after_script:
    - rm -rf "./spack"
```

Having this logic and responsibility spread across two locations has caused both confusion and problems for users attempting to deploy auto-generated pipelines at their sites.  Also, it has always felt a little unsavory to be locked into this somewhat opaque and inflexibly generated `before_script` and `after_script`.

A specific problem this has caused is at sites where a custom version of spack is needed to run pipelines, but forcing every generated build job to begin by cloning that same version of spack (a large project with a lot of history) simply overwhelms the filesystem (see #17119).  In this scenario, it would be desirable to clone spack once at the beginning of the pipeline (pipeline generation would be a good place for this) and then have all the jobs re-use that cloned spack.  Giving users compete control over scripts in both generation and build jobs supports this goal.

Obviously cloning spack once at the beginning of the pipeline isn't feasible when the runners are kubernetes executor runners and do not have access to a shared file system, and in that case, some other approach to getting access to the right version of spack is required (i.e. every build job must begin with cloning the same version of spack).  User-provided scripts in generation and build jobs supports this use case as well.

### Description

Here we provide just a single concrete example of how you could set up a build pipeline with user-provided scripts.  In this example, the spack environment repo contains three files, `.gitlab-ci.yml`, `spack.yaml`, and `checkFirstClone.sh`, a shell script for cloning and activating spack.

The `spack.yaml` describes the environment to build, as usual.  But now the `gitlab-ci` section contains extra fields specifying the `before_script`, and `script` to be used.

```yaml
stages: [generate, build]

generate-pipeline:
  stage: generate
  before_script:
    - ./checkFirstClone.sh
  script:
    - spack -d ci generate
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  tags: ["my-runner-tag"]

build-jobs:
  stage: build
  trigger:
    include:
      - artifact: "jobs_scratch_dir/pipeline.yml"
        job: generate-pipeline
    strategy: depend
```

Not much new above, but note that `--spack-repo` and `spack-ref` are no longer passed to the `spack ci generate` command.  The `checkFirstClone.sh` shell script looks like this:

```bash
#!/bin/bash

if [ -d "./spack" ]; then
  # There's already a spack directory here
  echo "fast path"
  pushd ./spack
  git fetch ${SPACK_REPO} ${SPACK_REF}
  git checkout FETCH_HEAD
  popd
else
  echo "taking the long route"
  git clone ${SPACK_REPO}
  pushd ./spack
  git checkout ${SPACK_REF}
  popd
fi

. "./spack/share/spack/setup-env.sh"

spack --version
```

Obviously some checks for the needed environment variables with appropriate error messages could be nicer in that script, but they've been omitted here for the sake of brevity.  Then the spack environment could be defined as follows:

```yaml
spack:
  specs:
    - zlib%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64
    - bzip2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64
  gitlab-ci:
    mappings:
      - match: ['os=ubuntu18.04']
        runner-attributes:
          tags: ["my-runner-tag"]
          variables:
            SPACK_REPO: $env:SPACK_REPO
            SPACK_REF: $env:SPACK_REF
          before_script:
            - ./checkFirstClone.sh
          script:
            - spack -d ci rebuild
```

Once again, for the sake of clarity, some useful/required fields have been left out of the environment in order to focus on what's important to this discussion.  Recall from the existing implementation that the each `match` specifies its own `runner-attributes`, and now those attributes can include `before_script`, `script`, and (not shown here) `after_script`.  In the above case, the `before_script` simply invokes the same shell script we used in the generation job, and the `script` is customized to pass the `-d` flag to spack to turn on debug output (previously achieved with the `enable-debug-messages` field, which can now be removed from the schema).

### Additional information

One other thing to note is that this proposal includes a small change to the way `variables` are handled in the `gitlab-ci` section.  Previously any `variables` provided here were written verbatim into each job.  With this proposal, we would additionally allow the syntax above (`VAR_NAME: $env:VAR_VALUE`) to cause spack to interpolate `VAR_VALUE` from the environment at pipeline generation time.  This feature can be useful to propagate variables that are provided by, e.g. trigger jobs, which variables wouldn't otherwise be known in the rebuild jobs.

#17129 is a WIP implementation of this proposal.

Also, for interested folks, I can point you to a project on [gitlab.spack.io](https://gitlab.spack.io) where you can see a live example making use of the user-defined pipeline scripts PR mentioned above.
