### ISSUE TITLE
Installation issue: libxc with Intel 2020 compiler

### ISSUE THREAD

**Issue by roguephysicist** [LLNL/spack#17198]
The following error is produced when compiling libxc with the Intel 2020 compilers:

```console
  >> 1270    ": internal error: 010101_3096
     1271    
  >> 1272    icc: error #10014: problem during multi-file optimization compilation (code 4)
  >> 1273    make[4]: *** [libxc.la] Error 4
     1274    make[4]: Leaving directory `/tmp/user/spack-stage/spack-stage-libxc-4.3.2-ewkkgzjlqybyjkqwz3gguft33yoxijah/spack-src/src'
  >> 1275    make[3]: *** [all-recursive] Error 1
     1276    make[3]: Leaving directory `/tmp/user/spack-stage/spack-stage-libxc-4.3.2-ewkkgzjlqybyjkqwz3gguft33yoxijah/spack-src/src'
  >> 1277    make[2]: *** [all] Error 2
     1278    make[2]: Leaving directory `/tmp/user/spack-stage/spack-stage-libxc-4.3.2-ewkkgzjlqybyjkqwz3gguft33yoxijah/spack-src/src'
  >> 1279    make[1]: *** [all-recursive] Error 1
     1280    make[1]: Leaving directory `/tmp/user/spack-stage/spack-stage-libxc-4.3.2-ewkkgzjlqybyjkqwz3gguft33yoxijah/spack-src'
  >> 1281    make: *** [all] Error 2
```
This stems from line 91 of `$SPACK/var/spack/repos/builtin/packages/libxc/package.py`:

```console
optflags += ' -xSSE4.2 -axAVX,CORE-AVX2 -ipo'
```

If the first two flags are removed, libxc compiles correctly. It works perfectly fine with the flags when using the Intel 2018 compiler, so there must be some new behavior in the more recent version.

### Steps to reproduce the issue

```console
$ spack install libxc %intel@19.1.0.166
```

### Information on your system

* **Spack:** 0.14.2-1500-4e9a989
* **Python:** 3.6.8
* **Platform:** linux-rhel7-haswell

Relevant part of `compilers.yaml`:

```yaml
- compiler:
    modules: [compilers/gcc/6.5.0, compilers/intel/2018]
    spec: intel@18.0.5
    paths:
      cc: /opt/intel/parallel_studio_xe_2018_update4_cluster_edition/compilers_and_libraries_2018.5.274/linux/bin/intel64/icc
      cxx: /opt/intel/parallel_studio_xe_2018_update4_cluster_edition/compilers_and_libraries_2018.5.274/linux/bin/intel64/icpc
      f77: /opt/intel/parallel_studio_xe_2018_update4_cluster_edition/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort
      fc: /opt/intel/parallel_studio_xe_2018_update4_cluster_edition/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel7
    target: x86_64
    environment: {}
    extra_rpaths: [/opt/gcc/6.5.0/lib64, /opt/intel/parallel_studio_xe_2018_update4_cluster_edition/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64_lin]
- compiler:
    modules: [compilers/gcc/9.3.0, compilers/intel/2020]
    spec: intel@19.1.0.166
    paths:
      cc: /opt/intel/parallel_studio_xe_2020_cluster_edition/compilers_and_libraries_2020.0.166/linux/bin/intel64/icc
      cxx: /opt/intel/parallel_studio_xe_2020_cluster_edition/compilers_and_libraries_2020.0.166/linux/bin/intel64/icpc
      f77: /opt/intel/parallel_studio_xe_2020_cluster_edition/compilers_and_libraries_2020.0.166/linux/bin/intel64/ifort
      fc: /opt/intel/parallel_studio_xe_2020_cluster_edition/compilers_and_libraries_2020.0.166/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel7
    target: x86_64
    environment: {}
    extra_rpaths: [/opt/gcc/9.3.0/lib64, /opt/intel/parallel_studio_xe_2020_cluster_edition/compilers_and_libraries_2020.0.166/linux/compiler/lib/intel64_lin]
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/4814219/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/4814220/spack-build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
