### ISSUE TITLE
Installation issue: Trilinos with GCC on MacOSX

### ISSUE THREAD

**Issue by tmdelellis** [LLNL/spack#17662]
### Steps to reproduce the issue

```console
$ spack install trilinos%gcc@8.3.0+openmp ^cmake%clang@11.0.0-apple
```
This is a well-known issue with GCC on MacOSX with XCODE 11.  It has to do with the `-isysroot` path.  If you don't include this path things seem to work out fine.  For example, most of our spack packages that compile using gcc use autoconf, which doesn't detect the sysroot.  It appears a work-around when using cmake may be to set the following:
```cmake
set(CMAKE_OSX_SYSROOT /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk CACHE PATH "")
```
You can get this path using
```sh
xcrun --show-sdk-path
```
I have used this to build Trilinos manually with GCC 8/9 on MacOSX and it compiles/tests successfully.

### Information on your system

* **Spack:** 0.15.1
* **Python:** 3.7.3
* **Platform:** darwin-mojave-skylake

**packages.yaml**:
```yaml
  trilinos:
    variants:
       +amesos +anasazi +aztec +belos +ifpack +teuchos gotype=long +epetra +epetraext +kokkos +ifpack2 +intrepid +ml +sacado +shards +tpetra +stratimikos ~adios2 ~alloptpkgs ~amesos2 ~boost ~cgns ~chaco ~complex ~debug ~dtk ~exodus +explicit_template_instantiation ~float +fortran ~fortrilinos ~glm   ~gtest +hdf5 ~hypre  ~intrepid2 ~isorropia ~matio ~mesquite ~metis ~minitensor ~muelu ~mumps ~netcdf ~nox ~openmp ~phalanx ~piro ~pnetcdf ~python ~rol ~rythmos +shared ~shylu ~stk ~suite-sparse ~superlu ~superlu-dist ~teko ~tempus ~x11 ~xsdkflags ~zlib ~zoltan ~zoltan2
```
### Additional information

* [spack-build-env.txt](https://github.com/spack/spack/files/4961333/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/4961329/spack-build-out.txt)

@keitat 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
