### ISSUE TITLE
spack pipeline issue with spack env activate

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#17679]
@scottwittenburg 
This is my .gitlab-ci.yml trying to build at Cori 

```
variables:
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 48:00:00"
  SPACK_REPO: "https://github.com/spack/spack.git"
  SPACK_REF: "develop"  
   
stages:
  - build
  - prod

setup-spackpipeline:
  stage: build
  tags: [cori]
  before_script:
  - pwd
  - git clone ${SPACK_REPO} --branch ${SPACK_REF} --depth=1
  - cd spack
  - git log  --oneline -1
  - . share/spack/setup-env.sh
  script:
  - hostname
  - spack env activate .
  - spack concretize -f 2>&1 | tee concretize.log
  - spack -d ci generate --optimize --output-file pipeline.yml 
  after_script:
  - rm -rf ./spack/
  artifacts:
    paths:
    - concretize.log
    - pipeline.yml


build-spackpipeline:
  stage: prod
  trigger:
    include:
    - artifact: "pipeline.yml"
      job: setup-spackpipeline
    strategy: depend

```

Shown below is my `spack.yaml`

```
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  concretization: separately
  view: false
  config:
    install_tree: $spack/$padding:512
    build_stage: $tempdir/$user/spack-stage
  mirrors:
    local: /global/common/software/spackecp/mirror

  definitions:
  - e4s:    
    # - adios
    #- adios2
    #- aml
    #- bolt
    #- caliper
    #- darshan-runtime
    #- darshan-util
    #- dyninst
    #- faodel
    #- flecsi+cinch
    #- globalarrays
    #- gotcha
    #- hdf5
    #- hpctoolkit
    #- hypre
    #- kokkos-kernels
    #- kokkos+openmp
    #- libnrm
    #- libquo
    #- mercury
    #- mfem
    #- ninja
    #- openmpi
    #- openpmd-api
    #- papi
    #- papyrus@develop
    #- parallel-netcdf
    #- pdt
    #- petsc
    #- py-jupyterhub
    #- py-libensemble
    #- qthreads
    #- raja
    #- rempi
    #- scr
    #- strumpack
    #- sundials
    #- superlu
    #- superlu-dist
    #- sz
    #- tasmanian
    #- tau
    #- trilinos
    #- turbine
    #- umpire
    #- unifyfs
    #- upcxx
    #- veloc
    #- zfp
    - aml
    - darshan-runtime
    - darshan-util
  
  - arch:
    - '%intel@19.0.3.199 arch=cray-cnl7-haswell'
  
  specs:
    - matrix:
      - - $e4s
      - - $arch
 

  packages:
    all:
      compiler: [intel@19.0.3.199]
      version: []
      target: []
      providers: {}
      paths: {}
      modules: {}
      buildable: true

  gitlab-ci:
    mappings:
      - match: ['os=cnl7']
        runner-attributes:
          tags:
          - cori
          script:
          - export SPACK_GNUPGHOME=$HOME/.gnugpghome-spack
          - hostname
          - mkdir -p artifacts
          - env > artifacts/env.sh
          - git clone ${SPACK_REPO} --branch ${SPACK_REF}
          - . spack/share/spack/setup-env.sh
          - spack compiler find
          - spack -d -e . ci rebuild
  
    enable-artifacts-buildcache: False
```

The ``spack env activate .`` doesn't work anymore .

Here is the snapshot build at https://software.nersc.gov/ecp/spack-ecp/-/jobs/17290

```
$ cd spack
$ git log  --oneline -1
f42394d csa-c: added new package at master (#17676)
$ . share/spack/setup-env.sh
$ hostname
cori01
$ spack env activate .
==> Error: No such environment: '.'
$ spack concretize -f 2>&1 | tee concretize.log
==> Error: `spack concretize` requires an environment
  activate an environment first:
      spack env activate ENV
  or use:
      spack -e ENV concretize ...
Running after script...
$ rm -rf ./spack/
```

I am trying to figure out if i should create an environment name, if so can it be same name?  Should i run ``spack env create e4s spack.yaml``. Will this work for every spack build, i presume each gitlab job will invoke ``before_script`` which will clone spack in a unique path.

Due to some changes with `spack env activate` the documentation examples in https://spack.readthedocs.io/en/latest/pipelines.html will not work and require update.
