### ISSUE TITLE
Installation issue: E4S project: faodel will not install on Ascent (ORNL) with gcc/6.4.0

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#18198]
The package/application faodel fails to build on Ascent (ORNL) with gcc/6.4.0.  This is part of the E4S project.
The issue is that one of the libraries that faodel includes in the  build doesn't support Power systems.   I've added a potential fix in the text below and will submit a PR, if reviewers/commenters agree with the fix.

To recreate the original problem:
spack -e . install --no-cache
with this spack.yaml file in your spack top-level directory:
```
spack:
  packages:
    all:
      providers:
        mpi: [spectrum-mpi]
      target: [ppc64le]
      buildable: true
      version: []
      paths: {}
      modules: {}
      compiler: []
    cuda:
      buildable: false
      version: [10.1.243]
      modules:
        cuda@10.1.243: cuda/10.1.243
      target: []
      providers: {}
      paths: {}
      compiler: []
    spectrum-mpi:
      buildable: false
      version:
      - 10.3.1.2
      modules:
        spectrum-mpi@10.3.1.2: spectrum-mpi/10.3.1.2-20200121
      target: []
      providers: {}
      paths: {}
      compiler: []
    gcc:
      version:
      - 6.4.0
      buildable: true
      target: []
      providers: {}
      paths: {}
      modules: {}
      compiler: []
  specs:
#  - aml
  - faodel
#  - flecsi+cinch
#  - petsc
#  - turbine
#  - unifyfs
  config:
    misc_cache: $spack/cache
    install_tree: $spack/$padding:512
  view: false
  concretization: separately
```

I have a potential fix for this faodel build issue.
```
diff --git a/var/spack/repos/builtin/packages/faodel/package.py b/var/spack/repos/builtin/packages/faodel/package.py
index 255f039..74a9bf3 100644
--- a/var/spack/repos/builtin/packages/faodel/package.py
+++ b/var/spack/repos/builtin/packages/faodel/package.py
@@ -60,6 +60,15 @@ class Faodel(CMakePackage):
     def cmake_args(self):
         spec = self.spec
 
+        if spec.target.family == "ppc64le":
+            enable_tcmalloc = 'OFF'
+        else:
+            if '+tcmalloc' in spec:
+                enable_tcmalloc = 'ON'
+            else:
+                enable_tcmalloc = 'OFF'
+            
+
         args = [
             '-DBUILD_SHARED_LIBS:BOOL={0}'.format(
                 'ON' if '+shared' in spec else 'OFF'),
@@ -74,8 +83,7 @@ def cmake_args(self):
                 'ON' if '+leveldb' in spec else 'OFF'),
             '-DFaodel_ENABLE_MPI_SUPPORT:BOOL={0}'.format(
                 'ON' if '+mpi' in spec else 'OFF'),
-            '-DFaodel_ENABLE_TCMALLOC:BOOL={0}'.format(
-                'ON' if '+tcmalloc' in spec else 'OFF'),
+            '-DFaodel_ENABLE_TCMALLOC:BOOL={0}'.format(enable_tcmalloc),
             '-DFaodel_LOGGING_METHOD:STRING={0}'.format(
                 spec.variants['logging'].value),
             '-DFaodel_NETWORK_LIBRARY:STRING={0}'.format(
```

That patch resolves this message I was getting when not using the patch:

```
-DFaodel_ENABLE_IOM_LEVELDB:BOOL=OFF' '-DFaodel_ENABLE_MPI_SUPPORT:BOOL=ON' '-DFaodel_ENABLE_TCMALLOC:BOOL=ON' '-DFaodel_LOGGING_METHOD:STRING=stdout' '-DFaodel_NETWORK_LIBRARY:STRING=nnti' '-DFaodel_ENABLE_CEREAL:BOOL=OFF' '/ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-faodel-1.1906.1-jgy6p27i23sxorcsnm47sp7gwgeolsqc/spack-src'

1 error found in build log:
     32    -- MPI_CXX_FOUND = TRUE
     33    -- Checking for module 'cray-ugni'
     34    --   No package 'cray-ugni' found
     35    -- Found IBVerbs: /usr/lib64/libibverbs.so
     36    -- Checking for module 'cray-drc'
     37    --   No package 'cray-drc' found
  >> 38    CMake Error at CMakeLists.txt:346 (message):
     39      The TCMALLOC library included with FAODEL does not currently have 
           support
     40      for the ppc64le CPU (it has optimizations for x86_64).  You must s
           et
     41      Faodel_ENABLE_TCMALLOC to OFF in order to build FAODEL on this pla
           tform.
     42    
     43    
     44    -- Configuring incomplete, errors occurred!

See build log for details:
  /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-faodel-1.1906.1-jgy6p27i23sxorcsnm47sp7gwgeolsqc/spack-build-out.txt
```

@tkordenbrock
