### ISSUE TITLE
Installation issue: E4S project: AML will not install on Ascent (ORNL) with gcc/6.4.0 

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#18196]
The issue appears to be a problem in the AML code itself where they are copying files to a directory that wasn't created.
This was discovered while trying to address packages that did not build for the E4S project initially.   I have a suggested fix but am looking for advice on what is the best strategy.   The fix is to add a mkdir command to the doc directory Makefile.am file:
```
$ diff -Naur aml-0.1.0/doc/Makefile.am aml-0.1.0-fixed/doc/Makefile.am
--- aml-0.1.0/doc/Makefile.am	1969-12-31 19:00:01.000000000 -0500
+++ aml-0.1.0-fixed/doc/Makefile.am	2020-08-10 17:57:57.756347000 -0400
@@ -16,6 +16,7 @@
 
 install-doc-html: build-docs
 	if [ -d $(SPHINX_BUILD_DIR) ]; then \
+	mkdir -p $(DATA_INSTALL_DIR)/html \
 	cp -r $(SPHINX_BUILD_DIR) $(DATA_INSTALL_DIR)/html; \
 	fi
```

Because this is in the project code itself, should this fix be done by the project team responsible for aml or another option is to patch the file.   Patching the file will not take effect unless we do the autogen.sh command and perhaps just patch Makefile.in which is regenerated by the autogen.sh.   Does anyone have advice on how this could be done effectively?

To recreate the original problem:
spack -e . install --no-cache
with this spack.yaml file in your spack top-level directory:
```
spack:
  packages:
    all:
      providers:
        mpi: [spectrum-mpi]
      target: [ppc64le]
      buildable: true
      version: []
      paths: {}
      modules: {}
      compiler: []
    cuda:
      buildable: false
      version: [10.1.243]
      modules:
        cuda@10.1.243: cuda/10.1.243
      target: []
      providers: {}
      paths: {}
      compiler: []
    spectrum-mpi:
      buildable: false
      version:
      - 10.3.1.2
      modules:
        spectrum-mpi@10.3.1.2: spectrum-mpi/10.3.1.2-20200121
      target: []
      providers: {}
      paths: {}
      compiler: []
    gcc:
      version:
      - 6.4.0
      buildable: true
      target: []
      providers: {}
      paths: {}
      modules: {}
      compiler: []
  specs:
  - aml
#  - faodel
#  - flecsi+cinch
#  - petsc
#  - turbine
#  - unifyfs
  config:
    misc_cache: $spack/cache
    install_tree: $spack/$padding:512
  view: false
  concretization: separately
```

Here is the original failed output:
```
==> Installing aml
==> aml: Executing phase: 'autoreconf'
==> aml: Executing phase: 'configure'
==> aml: Executing phase: 'build'
==> aml: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'install'

4 errors found in build log:
     362    mkdir -p /autofs/nccsopen-svm1_home/jgalarowicz/luke_assignment/spa
            ck/spack_path_placeholder/spack_path_placeholder/spack_path_placeho
            lder/spack_path_placeholder/spack_path_placeholder/spack_path_place
            holder/spack_path_placeholder/spack_path_placeholder/spack_path_pla
            ceholder/spack_path_placeholder/spack_path_placeholder/spack_path_p
            laceholder/spack_path_placeholder/spack_path_placeholder/spack_path
            _placeholder/spack_path_placeholder/spack_path_placeholder/spack_pa
            th_placeholder/spack_path_placeholder/spack_path_placeholder/spack_
            path_placeholder/spack_path_placeholder/spack_/linux-rhel7-ppc64le/
            gcc-6.4.0/aml-0.1.0-xlnakyzomp5n6relmtb6ajb2ijrds3uz/share/aml
     363    echo "not building documentation"
     364    not building documentation
     365    if [ -d ./build-sphinx ]; then \
     366    cp -r ./build-sphinx /autofs/nccsopen-svm1_home/jgalarowicz/luke_as
            signment/spack/spack_path_placeholder/spack_path_placeholder/spack_
            path_placeholder/spack_path_placeholder/spack_path_placeholder/spac
            k_path_placeholder/spack_path_placeholder/spack_path_placeholder/sp
            ack_path_placeholder/spack_path_placeholder/spack_path_placeholder/
            spack_path_placeholder/spack_path_placeholder/spack_path_placeholde
            r/spack_path_placeholder/spack_path_placeholder/spack_path_placehol
            der/spack_path_placeholder/spack_path_placeholder/spack_path_placeh
            older/spack_path_placeholder/spack_path_placeholder/spack_/linux-rh
            el7-ppc64le/gcc-6.4.0/aml-0.1.0-xlnakyzomp5n6relmtb6ajb2ijrds3uz/sh
            are/aml/html; \
     367    fi
  >> 368    cp: cannot create directory '/autofs/nccsopen-svm1_home/jgalarowicz
            /luke_assignment/spack/spack_path_placeholder/spack_path_placeholde
            r/spack_path_placeholder/spack_path_placeholder/spack_path_placehol
            der/spack_path_placeholder/spack_path_placeholder/spack_path_placeh
            older/spack_path_placeholder/spack_path_placeholder/spack_path_plac
            eholder/spack_path_placeholder/spack_path_placeholder/spack_path_pl
            aceholder/spack_path_placeholder/spack_path_placeholder/spack_path_
            placeholder/spack_path_placeholder/spack_path_placeholder/spack_pat
            h_placeholder/spack_path_placeholder/spack_path_placeholder/spack_/
            linux-rhel7-ppc64le/gcc-6.4.0/aml-0.1.0-xlnakyzomp5n6relmtb6ajb2ijr
            ds3uz/share/aml/html': No such file or directory
  >> 369    make[2]: *** [install-doc-html] Error 1
     370    make[2]: *** Waiting for unfinished jobs....
     371    make[2]: Leaving directory `/autofs/nccsopen-svm1_home/jgalarowicz/
            tempspack/spack-stage/spack-stage-aml-0.1.0-xlnakyzomp5n6relmtb6ajb
            2ijrds3uz/spack-src/doc'
  >> 372    make[1]: *** [install-am] Error 2
     373    make[1]: Leaving directory `/autofs/nccsopen-svm1_home/jgalarowicz/
            tempspack/spack-stage/spack-stage-aml-0.1.0-xlnakyzomp5n6relmtb6ajb
            2ijrds3uz/spack-src/doc'
  >> 374    make: *** [install-recursive] Error 1

See build log for details:
  /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-aml-0.1.0-xlnakyzomp5n6relmtb6ajb2ijrds3uz/spack-build-out.txt
```

@freuk
