### ISSUE TITLE
Installation issue: E4S project: turbine will not install on Ascent (ORNL) with gcc/6.4.0 

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#18202]
The package/application turbine fails to build on Ascent (ORNL) with gcc/6.4.0. This is part of the E4S project.
The issue is that the turbine configure doesn't have an entry for IBM's Spectrum libmpi_ibm.so library.   They are only looking for libmpi and libmpich.    I've added a potential fix in the text below but hoping the turbine developers will give advice on whether we should patch turbine source or wait for a fix in the turbine source from the developers.

To recreate the original problem:
spack -e . install --no-cache
with this spack.yaml file in your spack top-level directory:
```
spack:
  packages:
    all:
      providers:
        mpi: [spectrum-mpi]
      target: [ppc64le]
      buildable: true
      version: []
      paths: {}
      modules: {}
      compiler: []
    cuda:
      buildable: false
      version: [10.1.243]
      modules:
        cuda@10.1.243: cuda/10.1.243
      target: []
      providers: {}
      paths: {}
      compiler: []
    spectrum-mpi:
      buildable: false
      version:
      - 10.3.1.2
      modules:
        spectrum-mpi@10.3.1.2: spectrum-mpi/10.3.1.2-20200121
      target: []
      providers: {}
      paths: {}
      compiler: []
    gcc:
      version:
      - 6.4.0
      buildable: true
      target: []
      providers: {}
      paths: {}
      modules: {}
      compiler: []
  specs:
#  - aml
#  - faodel
#  - flecsi+cinch
#  - petsc
  - turbine
#  - unifyfs
  config:
    misc_cache: $spack/cache
    install_tree: $spack/$padding:512
  view: false
  concretization: separately
```
The turbine build fails in this manner:
```
1 error found in build log:
     102    Found /autofs/nccsopen-svm1_sw/ascent/.swci/1-compute/opt/spack/201
            80914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20200121-
            awz2q5brde7wgdqqw4ugalrkukeub4eb/bin/mpiexec
     103    Using MPI launcher: /autofs/nccsopen-svm1_sw/ascent/.swci/1-compute
            /opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3
            .1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/bin/mpiexec
     104    checking for /autofs/nccsopen-svm1_sw/ascent/.swci/1-compute/opt/sp
            ack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20
            200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/include/mpi.h... yes
     105    MPI_LIB_DIR_ALTS /autofs/nccsopen-svm1_sw/ascent/.swci/1-compute/op
            t/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.
            2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib
     106    checking for MPI library libmpi at /autofs/nccsopen-svm1_sw/ascent/
            .swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/sp
            ectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib..
            . no
     107    checking for MPI library libmpich at /autofs/nccsopen-svm1_sw/ascen
            t/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/
            spectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/lib
            ... no
  >> 108    configure: error: Could not find MPI library in any alternative loc
            ations

See build log for details:
  /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-turbine-1.2.3-2cagfvjitzo4muzvw25v5bmyirfup362/spack-build-out.txt
```
The potential fix is to add the library into the configure.ac script:
```
diff -Naur turbine-1.2.3/configure.ac turbine-1.2.3.fixes/configure.ac
--- turbine-1.2.3/configure.ac    2019-04-29 13:07:03.000000000 -0400
+++ turbine-1.2.3.fixes/configure.ac    2020-08-11 17:47:20.662000000 -0400
@@ -386,7 +386,7 @@
 
 if [[ -z "${USE_MPI_LIB_NAME}" ]]
 then
-  MPI_LIB_NAME_ALTS="mpi mpich"
+  MPI_LIB_NAME_ALTS="mpi mpich mpi_ibm"
 else
   MPI_LIB_NAME_ALTS="${USE_MPI_LIB_NAME}"
 fi
```

@jmjwozniak
