### ISSUE TITLE
Installation issue: E4S project: flecsi+cinch will not install on Ascent (ORNL) with gcc/6.4.0 

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#18201]
The package/application flecsi fails to build on Ascent (ORNL) with gcc/6.4.0. This is part of the E4S project.
flecsi apparently needs stdc++17 features and it seems from what I could tell gcc/6.4.0 doesn't support those features.  It builds with gcc/7.4.0 and above.   Bringing this to the attention of the flecsi developers for their advice on any workarounds for the gcc/6.4.0 build.

To recreate the original problem:
spack -e . install --no-cache
with this spack.yaml file in your spack top-level directory:
```
spack:
  packages:
    all:
      providers:
        mpi: [spectrum-mpi]
      target: [ppc64le]
      buildable: true
      version: []
      paths: {}
      modules: {}
      compiler: []
    cuda:
      buildable: false
      version: [10.1.243]
      modules:
        cuda@10.1.243: cuda/10.1.243
      target: []
      providers: {}
      paths: {}
      compiler: []
    spectrum-mpi:
      buildable: false
      version:
      - 10.3.1.2
      modules:
        spectrum-mpi@10.3.1.2: spectrum-mpi/10.3.1.2-20200121
      target: []
      providers: {}
      paths: {}
      compiler: []
    gcc:
      version:
      - 6.4.0
      buildable: true
      target: []
      providers: {}
      paths: {}
      modules: {}
      compiler: []
  specs:
#  - aml
#  - faodel
  - flecsi+cinch
#  - petsc
#  - turbine
#  - unifyfs
  config:
    misc_cache: $spack/cache
    install_tree: $spack/$padding:512
  view: false
  concretization: separately
```

Output from spack build:
```
[+] /autofs/nccsopen-svm1_home/jgalarowicz/luke_assignment/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/parmetis-4.0.3-yy267qlytwjxllqn33rww3a3s56dlxh5
==> Installing flecsi
==> No binary for flecsi found: installing from source
==> flecsi: Executing phase: 'cmake'
==> flecsi: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

148 errors found in build log:
     150    /autofs/nccsopen-svm1_home/jgalarowicz/luke_assignment/spack/lib/sp
            ack/env/gcc/g++ -DFleCSI_EXPORTS -I/ccsopen/home/jgalarowicz/tempsp
            ack/spack-stage/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2tty
            eo/spack-src -I/autofs/nccsopen-svm1_home/jgalarowicz/tempspack/spa
            ck-stage/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spac
            k-build -I/autofs/nccsopen-svm1_home/jgalarowicz/luke_assignment/sp
            ack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/cinch-master-uek7agqzp
            i4fncsmb6c5oywbfyqgscnj/logging -I/autofs/nccsopen-svm1_home/jgalar
            owicz/luke_assignment/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.
            0/metis-5.1.0-agilkedb5lwhhmh7x56oxi5t6klvqs6t/include -I/autofs/nc
            csopen-svm1_home/jgalarowicz/luke_assignment/spack/opt/spack/linux-
            rhel7-power9le/gcc-6.4.0/parmetis-4.0.3-yy267qlytwjxllqn33rww3a3s56
            dlxh5/include -I/ccsopen/home/jgalarowicz/tempspack/spack-stage/spa
            ck-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi
             -I/autofs/nccsopen-svm1_home/jgalarowicz/tempspack/spack-stage/spa
            ck-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-build/flec
            si -I/ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-fl
            ecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/.. -I/auto
            fs/nccsopen-svm1_home/jgalarowicz/tempspack/spack-stage/spack-stage
            -flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-build/flecsi/.. -i
            system /autofs/nccsopen-svm1_sw/ascent/.swci/1-compute/opt/spack/20
            180914/linux-rhel7-ppc64le/gcc-8.1.1/spectrum-mpi-10.3.1.2-20200121
            -chae23sgwacfeot7vxkpfboz6wao2c33/include -fopenmp -O3 -DNDEBUG -fP
            IC -pthread -std=gnu++1z -o CMakeFiles/FleCSI.dir/flecsi/utils/dema
            ngle.cc.o -c /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-
            stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/ut
            ils/demangle.cc
     151    In file included from /ccsopen/home/jgalarowicz/tempspack/spack-sta
            ge/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/
            flecsi/control/phase_walker.h:19:0,
     152                     from /ccsopen/home/jgalarowicz/tempspack/spack-sta
            ge/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/
            flecsi/control/control.h:18,
     153                     from /ccsopen/home/jgalarowicz/tempspack/spack-sta
            ge/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/
            flecsi/control/test/policy.h:18,
     154                     from /ccsopen/home/jgalarowicz/tempspack/spack-sta
            ge/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/
            flecsi/control/test/runtime_model.cc:16:
     155    /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-flecsi-
            1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/utils/tuple_wal
            ker.h: In member function 'void flecsi::utils::tuple_walker_u<CRTP_
            TYPE>::walk_impl(TUPLE_TYPE&)':
  >> 156    /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-flecsi-
            1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/utils/tuple_wal
            ker.h:49:8: error: expected '(' before 'constexpr'
     157         if constexpr(index < std::tuple_size<TUPLE_TYPE>::value) {
     158            ^~~~~~~~~
     159    /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-flecsi-
            1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/utils/tuple_wal
            ker.h: In member function 'void flecsi::utils::tuple_walker_u<CRTP_
            TYPE>::walk_types_impl()':
  >> 160    /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-flecsi-
            1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/utils/tuple_wal
            ker.h:57:8: error: expected '(' before 'constexpr'
     161         if constexpr(index < std::tuple_size<TUPLE_TYPE>::value) {
     162            ^~~~~~~~~
     163    In file included from /ccsopen/home/jgalarowicz/tempspack/spack-sta
            ge/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/
            flecsi/control/control.h:18:0,
     164                     from /ccsopen/home/jgalarowicz/tempspack/spack-sta
            ge/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/
            flecsi/control/test/policy.h:18,
     165                     from /ccsopen/home/jgalarowicz/tempspack/spack-sta
            ge/spack-stage-flecsi-1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/
            flecsi/control/test/runtime_model.cc:16:
     166    /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-flecsi-
            1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/control/phase_w
            alker.h: In member function 'void flecsi::control::phase_walker_u<C
            ONTROL_POLICY>::handle_type()':
  >> 167    /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-flecsi-
            1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/control/phase_w
            alker.h:87:8: error: expected '(' before 'constexpr'
     168         if constexpr(std::is_same<typename PHASE_TYPE::TYPE, size_t>::
            value) {
     169            ^~~~~~~~~
  >> 170    /ccsopen/home/jgalarowicz/tempspack/spack-stage/spack-stage-flecsi-
            1-qx467zgzaqyzv33phjwc5tcihw2ttyeo/spack-src/flecsi/control/phase_w
            alker.h:106:3: error: expected '}' at end of input
     171       } // handle_type
     172       ^
```

@ktsai7 @JulienLoiseau
