### ISSUE TITLE
dev-build ignores environment settings

### ISSUE THREAD

**Issue by DraTeots** [LLNL/spack#18401]
In order to create a build environment for a package with exact packet versions (especially things like CERN ROOT) I create an environment with 

```
spack:    
    specs:
        - "root@6.20.04+vmc+pythia6+pythia8+root7 cxxstd=17"
        - "jana2@2.0.3 +root cxxstd=17"
        - "eic-smear@1.1.1"        
        - "ejana@master"
    concretization: together
```

Here 'ejana' depends on others and others depend on root and each other and having them all of one version is important. So ```concretization: together``` works well and does the job of getting consistent versions of packages during install. 

If sitting in this environment I do

```
$ spack dev-build ejana@master
```

Instead of using the installed versions it tries to install default versions of root (6.18 not 6.20) and other packages and nothing works as expected (by me). 

It is highly inconvenient as the only way to get a set of versions to be particular for dev-build is using its ```spec``` command line variable. If I add a bit more packages than in the above example such command becomes unbearable. 

```spack setup``` kind of respected ```concretization: together``` flag.

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
```
* **Spack:** 0.15.3
* **Python:** 3.7.7
* **Platform:** linux-ubuntu18.04-zen
```
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
(I run in debug mode, but there is nothing to report)
