### ISSUE TITLE
Installation issue: package (e.g. fgsl) using intel compiler

### ISSUE THREAD

**Issue by mo7ammedmostafa** [LLNL/spack#18606]
There seems to be a problem building some packages ( not all packages )  using the intel compiler.
Some packages compile fine without an issue ( for example packages such as zlib, openssl, and cmake  gives no issue ) but others give linking problem.
As an example to reproduce the problem I use fgsl package which produced an error as we see here.
```console
$ spack install fgsl%intel
```
now when I try installing a package that involves linking against something from the the math kernel library it fails providing the following error
```
==> Error: ProcessError: Command exited with status 2:
    'make'

1 error found in build log:
     165    /bin/bash ./libtool  --tag=CC   --mode=compile /home/mohamedkamra/LocalAppInstalls/spack/lib/spack/env/intel/icc -DHAVE_CONFIG_H -I.  -I. -I.  -I/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/gsl-2.4-jczpzktqce2fvi7ngav6krwd
            2qhdd4ba/include -I. -g -O2 -MT libfgsl_la-fgsl_utils.lo -MD -MP -MF .deps/libfgsl_la-fgsl_utils.Tpo -c -o libfgsl_la-fgsl_utils.lo `test -f 'fgsl_utils.c' || echo './'`fgsl_utils.c
     166    libtool: compile:  /home/mohamedkamra/LocalAppInstalls/spack/lib/spack/env/intel/icc -DHAVE_CONFIG_H -I. -I. -I. -I/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/gsl-2.4-jczpzktqce2fvi7ngav6krwd2qhdd4ba/include -I. -g -O2 -M
            T libfgsl_la-fgsl_utils.lo -MD -MP -MF .deps/libfgsl_la-fgsl_utils.Tpo -c fgsl_utils.c  -fPIC -DPIC -o .libs/libfgsl_la-fgsl_utils.o
     167    libtool: compile:  /home/mohamedkamra/LocalAppInstalls/spack/lib/spack/env/intel/icc -DHAVE_CONFIG_H -I. -I. -I. -I/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/gsl-2.4-jczpzktqce2fvi7ngav6krwd2qhdd4ba/include -I. -g -O2 -M
            T libfgsl_la-fgsl_utils.lo -MD -MP -MF .deps/libfgsl_la-fgsl_utils.Tpo -c fgsl_utils.c -o libfgsl_la-fgsl_utils.o >/dev/null 2>&1
     168    mv -f .deps/libfgsl_la-fgsl_utils.Tpo .deps/libfgsl_la-fgsl_utils.Plo
     169    /bin/bash ./libtool  --tag=FC   --mode=link /home/mohamedkamra/LocalAppInstalls/spack/lib/spack/env/intel/ifort  -g -version-info 1:2:0   -o libfgsl.la -rpath /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/fgsl-1.3.0-l6zncad
            usl3i22yk3ffhxqzu3oxyhcou/lib fgsl.lo libfgsl_la-fgsl_utils.lo  -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/gsl-2.4-jczpzktqce2fvi7ngav6krwd2qhdd4ba/lib -lgsl -lgslcblas -lm
     170    libtool: link: /home/mohamedkamra/LocalAppInstalls/spack/lib/spack/env/intel/ifort -shared -nofor_main  .libs/fgsl.o .libs/libfgsl_la-fgsl_utils.o   -Wl,-rpath -Wl,/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/gsl-2.4-jczpz
            ktqce2fvi7ngav6krwd2qhdd4ba/lib -Wl,-rpath -Wl,/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/gsl-2.4-jczpzktqce2fvi7ngav6krwd2qhdd4ba/lib -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19
            .1.2.254/gsl-2.4-jczpzktqce2fvi7ngav6krwd2qhdd4ba/lib /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/gsl-2.4-jczpzktqce2fvi7ngav6krwd2qhdd4ba/lib/libgsl.so /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.0
            4-zen2/intel-19.1.2.254/gsl-2.4-jczpzktqce2fvi7ngav6krwd2qhdd4ba/lib/libgslcblas.so -lm  -g   -Wl,-soname -Wl,libfgsl.so.1 -o .libs/libfgsl.so.1.0.2
  >> 171    ld: /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/bin/intel64/../../lib/LLVMgold.so: error loading plugin: libimf.so: cannot open shared object
             file: No such file or directory
```
the error indicate that library is not the `LD_LIBRARY_PATH`
I have confirmed that libimf when intel compiler is loaded by running
```
/sbin/ldconfig -N -v $(sed 's/:/ /g' <<< $LD_LIBRARY_PATH) | tee log.txt
```
```
/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin:
	libiomp5.so -> libiomp5.so
	libifport.so.5 -> libifport.so.5
	libifcore.so.5 -> libifcore.so.5
	libintlc.so.5 -> libintlc.so.5
	libistrconv.so -> libistrconv.so
	libimf.so -> libimf.so
	libifcoremt.so.5 -> libifcoremt.so.5
	libiomp5_db.so -> libiomp5_db.so
	libpdbx.so.5 -> libpdbx.so.5
	libcilkrts.so.5 -> libcilkrts.so.5
	libirc.so -> libirc.so
	libsvml.so -> libsvml.so
	libqkmalloc.so -> libqkmalloc.so
	libchkp.so -> libchkp.so
	libmpx.so -> libmpx.so
	libiompstubs5.so -> libiompstubs5.so
	libirng.so -> libirng.so
	libicaf.so -> libicaf.so
```
yet for some some reason it is not detected the package during build.

**Could be similar Issue**
I found the following issue 
https://github.com/spack/spack/issues/17100#issue-638768001
but I am not sure if it is the same or not and the issue remains open
### Information on your system

$ spack debug report
* **Spack:** 0.15.4-933-651cffae0
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-zen2

```yaml
**compilers.yml**
compilers:
- compiler:
    spec: gcc@8.4.0
    paths:
      cc: /usr/bin/gcc-8
      cxx: /usr/bin/g++-8
      f77: /usr/bin/gfortran-8
      fc: /usr/bin/gfortran-8
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@19.1.2.254
    paths:
      cc: /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/bin/intel64/icc
      cxx: /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/bin/intel64/icpc
      f77: /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort
      fc: /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/5201544/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5201549/spack-build-out.txt)

I don't know if this has to do with anything but when I run
```console
$ spack load intel@20.0.2 
==> Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      source /dev/null &> /dev/null && python3 -c "import os, json; print(json.dumps(dict(os.environ)))"
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
==> Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      source /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/bin/compilervars.sh intel64 &> /dev/null && python3 -c "import os, json; print(json.dumps(dict(os.environ)))"
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
```

**spack external find**
```console
$ spack external find
==> Error: 20.04-b01: Identifier cannot contain '.'
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers intel` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Can you try:
```console
$ spack install --dirty fgsl%intel
```
and see if that allows you to build? I agree, this sounds like the same issue as #17100.

**Comment by mo7ammedmostafa** [comment]
`$ spack install --dirty fgsl%intel`

Using  `--dirty` option installation was a success. 
```
==> Installing fgsl
==> No binary for fgsl found: installing from source
==> Using cached archive: /path/to/spack/var/spack/cache/_source-cache/archive/6d/6d73d558c889d7ea23e510a436f28618624035e8ffa07692894f10968aa83a4b.tar.gz
==> fgsl: Executing phase: 'autoreconf'
==> fgsl: Executing phase: 'configure'
==> fgsl: Executing phase: 'build'
==> fgsl: Executing phase: 'install'
[+] /path/to/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/fgsl-1.3.0-l6zncadusl3i22yk3ffhxqzu3oxyhcou
```
I tried using  `--dirty` option to install other packages, such as  openmpi%intel and mpich%intel, which also failed before due to similar reasons ( mostly failing during configure stage with an error a long the lines of "fortran solver failed to compile a real program" )
They all succeeded without a problem.

I read the doc of  the `--dirty` option, it seems like an unsafe way of installation.

I trield other packages such as 
`$ spack install --dirty hypre%intel`
but this time I got 
`==> hypre: Executing phase: 'install'
==> [2020-09-11-18:21:09.321979] './configure' '--prefix=/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/hypre-2.19.0-lfhlqgxzsptleo6n2dfuqrbpwtzjnmbn' '--with-lapack-libs=openblas' '--with-lapack-lib-dirs=/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/openblas-0.3.10-qqgo3ndcrfhnaimhuzc5cirbfdezs2yz/lib' '--with-blas-libs=openblas' '--with-blas-lib-dirs=/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/openblas-0.3.10-qqgo3ndcrfhnaimhuzc5cirbfdezs2yz/lib' '--with-MPI' '--without-openmp' '--disable-bigint' '--disable-mixedint' '--disable-complex' '--enable-shared' '--without-superlu' '--without-mli' '--without-fei' '--disable-debug'
configure: WARNING: unrecognized options: --without-fei
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking for gcc... /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/openmpi-3.1.6-z2lrmm7asdmspsttwowxqnwrtuzw4dx6/bin/mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/openmpi-3.1.6-z2lrmm7asdmspsttwowxqnwrtuzw4dx6/bin/mpicc accepts -g... yes
checking for /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/openmpi-3.1.6-z2lrmm7asdmspsttwowxqnwrtuzw4dx6/bin/mpicc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether /home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/intel-19.1.2.254/openmpi-3.1.6-z2lrmm7asdmspsttwowxqnwrtuzw4dx6/bin/mpic++ accepts -g... yes
checking whether we are using the GNU Fortran compiler... no
checking whether /home/mohamedkamra/LocalAppInstalls/spack/lib/spack/env/intel/ifort accepts -g... yes
checking how to get verbose linking output from /home/mohamedkamra/LocalAppInstalls/spack/lib/spack/env/intel/ifort... -v
checking for Fortran libraries of /home/mohamedkamra/LocalAppInstalls/spack/lib/spack/env/intel/ifort...  -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/tbb/lib/intel64/gcc4.8 -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/lib -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib/../lib/ -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/lib/../lib/ -L/usr/lib/gcc/x86_64-linux-gnu/9/ -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/ -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib64 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/ -L/lib/x86_64-linux-gnu/ -L/lib/../lib64 -L/lib/../lib/ -L/usr/lib/x86_64-linux-gnu/ -L/usr/lib/../lib64 -L/usr/lib/../lib/ -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib/ -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/compilers_and_libraries_2020.2.254/linux/tbb/lib/intel64/gcc4.8/ -L/home/mohamedkamra/LocalAppInstalls/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/intel-20.0.2-mrgwii556tj2jpbckrp3kjxx34ubk52j/lib/ -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -L/usr/lib/i386-linux-gnu -lifport -lifcoremt -limf -lsvml -lm -lipgo -lirc -lpthread -lirc_s -ldl
checking for dummy main to link with Fortran libraries... unknown
configure: error: in `/tmp/mohamedkamra/spack-stage/spack-stage-hypre-2.19.0-lfhlqgxzsptleo6n2dfuqrbpwtzjnmbn/spack-src/src':
configure: error: linking to Fortran libraries from C fails

`
This time it failed with another linking error

**Comment by dev-zero** [comment]
maybe a duplicate of #10308 ?
I had to specify a `modules` in my `compilers.yml` to get it to work, see https://github.com/spack/spack/issues/10308#issuecomment-716391950

**Comment by matz-e** [comment]
Similar issue here, and filling `modules` did not help.

I fixed this by specifying the environment modifications directly (I used a full path for the module before, and it did not seem to have an effect on Spack):
```
- compiler:
    target: x86_64
    spec: intel@19.1.2.254
    modules: ["…/modules/tcl/linux-rhel7-x86_64/intel/20.0.2"]
    paths:
      cxx: …/linux-rhel7-x86_64/gcc-4.8.5/intel-20.0.2-ilowey/compilers_and_libraries_2020.2.254/linux/bin/intel64/icpc
      cc: …/linux-rhel7-x86_64/gcc-4.8.5/intel-20.0.2-ilowey/compilers_and_libraries_2020.2.254/linux/bin/intel64/icc
      f77: …/linux-rhel7-x86_64/gcc-4.8.5/intel-20.0.2-ilowey/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort
      fc: …/linux-rhel7-x86_64/gcc-4.8.5/intel-20.0.2-ilowey/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort
    environment:
      append_path:
        LD_LIBRARY_PATH: /…/linux-rhel7-x86_64/gcc-4.8.5/intel-20.0.2-ilowey/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin
    operating_system: rhel7
```
