### ISSUE TITLE
Installation issue: quantum-espresso

### ISSUE THREAD

**Issue by tomgreen66** [LLNL/spack#18656]
### Steps to reproduce the issue

```console
$ spack install quantum-espresso%gcc@8.1.0
Then in bld output I hit in fft_scalar.f90
#error No fft_scalar backend selected!
```

### Information on your system

* **Spack:** 0.15.4
* **Python:** 3.6.10
* **Platform:** cray-sles15-thunderx2

```
fftw-api: [fftw]
fftw:
    externals:
    - spec: fftw@3.3.8.5
      prefix: /opt/cray/pe/fftw/3.3.8.5/arm_thunderx2
    buildable: False
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/5214061/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/5214062/spack-build-env.txt)

@naromero77 
### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
