### ISSUE TITLE
Installation issue: python@3.8.5 with shared library

### ISSUE THREAD

**Issue by Char-Aznable** [LLNL/spack#18749]
### Steps to reproduce the issue

```console
$ spack install python@3.8.5+optimizations+tkinter cflags="-O3" cppflags="-O3"
```

### Information on your system

* **Spack:** 0.15.4-1022-80fe51046
* **Python:** 3.8.5
* **Platform:** linux-centos7-haswell

packages.yaml:
```
packages:
  all:
    compiler: [gcc@9.3.0, clang@10.0.1]
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa+opengl, opengl]
      glx: [mesa+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
    permissions:
      read: world
      write: user
```

### Additional information

This is the relevant error message in the build log:
```
/home/aznable/spack/lib/spack/env/gcc/gcc -pthread -shared -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/gettext-0.21-55mhwod6a63ps4ottclomuy72an57his/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/readline-8.0-vlftkqsvkinigldvkpkwgqtsy7ulmycn/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/ncurses-6.2-ccpvja4f5mz6aw7ioz5u7ihdrxbugyzf/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/openssl-1.1.1g-jfooumullita6g74ujk5jgatwvhl7bea/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/sqlite-3.33.0-kgquxoe5whn75qbpfra54ydgoaweu3of/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/gdbm-1.18.1-yfizpfmx2nghsdmhdvxnl7y6drdbkxq7/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/zlib-1.2.11-gfes7f35rppowsinvimnaheom23qbs55/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/bzip2-1.0.8-mlz6pdrikglamnlrn55am5uvxl4xu6lz/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/xz-5.2.5-ou6sagf3ii3lp76leopjcl2kixnz27t5/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/expat-2.2.9-sue4c2adf3iqpbhs573xx4e4rqt2ugmy/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/libffi-3.3-cb3hqvbkpmzm7lt5teoc47243vjdbdxm/lib64 -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/tk-8.6.8-hdasonb3ps5wj22vrvpa2tbf6rpn2myt/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/tcl-8.6.10-xdusiasvah27lmkrbo3qfwuzlnecmdwn/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/libuuid-1.0.3-aaommvjgyqtanujnrt4ksjckrysm3lcn/lib   -fprofile-generate -Wl,--no-as-needed -o libpython3.so -Wl,-hlibpython3.so libpython3.8.so
/home/aznable/spack/lib/spack/env/gcc/gcc -pthread -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/gettext-0.21-55mhwod6a63ps4ottclomuy72an57his/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/readline-8.0-vlftkqsvkinigldvkpkwgqtsy7ulmycn/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/ncurses-6.2-ccpvja4f5mz6aw7ioz5u7ihdrxbugyzf/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/openssl-1.1.1g-jfooumullita6g74ujk5jgatwvhl7bea/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/sqlite-3.33.0-kgquxoe5whn75qbpfra54ydgoaweu3of/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/gdbm-1.18.1-yfizpfmx2nghsdmhdvxnl7y6drdbkxq7/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/zlib-1.2.11-gfes7f35rppowsinvimnaheom23qbs55/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/bzip2-1.0.8-mlz6pdrikglamnlrn55am5uvxl4xu6lz/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/xz-5.2.5-ou6sagf3ii3lp76leopjcl2kixnz27t5/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/expat-2.2.9-sue4c2adf3iqpbhs573xx4e4rqt2ugmy/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/libffi-3.3-cb3hqvbkpmzm7lt5teoc47243vjdbdxm/lib64 -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/tk-8.6.8-hdasonb3ps5wj22vrvpa2tbf6rpn2myt/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/tcl-8.6.10-xdusiasvah27lmkrbo3qfwuzlnecmdwn/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/libuuid-1.0.3-aaommvjgyqtanujnrt4ksjckrysm3lcn/lib   -fprofile-generate -Xlinker -export-dynamic -o python Programs/python.o -L. -lpython3.8 -lcrypt -lintl -lpthread -ldl  -lutil -lm   -lm 
/home/aznable/spack/lib/spack/env/gcc/gcc -pthread -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/gettext-0.21-55mhwod6a63ps4ottclomuy72an57his/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/readline-8.0-vlftkqsvkinigldvkpkwgqtsy7ulmycn/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/ncurses-6.2-ccpvja4f5mz6aw7ioz5u7ihdrxbugyzf/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/openssl-1.1.1g-jfooumullita6g74ujk5jgatwvhl7bea/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/sqlite-3.33.0-kgquxoe5whn75qbpfra54ydgoaweu3of/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/gdbm-1.18.1-yfizpfmx2nghsdmhdvxnl7y6drdbkxq7/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/zlib-1.2.11-gfes7f35rppowsinvimnaheom23qbs55/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/bzip2-1.0.8-mlz6pdrikglamnlrn55am5uvxl4xu6lz/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/xz-5.2.5-ou6sagf3ii3lp76leopjcl2kixnz27t5/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/expat-2.2.9-sue4c2adf3iqpbhs573xx4e4rqt2ugmy/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/libffi-3.3-cb3hqvbkpmzm7lt5teoc47243vjdbdxm/lib64 -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/tk-8.6.8-hdasonb3ps5wj22vrvpa2tbf6rpn2myt/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/tcl-8.6.10-xdusiasvah27lmkrbo3qfwuzlnecmdwn/lib -L/home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/libuuid-1.0.3-aaommvjgyqtanujnrt4ksjckrysm3lcn/lib   -fprofile-generate -Xlinker -export-dynamic -o Programs/_testembed Programs/_testembed.o -L. -lpython3.8 -lcrypt -lintl -lpthread -ldl  -lutil -lm   -lm 
LD_LIBRARY_PATH=/data/scratch/ssd/tmp/188620345.1.login.q/aznable/spack-stage/spack-stage-python-3.8.5-la275lvn6kira5qdx5vr7b2vq54lzofe/spack-src/spack-build ./python -E -S -m sysconfig --generate-posix-vars ;\
if test $? -ne 0 ; then \
        echo "generate-posix-vars failed" ; \
        rm -f ./pybuilddir.txt ; \
        exit 1 ; \
fi
./python: symbol lookup error: ./python: undefined symbol: __gcov_indirect_call
```

@adamjstewart 

### General information
Turns out the problem is that the compiled python executable /data/scratch/ssd/tmp/188620345.1.login.q/aznable/spack-stage/spack-stage-python-3.8.5-la275lvn6kira5qdx5vr7b2vq54lzofe/spack-src/spack-build/python has picked up a wrong version of libpython38.so in my home directory rather than the one in the same build directory. I think spack should do some environment santization at build time the prune away paths that are not part of the spack built package hiearchy.

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
