### ISSUE TITLE
Developing different specs of the same package in an environment

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#19359]
### Rationale

I'm trying out the new environment dev-build / develop feature, and I think it's great, so thanks a lot @becker33 :).

Two points of general feedback:

1. I can't seem to build two different specs of the same package in a single environment. Seems like a limitation of using keys instead of an array in the `develop` section of an environment file. 

2. It would be great to be able to specify the build directory, since I might want to build out of source with a folder name that I can specify myself

```yaml
spack:
  view: false
  specs:
    - sirius@develop-a ^openblas threads=openmp
    - sirius@develop-b ^intel-mkl
  develop:
    sirius:
      path: path/to/SIRIUS-branch-a
      spec: sirius@develop-a
    sirius: # oops
      path: path/to/SIRIUS-branch-b
      spec: sirius@develop-b
```

### Description

Maybe an alternative & more condensed structure would be:

```yaml
spack:
  view: false
  specs:
    - sirius@develop-a ^openblas threads=openmp
    - sirius@develop-b ^intel-mkl
  develop:
    - spec: sirius@develop-a
      path: path/to/SIRIUS-branch-a
      build_directory: ./SIRIUS-a
    - spec: sirius@develop-b
      path: path/to/SIRIUS-branch-b
      build_directory: ./SIRIUS-b
```
