### ISSUE TITLE
Specify trusted GPG keys in environment and/or configuration.

### ISSUE THREAD

**Issue by rblake-llnl** [LLNL/spack#19561]
I'd like a way to specify which GPG keys to trust in my spack environment.

### Rationale

If I currently want to use a buildcache, I need to tell spack which GPG keys it should trust.  This is a necessary step before anyone can use an environment configured for use with a build cache.  Instead, I'd like to specify trusted GPG keys directly in the environment file and save users some typing.

Something like 
```
spack:
  mirror:
   mymirror: http://url
 config:
   gpg:
     trust:
     - Key1
     - Key2

```

### Description

I have no idea how to implement this, nor do I know how hard it would be to implement.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
