### ISSUE TITLE
Installation issue: llvm

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#19652]
### Steps to reproduce the issue

```console
$ spack install <spec>
...
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikitayama** [comment]
```
packages:
  cuda:
    externals:
    - spec: cuda@11.0.221
      prefix: /home/app/cuda/11.0
```

and I executed on X86:

`$ spack install llvm+cuda+omp_debug cuda_arch=60`
