### ISSUE TITLE
Installation issue: environment-modules

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#19766]
### Steps to reproduce the issue

```console
$ spack install environment-modules
...
--- configuring extension library sources --------
libarglist = --with-tcl=/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tcl-8.6.10-rb5ebcc6dnpuiryq3gwgjrhne5hxez5o/lib/tclConfig.sh
pushd: error retrieving current directory: getcwd: cannot access parent directories: Invalid argument
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Bad file descriptor
checking for uname... ./configure: fork: retry: Resource temporarily unavailable
./configure: fork: retry: Resource temporarily unavailable
./configure: fork: retry: Resource temporarily unavailable
./configure: fork: retry: Resource temporarily unavailable
./configure: fork: Resource temporarily unavailable
```

### Information on your system

* **Spack:** 0.15.4-1831-0e025349f9
* **Python:** 3.8.6
* **Platform:** darwin-catalina-ivybridge

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/5497764/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/5497765/spack-build-env.txt)

@xdelaruelle

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by xdelaruelle** [comment]
@adamjstewart At first sight it seems that the host running this installation hit some resource limit or some external process changes some directory implied in this installation.

Are you able to reproduce this issue on your side. If yes, what is the version of `bash` used to execute the `./configure` script ? Is there some other concurrent tasks running ?

**Comment by adamjstewart** [comment]
@xdelaruelle I would be surprised if a resource limit was the problem. I have plenty of space on my hard drive, and no other concurrent processes running (aside from a web browser).

I just ran this again and the installation succeeded! I still see the same error messages though. I'm using a Spack-installed Bash 5.0.18. Here is the build log from the successful installation:

* [spack-build-out.txt](https://github.com/spack/spack/files/5502164/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/5502166/spack-build-env.txt)

If these error messages seem okay to you, then I'm fine with closing this. If not, let me know if there is any other debug info you would like to see.

**Comment by adamjstewart** [comment]
Ah, nevermind, I think I figured out my problem. I was testing a change in #19761. The problem was that I was mistakenly passing `--with-tcl=/path/to/tcl/lib/tclConfig.sh` instead of `--with-tcl=/path/to/tcl/lib`. Sorry for the noise!

**Comment by adamjstewart** [comment]
I may have spoken too soon. Even after fixing the problem in #19761 it still crashes. Is there any way to limit the parallelism of the configure script? Can you test out #19761 for me?

**Comment by xdelaruelle** [comment]
I am still curious to see the content of your `spack-build-out.txt` with the accurate `--with-tcl` option set as the bash shell running environment-modules ./configure script seems in bad shape in your above attempt.

**Comment by xdelaruelle** [comment]
> I may have spoken too soon. Even after fixing the problem in #19761 it still crashes. Is there any way to limit the parallelism of the configure script? Can you test out #19761 for me?

I will try that with bash installed through spack. Is there other requirement for the test ? May I use the gcc toolchain from my laptop or is llvm mandatory for the test ?

**Comment by adamjstewart** [comment]
I'm honestly not sure. At this point I've gotten the build to fail both on develop and with #19761, so it doesn't seem like #19761 is the problem anymore.

**Comment by xdelaruelle** [comment]
With bash@5.0 installed and loaded, I am not able to reproduce the issue. Could you give me the list of software you have loaded when you try to install environment-modules and if you have used some specific option/variant to build these software.

(also I have rebased on develop, but I cannot find bash@5.0.18, only 5.0)

**Comment by adamjstewart** [comment]
bash 5.0.18 is actually bash@5.0 with all 18 patches applied.

As for loaded packages, I have the following environment activated:
```yaml
spack:
  specs:

  # Shells
  - bash
  - fish

  # Spack dependencies
  - clingo@develop
  - gnupg
  #- graphviz
  - kcov

  # Newer versions of Linux tools
  - watch
  - wget

  # Software installation tools
  - automake
  - autoconf
  - m4
  - cmake
  - ninja
  - patchelf
  - scons

  # Version control systems
  - mercurial
  - subversion

  # Python libraries
  - python
  - py-black
  - py-cartopy
  - py-cmocean
  - py-codecov
  - py-flake8
  - py-jupyterlab
  - py-matplotlib
  - py-mypy
  - py-numpy
  - py-pandas
  - py-pyinstrument
  - py-pytest
  - py-pytest-cov
  - py-pytest-mock
  - py-pytest-runner
  - py-pyyaml
  - py-setuptools
  - py-scikit-learn
  - py-scipy
  - py-sphinx
  - py-sphinx-rtd-theme
  - py-sphinxcontrib-programoutput
  - py-tables
  - py-torch
  - py-torchvision
  - py-vermin

  # Research libraries
  - gdal

  concretization: together
```
I wouldn't bother installing all of those just to try to reproduce this...
