### ISSUE TITLE
Spack not using compiler from packages section of spack.yaml

### ISSUE THREAD

**Issue by birnbera** [LLNL/spack#19934]
I am using a `spack.yaml` file to create an environment inside a Docker container. In order to keep configuration simple and to a minimum I am putting all of it into `spack.yaml`. In particular, I would like to use a particular version of `gcc` to build all of my specs (8.4.0). Here's an example of what my `spack.yaml` looks like:

```yaml
spack:
    specs:
        - python@3.7.8
        - py-pip
    concretization: together
    view: true
    packages:
        all:
            compiler:: [gcc@8.4.0]
        gcc:
            version: [8.4.0]
            buildable: true
    config:
        install_missing_compilers: true
```

### Steps to reproduce the issue

To build the Docker image, I copy the `spack.yaml` file to `/etc/spack.yaml` in the container, clone a fresh copy of `spack`, and create an environment. E.g.:

```dockerfile
COPY spack.yaml /etc/
RUN git clone $SPACK_URL $SPACK_ROOT && \
. $SPACK_ROOT/share/spack/setup-env.sh && \
spack env create myenv /etc/spack.yaml && \
spack activate myenv && \
spack install
```
My expectation is that `spack` will use `gcc@8.4.0` to build Python and will build `gcc@8.4.0` in the process. However, `spack` uses the system `gcc` instead (4.8.5).

Importantly, in keeping with the double colon after `compiler` in the `all` section of `packages`, after the environment is activated if I run `spack config get packages` it shows `gcc@8.4.0` as the only suggested compiler:

```console
$ spack config get packages
packages:
  all:
    compiler: [gcc@8.4.0]
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa+opengl, opengl]
      glx: [mesa+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      iconv: [libiconv]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      rpc: [libtirpc]
      scalapack: [netlib-scalapack]
      sycl: [hipsycl]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
    permissions:
      read: world
      write: user
    buildable: true
    version: []
    target: []
  gcc:
    version: [8.4.0]
    buildable: true
    target: []
    providers: {}
    compiler: []
```

Whereas if you just make it a single colon it merely prepends `gcc@8.4.0` to the list of suggested compilers:

```console
$ spack config get packages
packages:
  all:
    compiler: [gcc@8.4.0, gcc, intel, pgi, clang, xl, nag, fj]
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa+opengl, opengl]
      glx: [mesa+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      iconv: [libiconv]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      rpc: [libtirpc]
      scalapack: [netlib-scalapack]
      sycl: [hipsycl]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
    permissions:
      read: world
      write: user
    buildable: true
    version: []
    target: []
  gcc:
    version: [8.4.0]
    buildable: true
    target: []
    providers: {}
    compiler: []
```

Since I have pinned `gcc` to version 8.4.0, in the above case you would doubly expect `spack` to use `gcc@8.4.0` regardless.

If I directly specify in the Python spec that I want to compile with `gcc@8.4.0`, then `spack` does build `gcc@8.4.0` before building Python with it. I.e. this works:

```yaml
spack:
    specs:
        - python@3.7.8 %gcc@8.4.0
        - py-pip
    concretization: together
    view: true
    config:
        install_missing_compilers: true
```

It seems that the `packages` section is not used for compiler selection during concretization if the compiler is not already present even with `install_missing_compilers: true`.

### Information on your system

```bash
$ spack debug report
* **Spack:** 0.14.1-2401-06b64c3
* **Python:** 2.7.5
* **Platform:** linux-centos7-haswell
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
Right now compilers listed as preferences in `packages.yaml` are only used for concretization if they are already installed. If you were to install the compiler outside of the environment and add it (with `spack compiler add`) then it would be used by the environment.

I'm going to relabel this as a feature since it is actually "working as intended", but I think there should be a more intuitive way to do it (also, as it is now, there's not a way to share an environment with another user which includes a new compiler and have the packages for that environment build with the new compiler).

**Comment by birnbera** [comment]
Hi @scheibelp, thanks for your reply. I was surprised by this behavior since I could specify `gcc@8.4.0` as a direct compiler dependency in the spec and get `spack` to install it without having to run `spack compiler add` first. In this sense, I disagree slightly with your comment about not being able to share environments with other users that include a new compiler; you *can* put the compiler in the spec and set the config option `install_missing_compilers` to `true`, then the environment should work out of the box for someone pulling in the `spack.yaml`.

The main drawback to this is if you have a long list of specs or many compiled dependencies it's not clear that even if you were to specify that one of them should use a particular compiler that they all would. As a result, you'd have to revert to running `spack compiler add` first and then specify it in the `packages` section as above. Now you have another problem, which is that you have to keep the call to `spack compiler add` in sync with `packages` section of the `spack.yaml` file. 

Since you're thinking of this as a new feature, it would be great to have an option in the `packages` section (or `packages.yaml`) to **force** a certain concretization preference using options from a compiler "object" rather than a simple list. So in my example, I could have something like:

```yaml
spack:
    specs:
        - python@3.7.8
        - py-pip
    concretization: together
    view: true
    packages:
        all:
            compiler:
                - gcc@8.4.0
                  required: true
                  buildable: true
    config:
        install_missing_compilers: true
```

That way, with the `install_missing_compilers: true`, Python ends up building with `gcc@8.4.0`. If you were to make `install_missing_compilers: false`, you would get an error rather than the next available compiler in the list of available compilers. Clearly there would also have to be some logic around forbidding multiple "required" compilers, etc.
