### ISSUE TITLE
Which is the correct way to specify the version of a group of dependencies? 

### ISSUE THREAD

**Issue by JavierCVilla** [LLNL/spack#1994]
I know it is possible to force spack to install a package using a concrete version for a dependency through the command line in this way:

`spack install Package ^Spec@X.Y.Z`

Now, I want to use spack to install a batch of packages, not only one. Each package have to use a concrete version, so I define a dictionary in a file (or a json, or similar) with the structure:

```
#external file

packages = {
    pkg1 : version_pkg1,
    pkg2 : version_pkg2,
    ...
}
```

So I have each package with its version in this file and I can modify the version to install in the next build easily. The problem is that I don't know which is the proper way to force spack to use the specified version in this file for `pk2` when it's a dependency of `pkg1`. In other words, I want to install `pkg1` and I specify the version that I want to install on his dependency `pkg2`. When I run spack to install `pkg1`, have I any method to declare the version of his dependencies without put them explicitly in the spack command?

**Comment by davydden** [comment]
you can specify your preferences in `~/packages.yaml`, i.e.
```
packages:
  all:
    compiler: [clang, gcc]
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
  libtool:
    compiler: [clang]
  cmake:
    version: [3.6.1]
    compiler: [clang]
  curl:
    version: [7.50.3]
  openssl:
    version: [1.0.2j]
  python:
    version: [2.7.12]
  boost:
    version: [1.62.0]
    variants: +python
```
