### ISSUE TITLE
Clingo concretizer does not support non-numeric versions

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/spack#20055]
I ran `spack spec` to concretize a package and was unable to concretize using non-numeric compiler or dependent package versions.

### Steps to reproduce the issue

```console
$ spack spec -I hdf5%clang@upstream_gfortran
==> [2020-11-23-10:49:21.285015] The following constraints are unsatisfiable:
  node_compiler_version_hard("hdf5","clang","upstream_gfortran")
  root("hdf5")
```
If the clang version is changed to a fake version (15.7), concretization without MPI succeeds.
But when MPI is added:
```console
$ spack spec -I hdf5+mpi%clang@15.7
==> [2020-11-23-10:50:54.382014] The following constraints are unsatisfiable:
  # a bunch of external_only facts for other MPI providers
  external_only("spectrum-mpi")
  external_version_declared("spectrum-mpi","release",-1,0)
  external_version_declared("spectrum-mpi","release",-2,1)
 # ... other possible_provider clauses for other MPI providers
  node("spectrum-mpi") :- possible_provider("mpi","spectrum-mpi",20).
  root("hdf5")
  single_provider_for("mpi",":") :- real_node("hdf5"),node("hdf5"),variant_value("hdf5","mpi","True").
  variant("hdf5","mpi")
  variant_set("hdf5","mpi","True")
```
Concretization succeeds when the external spectrum-mpi is also converted to use a fake numeric version number.

### Error Message

Above

### Information on your system

* **Spack:** 0.16.0-23-e75b76f43
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** clingo

```yaml
compilers:
- compiler:
    # ...
    spec: clang@upstream_gfortran
```
```yaml
packages:
mpi:
    buildable: false
  spectrum-mpi:
    externals:
      - spec: spectrum-mpi@release%clang@upstream_gfortran
        prefix: /path/to/mpi
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Thanks for the report. I can reproduce with a minimal example using this `compilers.yaml`:
```yaml
compilers:
- compiler:
    spec: clang@upstream_fortran
    paths:
      cc: /usr/bin/clang-3.9
      cxx: /usr/bin/clang++-3.9
      f77:
      fc:
    operating_system: ubuntu18.04
    target: x86_64
```
and trying to concretize:
```console
$ spack solve zlib%clang@upstream_fortran
/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/concretize.lp:302:8-59: info: atom does not occur in any rule head:
  compiler_supports_target(Compiler,Version,Target)

==> The following constraints are unsatisfiable:
  root("zlib")
==> Error: Unsatisfiable spec.
```
The issue is that with the custom version the concretizer cannot determine which target microarchitectures are supported by the compiler.
