### ISSUE TITLE
testing stage before 0.10 release

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2014]
i don't know what is the plan, but i think it would be good to freeze adding any extra features after `0.10` "project" is fulfilled and let everyone try building their favourite packages on their favourite OS+compiler combos. During this time only bug-fix PRs should be accepted. 

Alternatively there could be a seprate `0.10` branch to test. Bugfix PRs could be submitted to this branch and the whole branch can be merged to `develop`.

**Comment by adamjstewart** [comment]
Looks like there was some talk about this at the [last Telecon](https://github.com/LLNL/spack/wiki/Telcon:-2016-10-06). I would be willing to test the HDF4/HDF5/NetCDF/PnetCDF stack for GCC/Intel/PGI and MVAPICH/MPICH/OpenMPI.

**Comment by tgamblin** [comment]
Agree!  Any other volunteers?

**Comment by tgamblin** [comment]
@lee218llnl @alalazo @davydden @citibeth @mamelara

**Comment by davydden** [comment]
I an willing to test deal.ii on Ubuntu+GCC and Sierra with Clang+Gfortran.

**Comment by citibeth** [comment]
Make it easy for me... create a script full of `spack install` commands that can run without any `packages.yaml` in place.  I'll set it running on CentOS 7 and send back the logs.

**Comment by tgamblin** [comment]
I agree with @citibeth -- if we do testing we should just have the specs to be tested for releases written down someplace.  And we might consider multiplexing them with several different `packages.yaml` files to see how they do for compilers/MPI implementations.

What if we had a `release-test.yaml` similar to `travis.yml`, with the different configurations to try:

```yaml
release-test:
    # package specs below are installed using each of these
    # stack for concretization preferences.
    stacks:
        - intel-stack:
            # content of packages.yaml for intel builds goes here
        - gcc-stack:
            # content of packages.yaml for gcc builds goes here
            exclude:
                - # spec to exclude for gcc stack
    # Specs to install from the command line
    specs:
        - hdf
        - hdf5
        - netcdf
        - netcdf~mpi
        - etc.
```

We can iterate on this but I think we need a YAML description for Spack test matrices.  Then it would be very easy to define combinatorial test-suites.  And it would also give me a starting point for building a dashboard to report the build status of all the packages.

Possible addition to the above list: options to say how to combine variants/versions for each spec.
