### ISSUE TITLE
Clingo concretizer does not support numeric versions in CUDA packages

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/spack#20231]
This appears to be an extension of #20055 - I have been able to reproduce this with a handful of `CudaPackage`s.

### Steps to reproduce the issue

```console
$ spack spec -I ginkgo%clang@foo+cuda
```

```yaml
compilers:
- compiler:
    spec: clang@foo
    paths:
      cc: /usr/tce/packages/clang/clang-9.0.0/bin/clang
      cxx: /usr/tce/packages/clang/clang-9.0.0/bin/clang++
      f77:
      fc:
    target: ppc64le
    operating_system: rhel7
```

### Error Message

```console
spack/lib/spack/spack/util/executable.py:162 ==> [2020-12-03-06:52:04.720236] '/usr/tce/packages/clang/clang-9.0.0/bin/clang' '--version'

==> The following constraints are unsatisfiable:
  :- node("ginkgo"),variant_value("ginkgo","cuda","True"),node_compiler("ginkgo","clang"),node_compiler_version_satisfies("ginkgo","clang",":5"),node("cuda"),version_satisfies("cuda","11.0.2:"),node_platform("cuda","linux"),node_target_satisfies("cuda","ppc64le:"),not external("ginkgo").
  compiler_version("clang","foo")
  declared_dependency("ginkgo","cuda","build") :- node("ginkgo"),variant_value("ginkgo","cuda","True").
  external_only("cuda")
  node_compiler_version_hard("ginkgo","clang","foo")
  node_platform_default("linux")
  root("ginkgo")
  target("power8le")
  target("power9le")
  target("ppc64le")
  variant("ginkgo","cuda")
  variant_set("ginkgo","cuda","True")
  version_declared("cuda","10.1.243",3)
  version_declared("cuda","10.2.89",2)
  version_declared("cuda","11.1.0",0)
  version_satisfies("cuda","9:") :- depends_on("ginkgo","cuda"),node("ginkgo"),variant_value("ginkgo","cuda","True").
==> Error: ginkgo%clang@foo+cuda does not satisfy unknown

```

It looks like it queries the version (per the fix in #20099) but the `node_compiler_version_hard` looks like it might need to contain the "real" version.

Concretization succeeds if `foo` is changed to the real version, `9.0.0`.

### Information on your system

* **Spack:** 0.16.0-148-05848c87c
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
