### ISSUE TITLE
Concretize mixing architectures in dependencies (Theta)

### ISSUE THREAD

**Issue by giltirn** [LLNL/spack#20491]
I am trying to create an environment on ALCF Theta (Cray XC40) that installs all my dependencies. Among them is a more recent version of Python than is available on the system. The problem is that while I want the majority of specs to be cross-compiled for the KNL compute nodes, I want Python to be usable from the login and job head nodes which are Haswell cores (any Haswell code will of course work on KNL, albeit with a potential performance hit). My environment spack.yaml is as follows:

```
spack:
  specs:
  - python@3.6.0 %gcc@9.3.0-cray arch=cray-cnl7-haswell
  - cereal@1.3.0 %gcc@9.3.0-cray arch=cray-cnl7-mic_knl
  - libzmq@4.3.2 %gcc@9.3.0-cray arch=cray-cnl7-mic_knl
  - googletest@1.10.0 %gcc@9.3.0-cray arch=cray-cnl7-mic_knl
  - adios2 @2.6.0 %gcc@9.3.0-cray ^libfabric@1.9.0 arch=cray-cnl7-mic_knl
  - py-mochi-sonata ^mochi-sonata@master ^python@3.6.0 %gcc@9.3.0-cray ^libfabric@1.9.0 arch=cray-cnl7-mic_knl
  - mochi-sonata +benchmark @master %gcc@9.3.0-cray ^libfabric@1.9.0 arch=cray-cnl7-mic_knl
  - mercury @master %gcc@9.3.0-cray ^libfabric@1.9.0 arch=cray-cnl7-mic_knl
  concretization: together
  compilers:
  - compiler:
      spec: gcc@9.3.0-cray
      paths:
        cc: /opt/cray/pe/craype/2.6.5/bin/cc
        cxx: /opt/cray/pe/craype/2.6.5/bin/CC
        f77: /opt/cray/pe/craype/2.6.5/bin/ftn
        fc: /opt/cray/pe/craype/2.6.5/bin/ftn
      flags: {}
      operating_system: cnl7
      target: any
      modules:
      - PrgEnv-gnu
      - gcc/9.3.0
      - craype-mic-knl
      - cray-mpich/7.7.10
      environment:
        unset: []
      extra_rpaths: []
  repos:
  - /gpfs/mira-home/ckelly/install_chimbuko/sds/sds-repo
  upstreams:
    alcf-spack:
      install_tree: /soft/spack/root/opt/spack
  packages:
    all:
      compiler:
      - gcc@9.3.0-cray
      providers:
        mpi:
        - mpich
        pkgconfig:
        - pkg-config
      buildable: true
      version: []
      target: []
    mpich:
      buildable: false
      compiler: []
      version: []
      target: []
      providers: {}
      externals:
      - spec: mpich@7.7.10 %gcc@9.3.0-cray arch=cray-cnl7-mic_knl
        modules:
        - cray-mpich/7.7.10
    pkg-config:
      buildable: false
      compiler: []
      version: []
      target: []
      providers: {}
      externals:
      - spec: pkg-config@0.28 %gcc@9.3.0-cray arch=cray-cnl7-mic_knl
        prefix: /usr
    autoconf:
      buildable: false
      compiler: []
      version: []
      target: []
      providers: {}
      externals:
      - spec: autoconf@2.69%gcc@9.3.0-cray arch=cray-cnl7-mic_knl
        prefix: /usr
    automake:
      buildable: false
      compiler: []
      version: []
      target: []
      providers: {}
      externals:
      - spec: automake@1.13.4%gcc@9.3.0-cray arch=cray-cnl7-mic_knl
        prefix: /usr
    bzip2:
      buildable: false
      compiler: []
      version: []
      target: []
      providers: {}
      externals:
      - spec: bzip2@1.0.6%gcc@9.3.0-cray arch=cray-cnl7-mic_knl
        prefix: /usr
    zlib:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: zlib
        prefix: /usr
    openssl:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: openssl@1.1.1d
        prefix: /usr
    gdbm:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: gdbm
        prefix: /usr
    m4:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: m4
        prefix: /usr

    cmake:
      buildable: false
      compiler: []
      version: []
      target: []
      providers: {}
      externals:
      - spec: cmake@3.18.0%gcc@9.3.0-cray arch=cray-cnl7-mic_knl
        modules:
        - cmake/3.18.0



  view: true
```

However when concretizing I find that the dependencies are getting mixed up, with some being built with mic_knl and some with haswell. As a result the install of Python will not work on the head nodes.

```
ckelly@thetalogin6:~/install_chimbuko/sds> spack concretize -f
==> Concretized python@3.6.0%gcc@9.3.0-cray arch=cray-cnl7-haswell
 -   vf36ain  python@3.6.0%gcc@9.3.0-cray+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=ebdca648c9c1d25f586d7e2a495b62e6d91973b55264a13d89eda1beff72ef56 arch=cray-cnl7-haswell
[+]  albvl5x      ^bzip2@1.0.6%gcc@9.3.0-cray+shared arch=cray-cnl7-mic_knl
 -   h5vrrea      ^expat@2.2.10%gcc@9.3.0-cray+libbsd arch=cray-cnl7-haswell
 -   xrvm2xw          ^libbsd@0.10.0%gcc@9.3.0-cray arch=cray-cnl7-haswell
 -   rhegyfi      ^gdbm@1.18.1%gcc@9.3.0-cray arch=cray-cnl7-mic_knl
 -   ofd327t      ^gettext@0.21%gcc@9.3.0-cray+bzip2+curses+git~libunistring+libxml2+tar+xz arch=cray-cnl7-haswell
[+]  v7scibr          ^libiconv@1.16%gcc@9.3.0-cray arch=cray-cnl7-mic_knl
 -   rsmirl2          ^libxml2@2.9.10%gcc@9.3.0-cray~python arch=cray-cnl7-haswell
[+]  z47aiol              ^pkg-config@0.28%gcc@9.3.0-cray+internal_glib patches=49ffcd644e190dc5efcb2fab491177811ea746c1a526f75d77118c2706574358 arch=cray-cnl7-mic_knl
 -   blpwz5r              ^xz@5.2.5%gcc@9.3.0-cray~pic arch=cray-cnl7-haswell
[+]  w72h6fk              ^zlib@1.2.11%gcc@9.3.0-cray+optimize+pic+shared arch=cray-cnl7-mic_knl
 -   f4mjorj          ^ncurses@6.2%gcc@9.3.0-cray~symlinks+termlib arch=cray-cnl7-haswell
 -   w3tp7lv          ^tar@1.32%gcc@9.3.0-cray arch=cray-cnl7-haswell
[+]  5r3rs6d      ^libffi@3.3%gcc@9.3.0-cray patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=cray-cnl7-mic_knl
 -   jkc22se      ^libuuid@1.0.3%gcc@9.3.0-cray arch=cray-cnl7-haswell
 -   tq5pt7h      ^openssl@1.1.1d%gcc@9.3.0-cray+systemcerts arch=cray-cnl7-mic_knl
 -   a47tq6j      ^readline@8.0%gcc@9.3.0-cray arch=cray-cnl7-mic_knl
 -   xk53fxs      ^sqlite@3.33.0%gcc@9.3.0-cray+column_metadata+fts~functions~rtree arch=cray-cnl7-haswell
```

My thought was that I would need a separate compiler, but adding the compiler

```
  - compiler:
      spec: gcc@9.3.0-haswell
      paths:
        cc: /opt/cray/pe/craype/2.6.5/bin/cc
        cxx: /opt/cray/pe/craype/2.6.5/bin/CC
        f77: /opt/cray/pe/craype/2.6.5/bin/ftn
        fc: /opt/cray/pe/craype/2.6.5/bin/ftn
      flags: {}
      operating_system: cnl7
      target: any
      modules:
      - PrgEnv-gnu
      - gcc/9.3.0
      - craype-mic-haswell
      - cray-mpich/7.7.10
      environment:
        unset: []
      extra_rpaths: []
```

and changing the python spec:

`  - python@3.6.0 %gcc@9.3.0-haswell arch=cray-cnl7-haswell`

I get the most unhelpful error when reconcretizing:

`==> Error: gcc@9.3.0-cray does not satisfy gcc@9.3.0-haswell`

It's possible that the packages->all->compiler definition is causing the problem here, but I don't know how to override it. 

I'd appreciate any help you can provide.

* **Spack:** 0.16.0-123-42ed6e25e
* **Python:** 3.6.10
* **Platform:** cray-sles15-haswell
* **Concretizer:** original

- [x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output
