### ISSUE TITLE
Clingo concretizer does not use compiler to "tie-break" package versions

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/spack#20580]
### Steps to reproduce the issue

`compilers.yaml`:
```yml
compilers:
- compiler:
    spec: clang@10.0.0
    # ...
- compiler:
    spec: gcc@8.3.1
    # ...
```

`packages.yml`:
```yml
packages:
  mvapich2:
    externals:
    - spec: mvapich2@2.3%clang@10.0.0
      prefix: # ...
    - spec: mvapich2@2.3%gcc@8.3.1
      prefix: # ...
```

```console
$ spack spec -I hdf5+mpi%gcc@8.3.1
$ spack spec -I hdf5+mpi%clang@10.0.0
...
```

### Error Message

```console
Input spec
--------------------------------
 -   hdf5%gcc@8.3.1+mpi

Concretized
--------------------------------
==> The following constraints are unsatisfiable:
  declared_dependency("hdf5","mpi","build") :- node("hdf5"),variant_value("hdf5","mpi","True").
  # other mpi implementations...
  external_only("mvapich2")
  external_version_declared("mvapich2","2.3",-1,0)
  external_version_declared("mvapich2","2.3",-2,1)
  root("hdf5")
  variant("hdf5","mpi")
  variant_set("hdf5","mpi","True")
  virtual("mpi")
==> Error: hdf5%gcc@8.3.1+mpi does not satisfy unknown

```

Commenting out one of the mvapich externals allows this to concretize but the expected behavior is that the external whose compiler matches the requested compiler is selected.

### Information on your system

* **Spack:** 0.16.0
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
