### ISSUE TITLE
Modules projections always prepend `-` to hash

### ISSUE THREAD

**Issue by adrien-cotte** [LLNL/spack#20605]
Hello,

When I set the modules projections, "{architecture}" seems hard coded at the beginning of the path and "-{hash}" at the end.
I would like a path like this:

```
${HOME}/products/zlib-1.2.11/linux-centos7-haswell/j7b7tbjytsg6yfwe2vicshv4zygmidid
${HOME}/modules/zlib-1.2.11/linux-centos7-haswell/j7b7tbjytsg6yfwe2vicshv4zygmidid
```

### Steps to reproduce the issue

First, this is my file to reproduce:
```console
$ cat << EOF > spack.yaml
spack:

  config:
    install_tree:
      root: "${HOME}/products"
      projections:
        all: "${PACKAGE}-${VERSION}/${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${HASH}"
    module_roots:
      tcl: "${HOME}/modules"
    shared_linking: 'rpath'

  modules:
    tcl:
      hash_length: 32
      projections:
        all: '{name}-{version}/{architecture}/{compiler.name}-{compiler.version}/'

  view: false

  specs:
  - zlib
EOF
```

Then, let's install this env:

```console
$ spack env create reproducer ./spack.yaml
$ spack -e reproducer install
```
Finally, check products and modules paths:

```console
$ [ -e ${HOME}/products/zlib-1.2.11/linux-centos7-haswell/gcc-4.8.5/pkmj6e72vggig3epxjcwxgzmxncaqnmp ] ; echo $?
0
$ [ -e ${HOME}/modules/zlib-1.2.11/linux-centos7-haswell/gcc-4.8.5/pkmj6e72vggig3epxjcwxgzmxncaqnmp ] ; echo $?
1
```
As describe in spack.yaml, modules and products must have the same path (except at root) but instead there is the module path:

```console
$ [ -e ${HOME}/modules/linux-centos7-haswell/zlib-1.2.11/linux-centos7-haswell/gcc-4.8.5/-pkmj6e72vggig3epxjcwxgzmxncaqnmp ] ; echo $?
0
```
There are `linux-centos7-haswell/` as prefix and `-pkmj6e72vggig3epxjcwxgzmxncaqnmp` as suffix (I don't if it's clear but there is a "-" that I don't want).

### Information on your system

spack debug report
```
* **Spack:** 0.16.0-406-8f9297071
* **Python:** 2.7.5
* **Platform:** linux-centos7-haswell
* **Concretizer:** original
```

spack.yaml
```
spack:

  config:
    install_tree:
      root: "${HOME}/products"
      projections:
        all: "${PACKAGE}-${VERSION}/${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${HASH}"
    module_roots:
      tcl: "${HOME}/modules"
    shared_linking: 'rpath'

  modules:
    tcl:
      hash_length: 32
      projections:
        all: '{name}-{version}/{architecture}/{compiler.name}-{compiler.version}/'

  view: false

  specs:
  - zlib
```

### Additional information

Maybe this is not a bug but a feature, I don't know.
But this (very ugly) patch did the job to fix my problem:
```
diff --git a/lib/spack/spack/modules/common.py b/lib/spack/spack/modules/common.py
index fb688e4f1..4e254b409 100644
--- a/lib/spack/spack/modules/common.py
+++ b/lib/spack/spack/modules/common.py
@@ -573,7 +573,7 @@ def use_name(self):
         name = os.path.join(*parts)
         # Add optional suffixes based on constraints
         path_elements = [name] + self.conf.suffixes
-        return '-'.join(path_elements)
+        return ''.join(path_elements)
 
     @property
     def filename(self):
@@ -583,7 +583,7 @@ def filename(self):
         if self.extension:
             filename = '{0}.{1}'.format(self.use_name, self.extension)
         # Architecture sub-folder
-        arch_folder = str(self.spec.architecture)
+        arch_folder = ""
         # Return the absolute path
         return os.path.join(self.dirname(), arch_folder, filename)

```

Many thanks,
Adrien
