### ISSUE TITLE
Different linking behavior between spack load vs module load

### ISSUE THREAD

**Issue by s-sajid-ali** [LLNL/spack#20756]
### Details

For the following build of `openmpi`, I'm seeing a difference in behavior between `spack load` and `module load`. While using `spack load`, this build of `openmpi` is able to compile a test program but when using `module load`, it fails with a link error. Moreover, while it works with `spack load`, the same aforementioned linker error occurs inside a spack environment.

```
[sajid@xrm-backup test]$ spack find -ldv /syuu
==> 1 installed package
-- linux-rhel8-skylake_avx512 / clang@11.0.0 --------------------
syuuj6l openmpi@4.1.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=ucx,xpmem schedulers=none
iwlfut4     hwloc@2.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared
5lie7x5         libpciaccess@0.16
pngedkl         libxml2@2.9.10~python
tqv7s2m             libiconv@1.16
upcuvsx             xz@5.2.5~pic
rzzwkeg             zlib@1.2.11+optimize+pic+shared
mnhnykb     libevent@2.1.8+openssl
oifxmgy         openssl@1.1.1i+systemcerts
dmpip3f     numactl@2.0.14 patches=4e1d78cbbb85de625bad28705e748856033eaafab92a66dffd383a3d7e00cc94
crrzgox     ucx@1.9.0~assertions~cuda~debug~gdrcopy~java~knem~logging+optimizations~parameter_checking+pic+thread_multiple+xpmem cuda_arch=none
ff4ssqk         rdma-core@32.0~ipo build_type=RelWithDebInfo
mtlcksx             libnl@3.3.0
wejool4         xpmem@master+kernel-module

[sajid@xrm-backup test]$
```
#### via `spack load`
```
[sajid@xrm-backup test]$ module purge && spack unload --all && spack load /syuu
[sajid@xrm-backup test]$ mpicc test.c
[sajid@xrm-backup test]$ mpirun -np 2 ./a.out
"Hello World!" from MPI process 0. We are 2 MPI processes.
"Hello World!" from MPI process 1. We are 2 MPI processes.
[sajid@xrm-backup test]$
```

#### via `module load`
```
[sajid@xrm-backup test]$ module purge && spack unload
[sajid@xrm-backup test]$ module load openmpi-4.1.0-clang-11.0.0-syuuj6l
[sajid@xrm-backup test]$ mpicc test.c
/usr/bin/ld: cannot find -lxpmem
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
[sajid@xrm-backup test]$
```

#### as part of a spack environment
```
[sajid@xrm-backup test]$ spack env activate pirt-debug
[sajid@xrm-backup test]$ mpicc test.c
/usr/bin/ld: cannot find -lxpmem
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
[sajid@xrm-backup test]$
```

### Information on your system

```
[sajid@xrm-backup ~]$ spack debug report
* **Spack:** 0.11.2-10315-2f19346c9a
* **Python:** 3.6.8
* **Platform:** linux-rhel8-skylake_avx512
* **Concretizer:** original
[sajid@xrm-backup ~]$ cd packages/spack/
[sajid@xrm-backup spack]$ git log -n 1
commit 2f19346c9af459770aa879d2ee0b9dfde6ddbaff (HEAD -> develop, origin/develop, origin/HEAD)
Author: Robert Underwood <robertu94@users.noreply.github.com>
Date:   Thu Jan 7 15:58:33 2021 -0500

    py-scikit-learn: do parallel builds of C extension (#20733)

    Enabled parallel builds of the C-extension upto the parallelism allowed
    by spack.

    https://scikit-learn.org/stable/developers/advanced_installation.html#parallel-builds
[sajid@xrm-backup spack]$
```
#### `packages.yaml`
```
[sajid@xrm-backup ~]$ cat .spack/packages.yaml
packages:
  xpmem:
    externals:
      - spec: xpmem@master
        prefix: /opt/xpmem

[sajid@xrm-backup ~]$
```

#### `compilers.yaml`
```
[sajid@xrm-backup ~]$ cat .spack/linux/compilers.yaml
compilers:
- compiler:
    spec: gcc@8.3.1
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77:
      fc:
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.2.0
    paths:
      cc: /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/gcc-10.2.0-tt7scqffkarojn55xuhvwoqcmpfllqy4/bin/gcc
      cxx: /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/gcc-10.2.0-tt7scqffkarojn55xuhvwoqcmpfllqy4/bin/g++
      f77: /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/gcc-10.2.0-tt7scqffkarojn55xuhvwoqcmpfllqy4/bin/gfortran
      fc: /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/gcc-10.2.0-tt7scqffkarojn55xuhvwoqcmpfllqy4/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@11.0.0
    paths:
      cc:  /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/llvm-11.0.0-kw6zv7stfmz57ul5vccdif4ywqh6qga6/bin/clang
      cxx: /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/llvm-11.0.0-kw6zv7stfmz57ul5vccdif4ywqh6qga6/bin/clang++
      f77: /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/gcc-10.2.0-tt7scqffkarojn55xuhvwoqcmpfllqy4/bin/gfortran
      fc:  /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/gcc-10.2.0-tt7scqffkarojn55xuhvwoqcmpfllqy4/bin/gfortran
    flags:
      cflags :   -O2 -march=skylake-avx512 -mtune=skylake-avx512
      cxxflags : -O2 -march=skylake-avx512 -mtune=skylake-avx512
      fflags :   -O2 -march=skylake-avx512 -mtune=skylake-avx512
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths:
      - /home/sajid/packages/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-8.3.1/gcc-10.2.0-tt7scqffkarojn55xuhvwoqcmpfllqy4/lib64/libgfortran.so
[sajid@xrm-backup ~]$
```

### Additional information
- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output
