### ISSUE TITLE
Spack hangs during installation when target architecture is provided by spack.yaml file

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#20834]
I'm on the Theta supercomputer. I have a spack.yaml file describing an environment I want to install. When I create the environment, activate it, then type `spack install`, spack hangs indefinitely on this message:

```
==> No binary for argobots-1.0-fmw2ekbof2tuxbqb6b2a3tdynnrp3pvi found: installing from source
```

(The argobots package here is for the example; it blocks just as well when the environment contains anoother packages)

After experimenting with many variants of my spack.yaml file, I found that spack will hang if and only if the `target` field is provided. For example the following minimal spack.yaml will make spack hang:

```
spack:
  specs:
  - argobots%gcc@9.3.0
  packages:
    all:
      target:
      - mic_knl
  view: true
```
... but removing the two lines about the `target` makes it work fine.

For the sake of full reproducibility, here is a more complete spack.yaml file that also includes the compiler, so no yaml file is required in ~/.spack:

```
spack:
  specs:
  - argobots%gcc@9.3.0
  compilers:
  - compiler:
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      operating_system: cnl7
      target: any
      modules:
      - PrgEnv-gnu
      - gcc/9.3.0
      environment: {}
      extra_rpaths: []
      flags: {}
      spec: gcc@9.3.0
  packages:
    all:
      providers:
        mpi: [ mpich ]
      compiler:
      - gcc@9.3.0
      target:
      - mic_knl
      version: []
      buildable: true
```
### Steps to reproduce the issue

Copy the above spack.yaml on Theta.

```console
$ spack env create myenv spack.yaml
$ spack env activate myenv
$ spack install
...
```

### Error Message

```console
$ spack --debug --stacktrace install
```
The above shows the following debug message from spack many times before blocking:

```
gpfs/mira-home/mdorier/spack/lib/spack/spack/compilers/__init__.py:446 ==> [2021-01-13-11:46:50.769068] Multiple definitions of compiler gcc@9.3.0for architecture cray-cnl7-mic_knl:
 [gcc(cc
     CC
     ftn
     ftn
     ['PrgEnv-gnu', 'gcc/9.3.0']
     cnl7), gcc(cc
     CC
     ftn
     ftn
     ['PrgEnv-gnu', 'gcc/9.3.0']
     cnl7)]
```

I initially thought that spack was finding both the compiler definition in my ~/.spack/compilers.yaml file and in the spack.yaml file, but (1) the problem still persists if I remove gcc@9.3.0 from my compilers.yaml file, and (2) the problem still persists if I remove the compiler definition from the spack.yaml file.

### Information on your system

* **Spack:** 0.16.0 (tested with develop as well)
* **Python:** 3.6.10
* **Platform:** cray-sles15-haswell

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
