### ISSUE TITLE
Configuration scopes not working as expected for user level config on all packages

### ISSUE THREAD

**Issue by tmadlener** [LLNL/spack#20936]
As stated in the documentation user level configurations should take precedence over site level configurations. I have run into slightly unexpected behavior, where I have a variant which I want to set for all my packages in my user config, and this seems to not be applied to packages which have variants defined in the site level config.

### Steps to reproduce the issue

In more concrete terms:
`~/.spack/linux/packages.yaml` contains:
```yaml
packages:
  all:
    compiler: [gcc@8.3.0]
    variants: cxxstd=17
```
and the site level config in `$(prefix)/etc/spack/packages.yaml` contains:
```yaml
packages:
  geant4:
    variants: ~qt~opengl+vecgeom
```

Now I would have expected that the default concretized spec I get for `geant4` would be something along the lines of `geant4 ~qt~opengl+vecgeom cxxstd=17`, but instead I get the following:

```console
spack spec geant4
```
```
Input spec
--------------------------------
geant4

Concretized
--------------------------------
geant4@10.7.0%gcc@8.3.0~ipo~motif~opengl~python~qt+threads+vecgeom~x11 build_type=RelWithDebInfo cxxstd=11 arch=linux-centos7-haswell
[...]
```
As you can see, the `cxxstd=17` variant from my user level configuration is not applied on top of the sit level configuration, but instead the default `cxxstd=11` is used. Is this the intended behavior? I.e. is "adding" user level configuration for `all` packages to site level configuration of specific packages not possible? I would have naively expected that this should work.

### Information on your system
```console
spack debug report
```
```
* **Spack:** 0.16.0-656-330c48b
* **Python:** 2.7.5
* **Platform:** linux-centos7-haswell
* **Concretizer:** original
```

For completeness:
```console
spack config get packages
```
```
packages:
  all:
    compiler: [gcc@8.3.0, gcc, intel, pgi, clang, xl, nag, fj, aocc]
    variants: cxxstd=17
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas, amdblis]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw, amdfftw]
      gl: [mesa+opengl, mesa18, opengl]
      glx: [mesa+glx, mesa18+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      iconv: [libiconv]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas, amdlibflame]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      osmesa: [mesa+osmesa, mesa18+osmesa]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      rpc: [libtirpc]
      scalapack: [netlib-scalapack, amdscalapack]
      sycl: [hipsycl]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
      yacc: [bison, byacc]
      flame: [libflame, amdlibflame]
      uuid: [util-linux-uuid, libuuid]
    permissions:
      read: world
      write: user
  geant4:
    variants: ~qt~opengl+vecgeom
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output
