### ISSUE TITLE
`.real_version` not working as intended

### ISSUE THREAD

**Issue by maxim-belkin** [LLNL/spack#21344]
Tried to install Clingo on a Cray system (Blue Waters). Default compiler is gcc@6.3.0.

### Steps to reproduce the issue

```console
$ spack install clingo
...[snip]...
==> Installing clingo-master-7cfrbcc7vks2dbnzklogk5fpapsy7kof
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for clingo-master-7cfrbcc7vks2dbnzklogk5fpapsy7kof found: installing from source
==> clingo: Executing phase: 'cmake'
==> Error: NameError: global name 'UnsupportedCompilerFlag' is not defined

/mnt/abc/u/staff/mbelkin/spack/var/spack/repos/builtin/packages/clingo/package.py:56, in cmake_args:
         53    def cmake_args(self):
         54        try:
         55            self.compiler.cxx14_flag
  >>     56        except UnsupportedCompilerFlag:
         57            InstallError('clingo requires a C++14-compliant C++ compiler')
         58
         59        return [

See build log for details:
  /tmp/mbelkin/spack-stage/spack-stage-clingo-master-7cfrbcc7vks2dbnzklogk5fpapsy7kof/spack-build-out.txt
```

### Error Message

Didn't do this step as I pinged @adamjstewart for help and his proposed fix (changing `.real_version` to `.version` in `lib/spack/spack/compilers/gcc.py`) solved the problem. I can execute this step without the "fix" if desired.

```console
$ spack --debug --stacktrace <command>
```

### Information on your system

<details>
<summary><code>spack debug report</code></summary>

```
$ spack debug report
* **Spack:** 0.16.0-913-6b13909cc1
* **Python:** 2.6.9
* **Platform:** cray-suse_linux11-bulldozer
* **Concretizer:** clingo
```

</details>

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
> ```
> ==> Error: NameError: global name 'UnsupportedCompilerFlag' is not defined
> ```

This specific error is easy to fix with imports. The bigger error is that `self.compiler.cxx14_flag` isn't working for GCC 6.3.0, which definitely supports C++14.

@becker33 I believe this logic was introduced in #18179. Can you take a look at this? @maxim-belkin and I both have access to BW so we can try making changes and testing them. We're both also on Slack if you want to discuss there.

**Comment by adamjstewart** [comment]
@maxim-belkin I just tried reproducing this on BW but I'm having trouble. What does your `compilers.yaml` entry look like? Mine looks like:
```yaml
- compiler:
    paths:
      cc: /opt/gcc/6.3.0/bin/gcc
      cxx: /opt/gcc/6.3.0/bin/g++
      f77: /opt/gcc/6.3.0/bin/gfortran
      fc: /opt/gcc/6.3.0/bin/gfortran
    operating_system: suse_linux11
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@6.3.0
```
Can you make the following changes and share the output?
```diff
--- a/lib/spack/spack/compiler.py
+++ b/lib/spack/spack/compiler.py
@@ -521,11 +521,13 @@ def get_real_version(self):
         Use the runtime environment of the compiler (modules and environment
         modifications) to enable the compiler to run properly on any platform.
         """
+        print(self.cc)
         cc = spack.util.executable.Executable(self.cc)
         with self._compiler_environment():
             output = cc(self.version_argument,
                         output=str, error=str,
                         ignore_errors=tuple(self.ignore_version_errors))
+            print(output)
             return self.extract_version_from_output(output)
 
     #
```
This will let us see which compiler is actually being run and what version is being reported. If you run with `spack --debug` it will give us more info. You'll have to undo the `.real_version` changes.

**Comment by becker33** [comment]
Merged the first part of the fix. Now we just have the version discrepancy.

**Comment by maxim-belkin** [comment]
My `compilers.yaml` looks somewhat different (see the full listing below) -- it lists GCC and PGI compilers for the backend nodes (running CNL) that `spack compiler find` was able to find. So, the corresponding value for `gcc@6.3.0` is:

```
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/6.3.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@6.3.0
```

Then in `packages.yaml` I have: 
```
packages:
  all:
    compiler: [gcc@6.3.0, pgi@18.10.0]
```

And after the above patch I see:

```
cc
6.3.0
```

Should I keep "front-end" compilers instead? 

<details><summary><b><code>compilers.yaml</code></b></summary>

```
compilers:
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/14.2.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@14.2.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/15.9.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@15.9.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/17.5.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@17.5.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/14.4.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@14.4.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/16.3.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@16.3.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/18.10.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@18.10.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/15.10.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@15.10.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/16.4.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@16.4.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/18.3.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@18.3.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/15.3.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@15.3.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/16.5.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@16.5.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/18.7.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@18.7.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/15.7.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@15.7.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-pgi
    - pgi/16.9.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: pgi@16.9.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/13.1.3.192
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@13.1.3.192
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/16.0.0.109
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@16.0.0.109
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/14.0.0.080
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@14.0.0.080
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/16.0.2.181
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@16.0.2.181
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/18.0.3.222
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@18.0.3.222
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/14.0.1.106
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@14.0.1.106
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/16.0.3.210
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@16.0.3.210
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/14.0.4.211
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@14.0.4.211
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/18.0.6.288
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@18.0.6.288
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/15.0.090
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@15.0.090
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/16.0.4.258
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@16.0.4.258
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/15.0.3.187
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@15.0.3.187
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-intel
    - intel/17.0.4.196
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@17.0.4.196
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/4.6.1
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.6.1
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/4.9.3
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.9.3
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/4.7.3
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.7.3
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/5.1.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@5.1.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/4.8.1
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8.1
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/5.2.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@5.2.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/4.8.2
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8.2
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/5.3.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@5.3.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/7.3.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@7.3.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/4.9.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.9.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/6.1.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@6.1.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/8.2.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@8.2.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/4.9.1
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.9.1
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/6.2.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@6.2.0
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/4.9.2
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.9.2
- compiler:
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: cnl5
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/6.3.0
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@6.3.0
```
</details>
