### ISSUE TITLE
Global Variants

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2165]
I'm not sure if this has already been proposed before, but I would like to be able to set variants globally. The corresponding `packages.yaml` would look like:

``` yaml
packages:
  all:
    variants: ~mpi~docs~gui
```

This could be used to solve problems like #2095 and others, where a lot of users never want to build documentation or X11/GUI support.
