### ISSUE TITLE
Installation issue: cray-mpich

### ISSUE THREAD

**Issue by albestro** [LLNL/spack#21696]
### Steps to reproduce the issue

@victorusu @haampie 

```console
$ ftn a.f90
$ spack load cray-mpich/wyfi76i
$ ftn a.f90
a.f90:2:4:

 use mpi
    1
Fatal Error: Can't open module file 'mpi.mod' for reading at (1): No such file or directory
compilation terminated.
$ unset C_INCLUDE_PATH
$ ftn a.f90
$
```

This is just a minimal example, but my initial problem was inside an environment (without calling directly `spack load`)

### Information on your system

* **Spack:** 0.16.0-1199-bff4469d8f
* **Python:** 3.8.2
* **Platform:** cray-sles15-broadwell
* **Concretizer:** original

```yaml
packages:
  ...
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@7.7.15
      modules:
      - cray-mpich/7.7.15
```
### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
