### ISSUE TITLE
Installation issue: ParaView is over-reliant on LD_LIBRARY_PATH for setting up python link

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#21759]
### Steps to reproduce the issue

@chuckatkins @danlipsa For environments that blacklist environment variables, specifically LD_LIBRARY_PATH, paraview needs a different way to set up the python link.

This can be reproduced using an environment similar to this:
```yaml
# This is a Spack Environment file.
# 
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - paraview
  - python
  packages:
    paraview:
      version: [5.9.0]
      variants: [+python3]
    openmpi:
      buildable: false
      externals:
      - spec: openmpi@2.1.6
        modules:
        - openmpi/2.1.6-gcc_8.3.0
  compilers:
  - compiler:
      spec: gcc@8.3.0
      paths:
        cc: /projects/opt/x86_64/gcc/8.3.0/bin/gcc
        cxx: /projects/opt/x86_64/gcc/8.3.0/bin/g++
        f77: /projects/opt/x86_64/gcc/8.3.0/bin/gfortran
        fc: /projects/opt/x86_64/gcc/8.3.0/bin/gfortran
      flags: {}
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  view: false
  modules:
    tcl:
      all:
        filter:
          environment_blacklist: [LD_LIBRARY_PATH]
```

```console
$ spack concretize -f
$ spack install
$ spack env loads
$ source loads
$ module list
Currently Loaded Modulefiles:
  1) paraview-5.9.0-gcc-8.3.0-tkkmviq   2) python-3.8.7-gcc-8.3.0-35x4p2b
$ ldd `which pvpython` | grep python
	libpython3.8.so.1.0 => not found
$ pvpython
pvpython: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

### Error Message

```console
$ spack --debug --stacktrace <command>
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.0-1341-8e3ac85
* **Python:** 3.6.8
* **Platform:** linux-centos7-broadwell
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output
