### ISSUE TITLE
conflict directive not in lmod module files

### ISSUE THREAD

**Issue by wadudmiah** [LLNL/spack#21987]
Hi,

I have the following YAML in my `spack/etc/spack/defaults/modules.yaml`:
```
  lmod:
    naming_scheme: '{name}/{version}'
    verbose: True
    hash_length: 0
    all:
      conflict:
        - '{name}'
      autoload: direct
```
I then refresh my modules:

```
$ spack module lmod refresh --delete-tree -y
==> Regenerating lmod module files
$
```
When I open a module file, e.g. `/home/admwm1/spack/share/spack/lmod/linux-rhel7-x86_64/intel/18.0.1/autoconf/2.69.lua` there is no `conflict` directive in it, but exists for TCL module files, but not for lmod module file. Should be an easy fix :-)
