### ISSUE TITLE
Proposal: refactor config.yaml install_tree

### ISSUE THREAD

**Issue by gdolle** [LLNL/spack#22246]
Hi everyone,

It seems the config.yaml only allows to set the install root directory (+ specific path) and the current default tree does not really allow prefixed install in standard path (e.g /var, /etc, /usr/share, /usr/local/share etc..).

PS: I find also the current config keys a bit confusing (_dirs _roots _tree)

I'd have imagine something more like

```yaml
config:
  tree: # everything related to install tree.
    prefix:
      user:  $user/.spack/    # user (spack install --user <pkg>)
      admin: /usr/local       # admin local  (spack install <pkg>)
    root:   # default directories 
      bin:  # SPACK_BIN_PATH
        - $prefix/bin
      etc:    # SPACK_ETC_PATH
        - /etc
      lib:    # SPACK_LIB_PATH
        - $prefix/lib
      share:  # SPACK_SHARE_PATH
        - $prefix/share
      var:   # SPACK_VAR_PATH
        - /var
    custom: # optional
      templates:    # SPACK_TEMPLATE_PATH , below prepend default path ($prefix/share/spack)/template
        -  /template
      modules:   
        tcl: # SPACK_MODULES_TCL_PATH, below prepend default path ($prefix/share/spack/modules)
          -  /path/to/tcl
        lmod:  # SPACK_MODULES_LMOD_PATH, below prepend default path
          -  /path/to/lmod
      stages:
        build:
          -  /path/to
        test:
          -  /path/to
      caches:
        source:
          -  /path/to
        misc:
          -  /path/to
```
to allow system/user packages system wide similar to PyPI. That may require quite some (major?) changes..

Maybe a key `spack show` and `spack show tree` to print current information and directory tree.

what do you think ? (I may have missed some details though)
