### ISSUE TITLE
Installation issue: [llamps]

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#22336]
It looks like llamps is looking for the xxd utility? 
```
          api-config.cmake:463 (message):
     608      The xxd utility is required to build models and drivers.
```
The complete build error is [here](https://github.com/autamus/registry/pull/60/checks?check_run_id=2110523318) and the spack.yaml used for containerize is:

```yaml
spack:
  specs: ["lammps"]
  view: true
  container:
    os_packages:
      build:
        - python3-dev
      final:
        - ca-certificates
    strip: false
```
Is something default trying to build that we need to remove for this environment?
