### ISSUE TITLE
Allow for environment modifications by the external packages

### ISSUE THREAD

**Issue by skosukhin** [LLNL/spack#22824]
It would be nice to have an option to apply additional modifications to the environment when an external package is in use. We already have it for compilers, so the required logic is already more or less implemented.

### Rationale

This would help to customize the existing modules. For example, some packages need to run `srun` either at the configure time (to make sure that the provided MPI implementation does not suffer some particular bugs) or when running tests. A common assumption is that `srun -n 4 ./executable` does the job. There are cases, though, when this does not work. On one of the systems I have to specify an account, a constraint and a partition:
```console
srun -A some_account -C some_constraint -p some_partition -n 4 ./executable
```

This could be solved with the requested feature as follows:
```yaml
packages:
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@7.7.16
      modules:
      - cray-mpich/7.7.16
      environment:
        set:
          SLURM_ACCOUNT: some_account
          SLURM_CONSTRAINT: some_constraint
          SLURM_PARTITION: some_partition
```

and `srun -n 4 ./executable` would work.

### Description

The current way to solve this problem is to create an additional module and append it to the list of loaded modules. This is not very convenient though.

### Additional information
We need to discuss whether the environment modifications should affect the hash. This makes sense for the modules since we normally get the prefix from them but I don't think we should try to guess the prefix based on the environment modifications.

### General information

- [ ] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by skosukhin** [comment]
There is probably one more thing to consider. Imagine that `mpi` is not an external package. Say we build `openmpi`. We still have to set additional environment variables to make `srun` work. Therefore, it would be nice to have an additional `environment` section for the whole package, not only for externals:

```yaml
packages:
  openmpi:
    buildable: true
    environment:
# we want to set SLURM variables regardless of whether an external version is used
      set:
        SLURM_ACCOUNT: some_account
        SLURM_CONSTRAINT: some_constraint
        SLURM_PARTITION: some_partition
    externals:
    - spec: openmpi@4.0.5%gcc
      modules:
      - openmpi/4.0.5-gcc
      environment:
# the openmpi/4.0.5-gcc module sets some custom BAD_VAR variable, which we don't want in the build environment
        unset: BAD_VAR
```
