### ISSUE TITLE
Clingo concretization fails when compiler flags propagated to dependents

### ISSUE THREAD

**Issue by omor1** [LLNL/spack#22954]
`libgcrypt` is installed with `gcc@8.3.1`:
```console
$ spack find -lvd libgcrypt
==> 1 installed package
-- linux-centos8-zen / gcc@8.3.1 --------------------------------
6dooye5 libgcrypt@1.8.5
4jezmqq     libgpg-error@1.37
```

I want to install `ccache` with `gcc@10.2.0` and this existing `libgcrypt`:
```console
$ spack solve -Il ccache %gcc@10.2.0 ^/6dooye5
==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
==> Error:
```

The original concretizer handles this flawlessly:
```console
$ spack spec -Il ccache %gcc@10.2.0 ^/6dooye5
Input spec
--------------------------------
 -   ccache%gcc@10.2.0
[^]      ^libgcrypt@1.8.5%gcc@8.3.1 cflags="-O2 -march=core-avx2" cxxflags="-O2 -march=core-avx2" fflags="-O2 -march=core-avx2"  arch=linux-centos8-zen
[^]          ^libgpg-error@1.37%gcc@8.3.1 cflags="-O2 -march=core-avx2" cxxflags="-O2 -march=core-avx2" fflags="-O2 -march=core-avx2"  arch=linux-centos8-zen

Concretized
--------------------------------
 -   ktsmbuo  ccache@3.7.11%gcc@10.2.0 cflags="-O2 -march=znver2" cxxflags="-O2 -march=znver2" fflags="-O2 -march=znver2"  arch=linux-centos8-zen2
[^]  o2beapv      ^gperf@3.1%gcc@10.2.0 cflags="-O2 -march=znver2" cxxflags="-O2 -march=znver2" fflags="-O2 -march=znver2"  arch=linux-centos8-zen2
 -   wtsq5lb      ^libxslt@1.1.33%gcc@10.2.0 cflags="-O2 -march=znver2" cxxflags="-O2 -march=znver2" fflags="-O2 -march=znver2" +crypto~python arch=linux-centos8-zen2
[^]  6dooye5          ^libgcrypt@1.8.5%gcc@8.3.1 cflags="-O2 -march=core-avx2" cxxflags="-O2 -march=core-avx2" fflags="-O2 -march=core-avx2"  arch=linux-centos8-zen
[^]  4jezmqq              ^libgpg-error@1.37%gcc@8.3.1 cflags="-O2 -march=core-avx2" cxxflags="-O2 -march=core-avx2" fflags="-O2 -march=core-avx2"  arch=linux-centos8-zen
[^]  f5eijhm          ^libiconv@1.16%gcc@10.2.0 cflags="-O2 -march=znver2" cxxflags="-O2 -march=znver2" fflags="-O2 -march=znver2"  arch=linux-centos8-zen2
[^]  52hv55d          ^libxml2@2.9.10%gcc@10.2.0 cflags="-O2 -march=znver2" cxxflags="-O2 -march=znver2" fflags="-O2 -march=znver2" ~python arch=linux-centos8-zen2
[^]  sq6fdwt              ^pkgconf@1.7.3%gcc@10.2.0 cflags="-O2 -march=znver2" cxxflags="-O2 -march=znver2" fflags="-O2 -march=znver2"  arch=linux-centos8-zen2
[^]  dsly4qm              ^xz@5.2.5%gcc@10.2.0 cflags="-O2 -march=znver2" cxxflags="-O2 -march=znver2" fflags="-O2 -march=znver2" ~pic arch=linux-centos8-zen2
[^]  rchx6la              ^zlib@1.2.11%gcc@10.2.0 cflags="-O2 -march=znver2" cxxflags="-O2 -march=znver2" fflags="-O2 -march=znver2" +optimize+pic+shared arch=linux-centos8-zen2
```

### Steps to reproduce the issue

I'm not sure what exact setup will reproduce this; I believe it has to do with mixed-compiler setups where the compilers have different `cflags`, `cxxflags`, `fflags`, etc. It also maybe has something to do with the flags containing an `-march` different from that specified by `target` (so that the identical flags aren't collapsed).

### Error Message

```console
$ spack --debug --stacktrace solve -Il ccache %gcc@10.2.0 ^/6dooye5
lib/spack/spack/cmd/__init__.py:122 ==> [2021-04-12-22:23:51.303533] Imported solve from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2021-04-12-22:23:51.304433] Imported solve from built-in commands
lib/spack/spack/config.py:981 ==> [2021-04-12-22:23:51.308832] Reading config file /home/omor1/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:981 ==> [2021-04-12-22:23:51.327092] Reading config file /home/omor1/.spack/config.yaml
lib/spack/spack/config.py:981 ==> [2021-04-12-22:23:51.328696] Reading config file /home/omor1/.spack/upstreams.yaml
lib/spack/spack/database.py:363 ==> [2021-04-12-22:23:51.331821] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:367 ==> [2021-04-12-22:23:51.332083] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/database.py:363 ==> [2021-04-12-22:23:51.455313] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:367 ==> [2021-04-12-22:23:51.455531] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:981 ==> [2021-04-12-22:23:51.458050] Reading config file /home/omor1/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:981 ==> [2021-04-12-22:23:51.459911] Reading config file /home/omor1/.spack/repos.yaml
lib/spack/spack/config.py:981 ==> [2021-04-12-22:23:52.253150] Reading config file /home/omor1/.spack/linux/compilers.yaml
lib/spack/spack/config.py:981 ==> [2021-04-12-22:23:52.296843] Reading config file /home/omor1/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:981 ==> [2021-04-12-22:23:52.321079] Reading config file /home/omor1/.spack/packages.yaml
home/omor1/spack/lib/spack/spack/main.py:431 ==> [2021-04-12-22:23:53.068202] Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.557150] opt_criterion(15, version weight)
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.557315] opt_criterion(14, number of non-default variants (roots))
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.557426] opt_criterion(13, multi-valued variants + preferred providers for roots)
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.557538] opt_criterion(11, number of non-default variants (non-roots))
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.557645] opt_criterion(9, number of non-default providers (non-roots))
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.557750] opt_criterion(8, count of non-root multi-valued variants)
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.557854] opt_criterion(7, compiler matches + number of nodes)
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.557959] opt_criterion(6, version badness)
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.558063] opt_criterion(5, non-preferred compilers)
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.558167] opt_criterion(4, target matches)
lib/spack/spack/solver/asp.py:1566 ==> [2021-04-12-22:23:53.558271] opt_criterion(3, non-preferred targets)
Traceback (most recent call last):
  File "/home/omor1/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/home/omor1/spack/lib/spack/spack/main.py", line 772, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/omor1/spack/lib/spack/spack/main.py", line 496, in _invoke_command
    return_val = command(parser, args)
  File "/home/omor1/spack/lib/spack/spack/cmd/solve.py", line 105, in solve
    result = asp.solve(
  File "/home/omor1/spack/lib/spack/spack/solver/asp.py", line 1652, in solve
    return driver.solve(setup, specs, dump, models, timers, stats, tests)
  File "/home/omor1/spack/lib/spack/spack/solver/asp.py", line 367, in solve
    answers = builder.build_specs(tuples)
  File "/home/omor1/spack/lib/spack/spack/solver/asp.py", line 1586, in build_specs
    self.reorder_flags()
  File "/home/omor1/spack/lib/spack/spack/solver/asp.py", line 1517, in reorder_flags
    check_same_flags(spec.compiler_flags, compiler_flags)
  File "/home/omor1/spack/lib/spack/spack/solver/asp.py", line 178, in check_same_flags
    assert values1 == values2
AssertionErrors
```

### Information on your system

SDSC Expanse

```console
$ spack debug report
* **Spack:** 0.16.1-2177-03e3a4e40d
* **Python:** 3.8.5
* **Platform:** linux-centos8-zen2
* **Concretizer:** original
```

```yaml
- compiler:
    spec: gcc@8.3.1
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags:
      cflags: -O2 -march=core-avx2
      cxxflags: -O2 -march=core-avx2
      fflags: -O2 -march=core-avx2
    operating_system: centos8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.2.0
    paths:
      cc: /cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/bin/gcc
      cxx: /cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/bin/g++
      f77: /cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/bin/gfortran
      fc: /cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/bin/gfortran
    flags:
      cflags: -O2 -march=znver2
      cxxflags: -O2 -march=znver2
      fflags: -O2 -march=znver2
    operating_system: centos8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
