### ISSUE TITLE
spack external find should probably follow symlinks

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#23007]
### Steps to reproduce the issue

I have an environment with a bunch of packages including openssl and python. It creates a view. I add this `view/bin/` folder to my path. Now I run `spack external find openssl`. This adds an entry:

```yaml
packages:
  openssl:
  - spec: openssl@1.1.1k
    prefix: /root/my_environment/view
```

Now I run `spack install python`. Python *fails* to install, because everything in the environment view is exposed to the build, not just openssl.

Maybe spack should follow the symlink (recursively) of whatever executable it detects in the PATH?
