### ISSUE TITLE
Spack module path

### ISSUE THREAD

**Issue by skylerpaulus** [LLNL/spack#23150]
Hello, 

I am currently having issues with spacks target. Its installing packages for ivybridge but I need it to be x86_64
I have created a config file at: 
/opt/ohpc/pub/spack/etc/spack

```
$cat config.yaml 
config:
        target: "x86_64"
        front_os: "rhel7-x86_64"
        back_os: "rhel7-x86_64"
        operating_system: "rhel7-x86_64"
        os: "rhel7"
        frontend: 'rhel7'
        backend: 'rhel7'
```

but this is not working when installing a new package. Any help would be much appreciated.
