### ISSUE TITLE
Environments don't support namespaced packages?

### ISSUE THREAD

**Issue by flxmr** [LLNL/spack#23298]
Hello all, I'm still redoing our cluster (troubleshooting RoCE without previous experience is so much fun...) and I'd like to install some environments; the spack.yaml looks something like
```
spack:
  specs:
  - sne.openmpi@4.1.1+pmi+legacylaunchers+thread_multiple schedulers=slurm fabrics=ucx
  - sne.ucx@1.11-dev-210427+thread_multiple+rc+dc+ud+mlx5-dv
  - hdf5@1.10.7+hl+cxx+fortran+threadsafe+mpi%gcc@8.4.0
...
  view: true
  concretization: together
```
Now, my problem is that the concretization is not picking up the `sne`-namespace-specs, but instead defaulting to the ones from the namespace-repo (as visible in the generated spack.lock). The namespace is working as intended, I've already installed the specs!

Is this supposed to work that way, am I doing something wrong or is this in reality a bug?

EDIT: System info:
* **Spack:** 0.16.1-2332-febeca2b05
* **Python:** 3.7.3
* **Platform:** linux-debian10-skylake_avx512
* **Concretizer:** original
