### ISSUE TITLE
Installation issue: GCC@10.3.0

### ISSUE THREAD

**Issue by cdelv** [LLNL/spack#23304]
I ran the command `spack install gcc %gcc@7.3.1`. I'm using that compiler because the gcc@9.2 seems to be corrupted and I don't have root permissions on this computer. The OS is linux Fedora26. Everything installs well but when GCC is in the build phase this happens:
```
   >> 4043    /tmp/cdelv/spack-stage/spack-stage-gcc-10.3.0-wfiatze7uyjw5bcvybyzkgogjwypoh6r/spack-src/spack build/./gcc/xgcc: error wh
             ile loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
     4044    make[3]: *** [Makefile:2090: specs] Error 127
```
The build log shows the following:

```
make[3]: Leaving directory '/tmp/cdelv/spack-stage/spack-stage-gcc-10.3.0-wfiatze7uyjw5bcvybyzkgogjwypoh6r/spack-src/spack-build/gcc'
make[2]: *** [Makefile:4743: all-stage1-gcc] Error 2
make[2]: Leaving directory '/tmp/cdelv/spack-stage/spack-stage-gcc-10.3.0-wfiatze7uyjw5bcvybyzkgogjwypoh6r/spack-src/spack-build'
make[1]: *** [Makefile:23252: stage1-bubble] Error 2
make[1]: Leaving directory '/tmp/cdelv/spack-stage/spack-stage-gcc-10.3.0-wfiatze7uyjw5bcvybyzkgogjwypoh6r/spack-src/spack-build'
make: *** [Makefile:999: all] Error 2
```
The compilers.yaml file:

```
- compiler:
    spec: gcc@7.3.1
    paths:
      cc: /usr/lib64/ccache/gcc
      cxx: /usr/lib64/ccache/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: fedora26
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
