### ISSUE TITLE
Spack adds empty lines into `spack.yaml` files

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#23454]
When I run `spack compiler find` with an active environment, Spack modifies the respective `spack.yaml` file, rewriting the compiler information in there. The newly written file adds one emtpy line in front of every comment. After several iterations of this, the long stretches of empty lines become annoying.

### Steps to reproduce the issue

```console
$ spack --env-dir utils/spack/redshift compiler find view-compilers
```

### Error Message

`spack.yaml` before:
```yaml
# source ../spack/share/spack/setup-env.sh
# spack --env-dir utils/spack/redshift compiler find view-compilers && spack --env-dir utils/spack/redshift concretize --force && spack --env-dir utils/spack/redshift install --fail-fast
spack:
  definitions:
  - compilers:
    - gcc @11.1.0
  - packages:
    # +shared does not work on MacOS
    # - amrex ~fortran +hdf5 +openmp +particles +shared
    - amrex ~fortran +hdf5 +openmp +particles
    - boost cxxstd=17 +mpi
    - fftw +mpi +openmp
    - googletest
    - gsl
    - hdf5 @1.10.7 +cxx +fortran +hl +mpi +threadsafe
    - hwloc
    - jemalloc
    - jpeg
    - nsimd simd=AVX2
    - openblas
    - openmpi +thread_multiple
    - openssl
    # - silo @4.10.2-bsd ~fortran
    - silo @4.10.2-bsd ~fortran ~pic ~shared
    - simulationio ~python
    - ssht
    - yaml-cpp
    - zlib
  specs:
  - matrix:
    - [$%compilers]
    - [$packages]
  - cmake %apple-clang @12.0.5
  - python %apple-clang @12.0.5
  concretization: together
  view: /Users/eschnett/src/CarpetX/Cactus/view
  compilers:
  - compiler:
      spec: gcc@11.1.0
      paths:
        cc: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gcc
        cxx: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/g++
        f77: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gfortran
        fc: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gfortran
      flags: {}
      operating_system: bigsur
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: clang@11.1.0
      paths:
        cc: null
        cxx: null
        f77: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gfortran
        fc: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gfortran
      flags: {}
      operating_system: bigsur
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

The same file after:
```yaml
# source ../spack/share/spack/setup-env.sh
# spack --env-dir utils/spack/redshift compiler find view-compilers && spack --env-dir utils/spack/redshift concretize --force && spack --env-dir utils/spack/redshift install --fail-fast
spack:
  definitions:
  - compilers:
    - gcc @11.1.0
  - packages:

    # +shared does not work on MacOS
    # - amrex ~fortran +hdf5 +openmp +particles +shared
    - amrex ~fortran +hdf5 +openmp +particles
    - boost cxxstd=17 +mpi
    - fftw +mpi +openmp
    - googletest
    - gsl
    - hdf5 @1.10.7 +cxx +fortran +hl +mpi +threadsafe
    - hwloc
    - jemalloc
    - jpeg
    - nsimd simd=AVX2
    - openblas
    - openmpi +thread_multiple
    - openssl

    # - silo @4.10.2-bsd ~fortran
    - silo @4.10.2-bsd ~fortran ~pic ~shared
    - simulationio ~python
    - ssht
    - yaml-cpp
    - zlib
  specs:
  - matrix:
    - [$%compilers]
    - [$packages]
  - cmake %apple-clang @12.0.5
  - python %apple-clang @12.0.5
  concretization: together
  view: /Users/eschnett/src/CarpetX/Cactus/view
  compilers:
  - compiler:
      spec: gcc@11.1.0
      paths:
        cc: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gcc
        cxx: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/g++
        f77: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gfortran
        fc: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gfortran
      flags: {}
      operating_system: bigsur
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: clang@11.1.0
      paths:
        cc: null
        cxx: null
        f77: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gfortran
        fc: /Users/eschnett/src/CarpetX/Cactus/view-compilers/bin/gfortran
      flags: {}
      operating_system: bigsur
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

Note the additional empty lines.

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.1-2514-36a3bc465b
* **Python:** 3.8.5
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
