### ISSUE TITLE
Spack tries to use non-existent `PrgEnv-gnu` for manually installed GCC on HPE Apollo/Cray CS

### ISSUE THREAD

**Issue by andreipoe** [LLNL/spack#23539]
On HPE Apollo, and on the older Cray CS, a `PrgEnv` module is only available for the Cray Compiler. If additional compilers are installed manually, Spack expected them to be used using their own PrgEnv and the Cray wrappers, but these do not exist

### Steps to reproduce the issue

With a new install of Spack on an HPE Apollo 80, CCE and GCC are detected correctly:

```console
$ spack arch
cray-rhel8-aarch64

$ spack compilers
==> Available compilers
-- cce rhel8-any ------------------------------------------------
cce@10.0.3

-- gcc rhel8-any ------------------------------------------------
gcc@10.3.0  gcc@8.1.0
gcc@11.1.0  gcc@10.2.0
```

... but the commands picked for GCC are not:

```yaml
- compiler:
    spec: cce@10.0.3
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: rhel8
    target: any
    modules:
    - PrgEnv-cray
    - cce/10.0.3
- compiler:
    spec: gcc@11.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: rhel8
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.1.0
```

There exists no `PrgEnv-gnu` on these systems and GCC should be invoked directly:

```console
$ module av PrgEnv
--------------------------------------------- /opt/cray/pe/modulefiles ----------------------------------------------
PrgEnv-cray/7.0.0
```

Manually editing the compiler configuration to remove the `PrgEnv-gnu` module and to replace the `cc`/`CC`/`ftn` wrappers with `gcc`/`g++`/`gfortran` produces a working configuration.

### Information on your system

* **Spack:** 0.16.1
* **Python:** 3.6.8
* **Platform:** cray-rhel8-aarch64
* **Concretizer:** original

### Additional information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
