### ISSUE TITLE
Environments: exact match required in matrix exclude or will exclude all

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#23598]
Spack requires an exact match in `matrix` `exclude` or it will exclude all spec for the given package.

### Steps to reproduce the issue

environment:
```yaml
spack:
  concretization: separately
  view: false
  definitions:
  - compilers: ['%gcc@8.1.0', '%gcc@8.3.1', '%clang@10.0.0']
  - packages:
    - ncurses@6.2 ^pkg-config@0.28
  specs:
  - matrix:
    - [$packages]
    - [$compilers]
    exclude:
    - ncurses@6.2 %clang@10.0.0
```

Here the concretization will show nothing... all the specs for `ncurses` are excluded even though they use a different compiler.

To fix this, it is enough to exclude the exact match `ncurses@6.2 ^pkg-config@0.28 %clang@10.0.0`.

### Information on your system

* **Spack:** 0.16.1-2608-1ae28f66c6
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output
