### ISSUE TITLE
`spack test` tries to run tests for external packages that require additional files

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#24014]
### Steps to reproduce the issue

1. Add `openmpi` as an external package
2. Run `spack test openmpi`
3. Test fails because `examples` directory isn't found in installation prefix

### Error Message

```
Command exited with status 2:
    '/usr/bin/make' 'all'
make: *** No rule to make target `all'.  Stop.
```

### Recommended Solution

We should skip tests for external packages that require additional files.

### Information on your system

* **Spack:** 0.14.1-6842-6f534ac
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** original

```yaml
packages:
  openmpi:
    buildable: false
    externals:
    - spec: openmpi@3.1.6%gcc@9.3.0
      modules:
      - gnu/openmpi-3.1.6-gnu-9.3.0
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
