### ISSUE TITLE
Installation issue: gromacs %cce @10.0.1 "unknown argument: '-fstack-clash-protection'"

### ISSUE THREAD

**Issue by heaton-dev** [LLNL/spack#24128]
### Steps to reproduce the issue

```console
$ spack install gromacs@2020.4 +blas +hwloc +mpi +openmp +shared +plumed ~cuda %cce@10.0.1 build_type=RelWithDebInfo
...
clang-10: error: unknown argument: '-fstack-clash-protection'
clang-10: error: unknown argument: '-fstack-clash-protection'
clang-10: error: unknown argument: '-fstack-clash-protection'
Unable to find pgen, not compiling formal grammar.
error: command '/lustre/software/aarch64/spack/lib/spack/env/cce/cc' failed with exit status 1
```

### Information on your system

* **Spack:** 0.16.2-2995-c3898ca3bf
* **Python:** 3.6.10
* **Platform:** cray-sles15-thunderx2
* **Concretizer:** original

~/.spack/packages.yaml:
```
  mpi:
    externals:
    - spec: "mpich@7.7.16"
      modules:
      - cray-mpich/7.7.16
    buildable: False
  openblas:
    externals:
    - spec: "openblas@0.3.15"
      modules:
      - apps/openblas/0.3.15
  fftw:
    externals:
    - spec: "fftw+openmp"
      modules:
      - cray-fftw
  cray-libsci:
    externals:
    - spec: "cray-libsci"
      modules:
      - cray-libsci
    buildable: False
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6594924/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6594925/spack-build-env.txt)

@junghans @marvinbernhardt 

Looks like `-fstack-clash-protection` was introduced in clang-11 but cce 10.x.x is based on clang-10, the flag also only exists on x86, s390x and ppc64 but not aarch64/arm64 as far as I can see
https://releases.llvm.org/11.0.0/tools/clang/docs/ReleaseNotes.html#new-compiler-flags

A quick search suggests it isn't yet available on aarch64? https://reviews.llvm.org/D96007

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
