### ISSUE TITLE
Installation issue: libflame fails to build on Cray EX with "undefined reference to `main'"

### ISSUE THREAD

**Issue by dev-zero** [LLNL/spack#24210]
### Steps to reproduce the issue

```console
$ spack install amdlibflame threads=openmp
[...]
ranlib lib/x86_64-unknown-linux-gnu/libflame.a
/project/d110/timuel/spack/lib/spack/env/gcc/gcc -shared -Wl,-soname,libflame.so.3 -o lib/x86_64-unknown-linux-gnu/libflame.so -Wl,--whole-archive,libflame.a,--no-whole-archive -L/opt/cray/pe/mpich/8.1.4/ofi/gnu/9.1/lib -L/opt/cray/pe/dsmml/0.1.4/dsmml//lib -L/opt/cray/xpmem/2.2.40-7.0.1.0_1.9__g1d7a24d.shasta/lib64 -L/opt/gcc/10.2.0/snos/lib/gcc/x86_64-suse-linux/10.2.0 -L/opt/gcc/10.2.0/snos/lib/gcc/x86_64-suse-linux/10.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/opt/gcc/10.2.0/snos/lib/gcc/x86_64-suse-linux/10.2.0/../../.. -lblis-mt -lmpifort_gnu_91 -lmpi_gnu_91 -lxpmem -ldsmml -lgfortran -lquadmath -lpthread -lm -fopenmp
/usr/bin/ld: /usr/lib/../lib64/crt1.o: in function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.26/csu/../sysdeps/x86_64/start.S:110: undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:593: lib/x86_64-unknown-linux-gnu/libflame.so] Error 1
```

### Information on your system

```
* **Spack:** 0.16.2-3059-e321578bbe
* **Python:** 3.6.12
* **Platform:** cray-sles15-zen2
* **Concretizer:** original
```

```yaml
packages:
  ...
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.4%aocc
      prefix: /opt/cray/pe/mpich/8.1.4/ofi/aocc/2.2
    - spec: cray-mpich@8.1.4%gcc
      prefix: /opt/cray/pe/mpich/8.1.4/ofi/gnu/9.1
    buildable: False
...
```

```yaml
compilers:
- compiler:
    spec: gcc@10.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/10.2.0
    environment: {}
    extra_rpaths: []
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6619683/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6619686/spack-build-env.txt)

@amd-toolchain-support ... my guess is that the Cray compiler wrappers interfere and switch to executable output mode with the `-o ...` occurring after the `-shared`, but that's really just a guess.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
