### ISSUE TITLE
Informations about spack develop

### ISSUE THREAD

**Issue by Billae** [LLNL/spack#24393]
Hello,

I want to develop my project named readers (which has its own git repository) in a spack environnement: 
To this end, I have a spack.yaml which contain my develop spec:
``` 
 specs:
  - readers@develop
 develop:
    readers:
      path: reader_dev/
      spec: readers@develop+verbose

```

When I concretize my environnement, all seems ok, and a new directory is created named "reader_dev"  containing my git repository as expected.

 However, my project has multiple branchs and the default develop branch in my spack recipe is "master". Is it possible to switch branch in the spack develop and install the branch I want work on ?

I try to manually ```git checkout other_branch``` but it does not work indicating 

```
error: pathspec 'other_branch' did not match any file(s) known to git.

```

Confused, i try the exact same command in a fresh new pull of my repository and it's working fine. Is it spack develop who block branch change ?

Thanks for taking time to read me =)

Eloïse
