### ISSUE TITLE
spack spec --blame foo@1.2.3

### ISSUE THREAD

**Issue by sleak-lbl** [LLNL/spack#24796]
An option to help understand *why* spack decided on a particular spec (variants and dependencies chosen)  

### Rationale

Spack seems to treat my `packages.yaml` and command-line with disdain, and if I know why it chose each element of the concrete spec, I might be able to adjust things to get the spec I actually want. 

For example, my packages.yaml has:
```
packages:
  all:
    [snip]
    providers:
      mpi: [mpich, openmpi]
    [snip]
    cmake:
    buildable: false
    version: [3.20.5]
    externals:
    - spec: cmake@3.20.5
      modules: [cmake/3.20.5]
```

`spack spec -Il lammps` reveals that Spack intends to build lammps on mvapich2, but not before building a new, different cmake to build it with.

Presumably, this obstinacy happens because something further down the dependency tree has a default value for a variant that conflicts with .. something. And it's almost certainly something not relevant to my needs, so if I know what it is I can add a spec clause to switch it off, eg `^foo ~special_fix_for_vax` 

### Description

Something like `spack config blame`, but for `spack spec`, that eg showed the things leading to each variant and dependency, perhaps

```
 -   ztmbkt7  lammps@20210310%gcc@10.1.0~asphere~body
          @20210310     => preferred version
          %gcc@10.1.0   => packages.yaml:6
          ~asphere         => lammps/package.py:25
 -    ^cmake%gcc +static
          %gcc                => packages.yaml:6 => +static
          +static             => foo/package.py:11 (conflict when +shared)  => (some other thing overriding that) => ...  
```

### Additional information

Might be difficult to actually implement - not sure whether the concretizer can provide the necessary information 

### General information

- [x] I have run `spack --version` and reported the version of Spack
```
$ spack --version
0.16.1-6-9e40c75123
```

- [x] I have searched the issues of this repo and believe this is not a duplicate
