### ISSUE TITLE
[trilinos] build broken by PR23518 when custom compiler flags are required

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#25286]
### Steps to reproduce

I'm working on LLNL's rzansel machine (Power9).  Installing trilinos with XL drops custom flags defined in `compilers.yaml` that I require.  The install command is:

```console
spack install trilinos@12.18.1 %  % xl@2021.03.11-cuda-11.0.2
```

This build completes without error but the installed libraries are not useful to me.  

In my case, we need the XL options `--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -Wl,-rpath,/usr/tce/packages/xl/xl-2021.03.11/xlC/16.1.1/lib` so that the correct RPATH to `libstdc++.so.6` is embedded in the trilinos shared libraries.  My  `compiler.yaml` contains the following to ensure that these compiler flags are used.

```yaml
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cxxflags: >-
        --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
        -Wl,-rpath,/usr/tce/packages/xl/xl-2021.03.11/xlC/16.1.1/lib
      cflags: >-
        --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
        -Wl,-rpath,/usr/tce/packages/xl/xl-2021.03.11/xlC/16.1.1/lib
      fflags: >-
        --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
        -Wl,-rpath,/usr/tce/packages/xl/xl-2021.03.11/xlf/16.1.1/lib
    modules:
      - xl/2021.03.11-cuda-11.0.2
    operating_system: rhel7
    paths:
      cc: /usr/tce/packages/xl/xl-2021.03.11-cuda-11.0.2/bin/xlc_r
      cxx: /usr/tce/packages/xl/xl-2021.03.11-cuda-11.0.2/bin/xlC_r
      f77: /usr/tce/packages/xl/xl-2021.03.11-cuda-11.0.2/bin/xlf_r
      fc: /usr/tce/packages/xl/xl-2021.03.11-cuda-11.0.2/bin/xlf2003_r
    spec: xl@2021.03.11-cuda-11.0.2
    target: ppc64le
```

### Error message

When these extra compiler flags are dropped by spack's trilinos recipe, any dependent software cannot depend on C++14 features.  A link error is generated when my code attempts to link to trilinos libraries:

```console
.../libteuchosparameterlist.so.12.18.1: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
```

The problematic code is found in `trilinos/package.py` and was added by #23518.

```diff
+    def flag_handler(self, name, flags):
+        if self.spec.satisfies('%cce'):
+            if name == 'ldflags':
+                flags.append('-fuse-ld=gold')
+        return (None, None, flags)
```

The `return (None, None, flags)` seems to strip off any custom compiler flags.  If I comment out this block of code, my build completes and my custom compiler flags are used.  If I compare the _good_ and _bad_ trilinos builds I see this diff in `spack-build-01-cmake-out.txt`:

```diff
cmake  \
<options found for both builds>
+ '-DCMAKE_C_FLAGS=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -Wl,-rpath,/usr/tce/packages/xl/xl-2021.03.11/xlC/16.1.1/lib' \
+ '-DCMAKE_CXX_FLAGS=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -Wl,-rpath,/usr/tce/packages/xl/xl-2021.03.11/xlC/16.1.1/lib' \
+ '-DCMAKE_Fortran_FLAGS=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -Wl,-rpath,/usr/tce/packages/xl/xl-2021.03.11/xlf/16.1.1/lib'  
```

The `*_FLAGS` defines are only present when the custom `flag_handler` is commented out in `trilinos/package.py`.

Can someone help me correct the broken code `return (None, None, flags)`?  I'm not sure what the correct syntax should be.

### Information on your system

```console
% spack debug report
* **Spack:** 0.16.1-2680-b462ccb565
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** original
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### Resolution

* Fixed by #25290
