### ISSUE TITLE
Installation issue: binutils

### ISSUE THREAD

**Issue by BenWibking** [LLNL/spack#25353]
### Steps to reproduce the issue

```
$ spack install binutils
==> Warning: gcc@8.4.1 cannot build optimized binaries for "cascadelake". Using best target possible: "skylake_avx512"
[+] / (external diffutils-3.6-ug4ryzqf65k7ubjnlspxxyfspgqptvq7)
[+] / (external gettext-0.19.8.1-gyfx34m6ayzgy54ymnbayspjfyksg4aw)
[+] /g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.4.1/zlib-1.2.11-rqvwbys74elt7o6ozgcz42sbkeejkwb6
==> Installing binutils-2.36.1-pzrqxjmndqbz4o75oferejhzdyrsughk
==> No binary for binutils-2.36.1-pzrqxjmndqbz4o75oferejhzdyrsughk found: installing from source
==> Using cached archive: /g/data/jh2/bw0729/spack/var/spack/cache/_source-cache/archive/5b/5b4bd2e79e30ce8db0abd76dd2c2eae14a94ce212cfc59d3c37d23e24bc6d7a3.tar.bz2
==> No patches needed for binutils
==> binutils: Executing phase: 'autoreconf'
==> binutils: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/scratch/jh2/bw0729/tmp/spack-stage/spack-stage-binutils-2.36.1-pzrqxjmndqbz4o75oferejhzdyrsughk/spack-src/configure' '--prefix=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.4.1/binutils-2.36.1-pzrqxjmndqbz4o75oferejhzdyrsughk' '--disable-dependency-tracking' '--disable-werror' '--enable-multilib' '--enable-64-bit-bfd' '--enable-targets=all' '--with-system-zlib' '--with-sysroot=/' '--enable-shared' '--enable-static' '--disable-lto' '--disable-ld' '--disable-gas' '--disable-interwork' '--disable-gold' '--enable-plugins' '--disable-install-libiberty' '--enable-nls'

2 errors found in build log:
     9     checking whether ln -s works... yes
     10    checking for a sed that does not truncate output... /bin/sed
     11    checking for gawk... gawk
     12    configure: WARNING: neither ld nor gold are enabled
     13    checking for gcc... /g/data/jh2/bw0729/spack/lib/spack/env/gcc/gcc
     14    checking whether the C compiler works... no
  >> 15    configure: error: in `/scratch/jh2/bw0729/tmp/spack-stage/spack-stage-binutils-2.36.1-pzrqxjmnd
           qbz4o75oferejhzdyrsughk/spack-src':
  >> 16    configure: error: C compiler cannot create executables
     17    See `config.log' for more details

See build log for details:
  /scratch/jh2/bw0729/tmp/spack-stage/spack-stage-binutils-2.36.1-pzrqxjmndqbz4o75oferejhzdyrsughk/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.16.2-3870-5916afec84
* **Python:** 3.6.8
* **Platform:** linux-centos8-cascadelake
* **Concretizer:** original

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/6965871/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6965872/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
@BenWibking It seems to me there might be an issue with your compiler. I just tried on:

* **Spack:** 0.16.2-3887-fb8c954e2e
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-broadwell
* **Concretizer:** original

and binutils builds correctly (with GCC 11.1.0):
```console
$ spack install binutils
[ ... ]
==> binutils: Successfully installed binutils-2.36.1-56tyi6l2usws6mhfnjvzjh3ckv55wbv3
  Fetch: 4.03s.  Build: 6m 26.01s.  Total: 6m 30.04s.
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-11.1.0/binutils-2.36.1-56tyi6l2usws6mhfnjvzjh3ckv55wbv3
$ spack find
==> 13 installed packages
-- linux-ubuntu18.04-broadwell / gcc@11.1.0 ---------------------
binutils@2.36.1  diffutils@3.7  libiconv@1.16   ncurses@6.2    patchelf@0.13  tar@1.34  zlib@1.2.11
bzip2@1.0.8      gettext@0.21   libxml2@2.9.10  patchelf@0.12  pkgconf@1.7.4  xz@5.2.5
```

**Comment by BenWibking** [comment]
Lots of other packages build fine... so I'm not sure how to debug this, especially since there's no substantial additional information in the log files.

**Comment by BenWibking** [comment]
In fact, I can run the ./configure script for binutils successfully outside of the spack build environment, using the system gcc, rather than the gcc symlink inside of spack.

**Comment by alalazo** [comment]
Can you post your `compilers.yaml` (or the compiler entry in there that you're currently using)?

**Comment by alalazo** [comment]
Also, do you see in `config.log` where the test is failing to compile?

**Comment by sethrj** [comment]
I sometimes see errors like this when I unwittingly have compiler modules loaded. Can you check that your modules are clear (or as expected)?

**Comment by BenWibking** [comment]
I don't have any compiler modules loaded. Here is my compilers.yaml:
```
- compiler:
    spec: gcc@8.4.1
    paths:
      cc: /opt/nci/bin/gcc
      cxx: /opt/nci/bin/g++
      f77: /opt/nci/bin/gfortran
      fc: /opt/nci/bin/gfortran
    flags: {}
    operating_system: centos8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

And gcc version:
```
$ which gcc
/opt/nci/bin/gcc
[bw0729@gadi-login-01 spack-src]$ gcc -v
Using built-in specs.
COLLECT_GCC=/bin/gcc
COLLECT_LTO_WRAPPER=/half-root/usr/bin/../libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)
```

This is the error in config.log:

```
configure:4065: checking for gcc
configure:4092: result: /g/data/jh2/bw0729/spack/lib/spack/env/gcc/gcc
configure:4321: checking for C compiler version
configure:4330: /g/data/jh2/bw0729/spack/lib/spack/env/gcc/gcc --version >&5
gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4341: $? = 0
configure:4330: /g/data/jh2/bw0729/spack/lib/spack/env/gcc/gcc -v >&5
Using built-in specs.
COLLECT_GCC=/bin/gcc
COLLECT_LTO_WRAPPER=/half-root/usr/bin/../libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)
configure:4341: $? = 0
configure:4330: /g/data/jh2/bw0729/spack/lib/spack/env/gcc/gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4341: $? = 1
configure:4330: /g/data/jh2/bw0729/spack/lib/spack/env/gcc/gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
configure:4341: $? = 1
configure:4361: checking whether the C compiler works
configure:4383: /g/data/jh2/bw0729/spack/lib/spack/env/gcc/gcc   -lintl conftest.c  >&5
/bin/ld: cannot find -lintl
collect2: error: ld returned 1 exit status
configure:4387: $? = 1
configure:4425: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:4430: error: in `/scratch/jh2/bw0729/tmp/spack-stage/spack-stage-binutils-2.37-bvrxnn3z5pucziw2cavu3jqxooolpipf/spack-src':
configure:4432: error: C compiler cannot create executables
```

**Comment by BenWibking** [comment]
It looks like it's failing because it can't link with `-lintl`.

**Comment by sethrj** [comment]
Sounds like your local GCC installation isn't configured properly. You might be able to get it to work with the extra rpaths flag.

**Comment by BenWibking** [comment]
I can build binutils from source using gcc outside of Spack perfectly fine, by building manually from within the spack-src directory itself.

**Comment by mwkrentel** [comment]
@BenWibking I suspect there's something wonky in your spack config.
This works fine for the rest of us.  First,

1. Your distro is Linux Centos 8.x, right?  This normally comes with
/usr/bin/gcc 8.x.  Is there some reason you're using gcc 8.x from
/opt/nci as opposed to /usr/bin?  I'm using /usr/bin/gcc and it works
for me and I'd bet that it works for you.

Certainly, you are allowed to use compilers other than /usr/bin and
spack supports this, but sometimes this requires extra config lines in
compilers.yaml.

2. Where does /opt/nci/bin/gcc come from?  A Centos rpm?  Which one?
Did you build it yourself?
Is it from a module?

3. Does this system run modules?  What do 'module avail' and 'module list'
report?

Anyway, let's start over from scratch and go step by step.  Move your
.spack directory out of the way (so it doesn't add to the config),
make a fresh spack clone and run `spack compiler find` and let's see
what that says.  Don't do any extra config.

First, try `spack spec binutils` with the spec for /usr/bin/gcc, then
`spack install binutils`.  Let's see what both of those do.

If that works, and I'd expect it should, then try the same for
/opt/nci/bin/gcc.  If you have to do something else, like spack
compiler find to find the /opt/nci compiler, then let's see that.

Btw, I think the thing about `-lintl` failing is a red herring.  On my
RH 8.x system, there is no libintl anywhere in /usr and binutils
configure runs the same compile command with -lintl and it succeeds
for me.  Although, I'm not sure why.  :-)

Sorry, I don't mean to treat you like a child.  I think it's 75% you
have something misconfigured and 25% there's something about /opt/nci
that spack doesn't handle correctly.  But the only way we'll figure it
out is by starting from scratch and going step by step.  So, start
from a clean config, show us all the steps, and don't leave anything
out, because that will be the mistake.

**Comment by BenWibking** [comment]
I appreciate the assistance. Yes, it's a CentOS 8.4 system.

I've moved the ~/.spack folder out of the way and cloned a fresh spack repo. Then:
```
$ spack compiler find
==> Added 2 new compilers to /home/120/bw0729/.spack/linux/compilers.yaml
    gcc@8.4.1  clang@11.0.0
==> Compilers are defined in the following files:
    /home/120/bw0729/.spack/linux/compilers.yaml
$ cat .spack/linux/compilers.yaml
compilers:
- compiler:
    spec: clang@11.0.0
    paths:
      cc: /bin/clang
      cxx: /bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: centos8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.4.1
    paths:
      cc: /opt/nci/bin/gcc
      cxx: /opt/nci/bin/g++
      f77: /opt/nci/bin/gfortran
      fc: /opt/nci/bin/gfortran
    flags: {}
    operating_system: centos8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: [
$ module list
Currently Loaded Modulefiles:
 1) pbs   2) openmpi/4.1.0(default)   3) cuda/11.2.2   4) hdf5/1.10.5   5) szip/2.1.1   6) python3-as-python
```

/opt/nci/bin/gcc is a compiler wrapper installed by the system administrators of the cluster. It adjusts some header and library environment variables. I've attached those scripts below.
[nci_wrapper_gcc.txt](https://github.com/spack/spack/files/6989244/nci_wrapper_gcc.txt)
[wrapper_functions.txt](https://github.com/spack/spack/files/6989245/wrapper_functions.txt)

However, even when using this wrapper script, I am able to build binutils using this fresh spack clone. So it appears that somehow something in packages.yaml caused the problem.

**Comment by BenWibking** [comment]
And indeed, when I put the old packages.yaml into ~/.spack, it fails with the old error again. In case there is interest in debugging the problem, I've copied the bad packages.yaml below:

```
packages:
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.1
      prefix: /usr
  bash:
    externals:
    - spec: bash@4.4.20
      prefix: /
    - spec: bash@4.4.19
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /
  cmake:
    externals:
    - spec: cmake@3.21.1
      prefix: /home/120/bw0729/cmake-3.21.1
    - spec: cmake@3.18.2
      prefix: /usr
    - spec: cmake@3.11.4
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.12
      prefix: /
  cuda:
    externals:
    - spec: cuda@11.2.152
      prefix: /apps/cuda/11.2.2
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /
  doxygen:
    externals:
    - spec: doxygen@1.8.14+graphviz~mscgen
      prefix: /
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /
  flex:
    externals:
    - spec: flex@2.6.1+lex
      prefix: /
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.27
      prefix: /usr
    - spec: ghostscript@9.25
      prefix: /
  git:
    externals:
    - spec: git@2.27.0~tcltk
      prefix: /
    - spec: git@2.18.4~tcltk
      prefix: /
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
  openjdk:
    externals:
    - spec: openjdk@1.8.0_292-b10
      prefix: /usr
    - spec: openjdk@1.8.0_265-b01
      prefix: /
  krb5:
    externals:
    - spec: krb5@1.18.2
      prefix: /
  libfuse:
    externals:
    - spec: libfuse@3.2.1
      prefix: /
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  llvm:
    externals:
    - spec: llvm@11.0.0+clang~lld~lldb
      prefix: /
      extra_attributes:
        compilers:
          c: /bin/clang
          cxx: /bin/clang++
    - spec: llvm@11.0.0+clang~lld~lldb~gold
      prefix: /apps/llvm/11.0.0
      extra_attributes:
        compilers:
          c: /apps/llvm/11.0.0/bin/clang-11
          cxx: /apps/llvm/11.0.0/bin/clang++
  llvm-doe:
    externals:
    - spec: llvm-doe@11.0.0+clang~lld~lldb
      prefix: /
      extra_attributes:
        compilers:
          c: /bin/clang
          cxx: /bin/clang++
  lustre:
    externals:
    - spec: lustre@2.12.6_4.gadi
      prefix: /usr
    - spec: lustre@2.12.5_2.gadi_client
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@6.1.20180224+termlib abi=6
      prefix: /
    - spec: ncurses@6.1.20180224+termlib
      prefix: /
  ninja:
    externals:
    - spec: ninja@1.8.2
      prefix: /usr
  openmpi:
    externals:
    - spec: openmpi@4.1.0%gcc@8.4.1+cuda+cxx~cxx_exceptions~java+lustre~memchecker+pmi~sqlite3~static~thread_multiple~wrapper-rpath
        fabrics=ucx schedulers=tm
      prefix: /apps/openmpi/4.1.0
  openssh:
    externals:
    - spec: openssh@8.0p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1g
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.26.3~cpanm+shared+threads
      prefix: /
  pkgconf:
    externals:
    - spec: pkgconf@1.4.2
      prefix: /usr
  python:
    externals:
    - spec: python@2.7.18+bz2+ctypes+dbm~lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
    - spec: python@2.7.17+bz2+ctypes+dbm~lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /
    - spec: python@3.6.8+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /
  ruby:
    externals:
    - spec: ruby@2.5.5
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /
  texlive:
    externals:
    - spec: texlive@20180414
      prefix: /
  xz:
    externals:
    - spec: xz@5.2.4
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.19.8.1
      prefix: /
  pcre:
    externals:
    - spec: pcre@8.44
      prefix: /
  libxml2:
    externals:
    - spec: libxml2@2.9.7
      prefix: /
  libuuid:
    externals:
    - spec: libuuid@1.0.3
      prefix: /
```

Nothing seems obviously wrong here to me, unfortunately.

**Comment by mwkrentel** [comment]
First, I'm not really a fan of using spack externals.  It's fine for
build utils (cmake, perl, python) and for packages specific to the
system (mpi, cuda).  But for libraries that we link into hpctoolkit,
I'd rather you build them from scratch via spack.

So, it looks like spack external created a package spec that doesn't
work for binutils.  Start with `spack spec binutils` and try removing
the packages one by one.  My guess is gettext (where libintl comes from).

Spack external is fairly new, so I'm not sure exactly what is correct
and what is/not a bug.  It's possible that external find is producing
an incorrect spec, or maybe it's just something the original concretizer
is not smart enough to handle, I don't know.

Anyway, if it is a bug, it looks like a separate bug, that is, the
output of spack external find.  Even then, it may work fine with clingo
and thus not really a bug.

So, track down the bad package, delete it and see if you can finish
building hpctoolkit.

Btw, for hpctoolkit, you'll also need to remove the xz package.  The
default for xz is ~pic but hpctoolkit needs +pic.  That was your other
reported issue. (And one reason I'm not a fan of externals for libraries
that we link and run with.)

**Comment by BenWibking** [comment]
Removing gettext solves the build problem for binutils. hpctoolkit then builds successfully as long as ~viewer is added to the spec (since openjdk doesn't build for some other reason that I've opened another issue for) and xz is also removed from packages.yaml. Thanks.

**Comment by sethrj** [comment]
Thanks @mwkrentel for debugging! I agree that space external should generally not be used for linked libraries.

**Comment by mwkrentel** [comment]
@BenWibking    Where did you get the gettext entry in packages.yaml?  I don't see in
the gettext package.py the code to search for this, so I guess you
must have added it manually?

The spack built gettext provides libintl, but RH doesn't.  The intl
functions are also provide in libc, so RH doesn't provide a separate
libintl.  That was the mistake.  From the external gettext spec,
binutils was expecting libintl from gettext and it wasn't there.

**Comment by BenWibking** [comment]
No, all the entries were added by running spack external. I think I ran it a few months ago, so maybe it was in an older version of the package.

I'm glad you found the root cause. That was quite a subtle issue!

**Comment by KineticTheory** [comment]
I know this issue is closed, but I just ran into the exact same problem with RHEL8.  `spack external find` inserted the following into `packages.yaml`
```yaml
  gettext:
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
```
This prevented `binutils` from configuring.  Removing the offending externals block fixed the problem.
