### ISSUE TITLE
OpenMPI compiler can't be used outside of Spack on macOS with Clang

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2540]
that looks like a regression:
```
-- Check for working C compiler: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/openmpi-2.0.1-zgppod67vns7ojjqtw3qqwfid64jcclg/bin/mpicc -- broken
CMake Error at /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/cmake-3.6.1-jdgman4gzoaoidk22mgcdraxwudbbgj5/share/cmake-3.6/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/openmpi-2.0.1-zgppod67vns7ojjqtw3qqwfid64jcclg/bin/mpicc"
  is not able to compile a simple test program.
...
Spack compiler must be run from Spack! Input 'SPACK_PREFIX' is missing.
```

It certainly did not behave like that a month or so ago and one was able to build with Spack build MPI.

**Comment by adamjstewart** [comment]
This is supposed to be handled in the OpenMPI package under:
```python
@AutotoolsPackage.sanity_check('install')
def filter_compilers(self):
```
Can you add some debug messages and rebuild it and see if this gets run?

**Comment by davydden** [comment]
i checked files and it looks like this is was run, for example `mpicc-wrapper-data.txt` contains 
```
compiler=/Users/davydden/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
```
...and **this IS the problem**, actually! Because when building with `clang` it points not to 
```
    paths:
      cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
      cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
      f77: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-yuzfgyrrvsnlutzrys2hwgbr47km7cql/bin/gfortran
      fc: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-yuzfgyrrvsnlutzrys2hwgbr47km7cql/bin/gfortran
```
but on XCode mockup compilers.

@mathstuf any hints on how to fix this, related to XCode mockup issue?
