### ISSUE TITLE
spack.yaml: allow conditional dependencies

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#25514]
### Summary

We should allow conditional dependencies in `spack.yaml` files.

### Rationale

`spack.yaml` is designed to describe the dependencies of a project. Many of these dependencies are conditional on OS or dependency version. Other package managers like conda and pip support this like so:
```
wincertstore; sys_platform == 'win32'
enum34; python_version < '3.4'
```
Many of these dependencies either can't be installed or aren't needed for some platforms/versions.

Spack also supports this in a `package.py` with the `when=` arg to `depends_on`.

### Description

We could do something like:
```yaml
spack:
  specs:
  - py-h5py
  - py-wincertstore:
      when: platform=win32
  - py-enum34:
      when: ^python@:3.3
```
I believe this is valid YAML syntax and fairly intuitive. I'm open to other suggestions.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
I wonder if we can model spack.yaml as a declarative anonymous package definition (without source code), cause I'd also like to add `conflicts(...)` in spack.yaml sometimes if a particular version does not work (e.g. our docs environment does not work with a single version of py-sphinx). Now I have to write `specs: - pkg@1.0.0:1.2.3,1.2.5:`, but I'd rather write `specs: - pkg` and `conflicts: - pkg@1.2.4`.

```yaml
spack:
  depends_on:
  - py-h5py
  - py-wincert-store:
      when: platform=win32
  - py-enum34:
      when: "^python@:3.3"
  conflicts:
  - py-h5py@1.2.3
  - py-enum34@3.4:
      when: "^python@:2.6"
```

but I'm afraid this kind of thing is somewhat complicated thanks to `concretization: separately`

**Comment by alalazo** [comment]
Don't we have that already:
```yaml
spack:
  definitions:
    - compilers: ['%gcc', '%clang']
    - when: arch.satisfies('x86_64:')
      compilers: ['%intel']
```
? From [here](https://spack.readthedocs.io/en/latest/environments.html#spec-matrices):

> Any definitions with the same named list with true when clauses (or absent when clauses) will be appended together
