### ISSUE TITLE
Environment view updates are slow

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#25541]
### Steps to reproduce

Create an environment like this:

```
spack:
  view: true
  concretization: together
  specs:
  - clingo@spack
  - py-ipython
  - py-boto3
  - py-sphinx@4.0:4.1.1
  - py-sphinxcontrib-programoutput
  - py-sphinx-rtd-theme
  - py-python-levenshtein
```

and run `spack install`. The view takes more than 10 seconds to create.

When adding a new spec, and rerunning spack install, it takes as much time.

Also somehow I'm ending up with a bunch of files of the form `[name]~` in my path, like `pybabel~`.

@adamjstewart is reporting the same. ping @becker33 

### Error message

none

### Information on your system

* **Spack:** 0.16.2-3990-e41596c718
* **Python:** 3.8.11
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
