### ISSUE TITLE
Installation issue: netlib-scalapack

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#25859]
### Steps to reproduce the issue

On Spock:
Installing netlib-scalapack as a dependency of slate, installed like:
spack install slate+rocm amdgpu_target=gfx908 ~cuda
Fails like:

    27    -- Could NOT find MPI_C (missing: MPI_C_WORKS)
     28    -- Could NOT find MPI_Fortran (missing: MPI_Fortran_WORKS)
     29    -- Could NOT find MPI (missing: MPI_C_FOUND MPI_Fortran_FOUND)
     30    -- Found MPI_LIBRARY : FALSE
  >> 31    CMake Error at CMakeLists.txt:77 (message):
     32      --> MPI Library NOT FOUND -- please set MPI_BASE_DIR accordingly --

This is using the default PrgEnv-gcc environment and the cray-mpich as an external mpi provider, set up in packages.yaml like:

```
packages:
    mpich:
      buildable: false
      externals:
      - spec: mpich@8.1.7
        prefix: /opt/cray/pe/mpich/8.1.7/ofi/crayclang/10.0
        modules:
        - cray-mpich/8.1.7
```

This is a result of this issue:  https://github.com/spack/spack/issues/25612

### Information on your system

* **Spack:** 0.16.2-4192-c2a6ccbea8
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** original

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7132636/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7132637/spack-build-out.txt)
@vkallesh (not listed as a maintainer but has some notable contributions and this is an AMD platform)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
