### ISSUE TITLE
Spack does not auto-detect Apple's clang compiler

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#259]
On OS X (El Capitan), Spack does not auto-detect the default system compiler `/usr/bin/cc`. It should probably generate a configuration entry like this:
```yaml
    clang@apple-7.0.2:
      cc: /usr/bin/cc
      cxx: /usr/bin/c++
      f77: None
      fc: None
```
Note that Apple uses their own, non-standard version numbers. The compiler describes itself like this:
```
$ /usr/bin/cc --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

Spack does detect the very outdated gcc version that is also available as `/usr/bin/gcc`; this version is so old (4.2.1) that I cannot recommend using it for anything.
