### ISSUE TITLE
Installation issue: Trilinos on macos BigSur and m1 cpu

### ISSUE THREAD

**Issue by cpraveen** [LLNL/spack#25900]
### Steps to reproduce the issue

```spack install -j8 --fail-fast --only dependencies dealii```

Trilinos fails to compile.

### Information on your system

* **Spack:** 0.16.2-4210-b12f38383c
* **Python:** 3.9.6
* **Platform:** darwin-bigsur-m1
* **Concretizer:** original

compilers.yaml

```
compilers:
- compiler:
    spec: apple-clang@12.0.5
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /opt/homebrew/bin/gfortran
      fc: /opt/homebrew/bin/gfortran
    flags: {}
    operating_system: bigsur
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```

packages.yaml

```
packages:
   dealii: 
      variants: ~examples +simplex ~nanoflann ~gmsh ~oce +trilinos ~arborx
   hdf5:
      variants: +fortran +cxx +hl
   petsc:
      variants: +mumps +suite-sparse
   cgns:
      variants: +fortran
   trilinos:
      variants: +rol
   all:
      providers:
         mpi: [openmpi]
         blas: [openblas]
         lapack: [openblas]
```

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/7147193/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7147194/spack-build-env.txt)

@keitat  @kuberry  @sethrj

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
