### ISSUE TITLE
Installation issue: conduit

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#25927]
### Steps to reproduce the issue

On spock, the cray system. using the system cray-mpich as an external compiler like this in packages.yaml:

```
packages:
    mpich:
      buildable: false
      externals:
      - spec: mpich@3.4.2
        #prefix: /opt/cray/pe/mpich/8.1.7/ofi/gnu/9.1 #
        prefix: /opt/cray/pe/mpich/8.1.7/ofi/crayclang/10.0
        modules:
        - cray-mpich/8.1.7
        - craype-network-ofi
```

spack install conduit fails like

```
     30    -- Enable FindMPI:  ON
     31    -- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES) (found version "3.1")
     32    -- Found MPI_CXX: /gpfs/alpine/csc439/scratch/wspear/spack/lib/spack/env/case-insensitive/CC (found version "3.1")
  >> 33    CMake Error at /gpfs/alpine/csc439/scratch/wspear/spack/opt/spack/cray-sles15-x86_64/gcc-10.3.0/cmake-3.20.5-75wbmgevhkcmtaeubtrxgh7rfvqf6ul7/share/cmake-3.20/Modules/FindPackageHandleStandardA
           rgs.cmake:230 (message):
     34      Could NOT find MPI (missing: MPI_C_FOUND) (found version "3.1")
```
Maybe related to other mpi configuration issues on this platform: https://github.com/spack/spack/issues/25612

### Information on your system

* **Spack:** 0.16.2-4235-fca81c2ac8
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** original

### Additional information

Might be same as: https://github.com/spack/spack/issues/19551

@cyrush 
[spack-build-env.txt](https://github.com/spack/spack/files/7157817/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7157818/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
