### ISSUE TITLE
Installation issue: libcircle

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#25922]
### Steps to reproduce the issue

On spock, the cray system. using the system cray-mpich as an external compiler like this in packages.yaml:
```
packages:
    mpich:
      buildable: false
      externals:
      - spec: mpich@3.4.2
        #prefix: /opt/cray/pe/mpich/8.1.7/ofi/gnu/9.1 #
        prefix: /opt/cray/pe/mpich/8.1.7/ofi/crayclang/10.0
        modules:
        - cray-mpich/8.1.7
        - craype-network-ofi
```

`spack install libcircle` fails like
```
     97    Checking whether /gpfs/alpine/csc439/scratch/wspear/spack/lib/spack/env/gcc/gcc responds to '-show'... no
     98    Unable to find suitable MPI Compiler. Try setting MPICC.
  >> 99    configure: error: You should check to see if MPI is setup properly.
```

Maybe related to other issues with spack/mpi configuration on this platform: https://github.com/spack/spack/issues/25612

### Information on your system

* **Spack:** 0.16.2-4235-fca81c2ac8
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** original

### Additional information

[libcircle-config.log.txt](https://github.com/spack/spack/files/7157501/libcircle-config.log.txt)
[libcircle-spack-build-out.txt](https://github.com/spack/spack/files/7157502/libcircle-spack-build-out.txt)
[libcircle-spack-build-env.txt](https://github.com/spack/spack/files/7157503/libcircle-spack-build-env.txt)
@luke

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
