### ISSUE TITLE
Cannot set compiler in `spack: packages: all:` when building a container from environment

### ISSUE THREAD

**Issue by jacorvar** [LLNL/spack#25938]
### Steps to reproduce

I'm trying to build a very basic singularity container with the following (partially taken from [here](https://spack.readthedocs.io/en/latest/environments.html?highlight=concretize#spec-list-references)):
```yaml
spack:
  config:
     install_missing_compilers: true
     concretizer: clingo
     use_curl: true
  container:
    images:
      build: spack/centos7:latest
      final: spack/centos7:latest
    format: singularity
    strip: true
    os_packages:
      command: yum
      build:
        - python3
      final:
        - python3
  concretization: together
  packages:
    all:
      compiler:
      - gcc@7.5.0
      target:
      - linux-centos7-x86_64
  view: true
  definitions:
  - pkgs: [libiconv]

  specs:
    - matrix:
      - [\$pkgs]
```

When I set a given compiler for all packages, as well as a target, as in the config file, it is ignored when creating the environment. The workaround is to create spec lists for compiler and target:
```yaml
  definitions:
  - compilers: ['%gcc@7.5.0']
  - arch: ['arch=linux-centos7-x86_64']
  - pkgs: [libiconv@1.16]
  specs:
    - matrix:
      - [\$pkgs]
      - [\$compilers]
      - [\$arch]
```
Should I then forget about setting compiler and target in `spack: packages: all` section?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
