### ISSUE TITLE
lua modules, hash_length=0, suffixes and name collisions (oh my!).

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2595]
On a current-ish develop, I'm seeing this:

```
[hartzelg@rpbuchop001 spack-20161212]$ spack module refresh --module-type lmod --delete-tree -y
==> Error: Name clashes detected in module files:

file : /isilon/Analysis/scratch/hartzelg/spack/spack-20161212/share/spack/lmod/linux-centos7-x86_64/gcc/5.4.0/emacs/25.1.lua
spec : emacs@25.1%gcc@5.4.0~X toolkit=gtk arch=linux-centos7-x86_64
spec : emacs@25.1%gcc@5.4.0+X toolkit=gtk arch=linux-centos7-x86_64

==> Error: Operation aborted
```

given this:

```
[hartzelg@rpbuchop001 spack-20161212]$ cat etc/spack/modules.yaml
modules:
  enable::
    - lmod
  lmod:
    blacklist:
      -  '%gcc@4.8.3'
    hash_length: 0
    all:
      suffixes:
        '^X': X
```

Based on the discussion in [the tutorial](https://spack.readthedocs.io/en/latest/tutorial_sc16_modules.html#change-module-file-naming), I thought that the suffixes bit would fix the conflict.

**Comment by hartzell** [comment]
@alalazo -- ping....

**Comment by hartzell** [comment]
and @alalazo (and @everyone), if you're ever in Oakland, I owe you a beer....

**Comment by hartzell** [comment]
setting `hash_length: 0` leads to the collision.  Setting `hash_length: 1` (in the course of convincing myself I was editing the correct file) leads to e.g. **emacs/25.1-o6hdu7p**.  Setting `hash_length: 10` leads to e.g. **emacs/25.1-o6hdu7p**.

Seems like it works more like a boolean than an actual length.

**Comment by alalazo** [comment]
@hartzell `spack module` is right:
```console
$ spack info X
==> Error: Package X not found.
```
Try to change your `modules.yaml` to:
```yaml
modules:
  enable::
    - lmod
  lmod:
    blacklist:
      -  '%gcc@4.8.3'
    hash_length: 0
    all:
      suffixes:
        '+X': X
```

**Comment by alalazo** [comment]
Also, I cannot reproduce the problem you had with `hash_length`:
```console
$ tree share/spack/lmod/linux-ubuntu14-x86_64/gcc/
share/spack/lmod/linux-ubuntu14-x86_64/gcc/
└── 4.8
    └── emacs
        ├── 25.1.lua
        └── 25.1-X.lua
```
After changing `modules.yaml` to:
```yaml
modules:
  enable::
    - lmod
  lmod:
    blacklist:
      -  '%gcc@4.8.3'
    hash_length: 1
    all:
      suffixes:
        '+X': X
```
I get:
```console
$ tree share/spack/lmod/linux-ubuntu14-x86_64/gcc/
share/spack/lmod/linux-ubuntu14-x86_64/gcc/
└── 4.8
    └── emacs
        ├── 25.1-a.lua
        └── 25.1-X-k.lua
```
