### ISSUE TITLE
Installation issue: sz+python when using external python

### ISSUE THREAD

**Issue by kwryankrattiger** [LLNL/spack#25973]
### Steps to reproduce the issue

packages.yaml
```
packages:
  python:
    externals:
    - spec: 'python@3.8'
      # configure for module/path to system python paths not writable by user
    buildable: false
```

Install `sz+python` with spack
```
spack install sz+python
```

Error paraphrased
```
Cannot install sz python to <path/to/system/python/modules>, no write permissions
```

### Information on your system

ORNL Spock

* **Spack:** 0.16.2-4028-d27e0bff5a
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo

### Additional information

maintainers: @disheng222 @robertu94 

[spack-build-env.txt](https://github.com/spack/spack/files/7172102/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7172103/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
