### ISSUE TITLE
Installation issue: libnrm won't concretize with clingo and cray-mpich

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#26007]
### Steps to reproduce the issue

On the Cray system Spock we are using cray-mpich as an external mpi provider, set up in packages.yaml like this:

```
packages:
    mpich:
      buildable: false
      externals:
      - spec: cray-mpich@8.1.7 # mpich@3.4.2
        prefix: /opt/cray/pe/mpich/8.1.7/ofi/crayclang/10.0
        modules:
        - cray-mpich/8.1.7
        - craype-network-ofi
```

And the top of our environment like this:
```
spack:
  view: false
  concretization: separately
  packages:
    all:
      compiler:
      - gcc@10.3.0
      providers:
        blas:
        - openblas
        mpi:
        - cray-mpich
      target:
      - x86_64
      variants: +mpi
```

Libnrm built and configured under this configuration previously but with the new concretizer we instead get a lot of concretizer output concluding with:

```
  dependency_type(1132,"build")
  external_only("mpich")
  root("libnrm")
  variant_single_value("boost","mpi")
  variant_single_value("boost","numpy")
  variant_single_value("cairo","svg")
  variant_single_value("cmake","doc")
  variant_single_value("cmake","ownlibs")
  variant_single_value("cmake","qt")
  variant_single_value("curl","libssh")
  variant_single_value("curl","libssh2")
  variant_single_value("harfbuzz","graphite2")
  variant_single_value("hdf5","java")
  variant_single_value("hdf5","mpi")
  variant_single_value("hdf5","szip")
  variant_single_value("hwloc","cairo")
  variant_single_value("hwloc","gl")
  variant_single_value("hwloc","netloc")
  variant_single_value("hwloc","opencl")
  variant_single_value("hwloc","rocm")
  variant_single_value("icedtea","X")
  variant_single_value("knem","hwloc")
  variant_single_value("libgit2","curl")
  variant_single_value("libgit2","ssh")
  variant_single_value("llvm-amdgpu","openmp")
  variant_single_value("llvm-amdgpu","rocm-device-libs")
  variant_single_value("mesa","llvm")
  variant_single_value("mesa18","llvm")
  variant_single_value("mvapich2","fabrics")
  variant_single_value("mvapich2-gdr","pmi_version")
  variant_single_value("mvapich2-gdr","rocm")
  variant_single_value("mvapich2x","pmi_version")
  variant_single_value("netlib-lapack","external-blas")
  variant_single_value("openmpi","cuda")
  variant_single_value("openmpi","internal-hwloc")
  variant_single_value("openmpi","java")
  variant_single_value("openmpi","memchecker")
  variant_single_value("openmpi","singularity")
  variant_single_value("openmpi","thread_multiple")
  variant_single_value("pandoc","texlive")
  variant_single_value("pango","X")
  variant_single_value("pmix","docs")
  variant_single_value("pmix","restful")
  variant_single_value("poppler","boost")
  variant_single_value("poppler","cms")
  variant_single_value("poppler","glib")
  variant_single_value("poppler","gobject")
  variant_single_value("poppler","jpeg")
  variant_single_value("poppler","libcurl")
  variant_single_value("poppler","openjpeg")
  variant_single_value("poppler","qt")
  variant_single_value("poppler","tiff")
  variant_single_value("py-numpy","blas")
  variant_single_value("py-numpy","lapack")
  variant_single_value("py-urllib3","secure")
  variant_single_value("qt","doc")
  variant_single_value("qt","gtk")
  variant_single_value("qt","opengl")
  variant_single_value("slurm","gtk")
  variant_single_value("slurm","hdf5")
  variant_single_value("slurm","hwloc")
  variant_single_value("slurm","mariadb")
  variant_single_value("slurm","pmix")
  variant_single_value("slurm","restd")
  variant_single_value("ucx","java")
  variant_single_value("ucx","knem")
  variant_single_value("valgrind","boost")
  variant_single_value("valgrind","mpi")
==> Error: libnrm@0.1.0 does not satisfy unknown
```
Libnrm specifies mpich as a specific dependency instead of mpi but builds successfully with cray-mpich when it concretizes under the old system. 

Assuming the concretizer is trying to report this specific issue, the error output is not very useful.

### Information on your system

* **Spack:** 0.16.2-4271-c4e26ac7c8
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo

### Additional information

@freuk @alalazo 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
