### ISSUE TITLE
Spack arbitrarily switches interpretation of versions from closed-open range to concrete / exact version during concretization

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#26153]
### Steps to reproduce

Given:
1. Two system compilers with specs `gcc@10.2.0-myidentifier` and `gcc@10.3.0-myidentifier`
2. A package `x` depending on `y`, where `x` conflicts with `gcc@10.3.0`, and also conflicts with `y@2.0.0`
3. And a system version of `y` with the spec `y@2.0.0-myidentifier`

```spack spec x``` concretizes to

```
x@1.0.0%gcc@10.3.0-myflag arch=linux-ubuntu20.04-zen2
    ^y@2.0.0-flag%gcc@10.3.0-myflag arch=linux-ubuntu20.04-zen2
```

not satisfying either of the constraints, which is a bug, because the concrete output spec satisfies the specs of the conflicts:

```python
>>> x = spack.spec.Spec('x')
>>> x.concretize()
>>> x
x@1.0.0%gcc@10.3.0-myflag arch=linux-ubuntu20.04-zen2 ^y@2.0.0-flag%gcc@10.3.0-myflag arch=linux-ubuntu20.04-zen2
>>> x.satisfies(spack.spec.Spec('%gcc@10.3.0'))
True
>>> x.satisfies(spack.spec.Spec('^y@2.0.0'))
True
```

This is because Spack special-cases "concrete versions", where it arbitrarily switches interpretation of the meaning of `x.y.z` as the closed-open range `[x.y.z, x.y.z+1)` to the exact version `x.y.z`.

IMHO Spack should not do this, and uniformly interpret `x.y.z` as a range.

If I understand correctly this behavior was put in place just to support packages with weird numbering schemes `1.0`, `1.0.1`, `...`, `1.0.4`, `1.1`, `...`.

But this is not a good justification, cause in those packages we can simply work around the issue with ranges too, such as:

```python
depends_on('x@1.0:1.0.0')  # only allow 1.0, not 1.0.1, ...
conflicts('x@:1.0.0')  # support 1.0.1, 1.0.2, ... but not 1.0
```

---

To reproduce, create a repo `spack repo create example example`, put these two packages in there, and use the spack.yaml file in the same dir containing the repo:

```python
class X(Package):
    homepage = "localhost"
    has_code = False

    version('1.0.0')

    depends_on('y')

    conflicts('%gcc@10.3.0')
    conflicts('^y@2.0.0')
```

```python
class Y(Package):
    homepage = "localhost"
    has_code = False
    
    version('2.0.0')
    version('1.0.0')
```

```yaml
spack:
  specs:
  - x
  repos:
  - ./example
  packages:
    y:
      externals:
      - spec: y@2.0.0-myidentifier
        prefix: /path/to/somewhere
  'compilers:':
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      spec: gcc@10.2.0-myidentifier
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      spec: gcc@10.3.0-myidentifier
      target: x86_64
```

### Error message

.

### Information on your system

* **Spack:** 0.16.2-4356-2b6a8ccf29
* **Python:** 3.8.11
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
