### ISSUE TITLE
package.yaml does not resolve global variants

### ISSUE THREAD

**Issue by sknigh** [LLNL/spack#2653]
Lets suppose I have an infiniband cluster. I would like to have communication libraries to build with the +verbs variant when it is available. I tried to express this in package.yaml:

``` yaml
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    variants: +verbs
    providers:
      mpi: [openmpi, mpich]
      blas: [openblas]
      lapack: [openblas]
      pil: [py-pillow]
```

Unfortunately, it neither throws an error, nor influences spec concretization. 

``` bash
# spack spec mpich
mpich@3.2%gcc@4.8.5+hydra+pmi+romio~verbs
```
