### ISSUE TITLE
Documentation: how to create (tcl/lmod) module for a Spack environment

### ISSUE THREAD

**Issue by UweSauter** [LLNL/spack#26734]
Assume you have a Spack environment defined via
```
spack:
  concretization: together
  view: true
  packages:
    all:
      compiler: [gcc@7.5.0]
  specs:
  - package1
  - package2
```

What else needs to be defined so that Spack creates a (one) module that will set up the user's environment using Spack's environment's view?
I don't want to generate a tcl/lmod module for each installed package, just for the Spack's environment's view.
