### ISSUE TITLE
Spack install fails immediately with error "/usr/bin/python3: symbol lookup error: /usr/bin/python3: undefined symbol: _Py_LegacyLocaleDetected" on Spock

### ISSUE THREAD

**Issue by giltirn** [LLNL/spack#26799]
### Steps to reproduce

I am trying to build a spec that requires a dev-build of Python3 which is not presently available on Spock. I can have spack build Python in my environment without issue, but when I try to recreate the environment with additional specs or build a new environment that uses the same spack build of Python, spack install fails with the error

"/usr/bin/python3: symbol lookup error: /usr/bin/python3: undefined symbol: _Py_LegacyLocaleDetected"

It possibly indicates some conflict between the spack-installed python and the system installation. To reproduce use the following environment yaml (spock.yaml):

```
spack:
  specs:
  - python@3.6.13 %clang@amd
  concretization: together
  compilers:
  - compiler:
      spec: clang@amd
      paths:
        cc: /opt/rocm-4.2.0/llvm/bin/clang
        cxx: /opt/rocm-4.2.0/llvm/bin/clang++
        f77: /opt/rocm-4.2.0/llvm/bin/flang
        fc: /opt/rocm-4.2.0/llvm/bin/flang
      flags: {}
      operating_system: sles15
      target:  any
      modules:
      - PrgEnv-cray/8.1.0
      - rocm/4.2.0
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@7.5.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc:  /usr/bin/gfortran
      flags: {}
      operating_system: sles15
      target: any
      modules: []
      environment: {}
      extra_rpaths: []
  repos: []
  packages:
    all:
      compiler: [clang@amd,gcc@7.5.0]
      providers:
        mpi: [mpich]
        pkgconfig: [pkg-config]
      buildable: true
      version: []
      target: []
    mpi:
      buildable: False
    libfabric:
      variants: fabrics=verbs,rxm,mrail,tcp
      buildable: true
      version: []
      target: []
      providers: {}
      compiler: []
    mpich:
      externals:
      - spec: mpich@8.1.7-cray
        modules:
        - cray-mpich/8.1.7
      buildable: false
      version: []
      target: []
      providers: {}
      compiler: []

    libzmq:
      externals:
      - spec: libzmq@4.3.3
        modules:
        - libzmq/4.3.3
      buildable: false
      version: []
      target: []
      providers: {}
      compiler: []

    cmake:
      externals:
      - spec: cmake@3.21.3
        modules:
        - cmake/3.21.3
      buildable: false
      version: []
      target: []
      providers: {}
      compiler: []
      
    bzip2:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - bzip2/1.0.8
        spec: bzip2@1.0.8
      compiler: []

    boost:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - boost/1.77.0
        spec: boost@1.77.0
      compiler: []

    libffi:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - libffi/3.3
        spec: libffi@3.3.0
      compiler: []
    curl:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - curl/7.79.0
        spec: curl@7.79.0
      compiler: []

    c-blosc:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - c-blosc/1.21.0
        spec: c-blosc@1.21.0
      compiler: []

    diffutils:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - diffutils/3.8
        spec: diffutils@3.8
      compiler: []

    perl:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - perl/5.34.0
        spec: perl@5.34.0
      compiler: []

    zfp:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - zfp/0.5.5
        spec: zfp@0.5.5
      compiler: []

    papi:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - papi/6.0.0.7
        spec: papi@6.0.0.7
      compiler: []

    hwloc:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - hwloc/2.5.0
        spec: hwloc@2.5.0
      compiler: []

    gettext:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - gettext/0.21
        spec: gettext@0.21
      compiler: []

    zlib:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - zlib/1.2.11
        spec: zlib@1.2.11
      compiler: []

    gdbm:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - gdbm/1.19
        spec: gdbm@1.19
      compiler: []

    sqlite:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - sqlite/3.36.0
        spec: sqlite@3.36.0
      compiler: []

    googletest:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - googletest/1.11.0
        spec: googletest@1.11.0
      compiler: []

    libpng:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - libpng/1.6.37
        spec: libpng@1.6.37
      compiler: []

    libelf:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - libelf/0.8.13
        spec: libelf@0.8.13
      compiler: []

    elfutils:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - elfutils/0.182
        spec: elfutils@0.182
      compiler: []

    expat:
      version: []
      target: []
      buildable: false
      providers: {}
      externals:
      - modules:
        - expat/2.4.1
        spec: expat@2.4.1
      compiler: []



  view: true

```

And build with:

```
spack env create test_python_spack spock.yaml
spack --debug env activate test_python_spack
spack concretize -f
spack --debug install --no-checksum
```

Then edit spock.yaml and add another spec, e.g. 
```
  specs:
  - python@3.6.13 %clang@amd
  - py-numpy
```

then either remove and recreate the environment or just create a new one, e.g. "spack env create test_python_spack2 spock.yaml"

### Error message

spack install fails immediately with the error

"/usr/bin/python3: symbol lookup error: /usr/bin/python3: undefined symbol: _Py_LegacyLocaleDetected"

and produces no other output, even with --debug

### Information on your system

[ckelly@login2.spock test_spack_broken_python]$ spack debug report
* **Spack:** 0.16.3-4829-e2a64bb483
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo

Using develop branch commit   e2a64bb483f42a2ce73a8148eac2b821e8173b30   from 10/12/21

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
