### ISSUE TITLE
concretizer does not take a unique provider

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#26866]
### Steps to reproduce

```yaml
spack:
  specs:
  - sirius ^intel-mkl
  "packages:":
    all:
      compiler: [gcc, intel, pgi, clang, xl, nag, fj, aocc]
      providers:
        blas: [openblas, amdblis]
        fftw-api: [fftw, amdfftw]
        lapack: [openblas, amdlibflame]
        mkl: [intel-mkl]
        mpi: [openmpi, mpich]
        scalapack: [netlib-scalapack, amdscalapack]
```

`spack -e . concretize` shows `openblas@0.3.18`, `intel-mkl@2020.4.304`, `fftw@3.3.9`

meaning, repeated providers for blas, lapack (openblas / intel-mkl) and fftw-api (fftw, intel-mkl).

I can't find a Spack version where this does *not* happen right now.
