### ISSUE TITLE
raja: installation issue with nvhpc compiler on perlmutter (cray-sles15-zen3)

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#26995]
### Steps to reproduce the issue

@davidbeckingsale 

I am trying to install raja with nvhpc compiler and it failed
```
siddiq90@login37> spack concretize
==> Concretized raja@0.13.0%nvhpc@21.7+cuda cuda_arch=80 ^cmake%gcc
 -   mvpo23e  raja@0.13.0%nvhpc@21.7+cuda+examples+exercises~ipo+openmp~rocm+shared~tests amdgpu_target=none build_type=RelWithDebInfo cuda_arch=80 arch=cray-sles15-zen3
 -   d3dhu47      ^blt@0.3.6%nvhpc@21.7 arch=cray-sles15-zen3
[+]  acgtc2y          ^cmake@3.21.1%gcc@11.2.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=cray-sles15-zen3
[+]  3mchoh3              ^ncurses@6.2%gcc@11.2.0~symlinks+termlib abi=none arch=cray-sles15-zen3
[+]  kigy57x                  ^pkg-config@0.29.2%gcc@11.2.0+internal_glib arch=cray-sles15-zen3
[+]  jsad6zb              ^openssl@1.1.1k%gcc@11.2.0~docs+systemcerts arch=cray-sles15-zen3
 -   q7ji4lo      ^camp@0.1.0%nvhpc@21.7+cuda~ipo~rocm~tests amdgpu_target=none build_type=RelWithDebInfo cuda_arch=80 arch=cray-sles15-zen3
 -   zn4xdrw          ^cub@1.12.0-rc0%nvhpc@21.7 arch=cray-sles15-zen3
 -   ywfikjc          ^cuda@11.4.0%nvhpc@21.7~dev arch=cray-sles15-zen3
```

### Information on your system

```
siddiq90@login37> spack debug report
* **Spack:** 0.16.2-3949-8831cb2eed
* **Python:** 3.6.12
* **Platform:** cray-sles15-zen3
* **Concretizer:** original

```

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/7429334/spack-build-out.txt)

Shown below is my spack configuration for perlmutter.
```
spack:
  view: false
  config:
    install_tree:
      root: /tmp/spack
      padded_length: 127
    build_stage: $tempdir/spack-stage
    misc_cache: $tempdir/misc_cache
  mirrors:
    perlmutter-e4s-21.08: /global/common/software/spackecp/mirrors/perlmutter-e4s-21.08
  definitions:
  
          #- compilers:
          #    - nvhpc@21.7
          #    - nvhpc@21.7+mpi
  - nvhpc_cuda_specs:
    
    #- amrex@21.10 +openmp +pic +shared +cuda cuda_arch=80
    # - caliper@2.6.0 +cuda cuda_arch=80
      #- chai@2.3.0 +cuda ~benchmarks ~tests cuda_arch=80 ^umpire@4.1.2 ~shared concretization issue
      #- ginkgo@1.3.0 +cuda cuda_arch=80
      #- hpx@1.7.1 +cuda cuda_arch=80
      #    - hypre@2.22.0 +cuda cuda_arch=80
      #    - kokkos +cuda +wrapper cuda_arch=80
      #    - kokkos-kernels +cuda cuda_arch=80 ^kokkos +wrapper
      #    - magma@2.6.1 +cuda cuda_arch=80

    #  - mfem@4.3.0 +cuda cuda_arch=80
    #    - parsec@3.0.2012 +cuda cuda_arch=80
    - raja@0.13.0 +cuda cuda_arch=80
    #- slate +cuda cuda_arch=80
    #- strumpack +cuda ~slate cuda_arch=80
    #- sundials +cuda cuda_arch=80
    #- superlu-dist@6.4.0 +cuda cuda_arch=80
      #- tasmanian@7.5 +cuda cuda_arch=80
      #- umpire@4.1.2 +cuda ~shared cuda_arch=80
      #- zfp@0.5.5 +cuda cuda_arch=80

    #- hypre@2.22.0 +openmp +cuda cuda_arch=80
  - gcc_specs:
    
    #- adios2@2.7.1 +dataman ~mpi build failure
    - aml@0.1.0





















    
    #- amrex@21.08
    # - arborx@1.0 failed install
    - argobots@1.1






















    
    #- ascent@0.7.1  dep failed
    # - bolt@2.0  build failure
    - darshan-runtime@3.3.1 scheduler=slurm ~mpi
    - darshan-util@3.3.1


































    
    #- dyninst@11.0.1  failed install
    #- flecsi@1.4.2    failed install
    - flit@2.1.0


































    
    # - flux-core@0.28.0 skip for now
    #- fortrilinos@2.0.0 skip for now
    - gasnet@2021.3.0





















    
    # - geopm@1.1.0 skip for now
    - ginkgo@1.3.0
    - hdf5@1.12.0 ~mpi





















    
    #- heffte@2.1.0 +fftw install failed
    #- hpctoolkit@2021.05.15 install failed
    #- hypre@2.22.0












    #- kokkos@3.4.00 +openmp see https://github.com/spack/spack/issues/26950
    #- kokkos-kernels@3.2.00 +openmp
    - legion@21.03.0
    - metall@0.15





















    
    #- mfem@4.3.0 install failed
    #- netlib-scalapack@2.1.0













    # - omega-h@9.32.5 install failed
    - openmpi@4.1.1
    - papi@6.0.0.1


































    
    # - papyrus@1.0.1  install failed
    # - parallel-netcdf@1.12.2 Skip package 
    #- paraview@5.9.1 install failed
      #- parsec@3.0.2012 ~cuda failed install
      # - petsc@3.15.3 ~hypre ~hdf5 failed install
    - qthreads@1.16 scheduler=distrib
    - raja@0.13.0


































    
     #- rempi@1.1.0 failed install unable to find zlib
     #- scr@3.0rc1
      #- slate@2021.05.02 ~cuda ~mpi
      #- strumpack@5.1.1 ~slate
      #- sundials@5.7.0
    - superlu@5.2.2


































    
      #- superlu-dist@6.4.0 +openmp
    - swig@4.0.2
    - swig@4.0.2-fortran
    - sz@2.1.12 +fortran


































    
      #- tasmanian@7.5 +fortran +mpi
     #- tau@2.30.1 +mpi ~binutils not working
     #- trilinos@13.0.1 +amesos +amesos2 +anasazi +aztec +belos +boost +epetra +epetraext +ifpack +ifpack2 +intrepid +intrepid2 +isorropia +kokkos +ml +minitensor +muelu +nox +piro +phalanx +rol +rythmos +sacado +stk +shards +shylu +stokhos +stratimikos +teko +tempus +tpetra +trilinoscouplings +zoltan +zoltan2 +superlu-dist gotype=long_long
    - umap@2.1.0
    - umpire@4.1.2 +openmp



































    
    #- unifyfs@0.9.1 +fortran
    #- upcxx@2021.3.0
    #- veloc@1.4
    - vtk-m@1.6.0
    - zfp@0.5.5
  - nvhpc: ['%nvhpc@21.7']
  - gcc: ['%gcc@11.2.0']
  specs:
  - matrix:
    - [$nvhpc_cuda_specs]
    - [$nvhpc]
    - [^cmake%gcc]
  - matrix:
    - [$gcc_specs]
    - [$gcc]
  compilers:
  - compiler:
      spec: gcc@10.3.0
      paths:
        cc: /opt/cray/pe/gcc/10.3.0/bin/gcc
        cxx: /opt/cray/pe/gcc/10.3.0/bin/g++
        f77: /opt/cray/pe/gcc/10.3.0/bin/gfortran
        fc: /opt/cray/pe/gcc/10.3.0/bin/gfortran
      operating_system: sles15
      modules:
      - PrgEnv-gnu/8.1.0
      - gcc/10.3.0
  - compiler:
      spec: gcc@11.2.0
      paths:
        cc: /opt/cray/pe/gcc/11.2.0/bin/gcc
        cxx: /opt/cray/pe/gcc/11.2.0/bin/g++
        f77: /opt/cray/pe/gcc/11.2.0/bin/gfortran
        fc: /opt/cray/pe/gcc/11.2.0/bin/gfortran
      operating_system: sles15
      modules:
      - PrgEnv-gnu/8.1.0
      - gcc/11.2.0
  - compiler:
      spec: nvhpc@21.7
      paths:
        cc: /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin/nvc
        cxx: /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin/nvc++
        f77: /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin/nvfortran
        fc: /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin/nvfortran
      modules:
      - nvhpc/21.7
      flags: {}
      operating_system: sles15
      target: any
      environment: {}
      extra_rpaths: []
  packages:
    all:
      providers:
        compiler: [gcc@11.3.0, nvhpc@21.7]
        mpi: [cray-mpich]
        fftw: [cray-fftw]
        blas: [cray-libsci, nvhpc]
        scalapack: [cray-libsci]
        pkgconfig: [pkg-config]
    amrex:
      variants: +openmp +pic +fortran
    automake:
      version: [1.16.3]
    bzip2:
      version: [1.0.6]
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    cray-mpich:
      buildable: false
      externals:
      - spec: cray-mpich@8.1.0
        prefix: /opt/cray/pe/mpich/8.1.9
        modules:
        - cray-mpich/8.1.9
    cray-libsci:
      buildable: false
      externals:
      - spec: cray-libsci@20.06.1
        modules:
        - cray-libsci/21.08.1.2
    cuda:
      buildable: false
      version: [11.4.0]
      externals:
      - spec: cuda@11.4.0
        prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/
        modules:
        - nvhpc/21.7
    diffutils:
      version: [3.6]
      buildable: false
      externals:
      - spec: diffutils@3.6
        prefix: /usr
    cray-fftw:
      version: [3.3.8.8]
      buildable: false
      externals:
      - spec: cray-fftw@3.3.8.8
        modules:
        - cray-fftw/3.3.8.11
    hdf5:
      variants: +cxx +fortran
    gettext:
      version: [0.19.8.1]
      buildable: false
      externals:
      - spec: gettext
        prefix: /usr
    libfabric:
      buildable: false
      externals:
      - spec: libfabric@1.11.0
        modules:
        - libfabric/1.11.0.4.79
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    openssl:
      buildable: false
      externals:
      - spec: openssl@1.1.1k
        prefix: /usr
    openssh:
      version: [7.9p1]
      buildable: false
      externals:
      - spec: openssh
        prefix: /usr
    openmpi:
      version: [4.0.5]
      variants: +cxx schedulers=slurm
      externals:
      - spec: openmpi@3.1.5
        prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/openmpi/openmpi-3.1.5/
        modules:
        - nvhpc/21.7
    pdsh:
      buildable: false
      externals:
      - spec: pdsh@2.31
        prefix: /usr
    python:
      buildable: false
      externals:
      - spec: python@3.8.8
        modules:
        - python/3.9-anaconda-2021.05
    slurm:
      buildable: false
      version: [20-11-5-1]
      externals:
      - spec: slurm
        prefix: /usr
    tar:
      version: [1.3]
      buildable: false
      externals:
      - spec: tar@1.30
        prefix: /usr

```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
