### ISSUE TITLE
MKL is not virtual dependency

### ISSUE THREAD

**Issue by jrood-nrel** [LLNL/spack#2736]
After commit b9ec69dce15c69ba11f6d637614399b3a3a470e5 I am getting an error when listing MKL as an external package. My configuration was working previously.

My packages.yaml:
```
packages:
  mkl:
    paths:
      mkl@16.2.181%intel@16.0.2 arch=linux-centos6-x86_64: /.../intel/16.0/compilers_and_libraries_2016.2.181/linux/mkl
      mkl@16.2.181%intel@16.0.2 arch=linux-rhel6-x86_64: /.../intel/16.0/compilers_and_libraries_2016.2.181/linux/mkl
      mkl@16.2.181%gcc@5.2.0 arch=linux-centos6-x86_64: /.../intel/16.0/compilers_and_libraries_2016.2.181/linux/mkl
      mkl@16.2.181%gcc@5.2.0 arch=linux-rhel6-x86_64: /.../intel/16.0/compilers_and_libraries_2016.2.181/linux/mkl
    buildable: False
  all:
    compiler: [gcc@5.2.0, intel@16.0.2]
    providers:
      mpi: [openmpi]
      blas: [mkl]
      lapack: [mkl]
```

When trying to install anything I get an error:
```
[jrood@computer ~]$ spack install zlib
==> Error: packages.yaml entries cannot be virtual packages:
  in "/home/user/spack/etc/spack/packages.yaml", line 2, column 3: mkl
```

Does this mean Spack thinks MKL is virtual, when it is actually a concrete package?
