### ISSUE TITLE
system version not considered/respected during concretisation ?

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2846]
I am testing this on OS-X with version `v0.10.0`. `libxml2` spec looks like:

```
$ ./bin/spack spec libxml2
Input spec
--------------------------------
libxml2

Normalized
--------------------------------
libxml2
    ^pkg-config@0.9.0:
    ^xz
    ^zlib

Concretized
--------------------------------
libxml2@2.9.4%clang@3.9.0~python arch=darwin-elcapitan-x86_64
    ^pkg-config@0.29.1%clang@3.9.0+internal_glib arch=darwin-elcapitan-x86_64
    ^xz@5.2.2%clang@3.9.0 arch=darwin-elcapitan-x86_64
    ^zlib@1.2.10%clang@3.9.0+pic arch=darwin-elcapitan-x86_64
```

Now I add following in `packages.yaml` :

```
packages:

    pkg-config:
        paths:
            pkg-config@system%clang@3.9.0: /usr/local
        buildable: False
        version: [system]
```

Now I see below error:

```
$ ./bin/spack spec libxml2
Input spec
--------------------------------
libxml2

Normalized
--------------------------------
libxml2
    ^pkg-config@0.9.0:
    ^xz
    ^zlib

Concretized
--------------------------------
==> Error: The spec 'pkg-config' is configured as not buildable, and no matching external installs were found
```

The documentation says :

```
The @system “version” means “I don’t care what version it is, just use what is there.”
```

Am I missing anything **obvious** here?

More info : 

```
./bin/spack config get packages
packages:
  all:
    buildable: true
    compiler:
    - clang
    - gcc
    - intel
    - pgi
    - xl
    - nag
    modules: {}
    paths: {}
    providers:
      blas:
      - openblas
      lapack:
      - openblas
      mpi:
      - openmpi
      - mpich
      pil:
      - py-pillow
    version: []
  pkg-config:
    buildable: false
    compiler: []
    modules: {}
    paths:
      pkg-config@system%clang@3.9.0: /usr/local
    providers: {}
    version:
    - system
```

**Comment by davydden** [comment]
documentation should be updated. The issue comes from
```
    depends_on('pkg-config@0.9.0:', type='build')
```
in `libxml2`. 

> The @system “version” means “I don’t care what version it is, just use what is there.”

is ok for some cases, but won't work when there are versions requierements. In this case, you need to **tell Spack which version exactly** is provided on your system.

**Comment by adamjstewart** [comment]
What was the original purpose of `@system` anyway? I know we wanted to dictate that there was a rolling `system` version that might change, but that we didn't care about. But as long as `buildable=False`, Spack won't try to install it's own newer version, right? Maybe we should just ask users to always specify the actual version of external packages.

@citibeth You make heavy use of `@system` right? How do you feel about this? Maybe we should resurrect the `develop` holy wars while we're at it 😆

**Comment by davydden** [comment]
> Maybe we should just ask users to always specify the actual version of external packages.

:+1: I would say so.

**Comment by citibeth** [comment]
I think `@system` is an idea that needs to die.  The main idea was that you
could rely on `openssl@system`, and then you don't care what version of
`openssl` your System provides.  AFAIK, Spack has no special-purpose code
to do anything special for `@system`.

`openssl@system` seems to work OK.  Every other package I've tried it with,
I've come to conclude it's not really the right thing.  Better to just go
the extra km and figure out what version your system ACTUALLY provides.
See: https://github.com/LLNL/spack/pull/2703

**Comment by pramodk** [comment]
thanks for clarification!

**Comment by adamjstewart** [comment]
So it sounds like we only need to update the documentation then? If there's no special handling of `@system` anywhere in Spack that ought to be an easy change!

**Comment by citibeth** [comment]
Yes.

**Comment by citibeth** [comment]
BTW... my dream is to ship OS-specific `packages.yaml` files that already tell Spack what versions are installed on the system.  For example, for my CentOS 7:
```
# Use system version of certain packages on CentOS 7
#
# Try:
#     yum list installed | grep <package>
#     repoquery -l <package> | grep <expected filename>

packages:
    # Problems in the past installing Python2
    # See: https://github.com/LLNL/spack/issues/1100
    # yum: python
    python:
        paths:
            python@2.7.5: /usr
        version: [2.7.5]


    # Recommended for security reasons
    # Do not install OpenSSL as non-root user.
    # yum: openssl-devl
    openssl:
        paths:
            openssl@1.0.1e: /usr
        version: [1.0.1e]
        buildable: False

    # Recommended, unless your system doesn't provide Qt4
    # yum: qt
    qt:
        paths:
            qt@4.8.5: /usr
        version: [4.8.5]
        buildable: False

    # Recommended, unless your system doesn't provide X11 libs
    # yum: libXaw-devel
    libxaw:
        paths:
            libxaw@1.0.12: /usr
        version: [1.0.12]
        buildable: False

# freetype complains if you try to use external libpng
#    # Matplotlib uses the system libpng anyway
#    # yum: libpng-devel
#    libpng:
#        paths:
#            libpng@1.5.13: /usr
#        version: [1.5.13]
#        buildable: False

#    # yum: libssh2-devel
#    libssh2:
#        paths:
#            libssh2@1.4.3: /usr
#        version: [1.4.3]
#        buildable: False
#
#    # yum: curl libcurl-devel
#    curl:
#        paths:
#            curl@7.29.0: /
#        version: [7.29.0]
#        buildable: False


#    libxcb:
#        paths:
#            libxcb@0.4.0: /false/path
#        version: [0.4.0]
#        buildable: False

#    # ========= Efforts to build less
#    m4:
#        paths:
#            m4@1.4.17: /    # We lie...
#        version: [1.4.17]
#        buildable: False
#
#    doxygen:
#        paths:
#            doxygen@1.8.10: /    # We lie...
#        version: [1.8.10]
#        buildable: False
```
