### ISSUE TITLE
Spack compilation env variable setting (e.g. INCLUDE, C_INCLUDE_PATH) does not respect @property def headers

### ISSUE THREAD

**Issue by giltirn** [LLNL/spack#28595]
### Steps to reproduce

For example, the util-linux-uuid package defines
```    @property
    def headers(self):
        return find_headers('uuid', self.prefix, recursive=True)
```
which is supposed to tell spack that the include path should be <install_path>/include/uuid.  This is respected by the pkg-config .pc file produced by spack:  `Cflags: -I${includedir}/uuid` but not by the environment variables, e.g.
```
$ echo $INCLUDE
...:/gpfs/alpine/csc299/proj-shared/ckelly/chimbuko_1_25_22/spack/spack/opt/spack/linux-rhel8-power9le/gcc-9.1.0/util-linux-uuid-2.36.2-wwnknlydny7h2jjrqw3ujkejmyphvfpm/include:...
```

To reproduce: set ~/.spack/modules.yaml to include
```
modules:
 prefix_inspections:
   lib: [LIBRARY_PATH]
   lib64: [LIBRARY_PATH]
   include:
     - C_INCLUDE_PATH
     - CPLUS_INCLUDE_PATH
     - INCLUDE
```
then `spack install util-linux-uuid` and `echo $INCLUDE`

### Error message

```
$ echo $INCLUDE
...:/gpfs/alpine/csc299/proj-shared/ckelly/chimbuko_1_25_22/spack/spack/opt/spack/linux-rhel8-power9le/gcc-9.1.0/util-linux-uuid-2.36.2-wwnknlydny7h2jjrqw3ujkejmyphvfpm/include:...
```
expect
```
$ echo $INCLUDE
...:/gpfs/alpine/csc299/proj-shared/ckelly/chimbuko_1_25_22/spack/spack/opt/spack/linux-rhel8-power9le/gcc-9.1.0/util-linux-uuid-2.36.2-wwnknlydny7h2jjrqw3ujkejmyphvfpm/include/uuid:...
```

### Information on your system

Summit

```
[ckelly@login5.summit 2nodes_42clients_40shards]$ spack debug report
* **Spack:** 0.17.1-957-bed3a69498
* **Python:** 3.6.8
* **Platform:** linux-rhel8-power9le
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This:
```yaml
modules:
 prefix_inspections:
   lib: [LIBRARY_PATH]
   lib64: [LIBRARY_PATH]
   include:
     - C_INCLUDE_PATH
     - CPLUS_INCLUDE_PATH
     - INCLUDE
```
means "Inspect the prefix of the installation. If you find `<key>` append its path to `<values>`"
