### ISSUE TITLE
Environment Concretization w/ Definitions

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#28617]
### Steps to reproduce

I am using a Spack environment of the form:

```
spack:
  # variations of this environment can be controlled via environment variables during `spack env create`
  definitions:
  # CUDA
  - cuda: []
  - cuda: [cuda, blaspp +cuda, lapackpp ^blaspp +cuda]
    when: env.get("SPACK_STACK_USE_CUDA", "1") == "1"
  specs:
  - adios2
  - blaspp
  - ccache
  - cmake
  - fftw
  - hdf5
  - lapackpp
  - mpi
  - pkgconfig
  - $cuda
```

I think this should work, as the `spec`s are similar to what I write in `depends_on` for the `warpx` package.
In particular, would expect that the concretizer picks the `+cuda` variant of `blaspp`. But instead, it concretizes out two versions of `blaspp` (`+cuda` is not a default variant) and then collides in creating the final environment.

The work-around I have to do is:
```
spack:
  # variations of this environment can be controlled via environment variables during `spack env create`
  definitions:
  # CUDA
  - cuda: []
  - cuda: [cuda, blaspp +cuda, lapackpp ^blaspp +cuda]
    when: env.get("SPACK_STACK_USE_CUDA", "") == "1"
  - cuda: [cuda, blaspp, lapackpp]
    when: env.get("SPACK_STACK_USE_CUDA", "") != "1"
  specs:
  - adios2
  - ccache
  - cmake
  - fftw
  - hdf5
  - mpi
  - pkgconfig
  - $cuda
```

### Error message

```
==> Updating view at spack/var/spack/environments/warpx-lxplus-cuda-py/.spack-env/view
==> Error: Package merge blocked by file: spack/var/spack/environments/warpx-lxplus-cuda-py/.spack-env/._view/lguqkqwqj5twvkl5tonmcwbv3ivpaflh/.spack/blaspp/spec.json
```

### Information on your system

Any linux.

* **Spack:** 0.17.1-930-f6d6153410
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
