### ISSUE TITLE
Non-numeric spec version in compilers.yaml and Multiple compilers error

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2866]
I would like to define spec in `compilers.yaml` with `non-numeric` version as: 

```
compilers:
- compiler:
    modules: [bg-xl]
    operating_system: cnk
    paths:
      cc: /opt/ibmcmp/vacpp/bg/12.1/bin/bgxlc
      cxx: /opt/ibmcmp/vacpp/bg/12.1/bin/bgxlc++
      f77: /opt/ibmcmp/xlf/bg/14.1/bin/xlf
      fc: /opt/ibmcmp/xlf/bg/14.1/bin/xlf2008
    spec: xl@12.1
- compiler:
    modules: [bg-xl]
    operating_system: cnk
    paths:
      cc: /opt/ibmcmp/vacpp/bg/12.1/bin/bgxlc_r
      cxx: /opt/ibmcmp/vacpp/bg/12.1/bin/bgxlc++_r
      f77: /opt/ibmcmp/xlf/bg/14.1/bin/xlf_r
      fc: /opt/ibmcmp/xlf/bg/14.1/bin/xlf2008_r
    spec: xl@12.1.r
```

`spack compilers` show versions correctly :

```
spack compilers
==> Available compilers
-- xl -----------------------------------------------------------
xl@12.1.r  xl@12.1
```

I can spec/install package with `xl@12.1.r`:
```
spack spec mod2c %xl@12.1.r
Input spec
--------------------------------
mod2c%xl@12.1.r

Normalized
--------------------------------
mod2c%xl@12.1.r
    ^cmake@2.8.12:

Concretized
--------------------------------
mod2c@develop%xl@12.1.r arch=bgq-cnk-ppc64
    ^cmake@2.8.12%xl@12.1.r~doc+ncurses+openssl+ownlibs~qt arch=bgq-cnk-ppc64
```

But `xl@12.1` gives below error:

```
spack spec mod2c %xl@12.1
Input spec
--------------------------------
mod2c%xl@12.1

Normalized
--------------------------------
mod2c%xl@12.1
    ^cmake@2.8.12:

Concretized
--------------------------------
==> Error: Multiple compilers satisfy spec xl@12.1
```

Is this bug or invalid `compilers.yaml` ?
