### ISSUE TITLE
Installation issue: intel: Can't build Intel lmod file from module-based Intel install

### ISSUE THREAD

**Issue by mathomp4** [LLNL/spack#28768]
### Steps to reproduce the issue

```console
$ spack install intel@2021.3.0
==> intel@2021.3.0 : has external module in ['comp/gcc/10.1.0', 'comp/intel/2021.3.0']
==> Warning: cannot perform the requested write operation on module files [Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh]
==> Warning: cannot perform the requested write operation on module files [Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh]
[+] /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux (external intel-2021.3.0-hdgcisraeacu42xktiqns4w5raaqizir)
```

### Information on your system

* **Spack:** 0.17.1-1070-5208fcf1ea
* **Python:** 3.9.9
* **Platform:** linux-sles12-skylake_avx512
* **Concretizer:** clingo

### Additional information

This is an odd one. I'm trying to use Intel 2021.3 on a cluster where Intel 2021.3 has *already been installed* by the sysadmin. Normally, I'd do:
```
ml comp/gcc/10.1.0 comp/intel/2021.3.0
```
and I'd get it.

So with spack, in my `compilers.yaml` I have (truncated for this issue, and gcc 4.8 is the "base" gcc on this system):
```yaml
compilers:
- compiler:
    spec: gcc@4.8
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: sles12
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.3.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/icc
      cxx: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/icpc
      f77: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/ifort
      fc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles12
    target: x86_64
    modules:
    - comp/gcc/10.1.0
    - comp/intel/2021.3.0
    environment: {}
    extra_rpaths: []
```
I have a `packages.yaml`:
```yaml
packages:
...
  intel:
    buildable: false
    externals:
    - spec: intel@2021.3.0%gcc@4.8
      modules:
        - comp/gcc/10.1.0
        - comp/intel/2021.3.0
...
```

And when I try to install, `spack` installs, but then fails at the Lua module creation phase. As seen above, it's looking for a `compilervars.sh` file that doesn't exist.

Now, as a test, I essentially duplicated all the above with `intel-oneapi-compilers` as I didn't quite know what 2021.3 actually is in spack speak. When i do that I get:

```console
$ spack install intel-oneapi-compilers@2021.3.0
==> intel-oneapi-compilers@2021.3.0 : has external module in ['comp/gcc/10.1.0', 'comp/intel/2021.3.0']
==> Warning: cannot perform the requested write operation on module files [Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compiler/2021.3.0/env/vars.sh]
==> Warning: cannot perform the requested write operation on module files [Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compiler/2021.3.0/env/vars.sh]
[+] /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux (external intel-oneapi-compilers-2021.3.0-kucwu2giszpwh4daajsxfq5zabcz7f2p)
```

Now this is slightly better as there is a `vars.sh` file in the install on my system, but it's at:
```
/usr/local/intel/oneapi/2021/compiler/2021.3.0/env/vars.sh
```
not:
```
/usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compiler/2021.3.0/env/vars.sh
```

Is there something I need to add to `modules.yaml` to tell it where `vars.sh` lives?

---

Maintainers: @rscohn2

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
I am not that familiar with spack's support for modules and external packages. The intel-oneapi-compilers package constructs the path to the vars.sh file relative to the prefix.  For your install: ``/usr/local/intel/oneapi/2021`` is the prefix and it should add ``compiler/2021.3.0/env/vars.sh`` to the prefix to find the vars.sh file. Apparently, in your case it thinks the prefix is: ``/usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/``. I don't know how spack computes the prefix in your scenario.

**Comment by mathomp4** [comment]
> I am not that familiar with spack's support for modules and external packages. The intel-oneapi-compilers package constructs the path to the vars.sh file relative to the prefix. For your install: `/usr/local/intel/oneapi/2021` is the prefix and it should add `compiler/2021.3.0/env/vars.sh` to the prefix to find the vars.sh file. Apparently, in your case it thinks the prefix is: `/usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/`. I don't know how spack computes the prefix in your scenario.

@rscohn2 Interesting. Okay. Any ideas who might be a good person to "ping" on here? Is there an "lmod-construction" maintainer?

**Comment by rscohn2** [comment]
@scheibelp: Can you point us at code to look at for this problem?

**Comment by kgerheiser** [comment]
Hey @mathomp4 , I was looking into a similar issue because I wanted to implement a `spack external find intel-oneapi-mpi`. There are two related issues going on, but basically the information from `setup_run_environment` is also put into your modules, which includes sourcing some files. Spack isn't great at generating meta modules.

First, just kind of reiterating was @rscohn2 said for your test case. Aside from `modules.yaml`, `setup_run_environment` also populates your modules like this:

https://github.com/spack/spack/blob/93377942d17d356aaae793c5d665a3e48ab7649e/lib/spack/spack/build_systems/oneapi.py#L97-L98

Where component path is:

https://github.com/spack/spack/blob/93377942d17d356aaae793c5d665a3e48ab7649e/lib/spack/spack/build_systems/oneapi.py#L39-L41

And your prefix is: 

`/usr/local/intel/oneapi/2021/compiler/2021.3.0/linux`

I'm guessing the prefix is formed from truncating the `/bin` where the compiler is located. I don't know the exact mechanism.


Now, for your original issue, you have to look at the `intel` package (different than intel-oneapi-compilers). The `setup_run_environment` sources `bin/compilevars.sh`

https://github.com/spack/spack/blob/93377942d17d356aaae793c5d665a3e48ab7649e/lib/spack/spack/build_systems/intel.py#L643

**Comment by scheibelp** [comment]
> And when I try to install, spack installs, but then fails at the Lua module creation phase. As seen above, it's looking for a compilervars.sh file that doesn't exist.

I wanted to check: do you need a module file for these packages? If you are trying to get past this quickly and don't need the module files, you can disable them entirely or on a per-package basis (see https://spack-tutorial.readthedocs.io/en/latest/tutorial_modules.html#hierarchical-module-files).

If you do need the module, https://github.com/spack/spack/issues/28768#issuecomment-1030731842 explains how that works for `intel` and `intel-oneapi-compilers`.

From examining the code, it appears we'd terminate the installation if the module generation fails, but I wanted to confirm that the install failed since the snippet you included did not show a termination 

```
$ spack install intel@2021.3.0
==> intel@2021.3.0 : has external module in ['comp/gcc/10.1.0', 'comp/intel/2021.3.0']
==> Warning: cannot perform the requested write operation on module files [Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh]
==> Warning: cannot perform the requested write operation on module files [Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh]
[+] /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux (external intel-2021.3.0-hdgcisraeacu42xktiqns4w5raaqizir)
```

(if there was no further output after that I'm also interested, since in that case IMO we ought to make sure the errors are reported more clearly).

I think you can set `prefix` and `modules` separately on the external package entry (to avoid a false inference) but if your Intel installation doesn't have a `compilervars.sh` anywhere, then it would seem that it doesn't conform to our expectations (so skipping the module or fortifying our hooks to bypass this particular module would seem to be the only solution for the `intel` package).

**Comment by scheibelp** [comment]
@rscohn2 based on https://github.com/spack/spack/issues/28768#issuecomment-1030731842, do you think that `build_systems.oneapi.setup_run_environment` should omit the component directory in some cases (perhaps all cases)?

**Comment by rscohn2** [comment]
> Hey @mathomp4 , I was looking into a similar issue because I wanted to implement a `spack external find intel-oneapi-mpi`.

@kgerheiser: There was some discussion here: https://github.com/spack/spack/pull/28066. It would be great if you can do it.

**Comment by rscohn2** [comment]
> @rscohn2 based on [#28768 (comment)](https://github.com/spack/spack/issues/28768#issuecomment-1030731842), do you think that `build_systems.oneapi.setup_run_environment` should omit the component directory in some cases (perhaps all cases)?

If I am understanding your question, I think it is correct the way it is. The problem is the inconsistency in the way prefix is defined between external and internal installations. If you look at https://github.com/spack/spack/blob/93377942d17d356aaae793c5d665a3e48ab7649e/lib/spack/spack/build_systems/intel.py#L645 you will see that the path for compilervars.sh does not have a component directory, but the other components include a component directory. It matches the layout of parallel studio: 
```
rscohn1@rscohn1-mobl1:spack$ ls $(spack location -i intel-parallel-studio)/tbb/bin
tbbvars.csh  tbbvars.sh
rscohn1@rscohn1-mobl1:spack$ ls $(spack location -i intel-parallel-studio)/bin
codecov  compilervars.csh  compilervars.sh  fpp  icc  iccvars.csh  iccvars.sh  icpc  ifort  ifortvars.csh  ifortvars.sh  map_opts  profdcg  profmerge  proforder  tselect  xiar  xild
rscohn1@rscohn1-mobl1:spack$
```
oneapi has a more consistent layout:
```
rscohn1@rscohn1-mobl1:spack$ ls $(spack location -i intel-oneapi-compilers@2021.4.0%gcc@10.3.0)/compiler/latest/env
vars.sh
rscohn1@rscohn1-mobl1:spack$ ls $(spack location -i intel-oneapi-compilers@2021.4.0%gcc@10.3.0)/tbb/latest/env
vars.sh
rscohn1@rscohn1-mobl1:spack$ 
```

**Comment by scheibelp** [comment]
OK got it, so I think then that for `intel-oneapi-compilers`, setting the `prefix` attribute on the external would resolve that issue, and we'd have to update Spack to retrieve the appropriate prefix from the module (the generic code would not know to strip off the component directory).

For `intel` package, I think that the missing `compilervars.sh` is a problem regardless of how we determine the prefix (so either Spack needs to skip invalid module files automatically, or the config needs to be updated in your case to skip it).

**Comment by mathomp4** [comment]
All,

Okay, I managed to get some time to work on this. So I did this:
```yaml
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@2021.3.0%gcc@4.8
      prefix: /usr/local/intel/oneapi/2021
      modules:
        - comp/gcc/10.1.0
        - comp/intel/2021.3.0
```
and the `spack install` was much happier:
```
$ spack install intel-oneapi-compilers
==> intel-oneapi-compilers@2021.3.0 : has external module in ['comp/gcc/10.1.0', 'comp/intel/2021.3.0']
[+] /usr/local/intel/oneapi/2021 (external intel-oneapi-compilers-2021.3.0-2o4kz7f7zjh4tepc56yulnz3d7heh6hn)
```
So that's nice. But now the generate modulefile is a bit...lacking. For example, when I did `spack install gcc@11.2.0` based on:
```yaml
  gcc:
    buildable: false
    externals:
    - spec: gcc@11.2.0%gcc@4.8
      modules:
      - comp/gcc/11.2.0
```
In the resulting lua module I have (at the end):
```lua
...
-- Services provided by the package
family("compiler")

-- Loading this module unlocks the path below unconditionally
prepend_path("MODULEPATH", "/gpfsm/dnb44/mathomp4/spack/share/spack/lmod/gcc/11.2.0")



prepend_path("PATH", "/usr/local/other/gcc/11.2.0/bin", ":")
prepend_path("MANPATH", "/usr/local/other/gcc/11.2.0/share/man", ":")
prepend_path("LD_LIBRARY_PATH", "/usr/local/other/gcc/11.2.0/lib", ":")
prepend_path("LD_LIBRARY_PATH", "/usr/local/other/gcc/11.2.0/lib64", ":")
prepend_path("CMAKE_PREFIX_PATH", "/usr/local/other/gcc/11.2.0/", ":")
setenv("CC", "/usr/local/other/gcc/11.2.0/bin/gcc")
setenv("CXX", "/usr/local/other/gcc/11.2.0/bin/g++")
setenv("FC", "/usr/local/other/gcc/11.2.0/bin/gfortran")
setenv("F77", "/usr/local/other/gcc/11.2.0/bin/gfortran")
setenv("GCC_ROOT", "/usr/local/other/gcc/11.2.0")
setenv("DIR_GCC", "/usr/local/other/gcc/11.2.0")
setenv("GCC_DIR", "/usr/local/other/gcc/11.2.0")
```
Now the last three are due to settings in my `modules.yaml` file, but notice that I get `CC`,`CXX`,`FC,`and `F77`. But in my `intel-oneapi-compiler` module those aren't there.

My guess is the ones for gcc are filled by `linux/compilers.yaml`:
```yaml
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: /usr/local/other/gcc/11.2.0/bin/gcc
      cxx: /usr/local/other/gcc/11.2.0/bin/g++
      f77: /usr/local/other/gcc/11.2.0/bin/gfortran
      fc: /usr/local/other/gcc/11.2.0/bin/gfortran
    flags: {}
    operating_system: sles12
    target: x86_64
    modules:
    - comp/gcc/11.2.0
    environment: {}
    extra_rpaths: []
```
But `spack compiler find` only creates `intel` and `oneapi` (and `dpcpp` I guess) for Intel-based compilers:
```yaml
- compiler:
    spec: intel@2021.3.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/icc
      cxx: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/icpc
      f77: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/ifort
      fc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles12
    target: x86_64
    modules:
    - comp/gcc/10.1.0
    - comp/intel/2021.3.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2021.3.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/icx
      cxx: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/icpx
      f77: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/ifx
      fc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/ifx
    flags: {}
    operating_system: sles12
    target: x86_64
    modules:
    - comp/gcc/10.1.0
    - comp/intel/2021.3.0
    environment: {}
    extra_rpaths: []
```
So, I thought, okay, let's add a new section and copy-paste the intel section, but make it for `intel-oneapi-compilers`:
```yaml
- compiler:
    spec: intel-oneapi-compilers@2021.3.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/icc
      cxx: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/icpc
      f77: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/ifort
      fc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles12
    target: x86_64
    modules:
    - comp/gcc/10.1.0
    - comp/intel/2021.3.0
    environment: {}
    extra_rpaths: []
```
But now when I run the install (after uninstalling):
```yaml
$ spack install --verbose intel-oneapi-compilers
==> Error:
```
Any ideas now?

**Comment by rscohn2** [comment]
I don't understand this part of spack very well. Is it because parallel studio compilers set CC & friends: https://github.com/spack/spack/blob/81a6d17f4cfac04107c8560e7b3364cb57d2df97/lib/spack/spack/build_systems/intel.py#L1022

But oneapi compilers do not?
https://github.com/spack/spack/blob/81a6d17f4cfac04107c8560e7b3364cb57d2df97/lib/spack/spack/build_systems/oneapi.py#L88

**Comment by mathomp4** [comment]
@rscohn2 Maybe? I guess since the OneAPI packages can supply up to three different "compilers" (intel, oneapi, dpcpp), then it can't be generalized? Hmm.

**Comment by rscohn2** [comment]
dpcpp is effectively (icpx -fsycl) and we are transitioning from icpc to icpx so if I should be defining CC & friends then it would be icx/icpx/ifx. Can you check if it solves the problem you are seeing?

**Comment by mathomp4** [comment]
> dpcpp is effectively (icpx -fsycl) and we are transitioning from icpc to icpx so if I should be defining CC & friends then it would be icx/icpx/ifx. Can you check if it solves the problem you are seeing?

@rscohn2 Unfortunately, I can't use the intel x-compilers. They don't support enough of the Fortran Standard yet to build my codes. So at the moment, I'm stuck with the "Classic" compilers.

**Comment by rscohn2** [comment]
We could use a variant to decide which set of compilers to use. I will try it out later.

**Comment by rscohn2** [comment]
I spent some time learning how the module files and external packages work. I believe adding the prefix to packages.py should solve the initial problem of not finding the vars.sh and your experience confirms that. The 2nd problem where the module file does not have CC set is because I was not setting it in the package. #28901 should address that issue.

**Comment by mathomp4** [comment]
Zombie thread activate! So, I tried some spack+intel stuff on this same machine today. In my `compilers.yaml` I have:
```yaml
- compiler:
    spec: intel@=2022.1.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/bin/intel64/icc
      cxx: /usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/bin/intel64/icpc
      f77: /usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/bin/intel64/ifort
      fc: /usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: [comp/gcc/11.4.0, comp/intel/2021.6.0]
    environment: {}
    extra_rpaths: []
```
but when I try to install:
```
$ spack install intel
==> intel@2022.1.0 : has external module in ['comp/gcc/11.4.0', 'comp/intel/2021.6.0']
==> Warning: cannot perform the requested write operation on module files [Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/compilers_and_libraries/linux/bin/compilervars.sh]
[+] /usr/local/intel/oneapi/2021/compiler/2022.1.0/linux (external intel-2022.1.0-vb44wu6kr5n3fi4v4o342dtiudw7z7r4)
```
and it is right that path does not exist:
```
$ ls /usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/compilers_and_libraries/linux/bin/compilervars.sh
ls: cannot access '/usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/compilers_and_libraries/linux/bin/compilervars.sh': No such file or directory
```

Indeed, it doesn't exist until you get back to `linux`:
```
$ ls /usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/
IntelDPCPP/  bin/  bin-llvm/  compiler/  doc/  ide_support/  include/  lib/  pkg_bin@
```

and `compilervars.sh` just doesn't exist:
```
$ find /usr/local/intel/oneapi/2021/compiler/2022.1.0 -iname 'compilervars.sh'
$
```

Now up the thread @scheibelp talked about using `prefix` and it worked in the old days, so I tried adding it to my `compilers.yaml` and:
```
$ spack install intel
==> Error: /home/mathomp4/.spack/linux/compilers.yaml:42: Additional properties are not allowed ('prefix' was unexpected)
```

Aww nuts.

**Comment by scheibelp** [comment]
Note:

* `prefix` is not a property of compilers (entries in `compilers.yaml`) but rather of packages (entries of `packages.yaml`).
* You don't need an external package entry for `intel` if you just want to install packages compiling them with `%intel` (the compiler entry you have is sufficient for that)
* If your intent here is to get spack to auto-generate a module for the (system-installed) Intel package, then I should say I don't know how well we support that (i.e. I don't know if for example we integrate external modules mentioned in the `packages.yaml` entry as dependency modules into the spack-generated module): do you want to do this so users can find the `intel` compiler by navigating the Spack-generated module tree?

**Comment by mathomp4** [comment]
@scheibelp Well, I guess my hope was I could do what I did for gcc:
```yaml
- compiler:
    spec: gcc@=12.3.0
    paths:
      cc: /usr/local/other/gcc/12.3.0/bin/gcc
      cxx: /usr/local/other/gcc/12.3.0/bin/g++
      f77: /usr/local/other/gcc/12.3.0/bin/gfortran
      fc: /usr/local/other/gcc/12.3.0/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: [comp/gcc/12.3.0]
    environment: {}
    extra_rpaths: []
```
and in `packages.yaml`:
```yaml
  gcc:
    externals:
    - spec: gcc@12.3.0 %gcc@7.5.0
      modules:
      - comp/gcc/12.3.0
    buildable: false
```

With this, I was able to have spack generate a module file in the lmod `Core` for gcc by doing a `spack install gcc @12.3.0`.

I forgot to say I also have in `packages.yaml`:
```yaml
  intel:
    externals:
    - spec: intel@2022.1.0 %gcc@7.5.0
      modules: [comp/gcc/11.4.0, comp/intel/2021.6.0]
    buildable: false
```

But can spack "piggyback" off the system lmod modulefiles? That is, if I did:
```
ml comp/gcc/12.3.0
```
is there a way to have spack's lmod "reveal" the gcc hierarchy of modulefiles generated by the `%gcc@12.3.0` installs?

If so, then that might be idea. Users load the system built GCC module they are used to and *bam* magically get the GCC packages. 

Or, I guess, should I just make my own "fake" Core modulefiles and ignore those made by spack? I mean, I guess something like:
```lua
-- Services provided by the package
family("compiler")

load("comp/gcc/12.3.0")

-- Loading this module unlocks the path below unconditionally
prepend_path("MODULEPATH", "/gpfsm/dnb05/projects/p50/spack/share/spack/lmod/linux-sles15-x86_64/gcc/12.3.0")
```
and then...all is well? I mean in the end it's just the `MODULEPATH` magic I need. Same for intel. Two `load()` and a `prepend_path(MODULEPATH)`?
