### ISSUE TITLE
Concretizer switches compilers rather than downgrade package versions

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#28889]
### Steps to reproduce

With https://github.com/spack/spack/pull/28888 merged (conflict for `go@1.17: %gcc@:4`) the following environment concretizes with a different compiler (clang%9) rather than downgrading go to @1.16 to match 
```
$ cat spack.yaml
spack:
  specs:
  - go
  packages:
    all:
      compiler: [gcc@4.4.7]
```

### Error message

```
$ spack -e . concretize -f
==> Starting concretization
==> Environment concretized in 12.80 seconds.
==> Concretized go
 -   r6egrzq  go@1.17.3%clang@9.0.1 arch=linux-rhel6-x86_64
# snip
```

### Information on your system

* **Spack:** 0.17.1-1118-c2849ef3d6
* **Python:** 3.8.7
* **Platform:** linux-rhel6-broadwell
* **Concretizer:** clingo

Worth noting that adding a package constraint fixes the concretization:
```
    go:
      version: [1.16.10]
```

and `spack solve go %gcc@:4` produces the expected result of using 1.16 rather than changing the compiler.

```yaml
compilers:
- compiler:
    spec: clang@9.0.1
    paths:
      cc: /projects/spack/opt/spack/gcc-8.3.0/llvm/kzsgxqy/bin/clang
      cxx: /projects/spack/opt/spack/gcc-8.3.0/llvm/kzsgxqy/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: rhel6
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@3.4.6
    paths:
      cc: /usr/bin/gcc34
      cxx: /usr/bin/g++34
      f77: null
      fc: null
    flags: {}
    operating_system: rhel6
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@4.4.7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: rhel6
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Closing this since you can now add

```yaml
packages:
  all:
    require: "%gcc"
```
