### ISSUE TITLE
Phantom compiler???

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2932]
We're having a problem here I can't diagnose.  The `~/.spack/compilers.yaml` file is set up as follows:
```
compilers:
- compiler:
    modules: [other/comp/gcc-5.3-sp3,linux-suse_linux11-x86_64/binutils-2.27-gcc-5.3.0-p7ewifc]
    operating_system: suse_linux11
    paths:
      cc: /usr/local/other/SLES11.3/gcc/5.3.0/bin/gcc
      cxx: /usr/local/other/SLES11.3/gcc/5.3.0/bin/g++
      f77: /usr/local/other/SLES11.3/gcc/5.3.0/bin/gfortran
      fc: /usr/local/other/SLES11.3/gcc/5.3.0/bin/gfortran
    spec: gcc@5.3.0
```
When we try a Spack command, it doesn't work.  For example:
```
$ spack setup everytrace@develop
==> Error: Multiple compilers satisfy spec gcc@5.3.0
$ spack compilers
==> Available compilers
-- gcc ----------------------------------------------------------
gcc@5.3.0  gcc@5.3.0  gcc@4.9.1  gcc@4.3.4  gcc@4.3
```
Why is `gcc@5.3.0` there twice?  `which gcc` yields:
```
/usr/local/other/SLES11.3/gcc/5.3.0/bin/gcc
```
Now if we get rid of `compilers.yaml`, everything works fine.  And Spack does not create a new `compilers.yaml` file.

Any idea what is going wrong?  This stuff worked for 10 other students running on the same supercomputer.  We did `module purge` and are running with `bash`.
