### ISSUE TITLE
Installation issue: boost fails with "classic" intel

### ISSUE THREAD

**Issue by pbrady** [LLNL/spack#29352]
### Steps to reproduce the issue

```console
$ spack spec -l boost cxxstd=17 %intel
Input spec
--------------------------------
boost%intel cxxstd=17

Concretized
--------------------------------
rwzzf7x  boost@1.78.0%intel@2021.5.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=17 visibility=hidden arch=linux-fedora35-broadwell
4meisx2      ^bzip2@1.0.8%intel@2021.5.0~debug~pic+shared arch=linux-fedora35-broadwell
4a6y247      ^zlib@1.2.11%intel@2021.5.0+optimize+pic+shared arch=linux-fedora35-broadwell
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing boost-1.78.0-rwzzf7xc6pnmk6oprr4y6m7njmsrfrfe
==> No binary for boost-1.78.0-rwzzf7xc6pnmk6oprr4y6m7njmsrfrfe found: installing from source
==> Using cached archive: /home/ptb/gitrepos/spack/var/spack/cache/_source-cache/archive/86/8681f175d4bdb26c52222665793eef08490d7758529330f98d3b29dd0735bccc.tar.bz2
==> Ran patch() for boost
==> boost: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    './bootstrap.sh' '--prefix=/usr/local/spack/opt/spack/linux-fedora35-broadwell/intel-2021.5.0/boost-1.78.0-rwzzf7xc6pnmk6oprr4y6m7njmsrfrfe' '--with-toolset=intel-linux' '--with-libraries=math,filesystem,wave,date_time,thread,chrono,system,locale,random,exception,timer,atomic,program_options,serialization,test,iostreams,graph,log,regex' '--without-icu'

5 errors found in build log:
     14    InstalledDir: /opt/intel/oneapi/compiler/2022.0.2/linux/bin-llvm
     15    
     16    ###
     17    ###
     18    
     19    > icpx -x c++ -std=c++11 -O3 -s -static -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp
            execcmd.cpp execnt.cpp execunix.cpp filesys.cpp filent.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp h
           eaders.cpp jam_strings.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp out
           put.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.c
           pp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/se
           t.cpp -o b2
  >> 20    ld: cannot find -lstdc++
  >> 21    ld: cannot find -lm
  >> 22    ld: cannot find -lc
  >> 23    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
     24    > cp b2 bjam
  >> 25    cp: cannot stat 'b2': No such file or directory
     26    
     27    Failed to build B2 build engine
</pre></details>

### Information on your system

* **Spack:** 0.17.1-1455-80a6eab2db
* **Python:** 3.10.1
* **Platform:** linux-fedora35-broadwell
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8189322/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8189324/spack-build-out.txt)

Boost is using the intel-oneapi compiler `icpx` when it should just be using `icpc`.  My `compilers.yaml`

```yaml
- compiler:
    spec: intel@2021.5.0
    paths:
      cc: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/intel64/icc
      cxx: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/intel64/icpc
      f77: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort
      fc: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort
    flags: {}
    operating_system: fedora35
    target: x86_64
    modules: [oneapi]
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2022.0.0
    paths:
      cc: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/icx
      cxx: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/icpx
      f77: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/ifx
      fc: /opt/intel/oneapi/compiler/2022.0.2/linux/bin/ifx
    flags: {}
    operating_system: fedora35
    target: x86_64
    modules: [oneapi]
    environment: {}
    extra_rpaths: []
```

maintainer: @hainest 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
