### ISSUE TITLE
Installation issue: openmpi with apple-clang/nag

### ISSUE THREAD

**Issue by pbrady** [LLNL/spack#29566]
### Steps to reproduce the issue

```console
$ spack spec -l openmpi
Input spec
--------------------------------
openmpi

Concretized
--------------------------------
4gnei6m  openmpi@4.1.2%apple-clang@13.0.1~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi~pmix+romio~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=darwin-bigsur-skylake
rxkb5sf      ^hwloc@2.7.0%apple-clang@13.0.1~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl~pci~rocm+shared arch=darwin-bigsur-skylake
6433533          ^libxml2@2.9.12%apple-clang@13.0.1~python arch=darwin-bigsur-skylake
kd7fiz2              ^libiconv@1.16%apple-clang@13.0.1 libs=shared,static arch=darwin-bigsur-skylake
f57raz2              ^pkgconf@1.8.0%apple-clang@13.0.1 arch=darwin-bigsur-skylake
tp3dwox              ^xz@5.2.5%apple-clang@13.0.1~pic libs=shared,static arch=darwin-bigsur-skylake
l3bxgs5              ^zlib@1.2.11%apple-clang@13.0.1+optimize+pic+shared arch=darwin-bigsur-skylake
7ofqabu          ^ncurses@6.2%apple-clang@13.0.1~symlinks+termlib abi=none arch=darwin-bigsur-skylake
gpdeyvz      ^libevent@2.1.12%apple-clang@13.0.1+openssl arch=darwin-bigsur-skylake
y7wfowo          ^openssl@1.1.1m%apple-clang@13.0.1~docs certs=system arch=darwin-bigsur-skylake
26uz7nt              ^perl@5.34.0%apple-clang@13.0.1+cpanm+shared+threads arch=darwin-bigsur-skylake
ycgmhnz                  ^berkeley-db@18.1.40%apple-clang@13.0.1+cxx~docs+stl patches=b231fcc arch=darwin-bigsur-skylake
qlibcdf                  ^bzip2@1.0.8%apple-clang@13.0.1~debug~pic+shared arch=darwin-bigsur-skylake
ozlu5w2                      ^diffutils@3.8%apple-clang@13.0.1 arch=darwin-bigsur-skylake
xbni7lt                  ^gdbm@1.19%apple-clang@13.0.1 arch=darwin-bigsur-skylake
h6thamg                      ^readline@8.1%apple-clang@13.0.1 arch=darwin-bigsur-skylake
2h4blv6      ^openssh@8.1p1%apple-clang@13.0.1 arch=darwin-bigsur-skylake
```

my environment spack.yaml
```yaml
spack:
  compilers:
  - compiler:
      spec: apple-clang@13.0.1
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: /usr/local/bin/nagfor
        fc: /usr/local/bin/nagfor
      flags: {}
      operating_system: bigsur
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  # add package specs to the `specs` list
  packages:
    all:
      compiler: [apple-clang@13.0.1]
  specs: [openmpi]
  view: true

```

### Error message

<details><summary>Error message</summary><pre>
     31189    libtool: install: /usr/local/bin/ginstall -c .libs/libmpi_usempi.40.dylib /Users/
              ptb/gitrepos/spack/opt/spack/darwin-bigsur-skylake/apple-clang-13.0.1/openmpi-4.1
              .2-4gnei6m2fqrzebi2bty6sxy776d6ayv5/lib/libmpi_usempi.40.dylib
  >> 31190    ginstall: cannot stat '.libs/libmpi_usempi.40.dylib': No such file or directory
  >> 31191    make[3]: *** [Makefile:1932: install-libLTLIBRARIES] Error 1
     31192    make[3]: Leaving directory '/private/var/folders/ck/bwzqcv_s1pz1t9fc86731shh0000g
              q/T/ptb/spack-stage/spack-stage-openmpi-4.1.2-4gnei6m2fqrzebi2bty6sxy776d6ayv5/sp
              ack-src/ompi/mpi/fortran/use-mpi-tkr'
  >> 31193    make[2]: *** [Makefile:2047: install-am] Error 2
     31194    make[2]: Leaving directory '/private/var/folders/ck/bwzqcv_s1pz1t9fc86731shh0000g
              q/T/ptb/spack-stage/spack-stage-openmpi-4.1.2-4gnei6m2fqrzebi2bty6sxy776d6ayv5/sp
              ack-src/ompi/mpi/fortran/use-mpi-tkr'
  >> 31195    make[1]: *** [Makefile:3555: install-recursive] Error 1
     31196    make[1]: Leaving directory '/private/var/folders/ck/bwzqcv_s1pz1t9fc86731shh0000g
              q/T/ptb/spack-stage/spack-stage-openmpi-4.1.2-4gnei6m2fqrzebi2bty6sxy776d6ayv5/sp
              ack-src/ompi'
  >> 31197    make: *** [Makefile:1901: install-recursive] Error 1
</pre></details>

### Information on your system

* **Spack:** 0.17.1-1511-2dd9414bbb
* **Python:** 3.9.10
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8288700/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8288701/spack-build-out.txt)

maintainers: @hppritcha  @naughtont3

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
