### ISSUE TITLE
Environment virtual package version specification being ignored

### ISSUE THREAD

**Issue by jmansour** [LLNL/spack#29729]
Hi team@spack

As per title, I'm encountering unexpected behaviour when trying to specify versions within environments.

For example, say I have this environment:

```yaml
spack:
  specs:
  - hdf5
  view: true
  packages:
    perl:
      version: [5.32.1]
    openmpi:
      version: [3.1.6]
    all:
      compiler: [gcc@10.3.0]
      providers:
        mpi: [openmpi]
```

When I concretize I'm getting `openmpi@4.1.2` instead of `openmpi@3.1.6`.  The `perl` version specification, on the other hand, appears to be sticking (with it defaulting to `perl@5.34.0` if not specified). 

If I instead explicitly ask for `hdf5^openmpi@3.1.6` it concretizes as expected. 

I have tested this against `0.17.1` and against the current `develop`  branch, and in both cases my `openmpi` specification is ignored.  

I'm not sure if this is a bug or if I'm not understanding how to specify the environment correctly. 

Also, perhaps this is unrelated, but I notice my compiler specification doesn't stick across all specs (in more complex environments) for `0.17.1`, but it does for `develop`.  In both cases, if all specs explicitly request the desired compiler, they concretize fine.  Concretization is done in `separately` mode.  I can post a different issue for that if useful, although it's perhaps resolved in the bleeding edge.

Thanks for any help.

**Comment by alalazo** [comment]
Version specifications in the packages section are soft-preferences, which are not enforced if Spack consider the penalty of having to use `openmpi@3.1.6` greater than the benefit of considering `openmpi@3.1.6` the preferred `openmpi` version. If you want to enforce the use of that `openmpi` version you should specify it in the spec literals. 

If you can use:
```
spack:
   concretization: together
```
you just need to add `openmpi@3.1.6` to the list of specs.

**Comment by jmansour** [comment]
Okay. Thanks for the reply. 

Just wondering why is it set up this way? Seems counter-intuitive to me. Does this also explain why my compiler specifications were sometimes being ignored? 

What I'm trying to achieve here is an environment description that allows me to specify a bunch of specs minimally, and then simply state (within the `packages` config perhaps) which dependencies I'd like to explicitly require. I'd rather not concretize the specs together.

Thanks again.

**Comment by alalazo** [comment]
You can use the [spec matrix](https://spack.readthedocs.io/en/latest/environments.html#spec-matrices) syntax in a `spack.yaml` file if you want to encode in a compact way the construction of multiple specs. For instance:
```yaml
spack:
  specs:
    - matrix:
        - [hdf5, ...]
        - [^openmpi@3.1.6]
        - [%gcc@9.4.0]
```
