### ISSUE TITLE
scotch does not depend on intelmpi

### ISSUE THREAD

**Issue by Exteris** [LLNL/spack#2978]
Hi,

I'm trying to install an intelmpi version of scotch (just installed an openmpi version) with
`spack spec scotch+esmumps+mpi ^intelmpi` which fails with `==> Error: scotch does not depend on intelmpi
`, while the openmpi version gives
```bash
$ spack spec scotch+esmumps+mpi ^openmpi
Input spec
--------------------------------
scotch+esmumps+mpi
    ^openmpi

Normalized
--------------------------------
scotch+esmumps+mpi
    ^bison
        ^m4@1.4.6:
    ^flex@:2.6.1
        ^gettext@0.19:
        ^help2man
    ^openmpi
        ^hwloc
            ^libpciaccess
                ^libtool
                ^pkg-config@0.9.0:
                ^util-macros

Concretized
--------------------------------
scotch@6.0.4%gcc@6.1.0+compression+esmumps+metis+mpi+shared arch=linux-centos7-x86_64 
    ^bison@2.7%gcc@6.1.0 arch=linux-centos7-x86_64 
    ^flex@2.5.37%gcc@6.1.0 arch=linux-centos7-x86_64 
    ^openmpi@1.10.3%gcc@6.1.0~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-centos7-x86_64 
    ^zlib@1.2.8%gcc@6.1.0+pic+shared arch=linux-centos7-x86_64 

```

I do not understand why I cannot build with intelmpi (and intel compilers) here.
Relevant part of packages.yaml:
```yaml
packages:
  openmpi:
    modules:
      openmpi@1.10.3%gcc@6.1.0: openmpi/1-10.3--gnu--6.1.0
    buildable: False
  intelmpi:
    modules:
      intelmpi@2017.1.132%intel@17.0.1: intelmpi/2017--binary
    buildable: False
  zlib:
    modules:
      zlib@1.2.8%gcc@6.1.0: zlib/1.2.8--gnu--6.1.0
    buildable: False
  all:
    providers:
      mpi: [openmpi, intelmpi]
```

I have one guess: is this happening because zlib is only available in a gcc version?
Then I would find this to be a very cryptic error message.
