### ISSUE TITLE
Cannot build with nvhpc

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#30464]
### Steps to reproduce

I want to build `amrex` via `nvhpc`. The `spec -I` command you're asking for here doesn't work because `nvhpc` is not recognized as compiler. I'll list it anyway:
```
$ spack spec -I amrex %nvhpc
==> Error: amrex%nvhpc is unsatisfiable, errors are:
  Internal error: node compiler version mismatch

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
```
but this error is unrelated. (The error appears because `cmake` is a build dependency of `amrex`, and `cmake` lists `%nvhpc` as conflict.)

I am using an environment which includes the specs
```
- amrex %nvhpc
- cmake %gcc
```
and respective compiler stanzas. This avoids the error above.

### Error message

Building `amrex` fails with the error message
```
1 error found in build log:
     25    --    AMReX_LINEAR_SOLVERS
     26    --    AMReX_PARTICLES
     27    --    AMReX_PARTICLES_PRECISION = DOUBLE
     28    --    AMReX_PROBINIT
     29    -- Looking for pthread.h
     30    -- Looking for pthread.h - not found
  >> 31    CMake Error at /home/eschnetter/src/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-11.1.0/cmake-3.23.1-sqntdj2upay572
           gi4lmw6ywz7bdxkkr7/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     32      Could NOT find Threads (missing: Threads_FOUND)
     33    Call Stack (most recent call first):
     34      /home/eschnetter/src/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-11.1.0/cmake-3.23.1-sqntdj2upay572gi4lmw6ywz7bd
           xkkr7/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
     35      /home/eschnetter/src/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-11.1.0/cmake-3.23.1-sqntdj2upay572gi4lmw6ywz7bd
           xkkr7/share/cmake-3.23/Modules/FindThreads.cmake:238 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
     36      Tools/CMake/AMReXParallelBackends.cmake:7 (find_package)
     37      Src/CMakeLists.txt:14 (include)
```

cmake's `CMakeError.log` contains the line
```
nvcc fatal   : Unknown option '-Wl,--disable-new-dtags'
```
and `SPACK_DEBUG=TRUE` shows that this option is added by Spack when calling the linker.

[CMakeError.log](https://github.com/spack/spack/files/8614637/CMakeError.log)
[CMakeOutput.log](https://github.com/spack/spack/files/8614638/CMakeOutput.log)
[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/8614639/spack-build-01-cmake-out.txt)
[spack-build-env-mods.txt](https://github.com/spack/spack/files/8614640/spack-build-env-mods.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8614641/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8614642/spack-build-out.txt)
[spack-cc-amrex-xnaqv6p.in.log](https://github.com/spack/spack/files/8614643/spack-cc-amrex-xnaqv6p.in.log)
[spack-cc-amrex-xnaqv6p.out.log](https://github.com/spack/spack/files/8614644/spack-cc-amrex-xnaqv6p.out.log)

### Information on your system

$ spack debug report
* **Spack:** 0.18.0.dev0 (6ecee4e6d51a1c750a526c11c11dfd24162afc9e)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@samcmill

**Comment by samcmill** [comment]
I suspect you are setting `CXX=nvcc`?  

You probably need to add `--forward-unknown-to-host-compiler` to your `CXXFLAGS` in that case.

**Comment by eschnett** [comment]
No, I am simply using the equivalent `spack install amrex %nvhpc`. I am not setting `CXX` manually.

Also, this uses `nvhpc`, not `nvcc`. This is a new compiler from Nvidia that is a C++ compiler by itself, there is no separation between host and device compilers any more.

**Comment by samcmill** [comment]
You are referring to `nvc++`.  However, the error message is from `nvcc`, the CUDA compiler, not `nvc++`.  

I'm not familiar with the `amrex` build system.  It appears that it is trying to use `nvcc` for something and give it an argument it does not recognize.

**Comment by haampie** [comment]
I guess `nvc` was confused with `nvcc` in `compilers.yaml`?

**Comment by eschnett** [comment]
The additional argument comes from Spack, not from AMReX. Spack adds additional compiler arguments. These are present in `spack-cc-amrex-xnaqv6p.out.log`, but not in  `spack-cc-amrex-xnaqv6p.in.log`.

Spack wasn't able to pick up `nvhpc`. I installed `nvhpc` via Spack, and then added a stanza manually to the environment:
```yaml
  - compiler:
      spec: nvhpc@22.3
      paths:
        cc: /home/eschnetter/src/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-11.1.0/nvhpc-22.3-e3lyeliyea2pbyd2nxe3ffxgionv5sdt/Linux_x86_64/22.3/compilers/bin/nvcc
        cxx: /home/eschnetter/src/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-11.1.0/nvhpc-22.3-e3lyeliyea2pbyd2nxe3ffxgionv5sdt/Linux_x86_64/22.3/compilers/bin/nvc++
        f77: /home/eschnetter/src/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-11.1.0/nvhpc-22.3-e3lyeliyea2pbyd2nxe3ffxgionv5sdt/Linux_x86_64/22.3/compilers/bin/nvfortran
        fc: /home/eschnetter/src/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-11.1.0/nvhpc-22.3-e3lyeliyea2pbyd2nxe3ffxgionv5sdt/Linux_x86_64/22.3/compilers/bin/nvfortran
      flags: {}
      operating_system: ubuntu18.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```
Could this be wrong? There is a binary `nvc` as well; should I be using it instead?
