### ISSUE TITLE
Installation issue: Gromacs uses O2 when adding O3 flags to spack compilation

### ISSUE THREAD

**Issue by ixdi** [LLNL/spack#30805]
### Steps to reproduce the issue

@junghans
@marvinbernhardt

Compiling in a target zen2 using linux Rocky 8.5.  

```console
spack install gromacs+mpi+openmp cflags="-O3 -g0" cppflags="-O3 -g0" %gcc@11.3.0
```
![Captura de pantalla de 2022-05-24 17-27-25](https://user-images.githubusercontent.com/3193539/170075163-4e25644d-5947-4693-a8c9-d1014816c935.png)

### Error message

From the generated output when running Gromacs with Slurm

![gromacs](https://user-images.githubusercontent.com/3193539/170075320-49cf5e8d-b32c-4866-ae28-472c2f884145.png)

### Information on your system

* **Spack:** 0.18.0.dev0 (010068c50a2fbfda269dab2c2b41beaaf210b222)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

.spack/packages.yaml
```yml
packages:
  slurm:
    buildable: False
    externals:
      - spec: slurm@20.11.8
        prefix: /usr
  all:
    compiler: [gcc]
    permissions:
      read: world
      write: user
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8764285/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8764286/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
