### ISSUE TITLE
Bug or not? intel-oneapi-mpi compiler wrappers change when setting target

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#30956]
### Steps to reproduce

I installed packages on an HPC with intel-oneapi-mpi
```
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.6.0%intel@2022.1.0
      prefix: /work2/06146/tg854455/stampede2/spack-stack/intel-oneapi-2022.2
```
and the Intel compilers
```
- compiler:
    spec: intel@2022.1.0
    paths:
      cc: /work2/06146/tg854455/stampede2/spack-stack/intel-oneapi-2022.2/compiler/2022.1.0/linux/bin/intel64/icc
      cxx: /work2/06146/tg854455/stampede2/spack-stack/intel-oneapi-2022.2/compiler/2022.1.0/linux/bin/intel64/icpc
      f77: /work2/06146/tg854455/stampede2/spack-stack/intel-oneapi-2022.2/compiler/2022.1.0/linux/bin/intel64/ifort
      fc: /work2/06146/tg854455/stampede2/spack-stack/intel-oneapi-2022.2/compiler/2022.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: any
    modules: []
    ...
```
This set `spec['mpi'].mpicxx` to `mpiicpc` etc. When I add
```
packages:
  all:
    target:: [x86_64]
```
to avoid compiling for the login node CPU (which would be `skylake_avx512`), it seems to set `spec['mpi'].mpicxx` to `mpicxx`. This doesn't work with packages like ESMF (I got the `spec['mpi'].mpicxx` settings from looking at the ESMF configure output, and the package is configured such that for `+mpi`, it uses `os.environ['ESMF_CXX'] = spec['mpi'].mpicxx` etc).

Why is it doing that? I also tried `target:: [skylake]`, same result. Any ideas?

### Error message

Described above.

### Information on your system

```
[intel-2022.1.0-esmf830b09-targets-2] login1.stampede2(1096)$ spack debug report
uname * **Spack:** 0.18.0.dev0
* **Python:** 3.9.7
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo
[intel-2022.1.0-esmf830b09-targets-2] login1.stampede2(1097)$ uname -a
Linux login1.stampede2.tacc.utexas.edu 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
