### ISSUE TITLE
docs issue with spack file system view

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#31167]
### Steps to reproduce

Typo in docs here:
https://spack.readthedocs.io/en/latest/environments.html#configuration-in-spack-yaml

`projections/all` entry isn't valid yaml:

```
# spack.yaml (incomplete but will still demo problem)
spack:
  view:
    mpis:
      root: /path/to/view
      select: [^mpi]
      exclude: ['%pgi@18.5']
      projections:
        all: {name}/{version}-{compiler.name}
      link: all
      link_type: symlink
```

```console
spack install ./spack.yaml
```

### Error message

```
spack/bin/spack install ./spack.yaml 
==> Error: error parsing YAML spec:
while parsing a block mapping
  in "./spack.yaml", line 9, column 9
expected <block end>, but found '<scalar>'
  in "./spack.yaml", line 9, column 2
```

Entry in the docs needs quotes  `"{name}/{version}-{compiler.name}"` to parse

### Information on your system

 bin/spack debug report
* **Spack:** 0.19.0.dev0 (4f9f56630bbcee4bc040566d862d3f09f815c938)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
