### ISSUE TITLE
docs issue with using environments

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#31168]
### Steps to reproduce

This example is using a format that isn't valid:

https://spack.readthedocs.io/en/latest/environments.html?highlight=environments#spec-concretization

```
spack:
    specs:
      - hdf5~mpi
      - hdf5+mpi
      - zlib@1.2.8
    concretizer:
      unify: false
```

```
spack/bin/spack install ./spack.yaml 
```

### Error message

```
spack/bin/spack install ./spack.yaml 
==> Error: 'spec'
```

`specs` isn't supported? 
Not sure the new format, is it `spec/nodes` ?

### Information on your system

bin/spack debug report
* **Spack:** 0.19.0.dev0 (4f9f56630bbcee4bc040566d862d3f09f815c938)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@cyrush I think you are confusing the `spec.yaml` (old format) and `spec.json` (new format) that can be used directly with `spack install`:
```yaml
$ spack spec -y zlib
spec:
  _meta:
    version: 3
  nodes:
  - name: zlib
    version: 1.2.12
    arch:
      platform: linux
      platform_os: ubuntu18.04
      target: x86_64
    compiler:
      name: clang
      version: 7.0.0
    namespace: builtin
    parameters:
      optimize: true
      patches:
      - 0d38234384870bfd34dfcb738a9083952656f0c766a0f5990b1893076b084b76
      pic: true
      shared: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    patches:
    - 0d38234384870bfd34dfcb738a9083952656f0c766a0f5990b1893076b084b76
    hash: 3svypjaie5farii5zcgm6yfu43la2ixs
```
with an environment manifest file (`spack.yaml`). The docs are correct. From the directory where that `spack.yaml` file resides:
```console
$ spack -e . concretize
==> Starting concretization pool with 3 processes
==> Environment concretized in 16.89 seconds.
==> Concretized hdf5~mpi
[ ... ]
```
