### ISSUE TITLE
Creating environment views from installed specs only

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#31389]
I'd like to be able to setup an environment like this:

```yaml
spack:
  specs: [cmake, ccache, python, ...]
  view: {...}
```

and want to make sure that concretization will only produce installed packages or an error.

That'd be a nice way to deal expose a large upstream database to a system, and have users just assemble their environment view.

Maybe `spack concretize --installed` or `spack-concretize --reuse-only` or so?
