### ISSUE TITLE
Spack uses `ldflags` in two different contexts

### ISSUE THREAD

**Issue by cdfh** [LLNL/spack#31395]
### Summary

I propose introducing two new build variables, `ccldflags` and `ldldflags`, which are used in place of `ldflags` in cases where it matters whether the linker is being invoked directly (e.g., as `ld`) or indirectly via the compiler (e.g., as `clang`).

### Rationale

This issue is regarding the `ldflags` build variable, as configured in `compilers.yaml`, e.g., with

```
compilers::
- compiler:
    spec: clang@14.0.6
    paths:
      cc: /home/hdiags/hdiags/spack/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-12.1.0/llvm-14.0.6-hahteldt6ghsftolw2r6bjo27wkql3eo/bin/clang
      cxx: /home/hdiags/hdiags/spack/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-12.1.0/llvm-14.0.6-hahteldt6ghsftolw2r6bjo27wkql3eo/bin/clang++
      f77: /usr/bin/x86_64-linux-gnu-gfortran-9
      fc: /usr/bin/x86_64-linux-gnu-gfortran-9
    flags: {"ldflags": "-fuse-ld=lld -Xlinker --disable-new-dtags"}
    operating_system: ubuntu20.04
    target: x86_64
    modules: [llvm-14.0.6-gcc-12.1.0-hahteld]
    environment: {}
    extra_rpaths: []
```

The broader context is that I've been using `ldflags: -fuse-ld=lld` in order to use the `lld` linker when building packages with spack. This, with the above compiler configuration, works exactly as intended for almost all packages, including huge packages such as llvm, qt, vtk, and gcc, but fails for glib.

## Issue

The vast majority of packages invoke the linker via the compiler, i.e., in the above example, calling `clang` instead of `ld` for linking. In these cases, spack's compiler wrapper injects the configured `ldflags` when the compiler is invoked as a linker, and everything works perfectly. 

However, there are one or two degenerative packages that call `ld` directly, rather than calling `clang`. An example of such a package is `glib` (which uses Mason and Ninja, although the actual spack package itself extends the `Package` base class). In such cases, the spack compiler wrapper continues to inject `ldflags`, but this time, the build fails:

```
     1118    /home/hdiags/hdiags/spack/spack/lib/spack/env/ld -z noexecstack -r -b binary gio/tests/test5.gresource -o gio/tests/test_resources.o
  >> 1119    ld: cannot find -linker
```

Digging around confirms what we'd expect: the compiler wrapper is invoking `ld` directly and injecting `ldflags`, but because the `ldflags` were written to be passed to the compiler and not directly to the linker, the command fails (`-X` means different things to the linker and the compiler).

Looking at the spack compiler wrapper, we can confirm that `ldflags` is intended to be injected in both circumstances: when the linker is invoked directly and when it's invoked via the compiler:

```
# Linker flags
case "$mode" in
    ld|ccld)
       extend flags_list SPACK_LDFLAGS
       ;;
```
(`$mode` being `ld` implies direct invocation and mode being `ccld` implies compiler invocation).

### Description

I would propose that using the same variable under these different circumstances is a design issue as it substantially reduces the scope for configuring the linker (only arguments common to both `ld` and `clang` can be sanely used). I propose that it would be better to have three variables, `ldflags` for both direct and indirect invocations, `ccldflags` for compiler invocations, and `ldldflags` for direct invocations. While the naming is perhaps a little unfortunate, this would bring the substantial benefit of being inherently backwards compatible with the current behaviour for users who depend upon it.

### Additional information

The issue is present in the `develop` branch: [see here](https://github.com/spack/spack/blob/03843db00f9a61c54f437b1787e678be44c90fad/lib/spack/env/cc#L626).

```
$ spack --version
0.18.0 (4c6564f10aa516bc00c1d7dbfdeafe35128985fe)
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
