### ISSUE TITLE
Issue with SPACK_DISABLE_LOCAL_CONFIG and specific etc/spack/defaults/compilers.yaml

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#31612]
### Steps to reproduce

To start, I found a workaround for this issue. But I don't understand the root cause and this cost me several hours so I wanted to document it. 

To reproduce:

I am on macOS 10.15 (catalina), 

check out fresh copy of spack develop

copy the following `compilers.yaml` file to `etc/spack/defaults/compilers.yaml`  

```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: elcapitan
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@7.3.0-apple
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@8.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: highsierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@9.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: mojave
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@10.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: mojave
    paths:
      cc: /usr/local/opt/llvm/bin/clang
      cxx: /usr/local/opt/llvm/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@10.0.0
    target: x86_64
compilers:
- compiler:
    spec: apple-clang@11.0.1
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
compilers:
- compiler:
    spec: apple-clang@13.1.6
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /opt/homebrew/bin/gfortran
      fc: /opt/homebrew/bin/gfortran
    flags: {}
    operating_system: monterey
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```

Run:

```
env  SPACK_DISABLE_LOCAL_CONFIG=1 bin/spack spec ascent 
```

### Error message

```console
==> Error: No valid value for variant 'ownlibs' of package 'cmake'
```

Without `SPACK_DISABLE_LOCAL_CONFIG`, I get an sensible spec. 

Following the broken case a bit further, I started to provide specs to fill in gaps (as suggested by @tgamblin )

```
env  SPACK_DISABLE_LOCAL_CONFIG=1 bin/spack spec ascent ^cmake+ownlibs 
==> Error: cmake compiler '%apple-clang@13.1.6' incompatible with 'os=catalina'
```

So now I have a hint something is off in the compilers.yaml.

There is no entry for clang 13.1.6 for catalina, but there is one for monterey.

I remove the entry for monterey.  

And everything works. 

I have *no* clue why having this compiler undermined the concretization process. 
Something about the config process related to `SPACK_DISABLE_LOCAL_CONFIG` triggers some cascade, or spooky action at a distance, or unexplained sentience in the concretizer.
 
 

### Information on your system

```
* **Spack:** 0.19.0.dev0 (268ec998c0ef8468cdfb4d2f658f9f70144f4257)
* **Python:** 3.7.3
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
