### ISSUE TITLE
Concretizer does not respect external MPI provider

### ISSUE THREAD

**Issue by kgerheiser** [LLNL/spack#31669]
### Steps to reproduce

I have two compilers configured (Intel/GCC) along with corresponding MPI (`intel-oneapi-mpi`/`openmpi`) and no matter what I do Spack chooses to build with Intel and Intel MPI. 

I set `packages:all:compiler:[gcc@10.2.0]` and `packages:all:providers:mpi:[openmpi@4.0.4]` and in my specs I'm only building hdf5+mpi.

I have tried adding the variants/version in the external spec to the openmpi entry in `packages` so that they match, as well as overriding the default values for compiler/mpi with the double colons.

I can workaround it by removing the other MPI externals or by explicitly providing `%gcc` to the spec.

Maybe related to https://github.com/spack/spack/issues/27055

```
spack:
  compilers:
  - compiler:
      spec: intel@2022.0.2
      paths:
        cc: /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/icc
        cxx: /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/icpc
        f77: /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/ifort
        fc: /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/ifort
      flags: {}
      operating_system: centos7
      target: x86_64
      modules:
      - intel/2022.1.2
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@10.2.0
      paths:
        cc: /apps/gcc-10.2.0/gcc-10.2.0/bin/gcc
        cxx: /apps/gcc-10.2.0/gcc-10.2.0/bin/g++
        f77: /apps/gcc-10.2.0/gcc-10.2.0/bin/gfortran
        fc: /apps/gcc-10.2.0/gcc-10.2.0/bin/gfortran
      flags: {}
      operating_system: centos7
      target: x86_64
      modules:
      - gcc/10.2.0
      environment: {}
      extra_rpaths: []
  packages:
    all:
      compiler: [gcc@10.2.0]
      providers:
        mpi: [openmpi@4.0.4]
    cmake:
      buildable: false
      externals:
      - spec: cmake@3.22.1
        prefix: /apps/cmake-3.22.1
    openmpi:
      externals:
      - spec: openmpi@4.0.4%gcc@10.2.0~cuda~cxx~cxx_exceptions~java~memchecker+pmi~static~wrapper-rpath
          fabrics=ucx schedulers=slurm
        prefix: /apps/gcc-10.2.0/openmpi-4.0.4/openmpi-4.0.4
        modules:
        - gcc/10.2.0
        - openmpi/4.0.4
    intel-oneapi-mpi:
      externals:
      - spec: intel-oneapi-mpi@2021.5.1%intel@2022.0.2
        prefix: /apps/intel-2022.1.2/intel-2022.1.2
        modules:
        - impi/2022.1.2

  concretizer:
    unify: when_possible
  specs:
  - hdf5
```

```
==> Concretized hdf5
 -   utj3ibk  hdf5@1.12.2%intel@2022.0.2~cxx~fortran~hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=linux-centos7-skylake_avx512
 -   24o3ksm      ^cmake@3.22.1%intel@2022.0.2~doc+ncurses+ownlibs~qt build_type=Release arch=linux-centos7-skylake_avx512
 -   s7jho67      ^intel-oneapi-mpi@2021.5.1%intel@2022.0.2~external-libfabric~ilp64 arch=linux-centos7-skylake_avx512
 -   w4bzhrs      ^pkgconf@1.8.0%intel@2022.0.2 arch=linux-centos7-skylake_avx512
 -   a7ehv37      ^zlib@1.2.12%intel@2022.0.2+optimize+pic+shared patches=0d38234 arch=linux-centos7-skylake_avx512
```

And the output of `spack solve`

```
==> ROUND 0
==>
==> Best of 8 considered solutions.
==> Optimization Criteria:
  Priority  Criterion                                            Installed  ToBuild
  1         number of input specs not concretized                        -        0
  2         number of packages to build (vs. reuse)                      -        0
  3         deprecated versions used                                     0        0
  4         version weight                                               0        0
  5         number of non-default variants (roots)                       0        0
  6         preferred providers for roots                                0        0
  7         default values of variants not being used (roots)            0        0
  8         number of non-default variants (non-roots)                   0        0
  9         preferred providers (non-roots)                              0        0
  10        compiler mismatches                                          0        0
  11        OS mismatches                                                0        0
  12        non-preferred OS's                                           0        0
  13        version badness                                              0        0
  14        default values of variants not being used (non-roots)        0        0
  15        non-preferred compilers                                      5        0
  16        target mismatches                                            0        0
  17        non-preferred targets                                        0        0
```

### Information on your system

* **Spack:** 0.19.0.dev0 (bf8c2b05b34ce23b1c38bf5df30bd8b6b75b5dbe)
* **Python:** 2.7.5
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Looking at the output of `spack solve` it seems to me that Spack is reusing an already installed Intel oneAPI MPI. Can you confirm that? If that is the case using `--fresh` should solve concretise with GCC and OpenMPI.

**Comment by kgerheiser** [comment]
What do you mean by already installed? Of course they're already installed (outside of Spack) because they are external. This is a completely fresh environment aside from the externals. I've tried using `--fresh` with no difference. One idea that @becker33 had is that `Spack is punishing the external for having non-default variants/version, which are higher priority than the compiler match`, but I've tried adding the variants/version to `packages.yaml` to match the external with no success.

**Comment by alalazo** [comment]
> What do you mean by already installed?

Already present in Spack's DB if you try:
```console
$ spack find
```
That seems not to be the case according to your comment.

**Comment by kgerheiser** [comment]
I can confirm that nothing is installed with using `spack find`

```
==> In environment /work/noaa/stmp/gkyle/spack-stack/envs/test
==> Root specs
hdf5

==> 0 installed packages
```

**Comment by Jordan474** [comment]
I too have an issue with this: since spack 0.17 (clingo) the `providers` preferences seem to be ignored when dealing with external packages. Here is a simpler example:

```yaml
# ./test/spack.yaml
spack:
  packages:
    all:
      providers:
        mpi: [openmpi]
    openmpi:
      externals:
      - spec: openmpi@4.0.0
        prefix: /usr
    intel-mpi:
      externals:
      - spec: intel-mpi@2019.8.254
        prefix: /usr
  specs:
  - mpi
```

```sh
$ ./spack-0.16/bin/spack -e test concretize -f
==> Concretized mpi
 -   c6vmtpo  openmpi@4.0.0%gcc@11.2.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none patches=073477a76bba780c67c36e959cd3ee6910743e2735c7e76850ffba6791d498e4 schedulers=none arch=linux-ubuntu22.04-skylake

$ ./spack-0.17/bin/spack -e test concretize -f
==> Starting concretization
==> Environment concretized in 11.94 seconds.
==> Concretized mpi
 -   6buddzl  intel-mpi@2019.8.254%gcc@11.2.0 arch=linux-ubuntu22.04-skylake

$ ./spack-develop/bin/spack -e test concretize -f
==> Starting concretization
==> Environment concretized in 19.22 seconds.
==> Concretized mpi
 -   u3cbils  intel-mpi@2019.8.254%gcc@11.2.0~external-libfabric arch=linux-ubuntu22.04-skylake
 ```

Looking at `concretize.lp` it does seem suspicious that `possible_provider_weight` is forced to `0` when dealing with external ? Shouldn't it be offset using `default_provider_preference` or something ?

**Comment by alalazo** [comment]
This should be solved by package requirements:
```yaml
packages:
  mpi:
    require: openmpi
```
See [here](https://spack.readthedocs.io/en/latest/build_settings.html#package-requirements) for the details.
