### ISSUE TITLE
Defining a package with more than one flag in an environment causes "Invalid character" error

### ISSUE THREAD

**Issue by dmentock** [LLNL/spack#31695]
### Steps to reproduce

```
spack env create testenv
spack env activate testenv
spack add hdf5 fflags="-fPIC -qopenmp"
spack install --fresh

```
### Error message

```
==> Created environment 'testenv' in /opt/spack/var/spack/environments/testenv
==> You can activate this environment with:
==>   spack env activate testenv
==> Error: Invalid character
```

### Information on your system

* **Spack:** 0.19.0.dev0 (de8cb3d21c9e09d38ddebec94465393448979555)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-sandybridge
* **Concretizer:** clingo

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This error is unreproducible as of

* **Spack:** 0.20.0.dev0 (a7b2196eab54de4bb248f1706a1a69fbd1a9758f)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

But we have a parsing error tracked in #35756 , since add results in:
```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: [hdf5 fflags="-fPIC" ~qopenmp]
  view: true
  concretizer:
    unify: true

```
