### ISSUE TITLE
Concretizer unification: allow root specs to be considered for unification, but mark them as disabled/do-not-install

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#32243]
### Summary

If I have a Spack environment:

```
spack:
  concretizer:
    unify: when_possible
    reuse: false
  specs:
  - pkgA
  - pkgB
  - pkgC
```

I would like to be able to concretize this environment, try building it, and if pkgC fails, I want to be able to mark pkgC as essentially `do-not-install` but still have the concretizer consider it when unifying the environment.

Something like:
```
spack:
...
  specs:
  - pkgA
  - pkgB
  - spec: pkgC
    enable: false
```

In this way the Spack environment would retain it's unified concretization but just skip building of any part of the DAG tied only to `pkgC`.

For our big E4S environment, our deployment process on a facility is to take our whole environment, build it out as much as we can, and then comment out the specs that didn't build. At this point, we don't want the environment to say "oh we no longer see these specs you commented out, so let us change how the whole environment is built and build a bunch of things" -- instead, we expect, the environment is already built out as much as possible, so when we comment out the failing specs, we expect the install to be done.

@alalazo @wspear

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
I think this is a sensible request, modulo defining a few details. I like turning the spec string possibly into an object:
```yaml
spack:
  specs:
  - spec: 'foo'
    install: false
```
so that we have the possibility to add more markers, if needed, in the future. If we implement something like that we possibly need  to adapt Gitlab pipelines to understand the markers.
