### ISSUE TITLE
Compilers.yaml compiler defs need to be able to unload modules

### ISSUE THREAD

**Issue by Paul-Ferrell** [LLNL/spack#32247]
### Summary

On cray systems several package builds need tight control of compiler flags. Unfortunately the Cray programming environments load many modules, some of which force the insertion of compiler flags for the compiler wrappers. Our solution for manual builds was to unload those problematic modules before building, and we'd like to be able to do that with Spack as well. 

### Rationale

As it stands, there are a few packages that cannot be built under Spack in the configuration we needs on Cray systems, most notably openmpi and valgrind.

### Description

I would either add an additional option to the compiler definition or syntax to denote a module should be removed instead of loaded. I think the special syntax is best, as that would allow the user to specify where this unload needs to occur relative to the other module loads or swaps. 

For example, for the cce compiler we might have:
```yaml
compilers:
- compiler:
    spec: cce@13.0.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-cray
    - 'unload xpmem'
    - cce/13.0.0
```

### Additional information

$ spack --version
0.13.1-8432-c15077403e

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
