### ISSUE TITLE
To install compiler and packages depending on it

### ISSUE THREAD

**Issue by DeeliN221** [LLNL/spack#32346]
### Summary

To date, it seems that one has to install compiler, such as `gcc@12.2.0`, before installing packages depending on it.

How about integrate these actions into one single command?

### Description

Here is my `spack.yaml`

```yaml
spack:
  # add package specs to the `specs` list
  packages:
    all:
      compiler: [gcc]
      providers:
        blas: [openblas threads=openmp]
        scalapack: [netlib-scalapack]
  specs:
  - gcc@12.2.0
  - openmpi%gcc@12.2.0 +cxx+legacylaunchers+pmi schedulers=slurm fabrics=auto cflags="-fPIC
    -O3" cppflags="-fPIC -O3" fflags="-fPIC -O3"
  - netlib-scalapack%gcc@12.2.0 cflags="-fPIC -O3" cppflags="-fPIC -O3" fflags="-fPIC
    -O3"  ~shared
  - libxc%gcc@12.2.0 cflags="-fPIC -O3" cppflags="-fPIC -O3" fflags="-fPIC -O3"  ~shared
  concretizer:
    unify: true
  view: true
  compilers:
  - compiler:
      spec: gcc@8.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

when I run `spack concretize -f`, it complains about missing `gcc@12.2.0`, ignoring my command to install `gcc@12.2.0` as listed in the first item of `specs`.

### Additional information

`spack --version`: 0.19.0.dev0 (268ec998c0ef8468cdfb4d2f658f9f70144f4257)

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
