### ISSUE TITLE
Spack env did not copy python executable

### ISSUE THREAD

**Issue by lrtfm** [LLNL/spack#32456]
### Steps to reproduce

I have an env with python, the view path just contains links to python. The env is an environment for firedrake (https://github.com/firedrakeproject/firedrake-spack). 

I checked some cases,
1) when the root spec does __not__ include `python`, there will only links.
```
[complex-int64-gcc] z2yang@ws5:~/opt/firedrake/complex-int64-gcc$ ls -l .spack-env/view/bin/python*
lrwxrwxrwx 1 z2yang z2yang 124 Aug 31 18:28 .spack-env/view/bin/python -> /home/z2yang/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-tlv4wmlftqgi3yiz2pahdqveoc4se44r/bin/python
lrwxrwxrwx 1 z2yang z2yang 125 Aug 31 18:28 .spack-env/view/bin/python3 -> /home/z2yang/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-tlv4wmlftqgi3yiz2pahdqveoc4se44r/bin/python3
lrwxrwxrwx 1 z2yang z2yang 127 Aug 31 18:28 .spack-env/view/bin/python3.9 -> /home/z2yang/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-tlv4wmlftqgi3yiz2pahdqveoc4se44r/bin/python3.9
lrwxrwxrwx 1 z2yang z2yang 134 Aug 31 18:28 .spack-env/view/bin/python3.9-config -> /home/z2yang/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-tlv4wmlftqgi3yiz2pahdqveoc4se44r/bin/python3.9-config
lrwxrwxrwx 1 z2yang z2yang 134 Aug 31 18:28 .spack-env/view/bin/python3.9-gdb.py -> /home/z2yang/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-tlv4wmlftqgi3yiz2pahdqveoc4se44r/bin/python3.9-gdb.py
lrwxrwxrwx 1 z2yang z2yang 132 Aug 31 18:28 .spack-env/view/bin/python3-config -> /home/z2yang/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-tlv4wmlftqgi3yiz2pahdqveoc4se44r/bin/python3-config
lrwxrwxrwx 1 z2yang z2yang 131 Aug 31 18:28 .spack-env/view/bin/python-config -> /home/z2yang/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-tlv4wmlftqgi3yiz2pahdqveoc4se44r/bin/python-config
```
2) when `python` is the __last one__ in the list of the root spec, there will only links of python, same with 1).
3) when `python` is the __first one__ in the list of root spec, spack copy the `python` exe to view path.
```
[complex-int64-gcc] z2yang@ws5:~/opt/firedrake/complex-int64-gcc$ ls -l .spack-env/view/bin/python*
lrwxrwxrwx 1 z2yang z2yang   109 Aug 31 18:37 .spack-env/view/bin/python -> /home/z2yang/opt/firedrake/complex-int64-gcc/.spack-env/._view/xm7odt2r6e4lbvyvjpgfyphjcr3c32hi/bin/python3.9
lrwxrwxrwx 1 z2yang z2yang   109 Aug 31 18:37 .spack-env/view/bin/python3 -> /home/z2yang/opt/firedrake/complex-int64-gcc/.spack-env/._view/xm7odt2r6e4lbvyvjpgfyphjcr3c32hi/bin/python3.9
-rwxr-xr-x 1 z2yang z2yang 17688 Aug 31 18:37 .spack-env/view/bin/python3.9
-rwxr-xr-x 1 z2yang z2yang  3149 Aug 31 18:37 .spack-env/view/bin/python3.9-config
-rwxr-xr-x 1 z2yang z2yang 65501 Aug 31 18:37 .spack-env/view/bin/python3.9-gdb.py
lrwxrwxrwx 1 z2yang z2yang   116 Aug 31 18:37 .spack-env/view/bin/python3-config -> /home/z2yang/opt/firedrake/complex-int64-gcc/.spack-env/._view/xm7odt2r6e4lbvyvjpgfyphjcr3c32hi/bin/python3.9-config
lrwxrwxrwx 1 z2yang z2yang   116 Aug 31 18:37 .spack-env/view/bin/python-config -> /home/z2yang/opt/firedrake/complex-int64-gcc/.spack-env/._view/xm7odt2r6e4lbvyvjpgfyphjcr3c32hi/bin/python3.9-config
```

It seems the result of 2) is weird. Is the result of 1) expected?

The `spack.yaml`
```yaml
spack:
  # add package specs to the `specs` list
  specs: [python, py-firedrake@develop%gcc+64-bit-indices+complex ^mpich@3.4.3 ^openblas
      ^petsc+mumps+scalapack+int64+complex+libyaml+parmmg+mmg ^hypre+complex+int64+superlu-dist,
    py-meshio, py-tqdm, py-pygmsh]
  view: true
  concretizer:
    unify: true
  develop:
    py-firedrake:
      spec: py-firedrake@develop
    libsupermesh:
      spec: libsupermesh@develop
    petsc:
      spec: petsc@develop
    chaco:
      spec: chaco@petsc
    py-fiat:
      spec: py-fiat@develop
    py-finat:
      spec: py-finat@develop
    py-islpy:
      spec: py-islpy@develop
    py-petsc4py:
      spec: py-petsc4py@develop
    py-pyadjoint:
      spec: py-pyadjoint@develop
    py-pyop2:
      spec: py-pyop2@develop
    py-coffee:
      spec: py-coffee@develop
    py-loopy:
      spec: py-loopy@develop
    py-cgen:
      spec: py-cgen@develop
    py-codepy:
      spec: py-codepy@develop
    py-genpy:
      spec: py-genpy@develop
    py-tsfc:
      spec: py-tsfc@develop
    py-ufl:
      spec: py-ufl@develop
```

### Information on your system

* **Spack:** 0.19.0.dev0 (a6740eea5b8055b84b74d0a5cbd95c3908373772)
* **Python:** 3.10.4
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
