### ISSUE TITLE
Package requirements: target=... not respected.

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#32471]
### Steps to reproduce

This works/concretizes
```yaml
spack:
  specs: [ccache target=x86_64]
```

This does not work:

```yaml
spack:
  specs: [ccache]
  packages:
    all:
      require: target=x86_64
```

### Error message

```
$ spack -e . concretize 
==> Starting concretization
==> Error: Cannot satisfy requirement group for package 'ccache'
```

**Comment by alalazo** [comment]
I can reproduce even without an environment using:
```yaml
packages:
  all:
    require: "target=x86_64"
```
and with a package as simple as `zlib:
```console
 spack spec zlib
==> Error: Cannot satisfy requirement group for package 'zlib'
```
Inserting other constraints, e.g. compilers, seem to work.
