### ISSUE TITLE
Package requirements: virtuals and one_of

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#32657]
### Summary

@alalazo

https://github.com/spack/spack/pull/32369 added the ability to specify requirements for virtuals (e.g. to mandate that `openmpi` is always used as the `mpi` implementation).

A user wanted to do:

```
  packages:
    mpi:
      require:
      - one_of: [mvapich2, openmpi]
```

which could be taken to mean "if you need `mpi`, it should be either `mvapich2` or `openmpi`", if you do this and for example try:

```
spack spec hdf5+mpi
==> Error: Spec cannot include multiple providers for virtual 'mpi'
    Requested 'mvapich2' and 'openmpi'
```

Ideally we'd either report a clearer error message ("you can't do that...") or support this.

### Rationale

I think other users are likley to try this as an analog of virtual preferences.

### Additional information

A full example environment you can create to replicate this:

```
spack:
  # add package specs to the `specs` list
  specs: []
  packages:
    mpi:
      require:
      - one_of: [mvapich2, openmpi]
  view: true
  concretizer:
    unify: false
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
