### ISSUE TITLE
Unexpected results with require one_of

### ISSUE THREAD

**Issue by skosukhin** [LLNL/spack#32674]
I want to make sure that my installations of `curl` depend either on `openssl` or on `mbedtls` (not both). So I tried to add the following to my `packages.yaml`:
```yaml
packages:
  cmake:
    externals:
    - spec: cmake@3.18.4
      prefix: /usr
    buildable: false
  curl:
    require:
    - one_of:
      - +libssh2 tls=openssl ^libssh2 crypto=openssl
      - +libssh2 tls=mbedtls ^libssh2 crypto=mbedtls
```
I would expect the final `curl` spec to match only one of the above. However, I get `curl tls=mbedtls,openssl` in my final spec:
```shell
$ spack spec -U julia | grep '\^curl'
    ^curl@7.78.0%gcc@10.2.1~gssapi~ldap~libidn2~librtmp~libssh+libssh2+nghttp2 libs=shared,static tls=mbedtls,openssl arch=linux-debian11-skylake
```
@alalazo Is it a bug or a misuse of the feature?

**Comment by skosukhin** [comment]
On the other hand, it looks like I can go with just:
```yaml
packages:
  curl:
    require:
    - one_of:
      - +libssh2 ^openssl
      - +libssh2 ^mbedtls
```
But the result above still looks strange.
