### ISSUE TITLE
Environments: matrix of OS/arch

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#32894]
### Summary

I would like to be able to test the same stack in CI across multiple platforms.

### Rationale

I'm working on creating a CI stack for ML packages: https://github.com/spack/spack/pull/31592

I would like to be able to test this stack on multiple operating systems:

1. Linux
2. macOS
3. Windows?
4. Cray?

and multiple architectures:

1. x86_64
2. aarch64
3. ppc64le

at the moment, this is impossible without copy-n-pasting the entire stack into a separate file and changing a single line. Code duplication is bad.

### Description

Something like the following would be a good syntax:
```yaml
spack:
  packages:
    platforms:
      matrix:
        - linux
        - macos
        - windows
    targets:
      matrix:
        - x86_64
        - aarch64
        - powerpc
```

### Additional information

@becker33 @alalazo @scheibelp 

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
