### ISSUE TITLE
Core compilers prepend the Core directory to the modulepath

### ISSUE THREAD

**Issue by simonLeary42** [LLNL/spack#33069]
### Steps to reproduce

```
modules:
  default:
    enable::
      - lmod
    lmod:
      core_compilers:
      - "gcc@9.4.0"
```

```
compilers:
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

```
packages:
  gcc:
    version: [9.4.0]
    buildable: false
    externals:
    - spec: gcc@9.4.0
      prefix: /usr
```

```
spack install gcc@9.4.0
```

```
$ grep $spack/share/spack/lmod/linux-ubuntu20.04-x86_64/Core/gcc/9.4.0.lua 
prepend_path("MODULEPATH", "/modules/spack-0.18.1/share/spack/lmod/linux-ubuntu20.04-x86_64/gcc-9.4.0")
```

### Error message

What happens is that Lmod spider sometimes gets itself into a loop and has a seg fault.
While that is a separate bug report, I see no reason why the core compilers should add the core directory to modulepath, because the core directory by definition is always loaded.

### Information on your system

```
$ spack debug report
* **Spack:** 0.18.1 (04634df6ac48f5973a9795a2fb62542fb8220ce2)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-ivybridge
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
