### ISSUE TITLE
Wrong architecture detected on a cray platform

### ISSUE THREAD

**Issue by Thomas-Ulrich** [LLNL/spack#33304]
### Steps to reproduce

I'm trying to install a package on a cray cluster (shaheen, KAUST university).
But spack does not detect correctly the architecture:
```
x_ulricht@cdl4:/project/k1587/ulrich/seissol-spack-aid> spack --version
0.18.1 (13e6f87ef6527954b152eaea303841978e83b992)
x_ulricht@cdl4:/project/k1587/ulrich/seissol-spack-aid> spack arch
cray-cnl7-ivybridge
x_ulricht@cdl4:/project/k1587/ulrich/seissol-spack-aid> lsb_release -a
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 15 SP2
Release:        15.2
Codename:       n/a
```

### Error message

I would expect:
```cray-sles15-ivybridge```

### Information on your system

```
* **Spack:** 0.18.1 (13e6f87ef6527954b152eaea303841978e83b992)
* **Python:** 3.6.15
* **Platform:** cray-sles15-ivybridge
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mwkrentel** [comment]
Spack maintains separate front-end and back-end arch types, and the
default is BE.  In this case, `cnl7` is the back-end OS and this is
probably correct.  Try:

```
spack arch -f
spack arch -b
```

The default is to build for the BE.  If you want to build for the FE,
you would use:

```
spack install ... arch=cray-fe-ivybridge
```

https://spack.readthedocs.io/en/latest/getting_started.html#spack-on-cray

**Comment by Thomas-Ulrich** [comment]
Thank you, this is indeed the case:
```
x_ulricht@cdl4:~> spack arch -f
cray-sles15-ivybridge
x_ulricht@cdl4:~> spack arch -b
cray-cnl7-ivybridge
```
But now, if I connect interactively to a node, I get:
```
x_ulricht@nid00532:/lustre2/project/k1587/ulrich/spack/bin> ./spack debug report
* **Spack:** 0.18.1 (13e6f87ef6527954b152eaea303841978e83b992)
* **Python:** 3.6.15
* **Platform:** cray-sles15-haswell
* **Concretizer:** clingo
```
Which seems at odds with the backend using cnl7, right?
My problem is then that most compilers found are associated with operating_system: cnl7

```
x_ulricht@cdl4:~> cat ~/.spack/cray/compilers.yaml
compilers:
- compiler:
    spec: cce@12.0.3
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-cray
    - cce/12.0.3
    environment: {}
    extra_rpaths: []
- compiler:
    spec: cce@14.0.3
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-cray
    - cce/14.0.3
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/8.1.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/10.3.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/12.1.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/9.3.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.2.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@6.4.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/6.4.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@19.0.5.281
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-intel
    - intel/19.0.5.281
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2022.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-intel
    - intel/2022.1.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.4.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-intel
    - intel/2021.4.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@2021.4.0
    paths:
      cc: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/icx
      cxx: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/dpcpp
      f77: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/ifx
      fc: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/ifx
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: /opt/gcc/10.3.0/bin/gcc
      cxx: /opt/gcc/10.3.0/bin/g++
      f77: /opt/gcc/10.3.0/bin/gfortran
      fc: /opt/gcc/10.3.0/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: /opt/gcc/11.2.0/bin/gcc
      cxx: /opt/gcc/11.2.0/bin/g++
      f77: /opt/gcc/11.2.0/bin/gfortran
      fc: /opt/gcc/11.2.0/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: /opt/gcc/12.1.0/bin/gcc
      cxx: /opt/gcc/12.1.0/bin/g++
      f77: /opt/gcc/12.1.0/bin/gfortran
      fc: /opt/gcc/12.1.0/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@6.4.0
    paths:
      cc: /sw/xc40cle7up03/gcc/6.4.0/bin/gcc
      cxx: /sw/xc40cle7up03/gcc/6.4.0/bin/g++
      f77: /sw/xc40cle7up03/gcc/6.4.0/bin/gfortran
      fc: /sw/xc40cle7up03/gcc/6.4.0/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.1.0
    paths:
      cc: /opt/gcc/8.1.0/bin/gcc
      cxx: /opt/gcc/8.1.0/bin/g++
      f77: /opt/gcc/8.1.0/bin/gfortran
      fc: /opt/gcc/8.1.0/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: /opt/gcc/9.3.0/bin/gcc
      cxx: /opt/gcc/9.3.0/bin/g++
      f77: /opt/gcc/9.3.0/bin/gfortran
      fc: /opt/gcc/9.3.0/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@19.0.5.281
    paths:
      cc: /opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/icc
      cxx: /opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc
      f77: /opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/ifort
      fc: /opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.4.0
    paths:
      cc: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/intel64/icc
      cxx: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/intel64/icpc
      f77: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/intel64/ifort
      fc: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2021.4.0
    paths:
      cc: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/icx
      cxx: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/icpx
      f77: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/ifx
      fc: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/ifx
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
my packages.yaml look like that:
```
packages:
  mpich:
    buildable: true
    externals:
    - spec: mpich@7.7.18
      modules:
      - cray-mpich/7.7.18
    - spec: mpich@7.7.20
      modules:
      - cray-mpich/7.7.20
  all:
    providers:
      mpi: [mpich]
```

Then if  I get the following errors:

```
x_ulricht@cdl4:/project/k1587/ulrich/seissol-spack-aid> spack spec parmetis +int64 +shared %intel@2021.4.0 target=cray-sles15-x86_64
==> Error: 'parmetis target=x86_64' cannot satisfy constraint 'target=cray-sles15-x86_64'
```
