### ISSUE TITLE
Spack ignores `buildable=False` if available in binary cache

### ISSUE THREAD

**Issue by stephenmsachs** [LLNL/spack#33461]
### Steps to reproduce

It seems availaibility in binary cache is valued higher than the `buildable` flag by the concretizer.

## Reproducer
Use `packages.yaml` as
```yaml
packages:
  libfabric:
    externals:
    - spec: libfabric@1.16.0 fabrics=efa
      modules:
      - libfabric-aws/1.16.0
    buildable: false
``` 

The command will show that the extrnal defined libfabric version is used:
```console
spack spec openmpi fabrics=ofi | grep libfabric
```
Output:
```
    ^libfabric@1.16.0%gcc@7.3.1~debug~kdreg fabrics=efa,sockets,tcp,udp arch=linux-amzn2-skylake_avx512
```

Now add the binary mirror as:
```yaml
mirrors:
  binary_mirror: https://binaries.spack.io/develop
```

and the following line will produce an older version of libfabric which is available in the binary cache:
```console
spack buildcache keys --install --trust
spack spec openmpi fabrics=ofi | grep libfabric
```

Output:
```
 -       ^libfabric@1.14.1%gcc@7.3.1~debug~kdreg fabrics=efa,mrail,rxd,rxm,shm,sockets,tcp,udp,verbs arch=linux-amzn2-x86_64_v4
```

### Information on your system

* **Spack:** 0.19.0.dev0 (b1559cc831620ee2b2cf8e57fdecc5bb3bf8edfd)
* **Python:** 3.7.10
* **Platform:** linux-amzn2-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by stephenmsachs** [comment]
After reading some of the code it seems to me that installed specs and specs available in the binary cache are treated the same way. If the `reuse` flag is set, the concretizer wil try to fulfill the request from installed and binary cache specs first before using uninstalled specs. 

I would argue this behavior is not optimal. I would assume binary cache objects to be treated with the same level of priority as installable specs. 

Removing line https://github.com/spack/spack/blob/7c3d93465c1d76e084d6b0ce4a44d1c0b4b1ae68/lib/spack/spack/solver/asp.py#L2354 shows the desired behavior.

**Comment by alalazo** [comment]
This has been somewhat discussed in a bugfix https://github.com/spack/spack/pull/31558 The main issue is that `buildable: false` is too coarse grained[^1] and there is no way to specify from configuration what to reuse[^2]. There is a way to achieve what you want here:
```yaml
packages:
  libfabric:
    require: "@1.16.0"
    externals:
    - spec: libfabric@1.16.0 fabrics=efa
      modules:
      - libfabric-aws/1.16.0
    buildable: false
```
which is to require to use that version. We are also working on allowing users more control on what can be reused, but that will not come before v0.19.

[^1]: Note that also this is not wrong. Spack didn't _rebuild_ something from sources, it is just selecting an available binary
[^2]: `reuse` is an on/off switch
