### ISSUE TITLE
MPI: Unhelpful error message when no buildable MPIs are allowed and no externals match

### ISSUE THREAD

**Issue by white238** [LLNL/spack#33629]
### Steps to reproduce

The error message that comes out of concretizing when you have no MPI's that will satisfy the virtual package leads you down the wrong path.  It would be much more helpful to have something to the extent of "Error: cannot satisfy non-buildable virtual package MPI with any given externals."

The important two parts of reproducing this is the following:

* Have a MPI external that is `buildable: false` and list no externals that match
* Require a package that depends on MPI. Having a variant that defaults to true is not enough, Spack will flip it to off.

This worked for me on rzgenie:

```
  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: rhel7
      paths:
        cc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
        cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
        f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
        fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      spec: gcc@8.3.1
      target: x86_64

  packages:
    mpi:
      buildable: false
    mvapich2:
      buildable: false
      externals:
      # Notice that this is `gcc@4.9.3` not `gcc@8.3.1` like above
      - spec: mvapich2@2.3%gcc@4.9.3 process_managers=slurm arch=linux-rhel7-ivybridge
        prefix: /usr/tce/packages/mvapich2/mvapich2-2.3-gcc-8.3.1
```

Then load the environment and run a package that requires mpi. The following two commands should work:

```
spack env create test1 toss3-gcc8.yaml
spack spec axom+mpi
```

### Error message

```
==> Error: Attempted to use external for 'intel-parallel-studio' which does not satisfy any configured external spec
```

### Information on your system

* **Spack:** 0.19.0.dev0 (02097b18560934698fee5279807e59ca43fa4182)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
