### ISSUE TITLE
Installation issue: py-bottleneck 

### ISSUE THREAD

**Issue by markyoder** [LLNL/spack#33765]
### Steps to reproduce the issue

well... I'm trying to build `paraview` in an environment, something like:
```
paraview%gcc@12.1.0 ^mpich`
```
, which will expand out to:
```
paraview@5.10.1%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" ~adios2~advanced_debug~catalyst~cuda+development_files~examples~eyedomelighting~fortran+hdf5+ipo+kits~libcatalyst+mpi+opengl2+osmesa+pagosa~python+python3~qt+shared build_edition=canonical build_system=cmake build_type=RelWithDebInfo patches=acb3805 use_vtkm=default arch=linux-centos7-x86_64
``` 
I get an error on py-bottleneck, and a couple others as well (see Error message, below).

So, with the spec defined:

```
    paraview:
      variants: +hdf5 +python3 +osmesa +pagosa +ipo
```

this ought to do it:
```
spack install paraview
```

From within that environment,
```
(base) [myoder96@sh03-04n54 /scratch/users/myoder96/spack_dev] (job 169255) $ spack spec -I py-bottleneck
Input spec
--------------------------------
 -   py-bottleneck

Concretized
--------------------------------
 -   py-bottleneck@1.3.5%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=python_pip arch=linux-centos7-x86_64
[+]      ^py-numpy@1.23.4%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" +blas+lapack build_system=python_pip patches=873745d arch=linux-centos7-x86_64
[+]          ^openblas@0.3.21%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" ~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile patches=d3d9b15 symbol_suffix=none threads=none arch=linux-centos7-x86_64
[+]              ^perl@5.36.0%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" +cpanm+shared+threads build_system=generic arch=linux-centos7-x86_64
[+]                  ^berkeley-db@18.1.40%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" +cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-centos7-x86_64
[+]          ^py-cython@0.29.32%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=python_pip arch=linux-centos7-x86_64
[+]      ^py-pip@22.2.2%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=generic arch=linux-centos7-x86_64
[+]      ^py-setuptools@59.4.0%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=generic arch=linux-centos7-x86_64
[+]      ^py-versioneer@0.26%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=python_pip arch=linux-centos7-x86_64
[+]      ^py-wheel@0.37.1%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=generic arch=linux-centos7-x86_64
[+]      ^python@3.9.15%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" +bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,4c24573,f2fd060 arch=linux-centos7-x86_64
[+]          ^bzip2@1.0.8%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" ~debug~pic+shared build_system=generic arch=linux-centos7-x86_64
[+]              ^diffutils@3.8%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools arch=linux-centos7-x86_64
[+]          ^expat@2.4.8%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" +libbsd build_system=autotools arch=linux-centos7-x86_64
[+]              ^libbsd@0.11.5%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools arch=linux-centos7-x86_64
[+]                  ^libmd@1.0.4%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools arch=linux-centos7-x86_64
[+]          ^gdbm@1.23%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools arch=linux-centos7-x86_64
[+]          ^gettext@0.21.1%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" +bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-centos7-x86_64
[+]              ^libiconv@1.16%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools libs=shared,static arch=linux-centos7-x86_64
[+]              ^libxml2@2.10.1%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" ~python build_system=autotools arch=linux-centos7-x86_64
[+]              ^tar@1.26%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools patches=08921fc,5c314db,d428578 zip=pigz arch=linux-centos7-x86_64
[+]          ^libffi@3.4.2%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools arch=linux-centos7-x86_64
[+]          ^ncurses@6.3%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" ~symlinks+termlib abi=none build_system=autotools arch=linux-centos7-x86_64
[+]          ^openssl@1.1.1s%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" ~docs~shared build_system=generic certs=mozilla arch=linux-centos7-x86_64
[+]              ^ca-certificates-mozilla@2022-10-11%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=generic arch=linux-centos7-x86_64
[+]          ^pkgconf@1.8.0%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools arch=linux-centos7-x86_64
[+]          ^readline@8.1.2%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools arch=linux-centos7-x86_64
[+]          ^sqlite@3.39.4%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" +column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-centos7-x86_64
[+]          ^util-linux-uuid@2.38.1%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC"  build_system=autotools arch=linux-centos7-x86_64
[+]          ^xz@5.2.7%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" ~pic build_system=autotools libs=shared,static arch=linux-centos7-x86_64
[+]          ^zlib@1.2.13%gcc@12.1.0 cflags="-fPIC" cxxflags="-fPIC" +optimize+pic+shared build_system=makefile arch=linux-centos7-x86_64

...
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing py-bottleneck-1.3.5-wncycwug2t3qpze7do22sc5qaqe2xrxd
==> No binary for py-bottleneck-1.3.5-wncycwug2t3qpze7do22sc5qaqe2xrxd found: installing from source
==> Using cached archive: /scratch/users/myoder96/spack_dev/spack/var/spack/cache/_source-cache/archive/2c/2c0d27afe45351f6f421893362621804fa7dea14fe29a78eaa52d4323f646de7.tar.gz
==> No patches needed for py-bottleneck
==> py-bottleneck: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/python-3.9.15-wqrgx4zkgkidrfvmsawhg23z26ryja4v/bin/python3.9' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/py-bottleneck-1.3.5-wncycwug2t3qpze7do22sc5qaqe2xrxd' '.'

1 error found in build log:
     108      ╰─> See above for output.
     109    
     110      note: This error originates from a subprocess, and is likely not a problem with pip.
     111      full command: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/python-3.9.15-wqrgx4zkgkidrfvmsawhg23z26ryja4v/bin/python3.9 /scratch/users/myoder96/spack_
            dev/spack/opt/spack/linux-centos7-x86_64/gcc-12.1.0/py-pip-22.2.2-l5libo5ork2xbpxqjkomm7tvsk54ltrp/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_
            for_build_wheel /tmp/tmpb7n0m062
     112      cwd: /tmp/myoder96/spack-stage/spack-stage-py-bottleneck-1.3.5-wncycwug2t3qpze7do22sc5qaqe2xrxd/spack-src
     113      Preparing metadata (pyproject.toml): finished with status 'error'
  >> 114    error: metadata-generation-failed
     115    
     116    × Encountered error while generating package metadata.
     117    ╰─> See above for output.
     118    
     119    note: This is an issue with the package mentioned above, not pip.
     120    hint: See above for details.

See build log for details:
  /tmp/myoder96/spack-stage/spack-stage-py-bottleneck-1.3.5-wncycwug2t3qpze7do22sc5qaqe2xrxd/spack-build-out.txt
</pre></details>

### Information on your system

(base) [myoder96@sh03-04n54 /scratch/users/myoder96/spack_dev] (job 169255) $ spack debug report
* **Spack:** 0.19.0.dev0
* **Python:** 3.8.8
* **Platform:** linux-centos7-zen2
* **Concretizer:** clingo

### Additional information

@adamjstewart

note, I get the same error for `py-numexp`

spack.yaml environment file.
```
# This is a Spack Environment file.
spack:
  definitions:
  - compilers_core: [gcc@9.1.0]
  - compilers_gcc: [gcc@12.1.0]
  - compilers_intel: [intel]

#  - compilers_oneapi: [oneapi@2021.4.0]
#  
#  - packages_core: [intel-oneapi-compilers]
  #
  - mpis: [mpich]
  - packages_mpis: [mpich]

  #
  - packages_serial: [proj]

    #
  - packages_parallel: [paraview, parflow]
  specs:

  # compilers:
  # Do we need this, or can we just check the "build compilers if we need them" box?
#  - matrix:
#    - [$packages_core]
#    - [$%compilers_core]
  #
  # build serial packages and MPI(s)
  - matrix:
    - [$packages_serial, $packages_mpis]
    - [$%compilers_gcc]
  #
  # Parallel (MPI) packages:
  - matrix:
    - [$packages_parallel]
    - [$^mpis]
    - [$%compilers_gcc]
[spack-build-out.txt](https://github.com/spack/spack/files/9964815/spack-build-out.txt)

  #
  view: false
  concretizer:
    unify: when_possible
  packages:
    paraview:
      variants: +hdf5 +python3 +osmesa +pagosa +ipo
    parflow:
      variants: +ipo
    libxsmm:
      variants: +shared+generator
    hdf5:
      variants: ~cxx~debug+fortran+hl~java+mpi+shared~szip+threadsafe
    netcdf-c:
      variants: +mpi
    cmake:
      version: [3.23.1]
      externals:
      - spec: cmake@3.23.1
        prefix: /share/software/user/open/cmake/3.23.1
        modules: [system, curl/7.81.0, cmake/3.23.1]
    cdo:
      variants: ~szip
    curl:
      externals:
      - spec: cmake@7.81.0
        prefix: /share/software/user/open/curl/7.81.0
        modules: [system, curl/7.81.0]
        environment:
          set:
            CURL_LIBRARY: /share/software/user/open/curl/7.81.0/lib
    petsc:
      variants: +hdf5 +batch +fftw +hwloc +hypre
    libszip:
      externals:
      - spec: libszip@2.1.1
        prefix: /share/software/user/open/szip/2.1.1
        modules: [system, szip/2.1.1]
    tar:
      version: [1.26]
      externals:
      - spec: tar@1.26
        prefix: /usr
    metis:
      variants: +optimizations+int64+real64
    nco:
      version: [4.9.3]
    parmetis:
      variants: +int64+real64
    pumi:
      variants: +fortran +int64 +ipo +shared ~zoltan
    gmsh:
      variants: +mpi +hdf5 ~fltk
    gcc:
      version: [12.2.0]
      compiler: [gcc@10.1.0]
      target: [x86_64]
      externals:
      - spec: gcc@12.1.0
        prefix: /share/software/user/open/gcc/12.1.0
        modules: [gcc/12.1.0]
      - spec: gcc@10.1.0
        prefix: /share/software/user/open/gcc/10.1.0
        modules: [devel, gcc/10.1.0, binutils/]
    intel-oneapi-compilers:
      compiler: [gcc@9.1.0]
      target: [x86_64_v3]
    all:
      compiler: [gcc@12.1.0]
      target: [x86_64]
      variants: build_type=Release +mpi
      providers:
        mpi: [mpich]
      permissions:
        read: world
        write: user
  modules:
    default:
      roots:
        lmod: $spack/share/spack/lmod_seissol
        tcl: $spack/share/spack/modules_seissol
      'enable:':
      - lmod
      lmod:
        core_compilers:
        - gcc@4.8.5
        - gcc@9.1.0
        hierarchy:
        - mpi
        - compiler
        'hash_length:': 5
        projections:
          all: '{name}-cees/{version}'
          ^mpi: '{name}-cees/{^mpi.name}-{version}'
    prefix_inspections:
      bin:
      - PATH
      lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
      lib/pkgconfig:
      - PKG_CONFIG_PATH
      share/pkgconfig:
      - PKG_CONFIG_PATH
      include:
      - CPATH
  #
  config:
    install_missing_compilers: true
    checksum: true
    deprecated: false
    dirty: false
    ccache: false
    concretizer: clingo
    shared_linking: rpath
    build_stage:
    - /scratch/${user}/spack_stage
    - $tempdir/${user}/spack-stage
    - ~/.spack/stage
#
#
  compilers:
  - compiler:
      spec: gcc@4.8.5
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      operating_system: centos7
      target: x86_64
      flags:
        cflags: -fPIC
        cxxflags: -fPIC
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@9.1.0
      paths:
        cc: /share/software/user/open/gcc/9.1.0/bin/gcc
        cxx: /share/software/user/open/gcc/9.1.0/bin/g++
        f77: /share/software/user/open/gcc/9.1.0/bin/gfortran
        fc: /share/software/user/open/gcc/9.1.0/bin/gfortran
      flags:
        cflags: -fPIC
        cxxflags: -fPIC
      operating_system: centos7
      target: x86_64
      modules: [devel, gcc/9.1.0, binutils/2.38]
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@12.1.0
      paths:
        cc: /share/software/user/open/gcc/12.1.0/bin/gcc
        cxx: /share/software/user/open/gcc/12.1.0/bin/g++
        f77: /share/software/user/open/gcc/12.1.0/bin/gfortran
        fc: /share/software/user/open/gcc/12.1.0/bin/gfortran
      modules: [devel, gcc/12.1.0, binutils/2.38]
      flags:
        cflags: -fPIC
        cxxflags: -fPIC
      operating_system: centos7
      target: x86_64
  - compiler:
      spec: dpcpp@2022.2.0
      paths:
        cc: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/icx
        cxx: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/dpcpp
        f77: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/ifx
        fc: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/ifx
      flags: {}
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: intel@2021.7.0
      paths:
        cc: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/intel64/icc
        cxx: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/intel64/icpc
        f77: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/intel64/ifort
        fc: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/intel64/ifort
      flags:
        cflags: -fPIC -we147 -diag-disable=10441
        cxxflags: -fPIC -diag-disable=10441
        fflags: -fPIC -diag-disable=10441
      operating_system: centos7
      target: x86_64
      modules: [devel, gcc/9.1.0]
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: oneapi@2022.2.0
      paths:
        cc: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/icx
        cxx: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/icpx
        f77: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/ifx
        fc: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64_v3/gcc-9.1.0/intel-oneapi-compilers-2022.2.0-cz55wu6ueymbpsyyl2ntrkgqjtgqh5s6/compiler/2022.2.0/linux/bin/ifx
      flags:
        cflags: -fPIC
        cxxflags: -fPIC
        fflags: -fPIC
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
