### ISSUE TITLE
How to force spack to use dependencies built by core compiler ?

### ISSUE THREAD

**Issue by vitduck** [LLNL/spack#33986]
Hello, 

I've gone through the module file tutorials and successfully set up my environment. 
Below is the result for ```spack find``` with the most relevant entries for my question.
```
-- linux-ubuntu20.04-neoverse_n1 / gcc@9.4.0 --------------------
autoconf@2.69 ucx@1.13.1
... 
-- linux-ubuntu20.04-neoverse_n1 / gcc@10.2.0
autoconf@2.69 ucx@1.13.1
... 
-- linux-ubuntu20.04-neoverse_n1 / nvhpc@21.9 -------------------
autoconf@2.69 ucx@1.13.1
...
```
Since spack categorizes software according to compiler versions, ```autoconf``` and many other minor dependencies were automatically recompiled. ```nvhpc``` is somewhat picky, and often fails to compile dependencies such as ```ucx```. 
I have the following in ```packages.yaml``` to prevent it from rebuilding ```ucx``` and used the lib compiled with gcc
```
packages: 
  ucx:
    externals:
      - spec: "ucx@1.13.1 %nvhpc@21.9+cuda+dc+rc"
         prefix: "/chome/infra/spack/opt/spack/linux-ubuntu20.04-neoverse_n1/gcc-9.4.0/ucx-1.13.1-vgcdunrmv3diz4aplmhourun6n3s4qj2"
```
Is there a way to force all dependencies to be built by gcc@9.4.0 and recompiled only on a demand basis ? 

For example below is QE workflow: 
1. Set ```gcc@9.4.0`` as core compiler 
2. Install ```nvhpc@21.9```
3. Build openmpi@4.1.4 with ```nvhpc```` but all minor dependencies are built from gcc@9.4.0 
4. Build QE with ```nvhpc``` 
5. Repeat with other versions of ```nvhpc``` if neccessary

The desirable outcome would be 
```
-- linux-ubuntu20.04-neoverse_n1 / gcc@9.4.0 --------------------
autoconf@2.69 curl@7.85.0 perl@5.36.0 ucx@1.11.0 ucx@1.13.1 fftw@3.3.19 
...

-- linux-ubuntu20.04-neoverse_n1 / gcc@10.2.0 --------------------
openmpi@4.14 quantum-espresso@7.1 

-- linux-ubuntu20.04-neoverse_n1 / nvhpc@21.9 --------------------
openmpi@4.14 quantum-espresso@7.1
```
This would simulate yum/apt package management with the added benefit of maintaining multiple versions of a dependency and pick the correct one via ```packages.yaml``` if compatibility issue arises. 

Thanks.
