### ISSUE TITLE
Installation issue: hdf5+fortran+hl%oneapi@2022.2.0 ^intel-mpi - CMAKE_C_COMPIER path wrong 

### ISSUE THREAD

**Issue by zeekus** [LLNL/spack#34129]
### Steps to reproduce the issue

```
$ spack install hdf5+fortran+hl%oneapi@2022.2.0 ^intel-mpi


```

### Error message

<details><summary>Error message: not able to find the right intel-mpi compiler </summary><pre>
 [centos@ip-10-137-0-174 ~]$ spack install hdf5+fortran+hl%oneapi@2022.2.0 ^intel-mpi
[+] /modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/pkgconf-1.8.0-aaihhrfzc5wonl6axdfcjqim5doobvmi
[+] /usr (external openssl-1.0.2k-fips-nzhhr2wrlol7e665j5nvfokgdkb4acga)
[+] /opt/intel/mpi/2021.6.0 (external intel-mpi-2021.6.0-g4qwnaqiratt6ru42tlwgeboaccxerti)
[+] /modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/zlib-1.2.13-vkouti5jlqg7dxeh7hkbzalfhb2xejja
[+] /modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/ncurses-6.3-anxetblya75e456edpq42efx37xxkui5
[+] /modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/cmake-3.24.3-hicqdimidratbpf5ra2r6oxkvpfhh4rs
==> Installing hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt
==> No binary for hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt found: installing from source
==> Using cached archive: /modeling/spack/var/spack/cache/_source-cache/archive/2a/2a89af03d56ce7502dcae18232c241281ad1773561ec00c0f0e8ee2463910f14.tar.gz
==> Ran patch() for hdf5
==> hdf5: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/cmake-3.24.3-hicqdimidratbpf5ra2r6oxkvpfhh4rs/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/lib;/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/lib64;/opt/intel/mpi/2021.6.0/lib;/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/zlib-1.2.13-vkouti5jlqg7dxeh7hkbzalfhb2xejja/lib' '-DCMAKE_PREFIX_PATH:STRING=/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/zlib-1.2.13-vkouti5jlqg7dxeh7hkbzalfhb2xejja;/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/cmake-3.24.3-hicqdimidratbpf5ra2r6oxkvpfhh4rs;/opt/intel/mpi/2021.6.0' '-DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration' '-DALLOW_UNSUPPORTED:BOOL=ON' '-DHDF5_BUILD_EXAMPLES:BOOL=OFF' '-DBUILD_TESTING:BOOL=OFF' '-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON' '-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF' '-DHDF5_ENABLE_SZIP_ENCODING:BOOL=OFF' '-DBUILD_SHARED_LIBS:BOOL=ON' '-DONLY_SHARED_LIBS:BOOL=OFF' '-DHDF5_ENABLE_PARALLEL:BOOL=ON' '-DHDF5_ENABLE_THREADSAFE:BOOL=OFF' '-DHDF5_BUILD_HL_LIB:BOOL=ON' '-DHDF5_BUILD_CPP_LIB:BOOL=OFF' '-DHDF5_BUILD_FORTRAN:BOOL=ON' '-DHDF5_BUILD_JAVA:BOOL=OFF' '-DHDF5_BUILD_TOOLS:BOOL=ON' '-DCMAKE_C_COMPILER:STRING=/opt/intel/mpi/2021.6.0/compilers_and_libraries/linux/mpi/intel64/bin/mpicc' '-DCMAKE_Fortran_COMPILER:STRING=/opt/intel/mpi/2021.6.0/compilers_and_libraries/linux/mpi/intel64/bin/mpif90' '/tmp/centos/spack-stage/spack-stage-hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/spack-src'

1 error found in build log:
  >> 4    CMake Error at CMakeLists.txt:2 (project):
     5      The CMAKE_C_COMPILER:
     6
     7        /opt/intel/mpi/2021.6.0/compilers_and_libraries/linux/mpi/intel64/bin/mpicc
     8
     9      is not a full path to an existing compiler tool.
     10

See build log for details:
  /tmp/centos/spack-stage/spack-stage-hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/spack-build-out.txt
  
  Actual path:  /opt/intel/mpi/2021.6.0/bin/mpicc
</pre></details>

### Information on your system

* **Spack:** 0.19.0
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

packages modified for dependancies: $SPACK_ROOT/etc/spack/packages.yaml
```
packages:
    intel-mpi:
        externals:
        - spec: intel-mpi@2021.6.0
          prefix: /opt/intel/mpi/2021.6.0
        buildable: False
    libfabric:
        variants: fabrics=efa,tcp,udp,sockets,verbs,shm,mrail,rxd,rxm
        externals:
        - spec: libfabric@1.16.0 fabrics=efa,tcp,udp,sockets,verbs,shm,mrail,rxd,rxm
          prefix: /opt/amazon/efa
        buildable: False
    openmpi:
        variants: fabrics=ofi +legacylaunchers schedulers=slurm ^libfabric
        externals:
        - spec: openmpi@4.1.4 %gcc@4.8.5
          prefix: /opt/amazon/openmpi
    pmix:
        externals:
          - spec: pmix@3.2.3 ~pmi_backwards_compatibility
            prefix: /opt/pmix
    slurm:
        variants: +pmix sysconfdir=/opt/slurm/etc
        externals:
        - spec: slurm@22.05.5 +pmix sysconfdir=/opt/slurm/etc
          prefix: /opt/slurm
        buildable: False
```

### Additional information

```
[centos@ip-10-137-0-174 var]$ cat /tmp/centos/spack-stage/spack-stage-hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/spack-build-out.txt
==> hdf5: Executing phase: 'cmake'
==> [2022-11-25-13:01:06.182635] '/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/cmake-3.24.3-hicqdimidratbpf5ra2r6oxkvpfhh4rs/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/lib;/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/lib64;/opt/intel/mpi/2021.6.0/lib;/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/zlib-1.2.13-vkouti5jlqg7dxeh7hkbzalfhb2xejja/lib' '-DCMAKE_PREFIX_PATH:STRING=/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/zlib-1.2.13-vkouti5jlqg7dxeh7hkbzalfhb2xejja;/modeling/spack/opt/spack/linux-centos7-skylake_avx512/oneapi-2022.2.0/cmake-3.24.3-hicqdimidratbpf5ra2r6oxkvpfhh4rs;/opt/intel/mpi/2021.6.0' '-DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration' '-DALLOW_UNSUPPORTED:BOOL=ON' '-DHDF5_BUILD_EXAMPLES:BOOL=OFF' '-DBUILD_TESTING:BOOL=OFF' '-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON' '-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF' '-DHDF5_ENABLE_SZIP_ENCODING:BOOL=OFF' '-DBUILD_SHARED_LIBS:BOOL=ON' '-DONLY_SHARED_LIBS:BOOL=OFF' '-DHDF5_ENABLE_PARALLEL:BOOL=ON' '-DHDF5_ENABLE_THREADSAFE:BOOL=OFF' '-DHDF5_BUILD_HL_LIB:BOOL=ON' '-DHDF5_BUILD_CPP_LIB:BOOL=OFF' '-DHDF5_BUILD_FORTRAN:BOOL=ON' '-DHDF5_BUILD_JAVA:BOOL=OFF' '-DHDF5_BUILD_TOOLS:BOOL=ON' '-DCMAKE_C_COMPILER:STRING=/opt/intel/mpi/2021.6.0/compilers_and_libraries/linux/mpi/intel64/bin/mpicc' '-DCMAKE_Fortran_COMPILER:STRING=/opt/intel/mpi/2021.6.0/compilers_and_libraries/linux/mpi/intel64/bin/mpif90' '/tmp/centos/spack-stage/spack-stage-hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/spack-src'
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    /opt/intel/mpi/2021.6.0/compilers_and_libraries/linux/mpi/intel64/bin/mpicc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/tmp/centos/spack-stage/spack-stage-hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/spack-build-akpqfcm/CMakeFiles/CMakeOutput.log".
See also "/tmp/centos/spack-stage/spack-stage-hdf5-1.12.2-akpqfcmlsdcncnle425jw6lioawmj2jt/spack-build-akpqfcm/CMakeFiles/CMakeError.log".
```

_No response_

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
