### ISSUE TITLE
compiler find does not automatically mix clang and gfortran anymore

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#3426]
@BarrySmith added in https://github.com/LLNL/spack/pull/2192 a nice feature so that `gfortran` is setup within `clang` compiler in Spack. It appers that this feature is currently broken.
I am testing  a simple bash script which has:
```
spack install gcc
GCC_PATH=`spack location -i gcc`
export PATH="$GCC_PATH/bin:$PATH"
spack compiler remove clang
spack compiler find
```
which produces
```
==> gcc is already installed in /Users/davydden/spack.tmp/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.3.0-oauwkr2nrtqqtmq5d45cpduvxcjwxlgj
==> Removed compiler clang@8.0.0-apple
==> Added 1 new compiler to /Users/davydden/.spack/darwin/compilers.yaml
    clang@8.0.0-apple
```
however `fortran` part is still missing in `clang@8.0.0-apple`:
```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    spec: gcc@4.2.1
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /Users/davydden/spack.tmp/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.3.0-oauwkr2nrtqqtmq5d45cpduvxcjwxlgj/bin/gcc
      cxx: /Users/davydden/spack.tmp/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.3.0-oauwkr2nrtqqtmq5d45cpduvxcjwxlgj/bin/g++
      f77: /Users/davydden/spack.tmp/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.3.0-oauwkr2nrtqqtmq5d45cpduvxcjwxlgj/bin/gfortran
      fc: /Users/davydden/spack.tmp/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.3.0-oauwkr2nrtqqtmq5d45cpduvxcjwxlgj/bin/gfortran
    spec: gcc@6.3.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
      cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
      f77: null
      fc: null
    spec: clang@8.0.0-apple
    target: x86_64
```
