### ISSUE TITLE
spack mirror command not working

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#34532]
### Steps to reproduce

I was trying to build survey on snow at LANL using a mirror with the latest 12-14-2022 spack sources, but I get this message.   I was able to use the same mirror with an older 11-21-2022 version of the spack sources.   So, thought I would report this.
```
sn-fe1:/<4>survey/spack_12142022/spack [841] $ spack install --no-cache --keep-stage [survey@1.0.6.release-openmpi-2.1.2](mailto:survey@1.0.6.release-openmpi-2.1.2) %gcc@8.3.0 +mpi ^openmpi@2.1.2
==> Error: unknown url type: 'usr/projects/hpctools/survey/spack_12142022/survey-mirror-12-14-2022/build_cache/index.json'
```

### Error message

```
sn-fe1:/<4>survey/spack_12142022/spack [841] $ spack install --no-cache --keep-stage [survey@1.0.6.release-openmpi-2.1.2](mailto:survey@1.0.6.release-openmpi-2.1.2) %gcc@8.3.0 +mpi ^openmpi@2.1.2
==> Error: unknown url type: 'usr/projects/hpctools/survey/spack_12142022/survey-mirror-12-14-2022/build_cache/index.json'
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.20.0.dev0 (2387c116add454d6b7cf5400e368fb95bd3de415)
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Can you show what `spack config get mirrors` looks like?

It's likely related to e055dc0e64693782e5d98ffa90780ad57c855aa2. The issue being solved there is Windows support; in the past we've been using URLs and paths interchangeably, but that results in various issues, such as c:/users/x/y being interpreted as a URL like http://users/x/y where it should have been a windows path etc.

We can try to promote the path better to a URL.

**Comment by jgalarowicz** [comment]
@haampie 
Here is the information:
```
sn-fe1:/<4>survey/spack_12142022/spack [948] $ spack config get mirrors
mirrors:
  survey-mirror-12-14-2022:
    fetch:
      url: /usr/projects/hpctools/survey/spack_12142022/survey-mirror-12-14-2022
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: /usr/projects/hpctools/survey/spack_12142022/survey-mirror-12-14-2022
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
  spack-public: https://mirror.spack.io
```
