### ISSUE TITLE
attempt to containerize apptainer with strip: true leads to "File format not recognized"

### ISSUE THREAD

**Issue by anderbubble** [LLNL/spack#34629]
### Steps to reproduce

```
spack:
  specs:
  - apptainer

  container:
    format: singularity

    images:
      os: centos:stream
      spack: v0.19.0

    strip: true

    labels:
      app: "apptainer"
```

then

```
apptainer build --fakeroot apptainer.sif <(spack containerize)
```

### Error message

[Uploading apptainer-spack-containerize.log…]()

### Information on your system

```
* **Spack:** 0.20.0.dev0 (99fcc5760755e41f2af5431bcafc4fd3f326f47d)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen3
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
