### ISSUE TITLE
Building curl@7.52.1 with system openssl

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#3471]
Hi all,

I would like to build curl such that it supports https:// domains. This requires openssl. According to http://spack.readthedocs.io/en/latest/getting_started.html#openssl it is recommended to use the system openssl. I modified the packages.yaml file according to the documentation:

```
[sfux@develop02 ~]$ cat /local/cluster/spack/etc/spack/defaults/packages.yaml 
# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [gcc, intel, llvm]
    providers:
      mpi: [openmpi, mvapich2]
      blas: [openblas]
      lapack: [openblas]
      pil: [py-pillow]
  openssl:
    paths:
      openssl@system: /usr
    version: [system]
    buildable: False
[sfux@develop02 ~]$ 
```

I am using CentOS 7 and installed the required openssl rpms through the package manager:

```
[sfux@develop02 ~]$ ls -ltr /usr/lib64/libssl*
-rwxr-xr-x 1 root root 276760 Nov 22 00:29 /usr/lib64/libssl3.so
-rwxr-xr-x 1 root root 454008 Feb 20 15:41 /usr/lib64/libssl.so.1.0.1e
lrwxrwxrwx 1 root root     16 Feb 28 14:16 /usr/lib64/libssl.so.10 -> libssl.so.1.0.1e
[sfux@develop02 ~]$ ls -ltr /usr/bin/openssl*
-rwxr-xr-x 1 root root 508728 Feb 20 15:41 /usr/bin/openssl
[sfux@develop02 ~]$ 
```

For some reason the curl@7.52.1 build does not recognize openssl. Please find below some excerpts from the config log:

`==> openssl is externally installed in /usr`

`==> './configure' '--prefix=/local/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/curl-7.52.1-fitah5hmrfrhm7xg2huserepha774dhy' '--with-zlib=/local/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-rkzkdjjffuzl55dql2pm2o6dmiq2shu3' '--with-ssl=/usr'`

```
checking whether to enable Windows native SSL/TLS (Windows native builds only)... no
checking whether to enable Apple OS native SSL/TLS... no
configure: PKG_CONFIG_LIBDIR will be set to "/usr/lib/pkgconfig"
checking for HMAC_Update in -lcrypto... no
checking for HMAC_Init_ex in -lcrypto... no
checking for ssl_version in -laxtls... no
configure: WARNING: SSL disabled, you will not be able to use HTTPS, FTPS, NTLM and more.
configure: WARNING: Use --with-ssl, --with-gnutls, --with-polarssl, --with-cyassl, --with-nss, --with-axtls, --with-winssl, or --with-darwinssl to address this.
```

```
configure: Configured to build curl/libcurl:

  curl version:     7.52.1
  Host setup:       x86_64-pc-linux-gnu
  Install prefix:   /local/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/curl-7.52.1-fitah5hmrfrhm7xg2huserepha774dhy
  Compiler:         /local/cluster/spack/lib/spack/env/gcc/gcc
  SSL support:      no      (--with-{ssl,gnutls,nss,polarssl,mbedtls,cyassl,axtls,winssl,darwinssl} )
```

Any idea what is going wrong ?

Best regards

Sam

**Comment by adamjstewart** [comment]
First of all, you should never modify `etc/spack/defaults/packages.yaml`. These are the defaults that ship with Spack and are likely to change, preventing you from upgrading or causing you to accidentally push that commit to a PR. Spack has a hierarchy of configuration files:

* `~/.spack/linux`
* `~/.spack`
* `etc/spack/linux`
* `etc/spack`
* `etc/spack/defaults`

You can put your configuration files in any of these locations and Spack will pick them up.

Second, and this is likely what is causing your actual problem, you shouldn't use `@system`. This way is no longer recommended (and I swear I thought the documentation had been fixed), but you should either use the actual version or don't specify the version at all. If I remember correctly, Spack has trouble recognizing system packages in `packages.yaml` unless the version specified is in the `package.py`. Can you try that? I'll fix the documentation.

**Comment by adamjstewart** [comment]
For example, my `~/.spack/packages.yaml` contains:
```yaml
packages:
  openssl:
    paths:
      openssl@1.0.1e arch=linux-centos6-x86_64: /usr
    buildable: False
```
this should also work:
```yaml
packages:
  openssl:
    paths:
      openssl: /usr
    buildable: False
```

**Comment by samfux84** [comment]
Thank you for helping me with this issue.

Regarding the modification of packages.yaml, does this apply to all config files ? If I do a fresh spack installation, should I copy all of the .yaml files to ~/.spack and modify them there ?

I will soon try your suggestion and provide some feedback.

**Comment by adamjstewart** [comment]
Yes, you should leave the configuration files in `etc/spack/defaults` alone. There's no need to copy them. Any configuration files in `~/.spack` will be merged with the defaults. Although, if you want to keep track of everything Spack sets as default, there's no harm in copying them.

**Comment by adamjstewart** [comment]
Of course, there's nothing wrong with modifying `etc/spack/defaults`. It won't break Spack or anything, and it didn't cause your problem. But if you ever need to update to a newer version of Spack or contribute a PR, modifications to `etc/spack/defaults` could cause problems. These files are tracked by git, whereas things in `~/.spack` aren't.

**Comment by samfux84** [comment]
I am sorry for the misunderanding. I meant should I copy the config files to ~/.spack and modify then the config files in ~/.spack, not the ones in default.

**Comment by adamjstewart** [comment]
Actually, it looks like you do need to specify the version, you can't leave it blank. You can find the version of OpenSSL by running:
```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```
I'll add that to the documentation.

**Comment by samfux84** [comment]
I did now a fresh spack installation (currently I am only doing test installations, therefore redoing it does not take long) and modified only config files in ~/.spack/linux
```

[sfux@develop02 tools]$ cat ~/.spack/linux/packages.yaml 
# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [gcc, intel, llvm]
    providers:
      mpi: [openmpi, mvapich2]
      blas: [openblas]
      lapack: [openblas]
      pil: [py-pillow]
  openssl:
    paths:
      openssl@1.0.1e arch=linux-centos7-x86_64: /usr
    buildable: False
[sfux@develop02 tools]$
```

```
[sfux@develop02 tools]$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```
I tried both:

- spack install -v curl@7.52.1
- spack install -v curl@7.52.1 ^openssl@1.0.1e

In both cases openssl was not recognized.
