### ISSUE TITLE
Module generation error when computing Lmod path hierarchy

### ISSUE THREAD

**Issue by mathomp4** [LLNL/spack#34728]
### Steps to reproduce the issue

I was trying to `spack install gcc`.

```console
$ spack spec -I gcc
Input spec
--------------------------------
 -   gcc

Concretized
--------------------------------
 -   gcc@12.2.0%apple-clang@14.0.0~binutils+bootstrap~graphite~nvptx~piclibs~strip build_system=autotools build_type=RelWithDebInfo languages=c,c++,fortran arch=darwin-ventura-skylake
[+]      ^diffutils@3.8%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-skylake
[+]      ^gawk@5.2.1%apple-clang@14.0.0~nls build_system=autotools arch=darwin-ventura-skylake
[+]      ^gmp@6.2.1%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]          ^autoconf@2.69%apple-clang@14.0.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=darwin-ventura-skylake
[+]              ^perl@5.36.0%apple-clang@14.0.0+cpanm+shared+threads build_system=generic arch=darwin-ventura-skylake
[+]                  ^berkeley-db@18.1.40%apple-clang@14.0.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=darwin-ventura-skylake
[+]                  ^bzip2@1.0.8%apple-clang@14.0.0~debug~pic+shared build_system=generic arch=darwin-ventura-skylake
[+]                  ^gdbm@1.23%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-skylake
[+]                      ^readline@8.2%apple-clang@14.0.0 build_system=autotools patches=bbf97f1 arch=darwin-ventura-skylake
[+]                          ^ncurses@6.3%apple-clang@14.0.0~symlinks+termlib abi=none build_system=autotools arch=darwin-ventura-skylake
[+]                              ^pkg-config@0.29.2%apple-clang@14.0.0+internal_glib build_system=autotools arch=darwin-ventura-skylake
[+]          ^automake@1.16.5%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-skylake
[+]          ^m4@1.4.6%apple-clang@14.0.0+sigsegv build_system=autotools arch=darwin-ventura-skylake
[+]      ^libiconv@1.16%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]      ^libtool@2.4.7%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-skylake
[+]      ^mpc@1.2.1%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]      ^mpfr@4.1.0%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]          ^autoconf-archive@2022.02.11%apple-clang@14.0.0 build_system=autotools patches=139214f arch=darwin-ventura-skylake
[+]      ^texinfo@5.2%apple-clang@14.0.0 build_system=autotools patches=8554f52 arch=darwin-ventura-skylake
[+]      ^zlib@1.2.13%apple-clang@14.0.0+optimize+pic+shared build_system=makefile arch=darwin-ventura-skylake
[+]      ^zstd@1.5.2%apple-clang@14.0.0~programs build_system=makefile libs=shared,static arch=darwin-ventura-skylake
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: DuplicateCompilerSpecError: %gcc@12.2.0 cannot have multiple compilers
See build log for details:
  /var/folders/0p/4sfhr4b10yd891rdgj757cnc0000gn/T/fortran/spack-stage/spack-stage-gcc-12.2.0-o7cycranmikhyholodnohru7omojszp2/spack-build-out.txt
</pre></details>

### Information on your system

```console
$ spack debug report
* **Spack:** 0.20.0.dev0 (a98c400447c551ba92389b3ac8f591af8884dab0)
* **Python:** 3.10.9
* **Platform:** darwin-ventura-skylake
* **Concretizer:** clingo
```

My `packages.yaml`:
```
packages:
  curl:
    externals:
    - spec: curl@7.85.0+gssapi+ldap+nghttp2
      prefix: /usr
  git:
    externals:
    - spec: git@2.37.1~tcltk
      prefix: /usr
    - spec: git@2.39.0~tcltk
      prefix: /usr/local
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr/local
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr/local
  openssh:
    externals:
    - spec: openssh@9.0p1
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.6
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@9.1
      prefix: /usr/local
  gmake:
    externals:
    - spec: gmake@4.4
      prefix: /Users/fortran
    - spec: gmake@3.81
      prefix: /usr
  ninja:
    externals:
    - spec: ninja@1.11.1
      prefix: /usr/local
  cvs:
    externals:
    - spec: cvs@1.12.13
      prefix: /usr/local
  gawk:
    externals:
    - spec: gawk@5.2.1
      prefix: /usr/local
  subversion:
    externals:
    - spec: subversion@1.14.2
      prefix: /usr/local
  cmake:
    externals:
    - spec: cmake@3.25.1
      prefix: /usr/local
  git-lfs:
    externals:
    - spec: git-lfs@3.3.0
      prefix: /usr/local
  diffutils:
    externals:
    - spec: diffutils@3.8
      prefix: /usr/local
  texinfo:
    externals:
    - spec: texinfo@5.2
      prefix: /usr/local
  bison:
    externals:
    - spec: bison@2.3
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
```

My `modules.yaml`:
```
modules:
  default:
    enable::
      - lmod
    lmod:
      core_compilers:
      - 'apple-clang@14.0.0'
      hierarchy:
      - mpi
      hash_length: 0
      include:
      - gcc
      exclude:
      - 'apple-clang@14.0.0'
      all:
        filter:
          exclude_env_vars:
          - "C_INCLUDE_PATH"
          - "CPLUS_INCLUDE_PATH"
          - "LIBRARY_PATH"
        environment:
          set:
            '{name}_ROOT': '{prefix}'
      openmpi:
        environment:
          set:
            SLURM_MPI_TYPE: pmi2
            OMPI_MCA_btl_openib_warn_default_gid_prefix: '0'
      projections:
        all:          '{name}/{version}'
        ^lapack:      '{name}/{version}-{^lapack.name}'
```

### Additional information

I had to `gzip` up my build-out because, well, it's a `gcc` build. 

[spack-build-out.txt.gz](https://github.com/spack/spack/files/10322532/spack-build-out.txt.gz)
[spack-build-env.txt](https://github.com/spack/spack/files/10322533/spack-build-env.txt)

Mentions:
@alalazo
@michaelkuhn

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
