### ISSUE TITLE
Spack chooses old version of tar

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#35090]
### Steps to reproduce

I am installing a set of packages via a spack-build GCC on macOS. This is my `spack.yaml`:

```
spack:
  definitions:
  - compilers:
    - gcc @12.2.0-ffj46nt7qyec3b77cbqgfozgtkfuzx3k
  - packages:
    - adios2 ~python
    - amrex ~fortran +hdf5 +openmp +particles
    - boost @1.79 cxxstd=17 +filesystem +mpi +system
    - compose
    - einsteintoolkit
    - fftw +mpi +openmp
    - gperftools
    - gsl
    - hdf5 @1.12.1 +cxx +fortran +hl +mpi +threadsafe
    - hwloc +opencl
    - libjpeg-turbo
    - kadath
    - libfyaml
    - lorene
    - mpitrampoline
    - nsimd @3.0.1
    - openblas
    - openpmd-api
    - openssl
    - petsc +fftw +hwloc +openmp
    - reprimand
    - rnpletal
    - silo @4.11 ~fortran +hdf5 ~pic ~shared
    - simulationio +asdf +hdf5 ~python +rnpl +silo
    - spiner
    - sqlite
    - ssht
    - sz
    - yaml-cpp
    - zlib
  specs:
  - matrix:
    - [$%compilers]
    - [$packages]
  - cmake %apple-clang @14.0.0
  - curl %apple-clang @14.0.0
  - git %apple-clang @14.0.0
  - python %apple-clang @14.0.0
  concretizer:
    reuse: false
    unify: true
  view: /Users/eschnett/Cactus/view
  compilers:
  - compiler:
      spec: gcc@12.2.0-ffj46nt7qyec3b77cbqgfozgtkfuzx3k
      paths:
        cc: /Users/eschnett/Cactus/view-compilers/bin/gcc
        cxx: /Users/eschnett/Cactus/view-compilers/bin/g++
        f77: /Users/eschnett/Cactus/view-compilers/bin/gfortran
        fc: /Users/eschnett/Cactus/view-compilers/bin/gfortran
      flags: {}
      operating_system: ventura
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

I install these packages via
```sh
spack --env-dir utils/spack/redshift concretize --force
spack --env-dir utils/spack/redshift install --fail-fast
```

### Error message

Spack chooses `tar @1.30` instead of `tar @1.34`. I can make Spack use `tar @1.34` by explicitly specifying this version in `spack.yaml`. (I have a similar problem with the `nsimd` package.)

I see that the `tar` recipe contains this line:
```Python
    depends_on("zstd+programs", type="run", when="@1.31:")
```
which might explain this behaviour. I looked at all packages, and nothing else could seem to explain this behaviour.

### Information on your system

```
$ spack debug report
* **Spack:** 0.20.0.dev0 (fbc24d7bab80a2f761f2c63e80b572bbe19273f6)
* **Python:** 3.9.12
* **Platform:** darwin-ventura-skylake
* **Concretizer:** clingo
```

I have not run any failing commands in debug mode since no commands are failing.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
