### ISSUE TITLE
`spack concretize` duplicates comment in `spack.yaml` for specific list syntax

### ISSUE THREAD

**Issue by ltalirz** [LLNL/spack#35420]
### Steps to reproduce

Example `var/spack/environments/test/spack.yaml`
```yaml
spack:
  specs:
  - matrix:
    # test
    - - nwchem
      - quantum-espresso
  view: false
  compilers: []
  concretizer:
    unify: false
```

To reproduce the problem, now run

```console
spack env activate test
spack concretize
```

### Error message

The environment file is missing compilers to make it minimal; it may not be entirely valid (so I don't expect concretization to work necessarily), but the behavior is the same for successful concretization
```
# spack concretize
==> Starting concretization pool with 2 processes
==> Error: errors occurred during concretization of the environment:
not enough arguments for format string
not enough arguments for format string
```

The problem is that after running the concretization step, the `spack.yaml` file is rewritten to
```yaml
spack:
  specs:
  - matrix:
    
    # test
    -
    # test
      - nwchem
      - quantum-espresso
  view: false
  compilers: []
  concretizer:
    unify: false
```
i.e. the comment is duplicated ~~and the result is no longer valid yaml~~.

Edit: after pasting the resulting yaml into a [linter](https://www.yamllint.com/), it appears the output is actually still valid yaml, but `spack` doesn't seem able to parse it (`spack install` will report `==> Error: not enough arguments for format string`).

I.e. I guess there are two issues here:
 - the duplication of the comment (and the addition of the blank line)
 - the fact that `spack install` is not able to parse the valid yaml above

#### Context
The list syntax
```
- 
  - a
  - b
```
makes it easy to comment out items (e.g. during debugging) and add comments above a specific item (e.g. to explain why particular variants were chosen, etc.), which is why I prefer it over the alternative compact syntax for the spec matrix.
```
- [a,b]
```

### Information on your system

# spack debug report
* **Spack:** 0.20.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
