### ISSUE TITLE
Generated `autoheader` might fail, since it is not using `sbang`

### ISSUE THREAD

**Issue by tpadioleau** [LLNL/spack#35458]
### Steps to reproduce the issue

Configure a `config.yaml` file with:
```yaml
config:
  # This is the path to the root of the Spack install tree.                                                                                                                         
  # You can use $spack here to refer to the root of the spack instance.                                                                                                             
  install_tree:
    root: $spack/opt/spack
    projections:
      all: "quite-a-long-name-${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}"
```
then run:
```console
$ spack install autoconf@2.69
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing autoconf-2.69-w5e7uunp6w2hprnmhvnwc4jojzlwn2ju
==> No binary for autoconf-2.69-w5e7uunp6w2hprnmhvnwc4jojzlwn2ju found: installing from source
==> Using cached archive: /home/TP026749/spack-0.19.0/var/spack/cache/_source-cache/archive/95/954bd69b391edc12d6a4a51a2dd1476543da5c6bbf05a95b59dc0dd6fd4c2969.tar.gz
==> Using cached archive: /home/TP026749/spack-0.19.0/var/spack/cache/_source-cache/archive/77/7793209b33013dc0f81208718c68440c5aae80e7a1c4b8d336e382525af791a7
==> Using cached archive: /home/TP026749/spack-0.19.0/var/spack/cache/_source-cache/archive/35/35c449281546376449766f92d49fc121ca50e330e60fefcfc9be2af3253082c2
==> Using cached archive: /home/TP026749/spack-0.19.0/var/spack/cache/_source-cache/archive/a4/a49dd5bac3b62daa0ff688ab4d508d71dbd2f4f8d7e2a02321926346161bf3ee
==> Applied patch http://mirrors.mit.edu/gentoo-portage/sys-devel/autoconf/files/autoconf-2.69-fix-libtool-test.patch
==> Applied patch http://mirrors.mit.edu/gentoo-portage/sys-devel/autoconf/files/autoconf-2.69-perl-5.26.patch
==> Applied patch http://mirrors.mit.edu/gentoo-portage/sys-devel/autoconf/files/autoconf-2.69-perl-5.26-2.patch
==> Ran patch() for autoconf
==> autoconf: Executing phase: 'autoreconf'
==> autoconf: Executing phase: 'configure'
==> autoconf: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'

4 errors found in build log:
     260        --source='GNU Autoconf 2.69' \
     261        --output=/tmp/TP026749/spack-stage/spack-stage-autoconf-2.69-w5e7uunp6w2hprnmhvnwc4jojzlwn2ju/spack-src/man/autoscan.1.t `echo '/tmp/TP026749/spack-stage/spack-sta
            ge-autoconf-2.69-w5e7uunp6w2hprnmhvnwc4jojzlwn2ju/spack-src/man/autoscan' | sed 's,.*/,,'`
     262    help2man: can't get `--help' info from autoheader
     263    Try `--no-discard-stderr' if option outputs to stderr
     264    help2man: can't get `--help' info from autoscan
     265    Try `--no-discard-stderr' if option outputs to stderr
  >> 266    make[2]: *** [/tmp/TP026749/spack-stage/spack-stage-autoconf-2.69-w5e7uunp6w2hprnmhvnwc4jojzlwn2ju/spack-src/man/autoheader.1] Error 1
     267    make[2]: *** Waiting for unfinished jobs....
  >> 268    make[2]: *** [/tmp/TP026749/spack-stage/spack-stage-autoconf-2.69-w5e7uunp6w2hprnmhvnwc4jojzlwn2ju/spack-src/man/autoscan.1] Error 1
     269    make[2]: Leaving directory `/tmp/TP026749/spack-stage/spack-stage-autoconf-2.69-w5e7uunp6w2hprnmhvnwc4jojzlwn2ju/spack-src/spack-build/man'
  >> 270    make[1]: *** [all-recursive] Error 1
     271    make[1]: Leaving directory `/tmp/TP026749/spack-stage/spack-stage-autoconf-2.69-w5e7uunp6w2hprnmhvnwc4jojzlwn2ju/spack-src/spack-build'
  >> 272    make: *** [all] Error 2
</pre></details>

### Information on your system

* **Spack:** 0.19.0
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/10722988/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10722984/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
