### ISSUE TITLE
gitlabCI fails to generate a pipeline when external cray-mpich/cray-libsci is used with Spack CI

### ISSUE THREAD

**Issue by lukebroskop** [LLNL/spack#35483]
I already communicated with @scottwittenburg over slack on this issue. 

I'm running a CI from ORNL's gitlab. I'm testing the Cray PE SW stack (%cce, ^cray-mpich, ^cray-libsci) and running on ORNL's crusher system. When cray-mpich/cray-libsci are included as externals in my spec, the pipeline generation step throws an error. (see the error output in the following link:

[generate_output.txt](https://github.com/spack/spack/files/10736143/generate_output.txt)

If I comment out the cray-libsci/cray-mpich externals then the pipeline is generated without issue.

The following are the .gitlab-ci.yml and the spack.yaml that I use and receive the pipeline generation error.

.gitlab-ci.yml
```
stages: [generate, build]

variables:
  SPACK_REPO: git@github.com:spack/spack.git

generate-pipeline:
  stage: generate
  before_script:
    - git clone ${SPACK_REPO}
    - . "./spack/share/spack/setup-env.sh"
  script:
    - spack env activate --without-view .
    - spack -d ci generate
      --artifacts-root "${CI_PROJECT_DIR}/jobs_scratch_dir"
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/jobs_scratch_dir"

build-jobs:
  stage: build
  trigger:
    include:
      - artifact: "jobs_scratch_dir/pipeline.yml"
        job: generate-pipeline
    strategy: depend
```

spack.yaml:
```
spack:
  view: false
  concretizer:
    unify: false

  config:
    install_tree:
      padded_length: 256

  definitions:
  - pkgs:
    - zlib
    - bzip2
    - amdblis@3.1
    - papi@6.0.0.1
    - fftw@3.3.10 ~openmp
    - fftw@3.3.10 +openmp
    - trilinos@13.0.1
    - amdblis@3.1
    - amdblis@3.1 threads=openmp
    - petsc@3.17.4 #^superlu-dist@6.4.0
    - netcdf-c@4.8.1
    - netcdf-cxx@4.2    
    - netcdf-cxx4@4.3.1
    - netcdf-fortran@4.5.4     
    - parallel-netcdf@1.12.2
    - hdf5@1.12.2
    - libflame@5.2.0
    - libflame@master threads=openmp

  - arch:
    - '%cce@15.0.0'

  specs:
  - matrix:
    - - $pkgs
    - - $arch
  compilers:
  - compiler:
      spec: cce@15.0.0
      paths:
        cc: craycc
        cxx: crayCC
        f77: crayftn
        fc: crayftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-cray
      - cce/15.0.0
      environment:
        prepend_path:
          LIBRARY_PATH: /opt/amdgpu/lib64/
      extra_rpaths: []
  - compiler:
      spec: gcc@10.3.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-gnu
      - gcc/10.3.0
      environment:
        append_path:
          PKG_CONFIG_PATH: /usr/lib64/pkgconfig


  packages:
    all:
      compiler: [cce@15.0.0]
      providers:
        mpi: [cray-mpich]
        blas: [cray-libsci]
        lapack: [cray-libsci]

    cray-mpich:
      buildable: false
      externals:
      - spec: cray-mpich@8.1.23
        prefix: /opt/cray/pe/mpich/8.1.23/ofi/crayclang/10.0

    cray-libsci:
      buildable: false
      externals:
      - spec: cray-libsci@22.12.1.1
        prefix: /opt/cray/pe/libsci/22.12.1.1/CRAY/9.0/x86_64


  mirrors:
    mirror: file:///gpfs/alpine/ven114/proj-shared/lukebr/myMirror

  gitlab-ci:
    before_script:
      - git clone ${SPACK_REPO}
      - . "./spack/share/spack/setup-env.sh"
    script:
      - pushd ${SPACK_CONCRETE_ENV_DIR} && spack env activate --without-view . && popd
      - spack clean -a
      - spack -d ci rebuild
    enable-artifacts-buildcache: True
    rebuild-index: False
    mappings:
      - match: ["os=sles15"]
        runner-attributes:
          tags:
            - crusher
```
