### ISSUE TITLE
Installation issue: libx11 fails at configure stage with `error: spack/lib/spack/env/cpp defines unix with or without -undef.  I don't know what to do.`

### ISSUE THREAD

**Issue by mladenivkovic** [LLNL/spack#36161]
### Steps to reproduce the issue

```console
$ $ spack spec -I libx11@1.7.0 %gcc@12.1.0
Input spec
--------------------------------
 -   libx11@1.7.0%gcc@12.1.0

Concretized
--------------------------------
 -   libx11@1.7.0%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^inputproto@2.3.2%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^kbproto@1.0.7%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^libxcb@1.14%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]          ^libpthread-stubs@0.4%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]          ^libxau@1.0.8%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]          ^libxdmcp@1.1.2%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^libbsd@0.11.7%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]                  ^libmd@1.0.4%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]          ^xcb-proto@1.14.1%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^perl@5.36.0%gcc@12.1.0+cpanm+open+shared+threads build_system=generic arch=linux-ubuntu22.04-skylake
[+]          ^berkeley-db@18.1.40%gcc@12.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-skylake
[+]          ^bzip2@1.0.8%gcc@12.1.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-skylake
[+]              ^diffutils@3.8%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]                  ^libiconv@1.17%gcc@12.1.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-skylake
[+]          ^gdbm@1.23%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^readline@8.2%gcc@12.1.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-skylake
[+]                  ^ncurses@6.4%gcc@12.1.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu22.04-skylake
[+]          ^zlib@1.2.13%gcc@12.1.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu22.04-skylake
[+]      ^pkgconf@1.8.0%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^util-macros@1.19.3%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^xextproto@7.3.0%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^xproto@7.0.31%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^xtrans@1.3.5%gcc@12.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake

...
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: ProcessError: Command exited with status 1:
    '/tmp/mivkov/spack-stage/spack-stage-libx11-1.7.0-m67dhw4zpdelmecnl5z5qfpbehxtclk6/spack-src/configure' '--prefix=/home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/oneapi-2022.2.1/libx11-1.7.0-m67dhw4zpdelmecnl5z5qfpbehxtclk6'

1 error found in build log:
     137    checking if /home/mivkov/local/spack/lib/spack/env/cpp requires -undef... cpp: fatal error: no input files
     138    compilation terminated.
     139    cpp: fatal error: no input files
     140    compilation terminated.
     141    cpp: fatal error: no input files
     142    compilation terminated.
  >> 143    configure: error: /home/mivkov/local/spack/lib/spack/env/cpp defines unix with or without -undef.  I don't know what to do.

</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.19.1 (14d1fa7c559fee5332e4aee4398b75daaff33466)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

modules.yaml
------------------------------

```
modules:
  prefix_inspections:
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH

  default:
    enable:
    - lmod
    lmod:
      hash_length: 0
      hierarchy:
      - 'mpi'
      core_compilers:
      - gcc@12.1.0
      all:
        environment:
          set:
            '{name}_ROOT': '{prefix}'
      grackle:
        suffixes:
          ^hdf5@1.12.2: 'hdf5@1.12.2'
          ^hdf5@1.13.1: 'hdf5@1.13.1'
      grackle-float:
        suffixes:
          ^hdf5@1.12.2: 'hdf5@1.12.2'
      blacklist:
      - ant
      - autoconf
      - autoconf-archive
      - automake
      - berkeley-db
      - binutils
      - bison
      - boost
      - bzip2
      - cmake
      - curl
      - diffutils
      - double-conversion
      - eigen
      - expat
      - findutils
      - flex
      - freetype
      - gdbm
      - gettext
      - git
      - glproto
      - gnutls
      - gmp
      - hwloc
      - help2man
      - inputproto
      - isl
      - jsoncpp
      - kbproto
      - libaec
      - libarchive
      - libbsd
      - libedit
      - libevent
      - libfabric
      - libffi
      - libidn2
      - libice
      - libiconv
      - libjpeg-turbo
      - libmd
      - libogg
      - libpciaccess
      - libpng
      - libpthread-stubs
      - libsigsegv
      - libsm
      - libszip
      - libtheora
      - libtool
      - libunwind
      - libuv
      - libxau
      - libxcb
      - libxdmcp
      - libxml2
      - libunistring
      - lmod
      - lua-luafilesystem
      - lua-luaposix
      - lua
      - lz4
      - lzo
      - m4
      - mbedtls
      - meson
      - mpc
      - mpfr
      - nasm
      - ncurses
      - nettle
      - ninja
      - openjdk
      - openssl
      - openssh
      - patchelf
      - pcre
      - pcre2
      - perl
      - perl-data-dumper
      - pigz
      - pkgconf
      - pmix
      - proj
      - python
      - py-mako
      - py-markupsafe
      - py-pip
      - py-setuptools
      - py-wheel
      - randrproto
      - readline
      - re2c
      - renderproto
      - rhash
      - sqlite
      - tar
      - tcl
      - texinfo
      - unzip
      - util-linux-uuid
      - util-macros
      - xcb-proto
      - xextproto
      - xproto
      - xtrans
      - xz
      - yaksa
      - zlib
      - zstd
```

packages.yaml
----------------------------

```
packages:
  gettext:
    externals:
    - spec: gettext@0.21
      prefix: /usr
    buildable: false 
  all:
    compiler: [gcc@12.1.0]
    providers:
      mpi: [openmpi, mpich]
  fftw:
    variants: ~mpi
  git:
    externals:
    - spec: git@2.34.1
    buildable: false
  hdf5:
    variants: +cxx+fortran+hl+szip+threadsafe
  openmpi:
    variants: +thread_multiple+debug
  openssl:
    externals:
    - spec: openssl@3.0.2
      prefix: /usr
    buildable: false
  python:
    externals:
    - spec: python@3.10.6
      prefix: /usr
    buildable: false
  vtk:
    variants: -mpi
  automake:
    externals: 
      - spec: automake@1.16.5
        prefix: /usr
    buildable: false
  autoconf:
    externals: 
      - spec: autoconf@2.71
        prefix: /usr
    buildable: false
  cmake:
    externals:
      - spec: cmake@3.23.1
        prefix: /usr
    buildable: false
  libtool:
    externals:
      - spec: libtool@2.4.6
        prefix: /usr
    buildable: false
  m4:
    externals:
      - spec: m4@1.4.18
        prefix: /usr
    buildable: false
  llvm:
    externals:
      - spec: llvm@14.0.0
        prefix: /usr
        buildable: false

```

compilers.yaml
-----------------------

```
compilers:
- compiler:
    spec: clang@14.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.3.0
    paths:
      cc: /usr/bin/gcc-11
      cpp: /usr/bin/cpp-11
      cxx: /usr/bin/g++-11
      f77: /usr/bin/gfortran-11
      fc: /usr/bin/gfortran-11
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: /usr/bin/gcc-12
      cpp: /usr/bin/cpp-12
      cxx: /usr/bin/g++-12
      f77: /usr/bin/gfortran-12
      fc: /usr/bin/gfortran-12
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@2022.2.1
    paths:
      cc: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/icx
      cxx: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/dpcpp
      f77: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/ifx
      fc: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.7.1
    paths:
      cc: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/intel64/icc
      cxx: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/intel64/icpc
      f77: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/intel64/ifort
      fc: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/intel64/ifort
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2022.2.1
    paths:
      cc: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/icx
      cxx: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/icpx
      f77: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/ifx
      fc: /home/mivkov/local/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/intel-oneapi-compilers-2022.2.1-malnhriz2vh3cbo6rk2mvncapu4kunwp/compiler/2022.2.1/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Additional information

[spack-configure-args.txt](https://github.com/spack/spack/files/10990844/spack-configure-args.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10990846/spack-build-out.txt)
[spack-build-env-mods.txt](https://github.com/spack/spack/files/10990847/spack-build-env-mods.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10990848/spack-build-env.txt)
[spack-build-02-configure-out.txt](https://github.com/spack/spack/files/10990849/spack-build-02-configure-out.txt)
[spack-build-01-autoreconf-out.txt](https://github.com/spack/spack/files/10990850/spack-build-01-autoreconf-out.txt)

Additional Info
--------------------------

- This occurs when letting spack install autotools itself, as well as when I'm using my system's autotools (as is currently set up in my `packages.yaml` file)
-  Happens as well when I try compiling using the `intel-oneapi-compilers/2022.2.1` compiler suite instead of my system's gcc@12.1.0

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
