### ISSUE TITLE
spack command to test for existing compilers

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#36276]
@tgamblin @becker33 @jfinney10 @koysean @eugeneswalker 

### Summary

This feature is somewhat motivated by https://github.com/spack/spack/issues/36275, where we check for package externals. It would be nice to have a command let's say `spack compiler [test|check|verify]` that can be used to validate existing compilers and report issues for any malformed compilers.

Currently, spack has a good way to find compilers using `spack compiler find` along with removing compilers via `spack compiler remove` but no way of testing the compiler. This command would align well with removal of compilers if any are broken.

 

### Rationale

Shown below is an example compiler definition on Perlmutter for nvhpc compiler.

```yaml
compilers:
  - compiler:
      spec: nvhpc@21.11
      paths:
        cc: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/bin/nvc
        cxx: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/bin/nvc++
        f77: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/bin/nvfortran
        fc: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/bin/nvfortran
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-nvhpc
      - nvhpc/21.11
      - craype-x86-milan
      - libfabric
  - compiler:
      spec: nvhpc@22.5
      paths:
        cc: /opt/nvidia/hpc_sdk/Linux_x86_64/22.5/compilers/bin/nvc
        cxx: /opt/nvidia/hpc_sdk/Linux_x86_64/22.5/compilers/bin/nvc++
        f77: /opt/nvidia/hpc_sdk/Linux_x86_64/22.5/compilers/bin/nvfortran
        fc: /opt/nvidia/hpc_sdk/Linux_x86_64/22.5/compilers/bin/nvfortran
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-nvhpc
      - nvhpc/22.5
      - craype-x86-milan
      - libfabric
```

What i'd like to see is spack test path to `cc`, `cxx`, `f77`, `fc` and `modules` to make sure these are valid paths. We can go further and make sure these binaries actually are the compiler wrapper, which can be bit hard. May need to do `nvc --version` or something and grep for some output. For simplicity, we can just check if the file-path exist.

The output should be something like

```
spack compiler test
nvhpc@21.11 - FAIL
Unable to find path C wrapper /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/compilers/bin/nvc
nvhpc@22.5 - PASS
```

The command should return a non-zero returncode if any compilers failed, otherwise return zero.

It would be nice to also test the list of modules so if spack is unable to load the modules you should get an error.

```
spack compiler test
nvhpc@21.11 - FAIL
Unable to load modules - 'module load PrgEnv-nvhpc && module load 22.5 && module load craype-x86-milan && module load libfabric' 
```

Alternatively you can use `module try-load` instead of `module load` since it will return a zero/non-zero returncode without actually loading the module.

This is possible with [Lmodule](https://lmodule.readthedocs.io/en/latest/) python api but if spack has something built-in for testing modules it would be nice. The list of modules must be tested.

### Description

This feature can be extremely useful for facility during spack deployments. For instance at NERSC we use Gitlab CI using `spack ci` to perform our E4S deployment.

We would like to run `spack compiler test` as part of the pre spack sanity check before initiating the `spack ci` job. This type of check can be done in advance to help fix configuration issues. We don't need spack to fix them but just report the error messages.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
