### ISSUE TITLE
Spack command to verify all spack externals 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#36275]
@koysean @jfinney10 @mpbelhorn @eugeneswalker @tgamblin @becker33 @etpalmer63

### Summary

It would be nice to have a spack command that can verify spack externals and report an output of each spec with a `PASS` or `FAIL` to help facility detect errors during package configuration.

We would a new command perhaps `spack external [check|verify|validate]` that can be used to validate all externals.

### Rationale

Yes it is related to a problem we have. Currently, we have to update our package preference as system changes and this is very time-consuming process. 

For instance, shown below is our package preference for `cray-libsci` and `cray-mpich`.

```yaml
  cray-libsci:
    buildable: false
    version: [22.11.1.2]
    externals:
    - spec: cray-libsci@22.11.1.2 %gcc
      modules: [cray-libsci]
      prefix: /opt/cray/pe/libsci/default/GNU/9.1/x86_64
    - spec: cray-libsci@22.11.1.2 %nvhpc
      modules: [cray-libsci]
      prefix: /opt/cray/pe/libsci/default/NVIDIA/20.7/x86_64
    - spec: cray-libsci@22.11.1.2 %cce
      modules: [cray-libsci]
      prefix: /opt/cray/pe/libsci/default/CRAY/9.0/x86_64
  cray-mpich:
    buildable: false
    version: [8.1.22]
    externals:
    - spec: cray-mpich@8.1.22 %gcc@11.2.0
      prefix: /opt/cray/pe/mpich/default/ofi/gnu/9.1
      modules: [cray-mpich, cudatoolkit/11.5]
    - spec: cray-mpich@8.1.22 %nvhpc@22.5
      prefix: /opt/cray/pe/mpich/default/ofi/nvidia/20.7
      modules: [cray-mpich, cudatoolkit/11.5]
    - spec: cray-mpich@8.1.22 %cce@15.0.0
      prefix: /opt/cray/pe/mpich/default/ofi/cray/10.0/
      modules: [cray-mpich, cudatoolkit/11.5]
```

What i'd like for spack to do is test every spec that contains an `externals` keyword and check if `prefix` and `modules` can be tested for every spec. If any one fails the spec will fail. 

The output can be simple as 

```
spack external check
cray-libsci - PASS
cray-mpich - FAIL
/opt/cray/pe/mpich/default/ofi/gnu/9.1 is not a valid file path
```

If spack has way to test modules that would be great, an alternative is use [Lmodule](https://lmodule.readthedocs.io/en/latest/) python api for testing the modules. Basically we should have a spec failure if we see the following

```
spack external check 
cray-libsci - PASS
cray-mpich - FAIL
Unable to load modules - 'module load cray-mpich && module load cudatoolkit/11.5'
```

The command should run to completion and test all externals.

If no externals are declared in the package preference, the returncode can be a 0 with a message.

### Description

Since there is no spack command to verify externals we wrote our own script https://github.com/NERSC/spack-infrastructure/blob/main/check_spack_dependencies.sh to verify spack externals. We have this job is run in Gitlab

```
perlmutter:check_spack_dependencies:
  stage: check
  tags: [perlmutter-e4s]
  allow_failure: false
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule")
  when: always
  script:
    - export
    - bash check_spack_dependencies.sh
``` 

Then this job is dependent upon all of our spack builds using `needs`. Basically we want a built-in spack command that can show all this information and return a non-zero exit code when it fails. This would be very useful

```
perlmutter-e4s-22.11-gcc-generate:
  stage: generate
  needs: ["perlmutter:check_spack_dependencies"]
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate
