### ISSUE TITLE
Installing providers is broken

### ISSUE THREAD

**Issue by michaelkuhn** [LLNL/spack#3638]
I have set up `packages.yaml` like this:
```
packages:
  all:
    providers:
      mpi: [mvapich2]
```

Doing `spack install mpi` installs mvapich2 but for some reason no dependencies are installed first. If I do `spack install mvapich2`, everything works correctly.
