### ISSUE TITLE
Cray compilers detected with `compiler:target:any` not working

### ISSUE THREAD

**Issue by albestro** [LLNL/spack#36628]
### Steps to reproduce

On a Cray system, using a simple environment just for "scoping" the configuration (see `::` for `compilers` section)

```yaml
spack:
  # add package specs to the `specs` list
  specs: []
  view: true
  concretizer:
    unify: true
  compilers::
  - compiler:
      spec: gcc@11.2.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: cnl7
      target: any
      modules:
      - PrgEnv-gnu
      - gcc/11.2.0
      environment: {}
      extra_rpaths: []
```

```console
$ spack -e . config get compilers
compilers:
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.2.0
    environment: {}
    extra_rpaths: []
```

Trying to concretise a simple package

```console
$ spack -e . spec zlib
```

### Error message

```console
$ spack -e . spec zlib
==> Error: concretization failed for the following reasons:

   1. zlib compiler 'gcc@11.2.0' incompatible with 'target=x86_64'
```

### Information on your system

* **Spack:** 0.20.0.dev0 (712b30c9c5883b7682954fcc18d7b2ef35411a8e)
* **Python:** 3.6.15
* **Platform:** cray-sles15-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
