### ISSUE TITLE
Configuring ld in compilers config (-fuse-ld=lld)

### ISSUE THREAD

**Issue by DaveWK** [LLNL/spack#36948]
### Summary

It would be nice to be able to specify the linker inside the compiler config as either a flag or by specifying the `ld` 

### Rationale

For a concrete example, I noticed when I am using the AOCC compiler that it still is using the gnu linker -- when trying to debug an orthogonal issue when installing protobuf-c I noticed references to `/usr/bin/ld` IE:

```
checking if the linker (/usr/bin/ld) is GNU ld... yes
```
While I would have expected the aocc package to use it's included lld, it would be probably a less risky change and more practical to just allow this to be overridden in the config to avoid any breaking changes to the default config for the package.

### Description

For example with AOCC, in the compiler  (using an external ref installed in the default path by rpm) config I would've expected to be able to set either:
```
compilers:
- compiler:
    spec: aocc@4.0.0
    paths:
      cc: /opt/AMD/aocc-compiler-4.0.0/bin/clang
      cxx: /opt/AMD/aocc-compiler-4.0.0/bin/clang++
      f77: /opt/AMD/aocc-compiler-4.0.0/bin/flang
      fc: /opt/AMD/aocc-compiler-4.0.0/bin/flang
      ld: /opt/AMD/aocc-compiler-4.0.0/bin/ld.lld

```
or:
```
- compiler:
    spec: aocc@4.0.0
    paths:
...
    flags:
      cflags: null
      cxxflags: null
      fflags: null
      use-ld: lld
```

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
