### ISSUE TITLE
Git: Cannot generate configure: missing dependencies ['m4', 'autoconf', 'automake', 'libtool']

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#3790]
Hi,

I am trying to build git, but it fails with the following error message about missing dependencies:

```
==> Building git [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Error: RuntimeError: Cannot generate configure: missing dependencies ['m4', 'autoconf', 'automake', 'libtool']
/local/cluster/spack/lib/spack/spack/build_systems/autotools.py:208, in autoreconf:
     198      def autoreconf(self, spec, prefix):
     199          """Not needed usually, configure should be already there"""
     200          # If configure exists nothing needs to be done
     201          if os.path.exists(self.configure_abs_path):
     202              return
     203          # Else try to regenerate it
     204          autotools = ['m4', 'autoconf', 'automake', 'libtool']
     205          missing = [x for x in autotools if x not in spec]
     206          if missing:
     207              msg = 'Cannot generate configure: missing dependencies {0}'
  >> 208              raise RuntimeError(msg.format(missing))
     209          tty.msg('Configure script not found: trying to generate it')
     210          tty.warn('*********************************************************')
     211          tty.warn('* If the default procedure fails, consider implementing *')
     212          tty.warn('*        a custom AUTORECONF phase in the package       *')
     213          tty.warn('*********************************************************')
     214          with working_dir(self.configure_directory):
     215              m = inspect.getmodule(self)
     216              # This part should be redundant in principle, but
     217              # won't hurt
     218              m.libtoolize()
     219              m.aclocal()
     220              # This line is what is needed most of the time
     221              # --install, --verbose, --force
     222              autoreconf_args = ['-ivf']
     223              if 'pkg-config' in spec:
     224                  autoreconf_args += [
     225                      '-I',
     226                      join_path(spec['pkg-config'].prefix, 'share', 'aclocal'),
     227                  ]
     228              autoreconf_args += self.autoreconf_extra_args
     229              m.autoreconf(*autoreconf_args)
```
The dependencies are there:

```
[sfux@develop02 ~]$ spack find autoconf automake libtool m4
==> 4 installed packages.
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
autoconf@2.69  automake@1.15  libtool@2.4.6  m4@1.4.18
[sfux@develop02 ~]$
```

and I have added the path to the "bin" dir to the PATH variable:
```

[sfux@develop02 ~]$ which autoreconf
/local/cluster/spack/tools/autoreconf
[sfux@develop02 ~]$ which libtool
/local/cluster/spack/tools/libtool
[sfux@develop02 ~]$ which automake
/local/cluster/spack/tools/automake
[sfux@develop02 ~]$ which m4
/local/cluster/spack/tools/m4
[sfux@develop02 ~]$
```
I get similar error messages for the packages

- glib
- fonttosfnt

Any idea what is going wrong ?

Thank you for your help and best regards

**Comment by adamjstewart** [comment]
Those packages need to be added as dependencies of git and fonttosfont. This is needed any time the download does not come with a configure script. I'm surprised no one has run into this problem before.

**Comment by samfux84** [comment]
@adamjstewart:

It seems that they are listed in the spec:

```
    depends_on('autoconf', type='build')
    depends_on('automake', type='build')
    depends_on('libtool',  type='build')
    depends_on('m4',       type='build')
```

spack info git also shows the dependencies:

```
[sfux@develop02 tools]$ spack info git
AutotoolsPackage:    git
Homepage:            http://git-scm.com

Safe versions:  
    2.12.1    https://github.com/git/git/archive/v2.12.1.tar.gz
    2.12.0    https://github.com/git/git/archive/v2.12.0.tar.gz
    2.11.1    https://github.com/git/git/archive/v2.11.1.tar.gz
    2.11.0    https://github.com/git/git/archive/v2.11.0.tar.gz
    2.9.3     https://github.com/git/git/archive/v2.9.3.tar.gz
    2.9.2     https://github.com/git/git/archive/v2.9.2.tar.gz
    2.9.1     https://github.com/git/git/archive/v2.9.1.tar.gz
    2.9.0     https://github.com/git/git/archive/v2.9.0.tar.gz
    2.8.4     https://github.com/git/git/archive/v2.8.4.tar.gz
    2.8.3     https://github.com/git/git/archive/v2.8.3.tar.gz
    2.8.2     https://github.com/git/git/archive/v2.8.2.tar.gz
    2.8.1     https://github.com/git/git/archive/v2.8.1.tar.gz
    2.8.0     https://github.com/git/git/archive/v2.8.0.tar.gz
    2.7.3     https://github.com/git/git/archive/v2.7.3.tar.gz
    2.7.1     https://github.com/git/git/archive/v2.7.1.tar.gz

Variants:
    None

Installation Phases:
    autoreconf    configure    build    install

Build Dependencies:
    autoconf  automake  curl  expat  gettext  libiconv  libtool  m4  openssl  pcre  perl  zlib

Link Dependencies:
    curl  expat  gettext  libiconv  openssl  pcre  perl  zlib

Run Dependencies:
    None

Virtual Packages: 
    None

Description:
    Git is a free and open source distributed version control system
    designed to handle everything from small to very large projects with
    speed and efficiency.

[sfux@develop02 tools]$
```

**Comment by adamjstewart** [comment]
Are these externally installed packages? Are you using an alternate installation directory or something like `spack view`?

**Comment by samfux84** [comment]
The only external package that I am using is openssl. All other packages have been installed with spack:

```
[sfux@develop02 tools]$ spack find
==> 80 installed packages.
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
autoconf@2.69   expat@2.2.0           gmp@6.1.2            libdrm@2.4.70      libpciaccess@0.13.4   libxdmcp@1.1.2       ncurses@6.0        tcl@8.6.6
automake@1.15   flex@2.6.3            gperf@3.0.4          libelf@0.8.13      libpng@1.6.27         libxml2@2.9.4        patch@2.7.5        unzip@6.0
bash@4.4        font-util@1.3.1       gperftools@2.4       libffi@3.2.1       libpthread-stubs@0.3  lua@5.3.2            patchelf@0.9       util-macros@1.19.1
bdw-gc@7.4.4    fontcacheproto@0.1.3  guile@2.0.11         libfontenc@1.1.3   libsigsegv@2.11       lua-luaposix@33.4.0  pcre@8.40          wget@1.17
binutils@2.28   fontconfig@2.11.1     help2man@1.47.4      libfs@1.0.7        libsm@1.2.2           lz4@1.7.5            perl@5.24.1        xextproto@7.3.0
bison@3.0.4     fontsproto@2.1.3      inputproto@2.3.2     libgcrypt@1.6.2    libtiff@4.0.6         lzma@4.32.7          pkg-config@0.29.2  xproto@7.0.29
bzip2@1.0.6     freetype@2.7          jpeg@9b              libgpg-error@1.21  libtool@2.4.6         m4@1.4.18            python@2.7.13      xtrans@1.3.5
coreutils@8.26  gawk@4.1.4            kbproto@1.0.7        libice@1.0.9       libunistring@0.9.7    mawk@1.3.4           readline@7.0       xz@5.2.3
curl@7.53.1     gettext@0.19.8.1      libatomic-ops@7.4.4  libiconv@1.15      libunwind@1.1         mpfr@3.1.5           sqlite@3.8.5       yasm@1.3.0
dbus@1.11.2     gmake@4.0             libctl@3.2.2         libogg@1.3.2       libxau@1.0.8          nasm@2.11.06         tar@1.29           zlib@1.2.11
[sfux@develop02 tools]$
```
I am using the development branch (last "git pull" was about 6 hours ago) with PR's: 2548, 2972, 3735. I am using an alternate installation directory, which is specified in $HOME/.spack/linux/config.yaml:

```
[sfux@develop02 tools]$ cat $HOME/.spack/linux/config.yaml 
# -------------------------------------------------------------------------
# This is the default spack configuration file.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/config.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/config.yaml
# -------------------------------------------------------------------------
config:
  # This is the path to the root of the Spack install tree.
  # You can use $spack here to refer to the root of the spack instance.
  install_tree: $spack/apps


  # Locations where different types of modules should be installed.
  module_roots:
    lmod:   $spack/modules


  # Temporary locations Spack can try to use for builds.
  #
  # Spack will use the first one it finds that exists and is writable.
  # You can use $tempdir to refer to the system default temp directory
  # (as returned by tempfile.gettempdir()).
  #
  # A value of $spack/var/spack/stage indicates that Spack should run
  # builds directly inside its install directory without staging them in
  # temporary space.
  #
  # The build stage can be purged with `spack purge --stage`.
  build_stage:
    - /local/scratch
    - /nfs/tmp2/$user
    - $spack/var/spack/stage


  # Cache directory already downloaded source tarballs and archived
  # repositories. This can be purged with `spack purge --downloads`.
  source_cache: $spack/var/spack/cache


  # Cache directory for miscellaneous files, like the package index.
  # This can be purged with `spack purge --misc-cache`
  misc_cache: ~/.spack/cache


  # If this is false, tools like curl that use SSL will not verify
  # certifiates. (e.g., curl will use use the -k option)
  verify_ssl: true


  # If set to true, Spack will always check checksums after downloading
  # archives. If false, Spack skips the checksum step.
  checksum: true


  # If set to true, `spack install` and friends will NOT clean
  # potentially harmful variables from the build environment. Use wisely.
  dirty: false
[sfux@develop02 tools]$
```
