### ISSUE TITLE
Spack, Cray, mpich and link error

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#3816]
I am trying to build one of the package which looks like : 

```
spack spec neuron %intel -python +mpi +cross-compile ^mpich
.............
Concretised
--------------------------------
neuron@develop%intel@15.0.3.187+cross-compile+mpi~profile~python+static arch=cray-CNL-haswell
    ^autoconf@system%intel@15.0.3.187 arch=cray-CNL-haswell
    ^automake@system%intel@15.0.3.187 arch=cray-CNL-haswell
    ^libtool@system%intel@15.0.3.187 arch=cray-CNL-haswell
    ^mpich@7.5.0%intel@15.0.3.187+hydra+pmi+romio~verbs arch=cray-CNL-haswell
    ^pkg-config@0.28%intel@15.0.3.187+internal_glib arch=cray-CNL-haswell
```

I have setup `packages.yaml` and `compilers.yaml` correctly : 
```

# in packages.yaml
    mpich:
        modules:
            mpich@7.5.0%intel@15.0.3.187+hydra+pmi+romio~verbs arch=cray-CNL-haswell: cray-mpich/7.5.0
        version: [7.5.0]
        buildable: False

# in compilers.yaml
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - !!python/unicode 'intel/15.0.3.187'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@15.0.3.187
    target: any
```

While building the package I get link error : 
```
libtool: link: /users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/icc -O2 -o oc ocmain.o ocnoiv.o nocable.o modlreg.o ockludge.o  ./.libs/libocxt.a ./.libs/liboc.a ../nrnmpi/.libs/libnrnmpi.a -lm -ldl
../nrnmpi/.libs/libnrnmpi.a(nrnmpi.o): In function `nrnmpi_init':
nrnmpi.c:(.text+0x9b): undefined reference to `MPI_Initialized'
nrnmpi.c:(.text+0xb8): undefined reference to `MPI_Init_thread'
```

I see the mpi library linking error. But as we are using cray wrappers via `spack/env/intel/icc` I don't understand how this could end with link error.  I am checking at `spack-build.env` and see that variables are properly set : 
```
..........
CRAY_MPICH2_DIR=/opt/cray/pe/mpt/7.5.0/gni/mpich-intel/16.0
CRAY_MPICH2_VER=7.5.0
CRAY_MPICH_BASEDIR=/opt/cray/pe/mpt/7.5.0/gni
CRAY_MPICH_DIR=/opt/cray/pe/mpt/7.5.0/gni/mpich-intel/16.0
CRAY_MPICH_ROOTDIR=/opt/cray/pe/mpt/7.5.0
CRAY_PMI_INCLUDE_OPTS=-I/opt/cray/pe/pmi/5.0.10-1.0000.11050.0.0.ari/include
CRAY_PMI_POST_LINK_OPTS=-L/opt/cray/pe/pmi/5.0.10-1.0000.11050.0.0.ari/lib64
.................
MPICC=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/icc
MPICH_ABORT_ON_ERROR=1
MPICH_CC=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/icc
MPICH_CXX=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/icpc
MPICH_DIR=/opt/cray/pe/mpt/7.5.0/gni/mpich-intel/16.0
MPICH_F77=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/ifort
MPICH_F90=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/ifort
MPICH_FC=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/ifort
MPICXX=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/icpc
MPIF77=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/ifort
MPIF90=/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/env/intel/ifort
```
I am looking at this for an hour and don't have clue. This is on Cray XC50 Daint @ CSCS. Any suggestions?

**Comment by KineticTheory** [comment]
I don't see anything obviously wrong with your setup.  Maybe there is something wrong with the recipe for neuron .  As a sanity check, I review my settings for Trinity (Cray XC40) below (maybe you can see something useful in my settings).  In `compilers.yaml`, I have

```                                                                                 
- compiler:                                                                                        
    environment: {}                                                                                
    extra_rpaths: []                                                                               
    flags: {}                                                                                      
    modules:                                                                                       
    - PrgEnv-intel                                                                                 
    - intel/17.0.1                                                                                 
    operating_system: CNL                                                                          
    paths:                                                                                         
      cc: cc                                                                                       
      cxx: CC                                                                                      
      f77: ftn                                                                                     
      fc: ftn                                                                                      
    spec: intel@17.0.1                                                                             
    target: any
```

I setup cray-mpich in `package.yaml` as

```
packages:                                                                         
  mpich:                                                                                           
    modules:                                                                                       
      mpich@7.5.2%intel@17.0.1 arch=cray-CNL-haswell: cray-mpich/7.5.2                             
      mpich@7.4.2%intel@17.0.1 arch=cray-CNL-haswell: cray-mpich/7.4.2                             
    buildable: False                                                                               
  all:                                                                                             
    compiler: [intel@17.0.1, gcc]                                                                  
    providers:                                                                                     
      mpi: [mpich@7.5.2]  
```

and if I look at the build.out file for trilinos, I see an equivalent environment:

```                                                         
CRAY_MPICH2_DIR=/opt/cray/pe/mpt/7.5.2/gni/mpich-intel/16.0                                        
CRAY_MPICH2_VER=7.5.2                                                                              
CRAY_MPICH_BASEDIR=/opt/cray/pe/mpt/7.5.2/gni                                                      
CRAY_MPICH_DIR=/opt/cray/pe/mpt/7.5.2/gni/mpich-intel/16.0                                         
CRAY_MPICH_ROOTDIR=/opt/cray/pe/mpt/7.5.2                                                          
CRAY_PMI_INCLUDE_OPTS=-I/opt/cray/pe/pmi/5.0.11/include                                            
CRAY_PMI_POST_LINK_OPTS=-L/opt/cray/pe/pmi/5.0.11/lib64  
...........................                                                                                        
MPICC=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/icc                        
MPICH_ABORT_ON_ERROR=1                                                                             
MPICH_CC=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/icc                     
MPICH_CXX=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/icpc                   
MPICH_DIR=/opt/cray/pe/mpt/7.5.2/gni/mpich-intel/16.0                                              
MPICH_F77=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/ifort                  
MPICH_F90=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/ifort                  
MPICH_FC=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/ifort                   
MPICXX=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/icpc                      
MPIF77=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/ifort                     
MPIF90=/usr/projects/draco/vendors/spack.tt.20170322/lib/spack/env/intel/ifort 
```
