### ISSUE TITLE
Unable to set PACKAGE_ROOT in module files

### ISSUE THREAD

**Issue by huntercih** [LLNL/spack#38278]
### Steps to reproduce

There seems to be an issue with exporting package roots in the `lmod` files  after I pulled the latest version of the `spack`.
I get **$<SPACK.PKG.BUILTIN._PACKAGE_._PACKAGE_ OBJECT AT 0X7FD920D5C8B0>_ROOT** instead of **PACKAGE_ROOT** in the generated module file and causing me headaches in my configurations.
 Everything works if I manually fix the package names or the `modules.yaml` file by removing lines about `${PACKAGE}_ROOT`. I would like to have the ability of exporting the package root into my environment so that I can do further configuration updates on my end.

**Spack version:** 
```console
$ git last
commit a0ba3d890ade82e74411d0bd93a67b264584834b (HEAD -> develop, origin/develop, origin/HEAD)
Author: Alec Scott <hi@alecbcs.com>
Date:   Thu Jun 8 01:27:20 2023 -0700

    cni-plugins: add v1.3.0 (#38064)
```

**Modules config:** 
```yaml
modules:
  prefix_inspections:
    bin:
    - PATH
    man:
    - MANPATH
    share/man:
    - MANPATH
    share/aclocal:
    - ACLOCAL_PATH
    include:: []
    lib:
    - LIBRARY_PATH
    lib64:
    - LIBRARY_PATH
    lib/pkgconfig:
    - PKG_CONFIG_PATH
    lib64/pkgconfig:
    - PKG_CONFIG_PATH
    share/pkgconfig:
    - PKG_CONFIG_PATH
    '':
    - CMAKE_PREFIX_PATH
    - '${PACKAGE}_ROOT'
  default:
    enable:
      - lmod
    # Where to install modules
    roots:
     lmod:   $spack/share/spack/lmod
    lmod:
      #blacklist_implicits: true
      core_compilers:
        - 'apple-clang@14.0.0'
      hash_length: 4
      hierarchy:: []
      ^python:
        autoload:  'direct'
      all:
        suffixes:
          '^python@2': py2
          '+cuda': 'cuda'
          '+debug': debug
          '+mpi': mpi
          '+multithreaded': mt
          '+openmp': mt
          '+threads': mt
          '~shared': 'static'
          'cxxstd=98': 'c++98'
          'cxxstd=14': 'c++14'
          'cxxstd=17': 'c++17'
        filter:
          environment_blacklist: ['CPATH', 'LIBRARY_PATH', 'DYLD_LIBRARY_PATH']
        environment:
          set:
            '${PACKAGE}_ROOT': '${PREFIX}'
```

**Generated module file:** 
```lua
prepend_path("PATH", "/usr/local/Cellar/cmake/3.26.4/bin", ":")
prepend_path("ACLOCAL_PATH", "/usr/local/Cellar/cmake/3.26.4/share/aclocal", ":")
prepend_path("CMAKE_PREFIX_PATH", "/usr/local/Cellar/cmake/3.26.4/.", ":")
prepend_path("$<SPACK.PKG.BUILTIN.CMAKE.CMAKE OBJECT AT 0X7FD920D5C8B0>_ROOT", "/usr/local/Cellar/cmake/3.26.4/.", ":")
prepend_path("PATH", "/usr/local/Cellar/cmake/3.26.4/bin", ":")
prepend_path("ACLOCAL_PATH", "/usr/local/Cellar/cmake/3.26.4/share/aclocal", ":")
prepend_path("CMAKE_PREFIX_PATH", "/usr/local/Cellar/cmake/3.26.4/.", ":")
setenv("$<SPACK.PKG.BUILTIN.CMAKE.CMAKE OBJECT AT 0X7FD920D5C8B0>_ROOT", "$/usr/local/Cellar/cmake/3.26.4")
```

### Error message

```console
 $ module load cmake
Lmod has detected the following error:  setenv names must be start with a letter or underscore followed letters, numbers and
underscores (Not: "$<SPACK.PKG.BUILTIN.CMAKE.CMAKE OBJECT AT 0X7FE4103E03D0>_ROOT")

While processing the following module(s):
    Module fullname    Module Filename
    ---------------    ---------------
    cmake/3.26.4-ez66  ${SPACK}/spack/share/spack/lmod/darwin-ventura-x86_64/Core/cmake/3.26.4-ez66.lua
```

### Information on your system

* **Spack:** 0.21.0.dev0 (a0ba3d890ade82e74411d0bd93a67b264584834b)
* **Python:** 3.10.8
* **Platform:** darwin-ventura-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
