### ISSUE TITLE
Invalid yaml syntax in documentation

### ISSUE THREAD

**Issue by olemorud** [LLNL/spack#38408]
### Steps to reproduce

I believe there is an error in
https://spack.readthedocs.io/en/latest/environments.html#view-projections

([link to highlight](https://spack.readthedocs.io/en/latest/environments.html#view-projections:~:text=projections%3A%0A%20%20zlib%3A%20%7Bname%7D%2D%7Bversion%7D%0A%20%20%5Empi%3A%20%7Bname%7D%2D%7Bversion%7D/%7B%5Empi.name%7D%2D%7B%5Empi.version%7D%2D%7Bcompiler.name%7D%2D%7Bcompiler.version%7D%0A%20%20all%3A%20%7Bname%7D%2D%7Bversion%7D/%7Bcompiler.name%7D%2D%7Bcompiler.version%7D))

## Option A

Copy yaml to a yaml linter (e.g. https://www.yamllint.com/) to get the following errors:

```
Unexpected scalar at node end at line 2, column 15
Unexpected scalar at node end at line 3, column 15
Unexpected scalar at node end at line 4, column 14
```

## Option B

**Copy yaml from documentation to `[...]/config.yaml`**
```yaml
config:
  install_tree:
    root: '/tmp/spack-root'
    projections:
      zlib: {name}-{version}
      ^mpi: {name}-{version}/{^mpi.name}-{^mpi.version}-{compiler.name}-{compiler.version}
      all: {name}-{version}/{compiler.name}-{compiler.version}
```

**Activate env and install**
```sh
# [... spack env activate ...]
$ spack install
```

### Error message

```
==> Error: error parsing YAML: near /[...]/config.yaml, 4, 6: expected <block end>, but found '<scalar>'
    while parsing a block mapping
  in "/[...]/config.yaml", line 5, column 7
expected <block end>, but found '<scalar>'
  in "/[...]/config.yaml", line 5, column 18
```

### Information on your system

* **Spack:** 0.20.0
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tbhaxor** [comment]
Wrapping values in quotes fixes lint issues

```yaml
---
projections:
  zlib: "{name}-{version}"
  ^mpi: "{name}-{version}/{^mpi.name}-{^mpi.version}-{compiler.name}-{compiler.version}"
  all: "{name}-{version}/{compiler.name}-{compiler.version}"
```
