### ISSUE TITLE
`singularity:files` configuration option

### ISSUE THREAD

**Issue by GodloveD** [LLNL/spack#38422]
### Summary

It would be great if the Spack yaml spec provided the ability to add content to the [`%files` section](https://apptainer.org/docs/user/main/definition_files.html#files) of an Apptainer definition file.  

### Rationale

Currently there are two workarounds that I can think of to add files to an Apptainer container using a def file generated via a `spack.yaml`.

1. Edit the def file manually after creating it with `spack containerize`.  
2. Copy the files to `/tmp` on the host and then copy them into the appropriate area within the container from `/tmp` at build time. 

Both of these methods are messy and error prone.  

There already exists [several `singularity:*`](https://spack.readthedocs.io/en/latest/containers.html#id3) configuration options that simply add arbitrary text to the appropriate sections.  So there is already precedent for this feature. 

### Description

I'm pretty new at writing `spack.yaml` files, so I don't know if this is the best way but I was thinking something like this.  Note that there needs to be a way to specify that the files will either need to be copied from the host during the build stage or from the build container to the final container during the final stage of the multi-stage builds. 

```yaml
spack:
  specs:
  - somepkg
  - someotherpkg

  container:
    format: singularity 

    images:
      os: rockylinux:8
      spack: v0.20.0

    singularity:
      files:
        build: |
          /file/from/host /location/in/build/container
        final: |
          /file/in/build/container /location/in/final/container
```

### Additional information

While this request is just for an `spack.yaml` addition for the `%files` section I could also imagine that every section that is possible in a def file could (and should?) be reflected in the spec files. 

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
