### ISSUE TITLE
Ipopt fails to build on OSX with clang

### ISSUE THREAD

**Issue by futuretristan** [LLNL/spack#3903]
When I try and install Ipopt on OSX 10.11.6 with clang via `spack install ipopt`, then the build fails with the messages
`ld: -rpath can only be used when creating a dynamic final linked image`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

The corresponding section in my compilers.yaml looks like this
compilers:
```
\- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: elcapitan
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /opt/local/bin/gfortran-mp-5
      fc: /opt/local/bin/gfortran-mp-5
    spec: clang@8.0.0-apple
    target: x86_6
```

If I compile Ipopt manually and independent of spack, everything works fine with the following configure line `../configure F77=gfortran-mp-5 --prefix="/Users/StTrSchl/libs/ipopt/lib/Ipopt-3.12.5-clang"`. Hard to say what's different to the Spack approach, as I don't know anything about the environment variables Spack sets for the build.
