### ISSUE TITLE
containerize: More customizable images

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#39226]
### Summary

`spack containerize` can be requested to generate a Dockerfile with a bootstrap phase instead of using a stock official Spack image. However, there is no option to bootstrap into a user-defined image, which greatly limits what `spack containerize` can build without externally modifying the Dockerfile. To make matters worse, enabling this bootstrap phase removes the option to customize the `final:` image the software is installed in, which is unnecessary and limiting.

### Rationale

As an example, I have an application that I want to build in a container that requires CUDA. I'd like to use the official CUDA  12.x images instead of a Spack `cuda` package. As such, I first need to bootstrap Spack into an official CUDA image (with the appropriate `packages.yaml`).

`spack containerize` will not generate the appropriate Dockerfile to do this, the bootstrap phase base image is determined by the `container:images:os:` option and there is no option for CUDA 12.x (much less other base images), I have to manually rewrite the `FROM` command to accomplish this at all.

To make matters worse, enabling the preliminary bootstrap phase *removes* the `container:images:final:` option (with schema errors), which means I have to `spack containerize` twice, once to build a bootstrap image and once to actually install anything. This is unnecessary and aggravating from a user experience perspective.

### Description

The primary suggested solution is to add a new `container:images:bootstrap:` option, and make the sibling `os:` and `final:` options non-conditional. For example, the following environment:
```yaml
spack:
  specs: [kokkos +cuda]
  packages:
    cuda:
      externals: # ...
  container:
    images:
      bootstrap: docker.io/nvidia/cuda:12.1.0-devel-ubuntu20.04
      os: ubuntu:20.04
      spack: develop
      final: docker.io/nvidia/cuda:12.1.0-runtime-ubuntu20.04
```
should generate a Dockerfile of the form:
```Dockerfile
FROM docker.io/nvidia/cuda:12.1.0-devel-ubuntu20.04 as bootstrap
# ... installs Spack develop for Ubuntu 20.04 ...
FROM bootstrap as build
# ... installs Kokkos using system CUDA installation ...
FROM docker.io/nvidia/cuda:12.1.0-runtime-ubuntu20.04 as final
COPY --from=build ...
```

The variant using `build:` would still be supported, and similar to how it is now `build:` cannot be specified if `bootstrap:` or `spack:` are specified and vice versa.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
