### ISSUE TITLE
Installation issue: openmpi with pbspro support 

### ISSUE THREAD

**Issue by roeverf** [LLNL/spack#39272]
### Steps to reproduce the issue

```console
$ spack install openmpi
...
```
```
packages.yaml:

packages:
  mpi:
    require: 'openmpi@4.1.5'
  openmpi:
    variants: schedulers=tm
  pbspro:
    externals:
    - spec: pbspro@2022.1.3
      prefix: /opt/pbs
      buildable: False
  all:
    compiler:
    - gcc@11.3.0
    providers:
      pbs: [pbspro, openpbs, torque]
      mpi: [openmpi]
```

### Error message

Error message

   1 error found in build log:
     2940    looking for library in lib64
     2941    checking for library containing tm_init... no
     2942    looking for library in lib
     2943    checking for library containing tm_init... no
     2944    looking for library in lib64
     2945    checking for library containing tm_init... no
   2946    configure: error: TM support requested but not found.  Aborting

### Information on your system

 **Spack:** 0.20.1 (bffd6ba02d893cb57c6fdf33a0efaa6bd3285bdd)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-cascadelake
* **Concretizer:** clingo

Installed PBS packages:
```
$ dnf info pbspro* | grep -B6 @System
Name         : pbspro-devel
Version      : 2022.1.3.20230614134139
Release      : 0.el8
Architecture : x86_64
Size         : 26 M
Quelle       : pbspro-2022.1.3.20230614134139-0.el8.src.rpm
Repository   : @System
--
Name         : pbspro-server
Version      : 2022.1.3.20230614134139
Release      : 0.el8
Architecture : x86_64
Size         : 354 M
Quelle       : pbspro-2022.1.3.20230614134139-0.el8.src.rpm
```

### Additional information

When installing OpenMPI with PBSPro support the configure step crashes with the error above. To investigate further we checked the config.log (after running the install process with "--keep-stage"):
```
configure:205054: checking for tm.h
configure:205054: result: yes
configure:205254: result: looking for library in lib
configure:205256: checking for library containing tm_init
configure:205287: /software/stages/2023.0/spack-0.20/lib/spack/env/gcc/gcc -o conftest -O3 -DNDEBUG -finline-functions -fno-strict-aliasing -pthread   -I[more stuff] -I/opt/pbs/include   -L[more stuff] -L/opt/pbs/lib conftest.c -lrt -lm -lutil  -lz  -lhwloc  -levent_core -levent_pthreads >&5
/tmp/cciGEDgY.o: In function main':
conftest.c:(.text.startup+0x7): undefined reference to `tm_init'
collect2: error: ld returned 1 exit status
configure:205287: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Open MPI"
[more stuff]
```

- Trying to compile OpenMPI manually outside of spack succeeded. However the error in the config.log is the same, but the configuration process does not stop upon this error. With this configuration we ware able to build OpenMPI.
- To get rid of the configure-error we set:
`` export LD_LIBRARY_PATH=/opt/pbs/lib:$LD_LIBRARY_PATH ``
`` export LDFLAGS="-L/opt/pbs/lib -lpbs -lpthread -lcrypto" ``
  This resolved the configre-issue.

So we tried to include this in spack by either:
1. ``spack edit openmpi:``

``` def setup_build_environment(self, env):
        env.append_flags('LDFLAGS', '-L/opt/pbs/lib -lpbs -lpthread')
        env.prepend_path('LD_LIBRARY_PATH', '/opt/pbs/lib')
```
2. ``spack config --scope site edit packages``
```
  openmpi:
    variants: schedulers=tm
    compilers:
      flags:
        ldflags: -L/opt/pbs/lib -lpbs -lpthread
        
```
We would be very grateful if someone could suggest a solution to this problem. We would prefer to not install openmpi externally and add it as an external package.

@hppritcha  @naughtont3
We  believe that we included the relevant parts of our build log and environment files here and above.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
