### ISSUE TITLE
Install missing compilers not respected

### ISSUE THREAD

**Issue by Siech0** [LLNL/spack#39290]
### Steps to reproduce

I am trying to build a completely standalone environment using spack. I'm using the following configuration for my spack.yaml

```yaml
spack:
  config:
    install_missing_compilers: true
    install_tree:
      root: /opt/software
    connect_timeout: 120 
  view:
    default:
      root: /opt/view
  packages:
    all:
      target: [x86_64]
      compiler: [gcc@9.2.0]
  specs:
  - gcc@9.2.0 +binutils +bootstrap +graphite +strip build_type=MinSizeRel languages=c,c++,fortran
  - valgrind %gcc@9.2.0 +ubsan
  concretizer:
    unify: when_possible
```

I run the following commands as part of my setup

```console
$ spack env activate .
$ spack install --fail-fast
```

It fails on the 'spack install' command. If I remove the '%gcc@9.2.0' it properly concretizes, however, I want all packages built using the gcc version installed by spack.

I have read the following similar issues, and the solutions did not work for me or were not relevant:
*  https://github.com/spack/spack/issues/30547
*  https://github.com/spack/spack/issues/10267

I also tested a similar config (though using the old syntax) on spack 1.17.0 and had the same issue.

### Error message

```console
$spack install --fail-fast
<omitted>
==> Installing "clingo-bootstrap@=spack%gcc@=10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-x86_64" from a buildcache
==> Error: concretization failed for the following reasons
  1. No valid version for 'valgrind'; compiler 'gcc' satisfies '@9.2.0'
```

It seems to me that it's not honoring the install_missing_compilers: true configuration item.

### Information on your system

* **spack:** 0.20.1 (e8658d6493887ef720dd38f0e9ee5870a1651c1e
* **Python:** 3.8.16
* **Platform:** linux-rhel8-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I don't think we ever had the possibility to specify the compiler spec to use, when `install_missing_compilers:true` @becker33 might know more

**Comment by Siech0** [comment]
> I don't think we ever had the possibility to specify the compiler spec to use, when `install_missing_compilers:true` @becker33 might know more

How should I have it automatically install compilers for packages? Even something like this fails:

```
spack:
  config:
    install_missing_compilers: true
  packages:
    all:
      target: [x86_64]
  specs:
    - cmake %gcc@9.2.0
    - gmake
  concretizer:
    unify: when_possible
```

I'm completely at a loss for how to use this setting.

**Comment by cameronrutherford** [comment]
Commenting here and tagging @becker33 as he recommended the same setting for me and I am finding that the concretizer is not really respecting this setting at all...

```
spack:
  specs:
  - cuda@11.8.0%gcc@11.1.0
  concretizer:
    unify: when_possible
    reuse: true
  config:
    install_missing_compilers: true
  mirrors:
    spack: https://binaries.spack.io/develop
  container:
    format: singularity
    images:
      os: ubuntu:22.04
      spack: develop
```

Even this short spec ends up resulting in their being no valid compiler, even though this should allow spack to build whatever compiler(s) are needed.
