### ISSUE TITLE
Module configs mixed up when multiple specs match

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#39420]
### Steps to reproduce

When multiple specs match in a module configuration, some configuration from one ends up "bleeding" into the other, resulting in modulefiles that make no sense.

Simplified example:
```yaml
# spack config get
spack:
  specs:
  - zlib+pic
  - zlib~pic

  concretizer:
    unify: false
    reuse: false
  view: false

  modules:
    default:
      enable: [tcl, lmod]
      roots:
        tcl: tcl-modules/
        lmod: lmod-modules/
      tcl: &cfg
        zlib:
          conflict: ['conflict/zlib']
          load: ['load/zlib']
        'zlib+pic':
          conflict: ['conflict/zlib-pic']
          load: ['load/zlib-pic']
        'zlib~pic':
          conflict: ['conflict/zlib-nopic']
          load: ['load/zlib-nopic']
      lmod: *cfg
```

Every module should load/conflict with `zlib-pic` or `zlib-nopic` but not both, however that is exactly what happens in practice:
```console
$ spack install
$ grep 'depends[_-]on\|conflict' `spack module tcl find --full-path zlib~pic`
    depends-on load/zlib
    depends-on load/zlib-pic
    depends-on load/zlib-nopic
conflict conflict/zlib
conflict conflict/zlib-pic
conflict conflict/zlib-nopic
$ grep 'depends[_-]on\|conflict' `spack module lmod find --full-path zlib~pic`
depends_on("load/zlib")
depends_on("load/zlib-pic")
depends_on("load/zlib-pic")
depends_on("load/zlib-nopic")
depends_on("load/zlib-nopic")
conflict("conflict/zlib")
conflict("conflict/zlib-pic")
conflict("conflict/zlib-pic")
conflict("conflict/zlib-nopic")
conflict("conflict/zlib-nopic")
```

### Error message

The modulefiles should contain two `depends_on`/`conflict` statements each, like so:
```console
$ grep 'depends[_-]on\|conflict' `spack module tcl find --full-path zlib~pic`
    depends-on load/zlib
    depends-on load/zlib-nopic
conflict conflict/zlib
conflict conflict/zlib-nopic
$ grep 'depends[_-]on\|conflict' `spack module lmod find --full-path zlib~pic`
depends_on("load/zlib")
depends_on("load/zlib-nopic")
conflict("conflict/zlib")
conflict("conflict/zlib-nopic")
```

### Information on your system

* **Spack:** 0.21.0.dev0 (abbd1abc1a265a1dc4bb8e3adb48ce1bf717bcb0)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
