### ISSUE TITLE
openmpi was concretizing to @4.1.5, now concretizes to @1.7

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#39455]
### Steps to reproduce

`openmpi` was concretizing to `openmpi@4.1.5` earlier today (c050b99a06a3ad11c76962b08141e513ea69b6c1) but now concretizes to `openmpi@1.7.4`
Using:
* spack@develop (b6ae7516578701aa4fe38bb3c09ca7d1b5fd3d92 from `Tue Aug 15 19:03:14 2023 -0600`)
* Docker image `ecpe4s/ubuntu20.04-runnner-amd64-gcc-11.4:2023.08.01`

<details><summary>Spack Environment</summary>

```
spack:
  view: false

  concretizer:
    reuse: false
    unify: false

  compilers:
  - compiler:
      spec: gcc@=11.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu20.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

  packages:
    all:
      require: '%gcc'
      providers:
        blas: [openblas]
        mpi: [mpich]
      target: [x86_64]
      variants: +mpi
    binutils:
      variants: +ld +gold +headers +libiberty ~nls
    elfutils:
      variants: +bzip2 ~nls +xz
    hdf5:
      variants: +fortran +hl +shared
    libfabric:
      variants: fabrics=sockets,tcp,udp,rxm
    libunwind:
      variants: +pic +xz
    openblas:
      variants: threads=openmp
    trilinos:
      variants: +amesos +amesos2 +anasazi +aztec +belos +boost +epetra +epetraext
        +ifpack +ifpack2 +intrepid +intrepid2 +isorropia +kokkos +ml +minitensor +muelu
        +nox +piro +phalanx +rol +rythmos +sacado +stk +shards +shylu +stokhos +stratimikos
        +teko +tempus +tpetra +trilinoscouplings +zoltan +zoltan2 +superlu-dist gotype=long_long
    xz:
      variants: +pic
    mesa:
      version: [21.3.8]
    mpi:
      require: mpich
    mpich:
      require: '@4.1.2 ~wrapperrpath ~hwloc'
    ncurses:
      require: '@6.3 +termlib'
    tbb:
      require: intel-tbb
    boost:
      version: [1.79.0]
      variants: +atomic +chrono +container +date_time +exception +filesystem +graph
        +iostreams +locale +log +math +mpi +multithreaded +program_options +random
        +regex +serialization +shared +signals +stacktrace +system +test +thread +timer
        cxxstd=17 visibility=global
    libffi:
      require: "@3.4.4"
    vtk-m:
      require: "+examples"
    cuda:
      version: [11.8.0]

  specs:
  - openmpi
```

</details>

This concretizes to `openmpi@1.7.4` using newer b6ae7516578701aa4fe38bb3c09ca7d1b5fd3d92
```
$> git -C spack checkout b6ae7516
$> spack -e . concretize -f
==> Starting concretization
==> Environment concretized in 16.46 seconds.
==> Concretized openmpi
 -   4xt54np  openmpi@1.7.4%gcc@11.4.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix+romio+rsh~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-ubuntu20.04-x86_64
 -   2hwgpaf      ^hwloc@1.11.13%gcc@11.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static patches=d1d94a4 arch=linux-ubuntu20.04-x86_64
 -   7uxwf7k          ^libpciaccess@0.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   kfwazxb              ^util-macros@1.19.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   gwafrd6          ^libxml2@2.10.3%gcc@11.4.0~python build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   5ou3smh              ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
 -   luns6tr              ^xz@5.4.1%gcc@11.4.0+pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
 -   sgkqpns          ^ncurses@6.3%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   rwmxi7s      ^numactl@2.0.14%gcc@11.4.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu20.04-x86_64
 -   z4wzfvz          ^autoconf@2.69%gcc@11.4.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-x86_64
 -   d27qa5c          ^automake@1.16.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   j6wekon          ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   cykjcob          ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
 -   l3hpi5r              ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   etzummq              ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   po5wf2y      ^openssh@9.3p1%gcc@11.4.0+gssapi build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   qo2sopq          ^krb5@1.20.1%gcc@11.4.0+shared build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   ggvteul              ^bison@3.8.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   q7cxbn3              ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu20.04-x86_64
 -   wklapkn              ^gettext@0.21.1%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   jytqscn                  ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-x86_64
 -   3bozewh                      ^pigz@2.7%gcc@11.4.0 build_system=makefile arch=linux-ubuntu20.04-x86_64
 -   56fzjs5                      ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-x86_64
 -   inheyqj          ^libedit@3.1-20210216%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   5jzg64q          ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu20.04-x86_64
 -   jid23vg          ^openssl@3.1.2%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64
 -   fz63wzq              ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
 -   duf3fb2          ^zlib@1.2.13%gcc@11.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-x86_64
 -   yectlsz      ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu20.04-x86_64
 -   w6fwhuc          ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
 -   soyi3s6          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64
 -   jpvceos          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   ocp3udv              ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64
 -   2tu42dq      ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
```

`git bisect` shows the last commit where this environment concretized to `openmpi@4.1.5` was c050b99a06a3ad11c76962b08141e513ea69b6c1

Concretizes to `openmpi@4.1.5` using c050b99a06a3ad11c76962b08141e513ea69b6c1
```
$> git -C spack checkout c050b99a
$> spack  -e . concretize -f
==> Starting concretization
==> Environment concretized in 16.62 seconds.
==> Concretized openmpi
 -   y4a7t2m  openmpi@4.1.5%gcc@11.4.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-ubuntu20.04-x86_64
 -   cdyugxd      ^hwloc@2.9.1%gcc@11.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
 -   7uxwf7k          ^libpciaccess@0.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   kfwazxb              ^util-macros@1.19.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   gwafrd6          ^libxml2@2.10.3%gcc@11.4.0~python build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   5ou3smh              ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
 -   luns6tr              ^xz@5.4.1%gcc@11.4.0+pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
 -   sgkqpns          ^ncurses@6.3%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   rwmxi7s      ^numactl@2.0.14%gcc@11.4.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu20.04-x86_64
 -   z4wzfvz          ^autoconf@2.69%gcc@11.4.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-x86_64
 -   d27qa5c          ^automake@1.16.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   j6wekon          ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   cykjcob          ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
 -   l3hpi5r              ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   etzummq              ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   po5wf2y      ^openssh@9.3p1%gcc@11.4.0+gssapi build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   qo2sopq          ^krb5@1.20.1%gcc@11.4.0+shared build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   ggvteul              ^bison@3.8.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   q7cxbn3              ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu20.04-x86_64
 -   wklapkn              ^gettext@0.21.1%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   jytqscn                  ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-x86_64
 -   3bozewh                      ^pigz@2.7%gcc@11.4.0 build_system=makefile arch=linux-ubuntu20.04-x86_64
 -   56fzjs5                      ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-x86_64
 -   inheyqj          ^libedit@3.1-20210216%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   5jzg64q          ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu20.04-x86_64
 -   jid23vg          ^openssl@3.1.2%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64
 -   fz63wzq              ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
 -   yectlsz      ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu20.04-x86_64
 -   w6fwhuc          ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
 -   soyi3s6          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64
 -   jpvceos          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   ocp3udv              ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64
 -   2tu42dq      ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   b5t7knl      ^pmix@4.2.4%gcc@11.4.0~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   exwtuxz          ^libevent@2.1.12%gcc@11.4.0+openssl build_system=autotools arch=linux-ubuntu20.04-x86_64
 -   duf3fb2      ^zlib@1.2.13%gcc@11.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-x86_64
```

CC @alalazo @tgamblin 

### Information on your system

* **Spack:** 0.21.0.dev0 (c050b99a06a3ad11c76962b08141e513ea69b6c1)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tgamblin** [comment]
@alalazo can you look at this one?

**Comment by alalazo** [comment]
Sure

**Comment by alalazo** [comment]
Undecided whether to mark it impact "low" or "medium". The bug is triggered by this minimal reproducer:
```yaml
spack:
  specs:
  - openmpi
  packages:
    mpi:
      require: mpich
```
Apparently it shows up only for potential providers that are forbidden to be the actual providers.
