### ISSUE TITLE
Partial arch packages in `packages.yaml` are silently skipped

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#3946]
This doesn't work:

```yaml
packages:  
  intel-mkl:
    paths:
      intel-mkl@17.0.098%gcc@4.8.5 arch=centos7-mic-knl: /opt/intel/compilers_and_libraries_2017.0.098/linux/mkl
      intel-mkl@17.0.098%intel@17.0.0 arch=centos7-mic-knl: /opt/intel/compilers_and_libraries_2017.0.098/linux/mkl
    buildable: False
```

this works:

```yaml
packages:  
  intel-mkl:
    paths:
      intel-mkl@17.0.098%gcc@4.8.5 arch=linux-centos7-x86_64: /opt/intel/compilers_and_libraries_2017.0.098/linux/mkl
      intel-mkl@17.0.098%intel@17.0.0 arch=linux-centos7-x86_64: /opt/intel/compilers_and_libraries_2017.0.098/linux/mkl
    buildable: False
```

See the difference?  Neither did the user who reported it.  We should add better checking for the specs provided in `packages.yaml`, to ensure they can actually be used.
