### ISSUE TITLE
openimagedenoise@1.4.3 build fails on ARM: core/pool.h:54:3: error: expected class-name before '{' token

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#39531]
### Steps to reproduce the issue

`openimagedenoise@1.4.3` build fails on ARM using:
* spack@develop (c9ec5fb9ac565033c7db643f0b51da5dc9315ac0 from `Sat Aug 19 00:46:50 2023 +0200`)
* Ubuntu 20.04, ARM64
* GCC 11.4.0
* Docker container image `ecpe4s/ubuntu20.04-runner-arm64-gcc-11.4:2023.08.01`

This is preventing us from building the following ECP DAV spec for ARM64:
```
ecp-data-vis-sdk ~cuda ~rocm +adios2 +ascent +cinema 
   +darshan +faodel +hdf5 +paraview +pnetcdf +sz +unifyfs +veloc +visit +vtkm +zfp
```

<details><summary>Spack environment</summary>

```
spack:
  view: false

  concretizer:
    reuse: false
    unify: false

  packages:
    all:
      require: '%gcc@11.4.0'
      providers:
        blas: [openblas]
        mpi: [mpich]
      target: [aarch64]
      variants: +mpi
    binutils:
      variants: +ld +gold +headers +libiberty ~nls
    elfutils:
      variants: +bzip2 ~nls +xz
    hdf5:
      variants: +fortran +hl +shared
    libfabric:
      variants: fabrics=sockets,tcp,udp,rxm
    libunwind:
      variants: +pic +xz
    openblas:
      variants: threads=openmp
    trilinos:
      variants: +amesos +amesos2 +anasazi +aztec +belos +boost +epetra +epetraext
        +ifpack +ifpack2 +intrepid +intrepid2 +isorropia +kokkos +ml +minitensor +muelu
        +nox +piro +phalanx +rol +rythmos +sacado +stk +shards +shylu +stokhos +stratimikos
        +teko +tempus +tpetra +trilinoscouplings +zoltan +zoltan2 +superlu-dist gotype=long_long
    xz:
      variants: +pic
    mesa:
      version: [21.3.8]
    mpi:
      require: mpich
    mpich:
      require: '@4.1.2 ~wrapperrpath ~hwloc'
    ncurses:
      require: '@6.3 +termlib'
    tbb:
      require: intel-tbb
    boost:
      version: [1.79.0]
      variants: +atomic +chrono +container +date_time +exception +filesystem +graph
        +iostreams +locale +log +math +mpi +multithreaded +program_options +random
        +regex +serialization +shared +signals +stacktrace +system +test +thread +timer
        cxxstd=17 visibility=global
    libffi:
      require: "@3.4.4"
    vtk-m:
      require: "+examples"
    cuda:
      version: [11.8.0]

  compilers:
  - compiler:
      spec: gcc@11.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu20.04
      target: aarch64
      modules: []
      environment: {}
      extra_rpaths: []

  specs:
  - ecp-data-vis-sdk ~cuda ~rocm +adios2 +ascent +cinema +darshan +faodel +hdf5 +paraview +pnetcdf +sz +unifyfs +veloc +visit +vtkm +zfp
```

</details>

<details><summary>Concretization</summary>

<pre>
 -   wqbs65q  openimagedenoise@1.4.3%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-aarch64
[+]  amwz5jt      ^cmake@3.26.3%gcc@11.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu20.04-aarch64
[+]  nkhvrzh          ^curl@8.1.2%gcc@11.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu20.04-aarch64
[+]  4jhk4yh              ^nghttp2@1.52.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  fzluouk          ^ncurses@6.3%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  kzszqob          ^zlib@1.2.13%gcc@11.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-aarch64
[+]  whozcr3      ^gmake@4.4.1%gcc@11.4.0~guile build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  4pfsqtg          ^gnuconfig@2022-09-17%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-aarch64
[+]  hj7hm2v      ^intel-tbb@2021.9.0%gcc@11.4.0~ipo+shared+tm build_system=cmake build_type=Release cxxstd=default generator=make patches=12a9c3e arch=linux-ubuntu20.04-aarch64
[+]  yhk3kcy          ^hwloc@2.9.1%gcc@11.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu20.04-aarch64
[+]  74eccrr              ^libpciaccess@0.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  lunrww6                  ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  cybqwl7                  ^util-macros@1.19.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  hqmyh2p              ^libxml2@2.10.3%gcc@11.4.0~python build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  llbw74i      ^ispc@1.20.0%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-aarch64
[+]  fegwesy          ^bison@3.8.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  esdggm2              ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  zojha6y              ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-aarch64
[+]  mtu7bgv                  ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  wr5hfa5              ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu20.04-aarch64
[+]  gk4kscx                  ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-aarch64
[+]  v7cxzi5          ^flex@2.6.3%gcc@11.4.0+lex~nls build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  36ha6pi              ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu20.04-aarch64
[+]  l5ftcah          ^llvm@14.0.6%gcc@11.4.0+clang~cuda~flang+gold~ipo+libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib~mlir+polly~python~split_dwarf~z3 build_system=cmake build_type=Release compiler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime patches=1f42874,25bc503,6379168,8248141,b216cff shlib_symbol_version=none targets=aarch64,all,arm version_suffix=none arch=linux-ubuntu20.04-aarch64
[+]  2aehw6p              ^binutils@2.40%gcc@11.4.0~gas+gold~gprofng+headers~interwork+ld+libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static arch=linux-ubuntu20.04-aarch64
[+]  6zef44j                  ^texinfo@7.0.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  iojwerc                  ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-aarch64
[+]  rcheb7w              ^libedit@3.1-20210216%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  blk2faa              ^ninja@1.11.1%gcc@11.4.0+re2c build_system=generic arch=linux-ubuntu20.04-aarch64
[+]  n7q2fwr                  ^re2c@2.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-aarch64
[+]  uc7g5hr              ^perl-data-dumper@2.173%gcc@11.4.0 build_system=perl arch=linux-ubuntu20.04-aarch64
[+]  z5eefh6      ^python@3.7.17%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,f2fd060 arch=linux-ubuntu20.04-aarch64
[+]  ja4d3qc          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-aarch64
[+]  wmuhzov          ^expat@2.5.0%gcc@11.4.0+libbsd build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  ormxkmq              ^libbsd@0.11.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  sbf43az                  ^libmd@1.0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  jm67j6t          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  b4ymrvu          ^gettext@0.21.1%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  dmdkgje              ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-aarch64
[+]  h7rmakm              ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-aarch64
[+]  zkgaasc                  ^pigz@2.7%gcc@11.4.0 build_system=makefile arch=linux-ubuntu20.04-aarch64
[+]  kgueuga          ^libffi@3.4.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  evoeirh          ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu20.04-aarch64
[+]  ryz3hxw          ^openssl@1.1.1v%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-aarch64
[+]  wfmbgoq              ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-aarch64
[+]  iv32a2d          ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  iptq6b7          ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-aarch64
[+]  loeyfnm          ^sqlite@3.42.0%gcc@11.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  xqflduv          ^util-linux-uuid@2.38.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-aarch64
[+]  q7galae          ^xz@5.4.1%gcc@11.4.0+pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-aarch64
</pre></details>

Error:
```
$> spack -e . install /wqbs65q
...
==> Installing openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq [33/33]
==> No binary for openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/32/3276e252297ebad67a999298d8f0c30cfb221e166b166ae5c955d88b94ad062a.tar.gz
==> No patches needed for openimagedenoise
==> openimagedenoise: Executing phase: 'cmake'
==> openimagedenoise: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
...
     152    In file included from /tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-src/core/network.cpp:5:
  >> 153    /tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-src/core/pool.h:54:3: error: expected class-name before '{' token
     154       54 |   {
     155          |   ^
  >> 156    /tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-src/core/pool.h:82:10: error: 'void oidn::PoolNode::execute()' marked 'override', but does
            not override
     157       82 |     void execute() override
     158          |          ^~~~~~~
  >> 159    /tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-src/core/pool.h:87:29: error: 'std::shared_ptr<oidn::Tensor> oidn::PoolNode::getDst() const
            ' marked 'override', but does not override
     160       87 |     std::shared_ptr<Tensor> getDst() const override { return dst; }
     161          |                             ^~~~~~
     162    /tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-src/core/pool.h: In constructor 'oidn::PoolNode::PoolNode(const oidn::Ref<oidn::Device>&, c
            onst string&, const std::shared_ptr<oidn::Tensor>&, const std::shared_ptr<oidn::Tensor>&)':
  >> 163    /tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-src/core/pool.h:64:9: error: class 'oidn::PoolNode' does not have any field named 'BNNSNode
            '
     164       64 |       : BNNSNode(device, name),
     165          |         ^~~~~~~~
  >> 166    /tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-src/core/pool.h:67:7: error: 'BNNSLayerParametersPooling' was not declared in this scope
     167       67 |       BNNSLayerParametersPooling params = {
...
  >> 250    make[2]: *** [CMakeFiles/OpenImageDenoise.dir/build.make:300: CMakeFiles/OpenImageDenoise.dir/core/network.cpp.o] Error 1
     251    make[2]: *** Waiting for unfinished jobs....
     252    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-build-wqbs65q'
  >> 253    make[1]: *** [CMakeFiles/Makefile2:103: CMakeFiles/OpenImageDenoise.dir/all] Error 2
     254    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-openimagedenoise-1.4.3-wqbs65qsfo44bk3utv4n5oyhdafxrqlq/spack-build-wqbs65q'
  >> 255    make: *** [Makefile:159: all] Error 2
```

### Error message

<details><summary>Error message</summary>

<pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (a38535fa8ee17c6fcafeb7a4ab7665a27d2b569e)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-neoverse_n1
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/12386252/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/12386253/spack-build-out.txt)

FYI @kwryankrattiger 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
