### ISSUE TITLE
Installation issue: opencv

### ISSUE THREAD

**Issue by LydDeb** [LLNL/spack#39845]
### Steps to reproduce the issue

```console
$ spack env create debug
$ spack -e debug add opencv
$ spack config add packages:all:variants:cuda_arch=60,70,80
$ spack -e debug concretize
```

### Error message

<details>==> Error: cannot append the new value '70' to the single-valued variant 'cuda_arch=60'
</details>

### Information on your system

* **Spack:** 0.21.0.dev0 (61415014f23bbbb871c25ebcd2ce8f0d010c30fa)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo

### Additional information

packages.yaml
```yaml
packages:
  all:
    variants:
      cuda_arch=60,70,80
```

spack.yaml
```yaml
# This is a Spack Environment file.
# 
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - opencv
  view: true
  concretizer:
    unify: true
```

@adamjstewart  @bvanessen

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by LydDeb** [comment]
Dear @adamjstewart and @bvanessen, I encounter an error during the concretize of an environment with opencv and the cuda_arch variant. I perform the following tests:
1. The environment **succeed** to concretize if I remove cuda_arch from global definition (from packages:all:variants)  and set it directly in specs.
1.  The environment **failed** to concretize if I set cuda_arch from global definition (from packages:all:variants)  and set it directly in specs.
1.  The environment **failed** to concretize if I set cuda_arch from global definition (from packages:all:variants)  and dont set it in specs.

**Comment by adamjstewart** [comment]
I managed to reproduce this issue. After adding some debug print statements, it looks like the issue is with the `kokkos` package. The `cuda_arch` variant supports multiple values for most packages, but not for kokkos. I believe kokkos is an optional indirect dep of opencv, which is why the concretizer is parsing it just in case.

A few possible solutions. If you only care about OpenCV:
```yaml
packages:
  opencv:
    variants: +cuda cuda_arch=60,70,80
```
If you want all packages except kokkos to build with cuda:
```yaml
packages:
  all:
    variants: +cuda cuda_arch=60,70,80
  kokkos:
    variants: ~cuda cuda_arch=none
```

P.S. @crtrott @janciesko is it true that kokkos can't support multiple cuda arches at once or can we change this?
