### ISSUE TITLE
environment concretized to different target when host_compatible=true

### ISSUE THREAD

**Issue by lorisercole** [LLNL/spack#40124]
### Steps to reproduce

Here is my `spack.yaml` environment file, asking to use `skylake_avx512` as target
```yaml
spack:
  config:
    install_tree:
      padded_length: 128
  concretizer:
    unify: when_possible
    targets:
      host_compatible: true
  modules:
    default:
      enable:
       - tcl
      tcl:
        all:
          autoload: direct
  compilers:
  - compiler:
      spec: gcc@8.5.0
      paths:
        cc: /bin/gcc
        cxx: /bin/g++
        f77: /bin/gfortran
        fc: /bin/gfortran
      flags: {}
      operating_system: almalinux8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  packages:
    all:
      providers:
        mpi: [hpcx-mpi]
        blas: [intel-oneapi-mkl +cluster]
        mkl: [intel-oneapi-mkl +cluster]
        lapack: [intel-oneapi-mkl +cluster]
        scalapack: [intel-oneapi-mkl +cluster]
        fftw-api: [intel-oneapi-mkl +cluster]
      permissions:
        read: world
        write: group
        group: hpcadmin
      target: [skylake_avx512]
      compiler: ["gcc"]
    hpcx-mpi:
      buildable: false
      externals:
      - spec: hpcx-mpi@2.15
        prefix: /opt/hpcx-v2.15-gcc-MLNX_OFED_LINUX-5-redhat8-cuda12-gdrcopy2-nccl2.17-x86_64/ompi
  view: false
  specs:
  - gromacs
```
I am running on a `zen2` machine, and the specs get concretized with `arch=linux-almalinux8-zen` instead of `arch=linux-almalinux8-skylake_avx512`:
```console
$ spack arch
linux-almalinux8-zen2
$ spack concretize -Uf
==> Concretized gromacs
 -   jy5txzw  gromacs@2022.5%gcc@8.5.0~blas~cp2k~cuda~cycle_subcounters~double+hwloc~intel_provided_gcc~ipo~lapack~mdrun_only+mpi~nosuffix~opencl+openmp~plumed~relaxed_double_precision+shared~sycl build_system=cmake build_type=Release generator=make openmp_max_threads=none arch=linux-almalinux8-zen
 -   malczbz      ^cmake@3.26.3%gcc@8.5.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-almalinux8-zen
 -   wnx2fxf          ^curl@8.1.2%gcc@8.5.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-almalinux8-zen
 -   p53ycgq              ^nghttp2@1.52.0%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
 -   23ut6ya              ^openssl@3.1.2%gcc@8.5.0~docs+shared build_system=generic certs=mozilla arch=linux-almalinux8-zen
 -   p2uwkgs                  ^ca-certificates-mozilla@2023-05-30%gcc@8.5.0 build_system=generic arch=linux-almalinux8-zen
[+]  aj3kaoc                  ^perl@5.38.0%gcc@8.5.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-almalinux8-zen
[+]  dcngoex                      ^berkeley-db@18.1.40%gcc@8.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-almalinux8-zen
[+]  kxwwfnp                      ^bzip2@1.0.8%gcc@8.5.0~debug~pic+shared build_system=generic arch=linux-almalinux8-zen
[+]  yw7l6ge                      ^gdbm@1.23%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
[+]  iur6gk5                          ^readline@8.2%gcc@8.5.0 build_system=autotools patches=bbf97f1 arch=linux-almalinux8-zen
[+]  qtknm74          ^ncurses@6.4%gcc@8.5.0~symlinks+termlib abi=none build_system=autotools arch=linux-almalinux8-zen
[+]  t5ryxxp          ^zlib@1.2.13%gcc@8.5.0+optimize+pic+shared build_system=makefile arch=linux-almalinux8-zen
[+]  6bniiam      ^gmake@4.4.1%gcc@8.5.0~guile build_system=autotools arch=linux-almalinux8-zen
[e]  jgj3krm      ^hpcx-mpi@2.15%gcc@8.5.0 build_system=generic arch=linux-almalinux8-zen
 -   5ktapv4      ^hwloc@2.9.1%gcc@8.5.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-almalinux8-zen
 -   puhffzg          ^libpciaccess@0.17%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
[+]  ydr6ojy              ^libtool@2.4.7%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
[+]  4ea63qu                  ^m4@1.4.19%gcc@8.5.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-almalinux8-zen
[+]  u4i2px7                      ^diffutils@3.9%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
[+]  e6slirn                      ^libsigsegv@2.14%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
 -   pw6qf7z              ^util-macros@1.19.3%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
[+]  6s4u5js          ^libxml2@2.10.3%gcc@8.5.0~python build_system=autotools arch=linux-almalinux8-zen
[+]  gumuar2              ^libiconv@1.17%gcc@8.5.0 build_system=autotools libs=shared,static arch=linux-almalinux8-zen
[+]  yci52ge              ^xz@5.4.1%gcc@8.5.0~pic build_system=autotools libs=shared,static arch=linux-almalinux8-zen
[+]  m7cpiq7          ^pkgconf@1.9.5%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
 -   q3dciyq      ^intel-oneapi-mkl@2023.2.0%gcc@8.5.0~cluster+envmods~ilp64+shared build_system=generic mpi_family=none threads=none arch=linux-almalinux8-zen
 -   jjah62o          ^intel-tbb@2021.9.0%gcc@8.5.0~ipo+shared+tm build_system=cmake build_type=Release cxxstd=default generator=make patches=12a9c3e arch=linux-almalinux8-zen
```
No error message is returned, so one could erroneously concretize for the wrong target (happened to me).

Instead, if I modify the specs in this way:
```yaml
  specs:
  - gromacs target=skylake_avx512
```
I get this error:
```console
$ spack concretize -Uf
==> Error: concretization failed for the following reasons:

   1. No valid compiler version found for 'NodeArgument(id='0', pkg='gromacs')'
   2. Cannot find compatible targets for NodeArgument(id='0', pkg='gromacs') and NodeArgument(id='0', pkg='intel-parallel-studio')
   3. Cannot find compatible targets for NodeArgument(id='0', pkg='gromacs') and NodeArgument(id='0', pkg='gmake')
   4. Cannot find compatible targets for NodeArgument(id='0', pkg='gromacs') and NodeArgument(id='0', pkg='cmake')
   5. 'NodeArgument(id='0', pkg='gromacs') target=skylake_avx512' is not compatible with this machine
```

This problem seems similar to #31075

### Information on your system

* **Spack:** 0.21.0.dev0 (843dfb6dec985b098b88cdfff7f3de1a2dda400f)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-zen2
* **Concretizer:** cling

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This is not a bug. The first misunderstanding is that:
```yaml
packages:
    all:
      target: [skylake_avx512]
```
is a soft-preference. This means that if clingo cannot use `skylake_avx512`, it will fall-back to another target. In this case it can't because `host_compatible:true` forbids the skylake target.

If you require a forbidden target, you get an error - which is the second case.

The solution would be to set:
```yaml
concretizer:
  targets:
    host_compatible: false
```
if there is a need to build a binary optimized for skylake on a zen2 CPU.

Closing, but let me know if there's anything else to discuss, or if anything is unclear.

**Comment by lorisercole** [comment]
Thanks for your explanation @alalazo. 
The reason why we want to enforce the host compatibility is that we encountered compilation errors when building some specific software for skylake on a zen2 CPU. It was a very specific case (`namd`, if I recall well), I should probably try to reproduce it and submit an issue then, but building it on skylake solved the problem.

Anyway, the point for me was that concretized target was different from the one I was asking for, and this is something that normally I want to be enforced, not a soft requirement.
I have also tried to set a requirement instead:
```yaml
  packages:
    all:
      require: "arch=linux-almalinux8-skylake_avx512"
```
but I get a concretization error, even with `host_compatible: false`:
```console
$ spack concretize -Uf
==> Error: concretization failed for the following reasons:
   1. cannot satisfy a requirement for package 'zlib'.
   2. cannot satisfy a requirement for package 'pkgconf'.
   3. cannot satisfy a requirement for package 'gromacs'.
   4. cannot satisfy a requirement for package 'gmake'.
   5. cannot satisfy a requirement for package 'curl'.
   6. cannot satisfy a requirement for package 'cmake'.
   7. cannot satisfy a requirement for package 'armpl-gcc'.
   8. curl: Only supported on macOS
```
Is `arch` something that I cannot use in `require`? It does not seem to work, whatever the arch...
Thank you!

CC: @ltalirz
