### ISSUE TITLE
spack env loads -r fails

### ISSUE THREAD

**Issue by skwde** [LLNL/spack#40210]
### Steps to reproduce

I have an additional compiler installed via spack, I added this compiler to `compilers.yaml`

```sh
spack install gcc@13.1.0
spack load gcc@13.1.0
spack compiler find
```

I used this compiler to install an environment.

I tried both, a unmanaged environment

```sh
spack env create -d ~/test-envs/base
```

and then a managed environemnt

```sh
spack env create base
spacktivate -p base
spack config edit
```

In both I ensuree that the `spack.yaml` looks like

```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
    - tmux
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler:
        - gcc@13.1.0
      target:
        - x86_64_v3
```

After the install

```sh
spack install
```

when I then try to create the source script via

```sh
spack env loads -r
```

### Error message

```sh
$ spack --debug --stacktrace env loads -r
==> Error: The module for package tmux@3.3a/dj5uwwz should be at ~/opt/spack/share/spack/modules/linux-rocky9-x86_64_v3/tmux-3.3a-gcc-13.1.0-dj5uwwz, but it does not exist
```

### Information on your system

```sh
$ spack debug report
* **Spack:** 0.20.1 (e8658d6493887ef702dd38f0e9ee5870a1651c1e)
* **Python:** 3.9.16
* **Platform:** linux-rocky9-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
