### ISSUE TITLE
Installation issue: amdlibflame won't build with Intel OneAPI

### ISSUE THREAD

**Issue by pbisbal1** [LLNL/spack#40915]
### Steps to reproduce the issue

Trying to build an environment ("test") with the spack.yaml file below, and building amdlibflame fails when building with the intel-oneapi compiler. Not sure if this a bug, or by design. 

```
spack:
  definitions: 
  - compilers: ['aocc@4.1.0', 'gcc@13.2.0', 'oneapi@2023.2.0'] 
  - mpis: ['openmpi fabrics=ucx schedulers=slurm +pmi']
  - packages: ['hpl +openmp', 'ior']
  
  specs:
  - aocc@4.1.0%gcc@11.3.1
  - gcc@13.2.0%gcc@11.3.1
  - intel-oneapi-compilers@2023.2.1%gcc@11.3.1
  - matrix: 
    - ['amdblis', 'amdlibflame']
    - [$%compilers]
#  - matrix:
#    - [$mpis]
#    - [$%compilers]
#  - matrix:
#    - [$packages]
#    - [$^mpis]
#    - [$%compilers]   

  concretizer:
    unify: false

  packages: 
    blas:
      require: amdblis
    lapack: 
      require: amdlibflame

  view: false
```
I then do 

```console

# spack env activate test

# spack install
```

### Error message

<details><summary>The build of amdlibflame fails with an error that it can't determine the compiler vendor for icx</summary>

<pre>
1 error found in build log:                                                                                             
     20    checking for suffix of executables...                                                                        
     21    checking whether we are cross compiling... no                                                                
     22    checking for suffix of object files... o                                                                     
     23    checking whether we are using the GNU C compiler... yes                                                           24    checking whether /usr/lynx/spack/lib/spack/env/oneapi/icx accepts -g                                         
           ... no                                                                                                       
     25    checking for /usr/lynx/spack/lib/spack/env/oneapi/icx option to acce                                                    pt ISO C89... none needed                                                                                    
  >> 26    configure: error: configure can't determine the compiler vendor for                                                     /usr/lynx/spack/lib/spack/env/oneapi/icx. Please submit a bug report                                         
            to the FLAME developers.   
</pre></details>

<details><summary>spack-build-out.txt provides a similar error message:</summary>

<pre>
checking whether user requested a specific C compiler... no
configure: CC environment variable is set to /usr/lynx/spack/lib/spack/env/oneapi/icx, which will override --with-cc option and default search list for C compiler.
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/lynx/spack/lib/spack/env/oneapi/icx accepts -g... no
checking for /usr/lynx/spack/lib/spack/env/oneapi/icx option to accept ISO C89... none needed
configure: error: configure can't determine the compiler vendor for /usr/lynx/spack/lib/spack/env/oneapi/icx. Please submit a bug report to the FLAME developers.
</pre>
</details>

### Information on your system

* **Spack:** 0.21.0.dev0 (81172f9251ff0b3409b07d5b9d13b214766ff1b1)
* **Python:** 3.9.16
* **Platform:** linux-rhel9-zen2
* **Concretizer:** clingo

### Additional information

[config.log](https://github.com/spack/spack/files/13271958/config.log)
[spack-build-env.txt](https://github.com/spack/spack/files/13271959/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/13271960/spack-build-out.txt)

@amd

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
