### ISSUE TITLE
Environment errors when reconcretizing

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#41292]
### Steps to reproduce

Activate the following environment:
```yaml
spack:
  specs:
  - zlib-ng
  - hdf5@1.14.2 ~mpi
  - zlib-ng generator=make
  view: false
  concretizer:
    unify: true
```
and concretize it:
```console
$ spack concretize
[ ... ]
```
Then deconcretize `hdf5` and reconcretize:
```console
$ spack deconcretize hdf5
$ spack concretize
```

### Error message

During the last command an assertion error is enmitted:
```console
$ spack concretize 
==> Error: literal specs have different requirements. clear cache before computing literals
```

The trigger is, in general:
- Have 2 or more user specs that map to the same concrete spec on a first concretization
- Deconcretize something else, and try to reconcretize the environment

### Information on your system

* **Spack:** 0.22.0.dev0 (5299b84319d34072fae5be6abdf8e57f06be94e9)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
