### ISSUE TITLE
packages.yaml can't set version for go (problem with 2 vs 3 digit version numbers?)

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#4133]
I have an `etc/spack/packages.yaml` looks like this (lines elided):

```yaml
packages:
  all:
    compiler: [gcc@5.4.0, gcc@4.8.5, gcc@4.8.3]
  ack:
    version: [2.16]
[...]
  emacs:
    version: [25.1]
    variants: +X
[...]
  go:
    version: [1.8]
    # tests have two false positives, user_namespaces and threads/exceptions
    variants: ~test
  hdf5:
    version: [1.10.0-patch1]
[...]
```

As a control, I can `spack spec emacs` and it reports:

```
Concretized
--------------------------------
emacs@25.1%gcc@5.4.0+X toolkit=gtk arch=linux-centos7-x86_64
```

If I change the emacs version to `25.2`, then I get 

```
Concretized
--------------------------------
emacs@25.2%gcc@5.4.0+X toolkit=gtk arch=linux-centos7-x86_64
```

so I'm using the right file, and etc...

In spite of the constraint to version 1.8 in the yaml file, `spack spec go` sez:

```
Concretized
--------------------------------
go@1.8.1%gcc@5.4.0 arch=linux-centos7-x86_64
```

`spack spec go@1.8` sez:

```
Concretized
--------------------------------
go@1.8%gcc@5.4.0 arch=linux-centos7-x86_64
```

so the version seems to exist, and etc...

If I change the go constraint in the yaml file to `1.7.5`, I get:

```
Concretized
--------------------------------
go@1.7.5%gcc@5.4.0 arch=linux-centos7-x86_64
```

Which kind of leaves my marbles rolling around on the floor.
