### ISSUE TITLE
Cannot enforce virtual dependency for only one specific target

### ISSUE THREAD

**Issue by fgava90** [LLNL/spack#41681]
### Steps to reproduce

I am attempting to enforce a different mpi library for a specific target.
I have a machine that is composed of x86_64 and x86_64_v2 and x86_64_v4 nodes.
On the x86_64_v2 nodes i have an externally built MPICH which i want to use, however this is not available on the x86_64 and x86_64_v4 nodes, so i want to build OpenMPI on those.

I have tried setting the following in packages.yaml:
```yaml
mpi:
  require:
    - one_of: ["mpich"]
      when: "target=x86_64_v2"
mpich:
  externals:
    - specs: mpich@4.0 target=x86_64_v2
       prefix: /opt/mpich-4.0
   buildable: false
   require: "target=x86_64_v2"
 all:
   providers:
     mpi: ["openmpi", "mpich"]
```

When i try to concretize something that depends on mpi, like scotch for example, i get mpich correctly for x86_64_v2, but i get mpich also for x86_64_v3 and v4 because they inherit from x86_64_v2. 
Note that because of the order specified in providers, openmpi should be preferred.

If i change packages.yaml:
```yaml
mpi:
  require:
    - one_of: ["mpich"]
      when: "target=x86_64_v2"
    - one_of: ["openmpi"]
      when: "target=x86_64_v4"
```
or
```yaml
mpi:
  require:
    - one_of: ["mpich target=x86_64_v2",  "openmpi"]
```
scotch drops the +mpi variant, and if i force it from CLI the concretizer fails.

```console
$ spack spec scotch+mpi target=x86_64_v4
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    scotch+mpi arch=None-None-x86_64_v4 is unsatisfiable
```

It would be really useful for these cases if syntax like `==`, `>=`, `<=` and `!=` would be introduced for targets (kind of like =@, @: etc for the versions) 

But since this doesn't exist yet, is there another way to obtain the result i'm after?

(Tagging the poor @alalazo because he helped me out on other concretizer issues (sorry :) ) )

### Error message

virtual packages specified for one target are concretized also in children targets.

### Information on your system

* **Spack:** 0.22.0.dev0 (a972314fa6eb8ca15ba0535f13c833c5c1adebf7)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-x86_64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by fgava90** [comment]
Continuing my investigaiton on this issue i have done some concretization tests.
I have tried:
Test 0: any of one mpich specific version
```yaml
mpi:
 require:
  - any_of: ["mpich@4.0"]
```
Obtaining a correct concretization

Test 1: any of 2 mpich versions
```yaml
mpi:
 require:
  - any_of: ["mpich@4.0", "mpich@4.1"]
```
Obtaining
```console
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "mpich"
   2. Cannot satisfy 'mpich@:4.0'
   3. Cannot satisfy 'mpich@4.1'
   4. Cannot satisfy 'mpich@4.0:4.0.3'
   5. Cannot satisfy 'mpich@4.0'
   6. Cannot satisfy 'mpich@4.1'
        required because mpich@4.1 is a requirement for package mpi 
   7. Cannot satisfy 'mpich@4.0'
        required because mpich@4.0 is a requirement for package mpi 
   8. Cannot satisfy 'mpich@4.1' and 'mpich@4.0
        required because mpich@4.0 is a requirement for package mpi 
        required because mpich@4.1 is a requirement for package mpi 
   9. Cannot satisfy 'mpich@4.0' and 'mpich@4.1
        required because mpich@4.0 is a requirement for package mpi 
        required because mpich@4.1 is a requirement for package mpi 
```

Test 2: one of two mpich versions
```yaml
mpi:
 require:
  - one_of: ["mpich@4.0", "mpich@4.1"]
```
Obtaining:
```console
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "mpich"
   2. cannot satisfy a requirement for package 'mpi'.
   3. Cannot satisfy 'mpich@:4.0'
   4. Cannot satisfy 'mpich@4.1'
   5. Cannot satisfy 'mpich@4.0:4.0.3'
   6. Cannot satisfy 'mpich@4.0'
   7. Cannot satisfy 'mpich@4.1'
        required because mpich@4.1 is a requirement for package mpi 
   8. Cannot satisfy 'mpich@4.0'
        required because mpich@4.0 is a requirement for package mpi 
   9. Cannot satisfy 'mpich@4.1' and 'mpich@4.0
        required because mpich@4.1 is a requirement for package mpi 
        required because mpich@4.0 is a requirement for package mpi 
   10. Cannot satisfy 'mpich@4.0' and 'mpich@4.1
        required because mpich@4.1 is a requirement for package mpi 
        required because mpich@4.0 is a requirement for package mpi 
```

Test 3: one of two other mpich specific versions
```yaml
mpi:
 require:
  - one_of: ["mpich@4.0", "mpich@4.0.3"]
```
Obtaining:
```console
==> Error: concretization failed for the following reasons:

   1. cannot satisfy a requirement for package 'mpi'.
```

Test 4: one of specific and generic version
```yaml
mpi:
 require:
  - one_of: ["mpich@4.0", "mpich"]
```
Obtaining
```console
==> Error: concretization failed for the following reasons:

   1. cannot satisfy a requirement for package 'mpi'.
```

Test 5: one of generic mpich and generic openmpi
```yaml
mpi:
 require:
  - one_of: ["mpich", "openmpi"]
```
Obtaining:
```console
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    scotch+mpi is unsatisfiable
```

**Comment by fgava90** [comment]
I have also tried with these settings:
```yaml
packages:
  mpi:
    buildable: false
    require:
      - one_of: [
          "openmpi@1.4.3%gcc@8.5.0 arch=linux-rocky8-x86_64",
          "openmpi@1.4.3%gcc@8.5.0 arch=linux-rocky8-x86_64+debug",
          "openmpi@1.6.5%intel@10.1 arch=linux-rocky8-x86_64"
        ]
  openmpi:
    externals:
      - spec: "openmpi@1.4.3%gcc@8.5.0 arch=linux-rocky8-x86_64"
        prefix: /opt/openmpi-1.4.3
      - spec: "openmpi@1.4.3%gcc@8.5.0 arch=linux-rocky8-x86_64+debug"
        prefix: /opt/openmpi-1.4.3-debug
      - spec: "openmpi@1.6.5%intel@10.1 arch=linux-rocky8-x86_64"
        prefix: /opt/openmpi-1.6.5-intel
```
Adapted from these https://spack.readthedocs.io/en/latest/packages_yaml.html#non-buildable-virtual-packages in the spack documentation (I have only changed the gcc version and the OS name) but still no luck:
```console
$  spack spec scotch%gcc@8.5.0+mpi arch=linux-rocky8-x86_64
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    scotch%gcc@8.5.0+mpi arch=linux-rocky8-x86_64 is unsatisfiable
```
