### ISSUE TITLE
Dependencies of external packages not concretized, and consequently missing from spack environments

### ISSUE THREAD

**Issue by fgava90** [LLNL/spack#41682]
This is not really a bug, but something i find  rather annoying and wanted to know if there was a clean solution to this.

Say I have built externally all OpenMPI dependencies (ucx, hwloc, pmix, slurm, etc...) in a custom location that is not set in PATH.
If i create an environment with a package depending on mpi say:
```yaml
spack:  
  specs:
    - scotch+mpi ^openmpi
   view: true
 ```
 I'll find in my environment the paths to the libraries and binaries of those external packages on which openmpi depends (ucx, hwloc, pmix, slurm, etc).
 Now, if I just declare openmpi as an external package, all those dependencies are no longer concretized (the tree stops at openmpi) and consequently their path is no longer added into the environment.  
When compiling openmpi externally i've done my job correctly so everything has been added in the rpath of the openmpi libraries, so no issues there, however all binaries are of course missing from PATH. 
 Other than adding them manually to PATH or to the list of specs in the environment, is there another solution to concretize also the dependencies of an external package and have them in the spack environment?

**Comment by haampie** [comment]
`spack env activate` should still add externals in non-default system dirs to your PATH.

Adding those packages to the view is intractable.

**Comment by fgava90** [comment]
Yes, it does if they are concretized as part of the environment.


In my case i have set this in my packages.yaml:
```yaml
packages:
    openmpi:
      variants: +pmi +legacylaunchers fabrics=ucx schedulers=slurm
    hwloc:
      externals:
        - spec: hwloc@2.2.0
          prefix: /path/to/hwloc
      buildable: False
    ucx:
      externals:
        - spec: ucxx@1.14.0 ...
          prefix: /path/to/ucx
      buildable: False
    slurm:
      externals:
        - spec: slurm@23-02-4-1 ...
          prefix: /path/to/slurm
      buildable: False
    pmix:
      externals:
        - spec: pmix@5.0.1
          prefix: /path/to/pmix
       buildable: False
```
which yelds to:
```console
$ spac spec mpi
 -  openmpi@4.1.6%gcc@13.2.0 ...
 ...
[e]      ^hwloc@2.2.0%gcc@13.2.0 ...
...
[e]      ^pmix@5.0.1%gcc@13.2.0 ...
[e]      ^slurm@23-02-4-1%gcc@13.2.0 ...
[e]      ^ucx@1.14.0%gcc@13.2.0 ...
...
```
In this case all external paths to hwloc, pmix, slurm and ucx are set by `spack env activate`, which is correct and i'm happy with this.

The issue happens if i set openmpi as well as external, leaving the rest unchanged:
```yaml
packages
  openmpi:
     variants: +pmi +legacylaunchers fabrics=ucx schedulers=slurm
     externals: 
       - spec: openmpi@4.16 +pmi +legacylaunchers fabrics=ucx schedulers=slurm
          prefix: /path/to/openmpi
    hwloc:
      externals:
        - spec: hwloc@2.2.0
          prefix: /path/to/hwloc
      buildable: False
    ucx:
      externals:
        - spec: ucxx@1.14.0 ...
          prefix: /path/to/ucx
      buildable: False
    slurm:
      externals:
        - spec: slurm@23-02-4-1 ...
          prefix: /path/to/slurm
      buildable: False
    pmix:
      externals:
        - spec: pmix@5.0.1
          prefix: /path/to/pmix
       buildable: False     
```
Which now yeads to:
```console
$ spack spec mpi
Input spec
--------------------------------
 -   mpi

Concretized
--------------------------------
[e]  openmpi@4.16%gcc@13.2.0...+legacylaunchers...+pmi  fabrics=ucx schedulers=slurm
```

This second environment does not concretize the openmpi dependencies anymore so it does not add their paths into the environment, and i'd miss command like srun coming from slurm, lstopo coming from hwloc, etc, and if i need to compile something else that links to those libraries, they are not found.

I can understand how this behaviour is somehow expected because openmpi does not need to be built, so its build dependencies are not strictly needed in order to install this environment, but they are still listed as link dependencies in the package.
I have tried editing the openmpi package and change slurm to be also a run dependency but the result doesn't change.
