### ISSUE TITLE
a cargo interface to expose spack packages to rust packages

### ISSUE THREAD

**Issue by cosmicexplorer** [LLNL/spack#41960]
### Summary

Currently, most cargo packages that need to link against C code make use of `pkg-config` through the [`pkg-config` crate](https://crates.io/crates/pkg-config). This is very appropriate for Rust packages written for use in Linux distros, but if `pkg-config` was a sufficient way to pull down every bit of C/C++ code in the world, spack wouldn't need to exist. I often want to write Rust crates to wrap high-performance native-compiled C/C++ code, and I cannot see how to do this without using spack.

### Rationale

Consider the [`hyperscan` crate](https://crates.io/crates/hyperscan). In order to use this Rust crate, the *end user* needs to not only install hyperscan separately, but if they want to use the chimera library feature, the user also needs to download PCRE and set an environment variable in their cargo build (see the README in the link). This is not a reliable way to ship and deploy applications, and more importantly, it shoves off the responsibility of reliably building the hyperscan library to each and every dependee.

One important thing to understand about cargo is that (like spack) it builds everything from source. I believe spack's from-source native-compiled approach aligns much better with cargo's philosophy than distro-specific package managers. However, spack obviously has world-class support for identifying existing package installations as well, so it should be noted that the ability to rely upon local distro package installs is retained.

### Description

I have developed a Rust crate [`spack-rs`](https://github.com/cosmicexplorer/spack-rs) which enables cargo packages to call into spack in a [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) to build and package a spack environment and expose it to cargo. I currently have two example crates incubating in this repo:
- [`re2`](https://crates.io/crates/re2) ([source](https://github.com/cosmicexplorer/spack-rs/tree/main/re2))
- [`vectorscan-async`](https://crates.io/crates/vectorscan-async) ([source](https://github.com/cosmicexplorer/spack-rs/tree/main/vectorscan))

### Additional information

Each of these crates itself has a `*-sys` dependency which actually does the work to link against the native code, which is the standard practice in the Rust community. In this case, that means the `*-sys` crates are what actually invokes spack in their build script--see [`vectorscan-sys`'s build script](https://github.com/cosmicexplorer/spack-rs/blob/main/vectorscan/sys/build.rs). However, spack's execution is modulated by a *declarative* interface in [`Cargo.toml`](https://github.com/cosmicexplorer/spack-rs/blob/754f6cde861ae28650726040553585e9f5b4fc49/vectorscan/sys/Cargo.toml#L18-L47):
```toml
[package.metadata.spack.repo]
path                    = "local-repo"


[package.metadata.spack.envs.vectorscan-static-with-compile]
spec                    = "vectorscan@v5.4.11+static~chimera"
deps                    = { vectorscan = { type = "static", lib_names = ["hs"] } }
features                = { needed = ["static", "compiler"], conflicting = ["chimera"] }


[package.metadata.spack.envs.vectorscan-dynamic-with-compile]
spec                    = "vectorscan@v5.4.11+shared~chimera"
deps                    = { vectorscan = { type = "dynamic", lib_names = ["hs"] } }
features                = { needed = ["dynamic", "compiler"], conflicting = ["chimera"] }


[package.metadata.spack.envs.vectorscan-static-runtime-only]
spec                    = "vectorscan@v5.4.11+static~chimera"
deps                    = { vectorscan = { type = "static", lib_names = ["hs_runtime"] } }
features                = { needed = ["static"], conflicting = ["compiler", "chimera"] }


[package.metadata.spack.envs.vectorscan-dynamic-runtime-only]
spec                    = "vectorscan@v5.4.11+shared~chimera"
deps                    = { vectorscan = { type = "dynamic", lib_names = ["hs_runtime"] } }
features                = { needed = ["dynamic"], conflicting = ["compiler", "chimera"] }


[package.metadata.spack.envs.vectorscan-static-chimera]
spec                    = "vectorscan@v5.4.11+chimera+static"
features                = { needed = ["chimera"] }


[package.metadata.spack.envs.vectorscan-static-chimera.deps]
vectorscan              = { type = "static", lib_names = ["hs", "chimera"] }
pcre                    = { type = "static", lib_names = ["pcre"] }
```

This declarative interface is currently **UNSTABLE** because I'm still trying to make sure it conforms to actual use cases. But the declarative nature is extremely useful to ensure that no Rust code/build script needs to be executed in order to get a complete description of how spack variants map to cargo features!
