### ISSUE TITLE
Spack doesn't concreatize the env with a specific already installed compiler

### ISSUE THREAD

**Issue by HealthyPear** [LLNL/spack#42007]
### Steps to reproduce

`spack install gcc@13.2.0`

`spack compiler add gcc@13.2.0`

now `spack compilers` gives the following

==> Available compilers
-- gcc ubuntu20.04-x86_64 ---------------------------------------
gcc@9.4.0  gcc@7.5.0  gcc@13.2.0

now I create and environment

`spack env create my_env my_env.yaml`

`my_env.yaml` contains something like this

```
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - boost+filesystem+iostreams+program_options+python+random+regex+system+test+thread cxxstd==14
  - root@6.28.06+tmva cxxstd==14
  - xcdf
  - healpix-cxx
  - photospline
  - doxygen
  - fftw~mpi
  - geant4@10.0.4+opengl+x11~threads cxxstd==14
  - xerces-c cxxstd==14
  view: true
  concretizer:
    unify: true
```

but then I did

`spack config add "packages:all:compiler:[gcc@13.2.0]"`

and indeed `spack config --scope env:aerie-dev get packages` gives

```yaml
packages:
  all:
    compiler: [gcc@13.2.0]
```
### Error message

not really an error, anyway e.g.

```
[+] /mnt/data27/spack/opt/spack/linux-ubuntu20.04-ivybridge/gcc-9.4.0/libpthread-stubs-0.4-yp7yaiitecdkjuinvtonk2nlnkdummbu
==> Installing fftw-3.3.10-voac3hq7zrowkzjtlustm6cgxuhmn6ca [25/143]
```

as you can see 13.2.0 is not used

### Information on your system

* **Spack:** 0.22.0.dev0 (6f9151481418555041f11ca690608307e6df9595)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-ivybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
