### ISSUE TITLE
"platform 'cray' not allowed" when using v0.21 to add packages to env built with v0.19

### ISSUE THREAD

**Issue by todbadrakh** [LLNL/spack#42035]
## Problem

I would like to use Spack v0.21 to install new versions of packages (with new external dependencies, i.e. hip/rocm) onto an existing stack built with v0.19 on a Cray platform but am getting `platform 'cray' not allowed on the current host`. @scheibelp and I had a discussion on this at the 1/10/24 [telcon](https://github.com/spack/spack/wiki/Telcon:-2024-01-10).

## Approach
I am adding new specs to the old `spack.yaml` file. In the example below, the old specs have `arch=cray-sles15-zen3` and the desired new packages have `arch=linux-sles15-zen3` due to Spack dropping the `cray` platform as an option. I had hoped that the old specs would not throw errors as they are installed already.
```
  - cpe_gcc_specs:
    - matrix:
      - - $e4s_21.11_cpu_specs
        - $e4s_21.11_gpu_packages_rocm4.5.0
        - $e4s_22.02_cpu_specs
        - $e4s_22.02_gpu_packages_rocm4.5.0
      - - '%gcc@11.2.0'
        - '%gcc@10.3.0'
      - - arch=cray-sles15-zen3
    ### new packages
    - matrix:
      - - $e4s_21.11_gpu_packages_rocm5.7.1
        - $e4s_22.02_gpu_packages_rocm5.7.1
      - - '%gcc@12.2.0'
      - - arch=linux-sles15-zen3
```
Attached `spack.yaml` file:  [spack.yaml](https://github.com/spack/spack/files/13891583/spack.yaml.txt)
(had to rename to `txt` file b/c github will not upload `yaml` files)
Attached database file: 
[index.json.zip](https://github.com/spack/spack/files/13891669/index.json.zip)

## Error
```
$ spack concretize
==> Error: concretization failed for the following reasons:

   1. platform 'cray' is not allowed on the current host
```
```
$ spack concretize -U
==> Error: concretization failed for the following reasons:

   1. platform 'cray' is not allowed on the current host
```
```
$ spack concretize -Uf
==> Error: concretization failed for the following reasons:

   1. platform 'cray' is not allowed on the current host
   2. Cannot select a single "node_platform" for package "numactl"
```

## Desired outcome
I would like to see if there's a way to trick Spack into accepting `cray` as a platform so that I can keep the already-existing packages and their associated modules directory structure intact.
