### ISSUE TITLE
External Package with Modulefile -- Consideration in Dependency Tree

### ISSUE THREAD

**Issue by roeverf** [LLNL/spack#42102]
### Summary

We would like to use intel-mpi (installed externally) for a package in spack e.g. for boost.
We declared intel-mpi as an external package for spack as follows (packages.yaml):
```
packages:
  intel-mkl:
    externals:
    - spec: "intel-mkl@2023.2"
      modules:
      - intel-mkl/2023.2
      buildable: False
  all:
    providers:
      mpi: [openmpi, intel-mpi]

```
Using now the following command to install boost:
```
spack install boost%oneapi +graph_parallel +iostreams +json +locale +log +math +python +timer +mpi ^intel-mpi
```
The installation of boost works fine, however the generated module file  contains a dependency to a "newly" generated intel-mpi module, declared as follows:
```
depends_on("intel-mpi/oneapi/2023.2.0/.2023.2-sagf5xs")
```
This module does not exist, however `spack find intel-mpi ` shows  this as an installed package:

```
$ spack find -vfL intel-mpi
-- linux-rocky8-cascadelake / oneapi@2023.2.0 -------------------
sagf5xs5mboqapeswsz7ikzpn5d3ya4c intel-mpi@2023.2%oneapi ~external-libfabric build_system=generic
==> 1 installed package
```

### Description

Would it be possible to replace the dependency on intel-mpi as a spack package with hash to the exact external package, such that the external modulefile is used or to generate a module-file fitted to the hash?
Our workaround so far is a symlink from the hashed modulefile to the external modulfile. 

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
