### ISSUE TITLE
Sticky variants seem to not be working with externals

### ISSUE THREAD

**Issue by white238** [LLNL/spack#42172]
### Steps to reproduce

Create environment file with an external cuda and clang that are unsupported together (clang@16.0.6 and cuda@12.2.2).

Partial `spack.yaml`:
```
  'compilers:':
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        # Required as spack cannot recognize compiler-specific linker
        # flags in mixed toolchains
        ldlibs: -lgfortran
      modules: []
      operating_system: rhel7
      paths:
        cc: /usr/tce/packages/clang/clang-ibm-16.0.6-gcc-8.3.1/bin/clang
        cxx: /usr/tce/packages/clang/clang-ibm-16.0.6-gcc-8.3.1/bin/clang++
        f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
        fc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      spec: clang@16.0.6
      target: ppc64le

  packages:
    cuda:
      externals:
      - spec: cuda@12.2.2+allow-unsupported-compilers
        prefix: /usr/tce/packages/cuda/cuda-12.2.2
      buildable: false
```

```
spack -D <path to environment that has cuda+allow-unsupported-compilers> spec cuda
```

### Error message

Partial error:

```
==> Error: concretization failed for the following reasons:

   1. Attempted to use external for 'cuda' which does not satisfy any configured external spec
   2. umpire: '%clang@16:' conflicts with '+cuda ^cuda@:12.3~allow-unsupported-compilers'
   3. serac: '%clang@16:' conflicts with '+cuda ^cuda@:12.3~allow-unsupported-compilers'
   4. raja: '%clang@16:' conflicts with '+cuda ^cuda@:12.3~allow-unsupported-compilers'
   5. mfem: '%clang@16:' conflicts with '+cuda ^cuda@:12.3~allow-unsupported-compilers'
   6. camp: '%clang@16:' conflicts with '+cuda ^cuda@:12.3~allow-unsupported-compilers'
```

### Information on your system

Machine name: Lassen
OS: blueos

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
