### ISSUE TITLE
Request for clearer error message on certain errors in spack.yaml

### ISSUE THREAD

**Issue by wdconinc** [LLNL/spack#42218]
### Summary

With `spack.yaml`
```yaml
spack:
  specs:
  - zlib=1.3
  view: true
  concretizer:
    unify: true
```
you get
```
$ spack concretize
==> Error: Invalid module name: 
$
```

### Rationale

The error message does not include anything that can help identify where or why there is a problem. A typo in a 6-line spack.yaml is easier to find than in a 200-line spack.yaml.

Even `spack -d concretize` does not give more information.

### Description

A possible solution would show the line number in spack.yaml where the issue occurred. 

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
