### ISSUE TITLE
flux security not found

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#42977]
Posting for tomorrow (to ask for help) - @grondo I'm installing this spack.yaml

```yaml
spack:
  specs:
  - openmpi@4.1.2%gcc@11.4.0 fabrics=ofi +legacylaunchers
  - libfabric@1.18.1%gcc@11.4.0 fabrics=efa,tcp,udp,sockets,verbs,shm,mrail,rxd,rxm
  - flux-core%gcc@11.4.0 +security
  - flux-sched%gcc@11.4.0
  - flux-pmix%gcc@11.4.0
  - flux-security%gcc@11.4.0
  concretizer:
    unify: true
  config:
    install_tree:
      root: /opt/software
  view: /opt/view
  compilers:
  - compiler:
      spec: clang@=14.0.0
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: null
        fc: null
      flags: {}
      operating_system: ubuntu22.04
      target: aarch64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=11.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu22.04
      target: aarch64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=12.3.0
      paths:
        cc: /usr/bin/gcc-12
        cxx: null
        f77: null
        fc: null
      flags: {}
      operating_system: ubuntu22.04
      target: aarch64
      modules: []
      environment: {}
      extra_rpaths: []
```
which superficially looks OK, and I can confirm flux security installs and the version.h is in the spack opt:

```
$ ls /opt/software/linux-ubuntu22.04-neoverse_v1/gcc-11.4.0/flux-security-0.10.0-awpaw72i3kyf46dqqi5i2kuywebhomx3/include/flux/security/
context.h  sign.h  version.h
```
But when it installs, it throws up.

```
   >> 2042    /tmp/ubuntu/spack-stage/spack-stage-flux-core-0.59.0-hv6cfoojgadhoyjpmwx2s7hw3fl55oik/spack-src/src/modules/job-exec/exec_config.c:21:10: fatal error: flux/security/version.h: No such file or directory
     2043       21 | #include <flux/security/version.h>
     2044          |          ^~~~~~~~~~~~~~~~~~~~~~~~~
     2045    compilation terminated.
  >> 2046    make[3]: *** [Makefile:882: exec_config.lo] Error 1
```
The "fix" I did was to move it to a system location that would be found:

```
sudo cp -R /opt/software/linux-ubuntu22.04-neoverse_v1/gcc-11.4.0/flux-security-0.10.0-awpaw72i3kyf46dqqi5i2kuywebhomx3/include/flux /usr/include/flux
```
And that allowed me to finish the install. But I suspect something is going wrong here with spack not adding the correct include path for the view? Maybe @alalazo you might have insight too.
