### ISSUE TITLE
hierarchical modules; 'environment_blacklist' was unexpected

### ISSUE THREAD

**Issue by johebll** [LLNL/spack#43055]
### Steps to reproduce

I want to configure Spack 0.21.1 to generate Lmod hierarchical modules in the Core/Compiler/MPI hierarchy, and start with the core config according to the Spack online documentation at https://spack-tutorial.readthedocs.io/en/ecp21/.

modules.yaml:
````
modules:
  enable::
    - lmod
  lmod:
    core_compilers:
      - 'gcc@7.5.0'
    hierarchy:
      - mpi
      - lapack
    hash_length: 0
    whitelist:
      - gcc
    blacklist:
      - '%gcc@7.5.0'
    all:
      filter:
        environment_blacklist:
          - "C_INCLUDE_PATH"
          - "CPLUS_INCLUDE_PATH"
          - "LIBRARY_PATH"
      environment:
        set:
          '{name}_ROOT': '{prefix}'
    openmpi:
      environment:
        set:
          SLURM_MPI_TYPE: pmi2
          OMPI_MCA_btl_openib_warn_default_gid_prefix: '0'
    projections:
      all:          '{name}/{version}'
````
But creating the modules always fail with the same error.

### Error message

````
spack module lmod refresh --delete-tree -y
==> Error: modules.yaml: Additional properties are not allowed ('environment_blacklist' was unexpected)
````

### Information on your system

````
spack debug report
* **Spack:** 0.21.1 (e30fedab102f9281a220fb4fae82e3f8c43a82ac)
* **Python:** 3.9.18
* **Platform:** linux-rocky9-broadwell
* **Concretizer:** clingo
````

I also tried to add this code to the default "etc/spack/defaults/modules.yaml", but that generates the same error.

If i remove/comment "environment_blacklist", the error disappears.

Isn't "environment_blacklist" valid for Lmod type of modules?
Or do i miss some fundamental point here?

Thank you in advance.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
