### ISSUE TITLE
Installation issue: pflotran@5.0.0%oneapi

### ISSUE THREAD

**Issue by dubmarm** [LLNL/spack#43154]
### Steps to reproduce the issue

```console
$ spack spec -I pflotran
Input spec
--------------------------------
 -   pflotran

Concretized
--------------------------------
 -   ygln4cn  pflotran@5.0.0%oneapi@2022.2.1~rxn build_system=autotools arch=linux-centos7-cascadelake
[+]  taxayrn      ^gmake@4.4.1%gcc@11.3.0~guile build_system=generic arch=linux-centos7-cascadelake
[+]  i2o6k2r      ^hdf5@1.14.3%oneapi@2022.2.1+cxx+fortran+hl~ipo~java~map+mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-centos7-cascadelake
[+]  fhemdtk          ^cmake@3.27.7%gcc@11.3.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-centos7-cascadelake
[+]  3bsgbua              ^curl@8.4.0%gcc@11.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-centos7-cascadelake
[+]  5l3gibs                  ^nghttp2@1.57.0%gcc@11.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]  7jtmg53              ^ncurses@6.4%gcc@11.3.0~symlinks+termlib abi=none build_system=autotools arch=linux-centos7-cascadelake
[+]  25jfobv          ^pkgconf@1.9.5%gcc@11.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]  7hdqddc          ^zlib-ng@2.1.4%gcc@11.3.0+compat+opt build_system=autotools arch=linux-centos7-cascadelake
[e]  nrd72h4      ^intel-oneapi-mpi@2021.7.1%oneapi@2022.2.1+envmods~external-libfabric+generic-names~ilp64 build_system=generic arch=linux-centos7-cascadelake
[+]  5fvfdkz      ^petsc@3.20.1%oneapi@2022.2.1~X~batch~cgns~complex~cuda~debug+double~exodusii+fftw+fortran~giflib+hdf5~hpddm~hwloc+hypre+int64~jpeg~knl~kokkos~libpng~libyaml~memkind+metis~mkl-pardiso~mmg~moab~mpfr+mpi~mumps+openmp~p4est~parmmg~ptscotch~random123~rocm~saws~scalapack+shared~strumpack~suite-sparse+superlu-dist~sycl~tetgen~trilinos~valgrind build_system=generic clanguage=C memalign=none arch=linux-centos7-cascadelake
[+]  wuc6owb          ^diffutils@3.9%gcc@11.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]  hvr65m7              ^libiconv@1.17%gcc@11.3.0 build_system=autotools libs=shared,static arch=linux-centos7-cascadelake
[+]  d653sgd          ^fftw@3.3.10%oneapi@2022.2.1+mpi+openmp~pfft_patches build_system=autotools precision=double,float arch=linux-centos7-cascadelake
[+]  ywijhzd          ^hypre@2.29.0%oneapi@2022.2.1~caliper~complex~cuda~debug+fortran~gptune+int64~internal-superlu~magma~mixedint+mpi+openmp~rocm+shared+superlu-dist~sycl~umpire~unified-memory build_system=autotools arch=linux-centos7-cascadelake
[e]  plhhvsd          ^intel-oneapi-mkl@2022.2.1%oneapi@2022.2.1~cluster+envmods~ilp64+shared build_system=generic mpi_family=none threads=openmp arch=linux-centos7-cascadelake
[+]  r5wjaz4          ^metis@5.1.0%oneapi@2022.2.1~gdb+int64~ipo+real64+shared build_system=cmake build_type=Release generator=make patches=4991da9,93a7903 arch=linux-centos7-cascadelake
[+]  3nid5b5          ^parmetis@4.0.3%oneapi@2022.2.1~gdb+int64~ipo+shared build_system=cmake build_type=Release generator=make patches=4f89253,50ed208,704b84f arch=linux-centos7-cascadelake
[+]  4dpag5d          ^python@3.11.6%gcc@11.3.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-centos7-cascadelake
[+]  xfygdfg              ^bzip2@1.0.8%gcc@11.3.0~debug+pic+shared build_system=generic arch=linux-centos7-cascadelake
[+]  cbosk6z              ^expat@2.5.0%gcc@11.3.0+libbsd build_system=autotools arch=linux-centos7-cascadelake
[+]  swzhaxs                  ^libbsd@0.11.7%gcc@11.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]  fo7p4zt                      ^libmd@1.0.4%gcc@11.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]  5fkmgpb              ^gdbm@1.23%gcc@11.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]  vpgnzm7              ^gettext@0.22.3%gcc@11.3.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-centos7-cascadelake
[+]  2eot3sc                  ^libxml2@2.10.3%gcc@11.3.0+pic~python+shared build_system=autotools arch=linux-centos7-cascadelake
[+]  gpfewpg                  ^tar@1.34%gcc@11.3.0 build_system=autotools zip=pigz arch=linux-centos7-cascadelake
[+]  ybi34hj                      ^pigz@2.7%gcc@11.3.0 build_system=makefile arch=linux-centos7-cascadelake
[+]  euqnuez                      ^zstd@1.5.5%gcc@11.3.0+programs build_system=makefile compression=none libs=shared,static arch=linux-centos7-cascadelake
[+]  iakepfh              ^libffi@3.4.4%gcc@11.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]  w57jsnq              ^libxcrypt@4.4.35%gcc@11.3.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-centos7-cascadelake
[+]  dev4gii                  ^perl@5.38.0%gcc@11.3.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-centos7-cascadelake
[+]  3ldbzzt                      ^berkeley-db@18.1.40%gcc@11.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-centos7-cascadelake
[+]  s45h7ud              ^openssl@3.1.3%gcc@11.3.0~docs+shared build_system=generic certs=mozilla arch=linux-centos7-cascadelake
[+]  2qjhnlp                  ^ca-certificates-mozilla@2023-05-30%gcc@11.3.0 build_system=generic arch=linux-centos7-cascadelake
[+]  whnskdj              ^readline@8.2%gcc@11.3.0 build_system=autotools patches=bbf97f1 arch=linux-centos7-cascadelake
[+]  rhvu3nw              ^sqlite@3.43.2%gcc@11.3.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-centos7-cascadelake
[+]  6lfwkhz              ^util-linux-uuid@2.38.1%gcc@11.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]  ikkkd5w              ^xz@5.4.1%gcc@11.3.0+pic build_system=autotools libs=shared,static arch=linux-centos7-cascadelake
[+]  qrvm5k5          ^superlu-dist@8.1.2%oneapi@2022.2.1~cuda+int64~ipo+openmp~rocm+shared build_system=cmake build_type=Release generator=make arch=linux-centos7-cascadelake
```

### Error message

<details><summary>Error message</summary>

<pre>
     33    /msc/omega/apps/compiler/oneapi/mpi/2021.7.1/bin/mpifc -o geomechanics_field.o -c -fPIC -g -O3   -fopenmp  -I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_pa
           th_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/petsc-3.20.1-5fvfdkzjionkjnewfxifgqsxm3rvh534/include -I/msc/omega/apps/spack-bu
           ilds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/hypre-2.29.0-ywijhzd2dn4ko5o2u4wm
           pujnuyyq3mzh/include -I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/on
           eapi-2022.2.1/superlu-dist-8.1.2-qrvm5k5opnnfxutago7skn75faifim2m/include -I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_pla
           ceholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/fftw-3.3.10-d653sgdaqhlo2lbnimep5wg5xofhv7de/include -I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spa
           ck/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/parmetis-4.0.3-3nid5b5pnwvk35az7q7nwzd6yczy5nao/include -I/msc/omeg
           a/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/metis-5.1.0-r5wjaz
           4pdxs4opjoizhcvjiiqfxcn2ne/include -I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-
           cascadelake/oneapi-2022.2.1/hdf5-1.14.3-i2o6k2rozdopfkjkv36xmnlzlc6bwrsl/include  -fopenmp -I.  `pwd`/geomechanics_field.F90
  >> 34    /tmp/dubi037/spack-stage/spack-stage-pflotran-5.0.0-ygln4cne4yb6nk7ppubkmq3goev6ajg2/spack-src/src/pflotran/petsc_utility.F90(42): error #6285: There is no matching specific subrou
           tine for this generic subroutine call.   [MATSETVALUESBLOCKEDLOCAL]
     35      call MatSetValuesBlockedLocal(A,1,irow-1,1,icol-1,ndof_mat,ADD_VALUES, &
     36    -------^
     37    compilation aborted for /tmp/dubi037/spack-stage/spack-stage-pflotran-5.0.0-ygln4cne4yb6nk7ppubkmq3goev6ajg2/spack-src/src/pflotran/petsc_utility.F90 (code 1)
  >> 38    make[1]: *** [/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022
           .2.1/petsc-3.20.1-5fvfdkzjionkjnewfxifgqsxm3rvh534/lib/petsc/conf/rules:169: petsc_utility.o] Error 1
     39    make[1]: *** Waiting for unfinished jobs....
     40    make[1]: Leaving directory '/tmp/dubi037/spack-stage/spack-stage-pflotran-5.0.0-ygln4cne4yb6nk7ppubkmq3goev6ajg2/spack-src/src/pflotran'
  >> 41    failed building pflotran, libpflotran.a, and/or libpflotranchem.a
  >> 42    make: *** [makefile:15: all] Error 1
</pre></details>

### Information on your system

```console
[oneapi] [dubi037@o1 oneapi]$ spack debug report
* **Spack:** 0.21.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo
```

Spack is not properly managing the external oneapi environment with regards to pflotran. Specifically, the failing command can be resolved by doing the following:

```bash
spack stage pflotran
pushd /pflotran/stage/dir/spack-src/src/pflotran
module load gcc

# this is key to resolving
export I_MPI_FC="ifx"

#re-execute the failed command
/msc/omega/apps/compiler/oneapi/mpi/2021.7.1/bin/mpifc -o geomechanics_field.o -c -fPIC -g -O3 -fopenmp  \
-I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/petsc-3.20.1-5fvfdkzjionkjnewfxifgqsxm3rvh534/include \
-I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/hypre-2.29.0-ywijhzd2dn4ko5o2u4wmpujnuyyq3mzh/include \
-I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/superlu-dist-8.1.2-qrvm5k5opnnfxutago7skn75faifim2m/include \
-I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/fftw-3.3.10-d653sgdaqhlo2lbnimep5wg5xofhv7de/include \
-I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/parmetis-4.0.3-3nid5b5pnwvk35az7q7nwzd6yczy5nao/include \
-I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/metis-5.1.0-r5wjaz4pdxs4opjoizhcvjiiqfxcn2ne/include \
-I/msc/omega/apps/spack-builds/spack-0.21.1-20240311/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_/linux-centos7-cascadelake/oneapi-2022.2.1/hdf5-1.14.3-i2o6k2rozdopfkjkv36xmnlzlc6bwrsl/include \
-fopenmp -I.  `pwd`/geomechanics_field.F90
```

Because the failing command is executing `oneapi/mpi/2021.7.1/bin/mpifc` ; this means that mpifc is failing to properly associate with the oneapi fortran compiler. The environment `I_MPI_FC` is supposed to be managed by the `compiler/2022.2.1` module listed in the compiler definition:

```yaml
  - compiler:
      spec: oneapi@=2022.2.1
      paths:
        cc: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/icx
        cxx: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/icpx
        f77: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/ifx
        fc: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/ifx
      flags: {}
      operating_system: centos7
      target: x86_64
      modules:
      - gcc@=11.3.0
      - oneapi@=2022.2.1
      - tbb/2021.7.1
      - compiler-rt/2022.2.1
      - oclfpga/2022.2.1
      - compiler/2022.2.1
      environment: {}
      extra_rpaths: []
```
Again, this appears to mean that for `pflotran%oneapi` ; mpi is failing to find `ifx` 

spack.yaml
```yaml
spack:
  view: false
  config:
    install_tree:
      padded_length: 128
      install_missing_compilers: true
  concretizer:
    reuse: true
    unify: false
  compilers:
  - compiler:
      spec: intel@=2021.7.1
      paths:
        cc: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/intel64/icc
        cxx: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/intel64/icpc
        f77: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/intel64/ifort
        fc: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/intel64/ifort
      flags: {}
      operating_system: centos7
      target: x86_64
      modules:
      - gcc@=11.3.0
      - intel@=2021.7.1
      - tbb/2021.7.1
      - compiler-rt/2022.2.1
      - icc/2022.2.1
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: oneapi@=2022.2.1
      paths:
        cc: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/icx
        cxx: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/icpx
        f77: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/ifx
        fc: /msc/omega/apps/compiler/oneapi/compiler/2022.2.1/linux/bin/ifx
      flags: {}
      operating_system: centos7
      target: x86_64
      modules:
      - gcc@=11.3.0
      - oneapi@=2022.2.1
      - tbb/2021.7.1
      - compiler-rt/2022.2.1
      - oclfpga/2022.2.1
      - compiler/2022.2.1
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=11.3.0
      paths:
        cc: /cluster/apps/compiler/gcc/11.3.0/bin/gcc
        cxx: /cluster/apps/compiler/gcc/11.3.0/bin/g++
        f77: /cluster/apps/compiler/gcc/11.3.0/bin/gfortran
        fc: /cluster/apps/compiler/gcc/11.3.0/bin/gfortran
      flags: {}
      operating_system: centos7
      target: x86_64
      modules:
      - gcc/site-11.3.0
      environment: {}
      extra_rpaths: []
  specs:
  # if it's GNU (gmake, pkgconf), use GCC
  # if it's a build package (cmake, ninja), use GCC
  # if it's X11/graphics (vtk, paraview), use GCC
  # if it's a language (python, r), use GCC
  # Only install OneAPI/Intel for the programs you NEED
  - mpifileutils
  - netcdf-c
  - netcdf-fortran
  - parallel-netcdf
  - parallelio
  - hdf5
  - nco
  - cdo
  - esmf
  - petsc
  - pflotran
  - wps
  packages:
    all:
      require: '%gcc@11.3.0' # this matters! it says to build everything with GCC and NOT intel, intel can't build everything
      compiler: [oneapi@2022.2.1, intel@2021.7.1, gcc@11.3.0]
      variants: +mpi +pic +shared +fortran +openmp +external-lapack +lustre ~cuda
        +xz +hdf5
    mpi:
      require: intel-oneapi-mpi
    mkl:
      require: intel-oneapi-mkl
    blas:
      require: intel-oneapi-mkl
    lapack:
      require: intel-oneapi-mkl
    scalapack:
      require: intel-oneapi-mkl+cluster
    tbb:
      require: intel-oneapi-tbb
    lustre:
      buildable: false
      externals:
      - spec: lustre@2.14.0_ddn54
        prefix: /usr
    slurm:
      buildable: false
      externals:
      - spec: slurm@23.11.1
        prefix: /usr
    ucx:
      buildable: false
      externals:
      - spec: "ucx@1.16.0 +cma +cuda +gdrcopy ~java +knem ~optimizations ~parameter_checking +rdmacm ~rocm +verbs +xpmem"
        prefix: /usr
    rdma-core:
      buildable: false
      externals:
      - spec: rdma-core@47.0
        prefix: /usr
    libfabric:
      buildable: false
      externals:
      - spec: "libfabric@1.13.2%oneapi fabrics=mlx,psm3,shm,sockets,tcp,verbs"
        prefix: /msc/omega/apps/compiler/oneapi/
        modules:
        - mpi/2021.7.1
    intel-oneapi-mpi:
      require: '@2021.7.1%oneapi +generic-names'
      externals:
      - spec: intel-oneapi-mpi@2021.7.1
        prefix: /msc/omega/apps/compiler/oneapi/
        modules:
        - mpi/2021.7.1
    intel-oneapi-mkl:
      require: '@2022.2.1%oneapi threads=openmp'
      externals:
      - spec: intel-oneapi-mkl@2022.2.1
        prefix: /msc/omega/apps/compiler/oneapi/
        modules:
        - mkl/2022.2.1
    intel-oneapi-tbb:
      require: '@2021.7.1%oneapi'
      externals:
      - spec: "intel-oneapi-tbb@2021.7.1%oneapi"
        prefix: /msc/omega/apps/compiler/oneapi/
        modules:
        - tbb/2021.7.1
    mpifileutils:
      require: '%oneapi +lustre'
    hdf5:
      require: '%oneapi +hl +shared +cxx +fortran'
    netcdf-c:
      require: '%oneapi'
    netcdf-fortran:
      require: '%oneapi'
    parallel-netcdf:
      require: '%oneapi'
    parallelio:
      require: '%oneapi'
    nco:
      require: '%oneapi'
    cdo:
      require: '%oneapi'
    esmf:
      # does not accept oneapi http://earthsystemmodeling.org/docs/nightly/develop/ESMF_usrdoc/node10.html
      # setting +external-parallelio will automatically set esmf_pio=external
      require: '%intel +mpi +external-parallelio +external-lapack +pnetcdf +netcdf'
    petsc:
      require: '%oneapi +hdf5 +fftw +openmp +fortran'  # requires superlu-dist
    pflotran:
      require: '%oneapi'
    wrf:
      require: '%intel'
    wps:
      require: '%intel'
    fftw:
      require: '%oneapi +openmp'
    hypre:
      require: '%oneapi +openmp +int64 +superlu-dist'
    metis:
      require: '%oneapi +int64 +real64'
    parmetis:
      require: '%oneapi +int64'
    superlu-dist:
      require: '%oneapi +int64 +openmp' #does not build with system intel, nor gcc@4.8.5
```

### Additional information

@mention balay 
@mention ghammond86

[spack-build-env.txt](https://github.com/spack/spack/files/14579834/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/14579835/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
