### ISSUE TITLE
Environments and matrices of compilers: reduce mixing

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#43475]
### Summary

Say you want to build a set of specs together, and you want to rebuild that set again for another compiler. Environments provide a mechanism for expressing this succinctly:

```
spack:
  specs:
    - matrix:
        - [x, y, ...]
        - ['%gcc', '%clang']
  concretizer:
    unify: when_possible
```

The problem is that

* This requires `unify: when_possible`
* For each `x`, the concretization can mix compilers for different dependencies in the DAG

We'd like a mechanism like being able to expand this matrix and force `unify: true` for each resulting "vector".

### Rationale

This has been reported by several users who find the behavior confusing (but this behavior is not strictly speaking a violation of any of our advertised functionality). If one creates an environment for each resulting vector, the problem goes away, but for larger matrices that would be tedious.

### Additional information

Related: https://github.com/spack/spack/issues/27829

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
