### ISSUE TITLE
Installation issue: atlas

### ISSUE THREAD

**Issue by curtisecombsjr** [LLNL/spack#43503]
### Steps to reproduce the issue

```console
alogin01:~ # spack spec -I atlas%intel@19.1.3.304
Input spec
--------------------------------
 -   atlas%intel@19.1.3.304

Concretized
--------------------------------
 -   atlas@3.10.3%intel@19.1.3.304+shared build_system=generic threads=none tune_cpu=-1 arch=linux-sles15-zen2

alogin01:~ #
```

### Error message

<details><summary>lib/Makefile: No such file or directory</summary>

<pre>
  >> 97     make: *** [Makefile:542: startup] Error 2
  >> 98     mv: cannot stat 'lib/Makefile': No such file or directory
  >> 99     ./../configure: line 482: lib/Makefile: No such file or directory
  >> 100    ./../configure: line 483: lib/Makefile: No such file or directory
  >> 101    ./../configure: line 484: lib/Makefile: No such file or directory
  >> 102    ./../configure: line 485: lib/Makefile: No such file or directory
  >> 103    ./../configure: line 534: lib/Makefile: No such file or directory
  >> 104    ./../configure: line 535: lib/Makefile: No such file or directory
  >> 105    ./../configure: line 536: lib/Makefile: No such file or directory
  >> 106    ./../configure: line 541: lib/Makefile: No such file or directory
     107    DONE configure
     108    ==> [2024-04-05-06:19:41.989285] 'make' '-j1'
     109    make -f Make.top build
     110    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-atlas-3.10.3-mezzb6jmxz4ibyc6c3v4c2kqq7dwt3fx/spack-src/spack-build'
  >> 111    Make.top:1: Make.inc: No such file or directory
  >> 112    make[1]: *** No rule to make target 'Make.inc'.  Stop.
</pre></details>

### Information on your system

alogin01:~ # spack debug report
* **Spack:** 0.21.1
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2
* **Concretizer:** clingo
alogin01:~ #

### Additional information

[atlas-build-env.txt](https://github.com/spack/spack/files/14880732/atlas-build-env.txt)
[atlas-build-out.txt](https://github.com/spack/spack/files/14880739/atlas-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by curtisecombsjr** [comment]
"spack maintainers atlas" does not return any maintainers, sorry

**Comment by curtisecombsjr** [comment]
compiler configuration:

```
- compiler:
    spec: intel@19.1.3.304
    paths:
      cc: /pe/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64/icc
      cxx: /pe/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64/icpc
      f77: /pe/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64/ifort
      fc: /pe/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - craype-x86-rome
    - libfabric/1.12.1.2.2.0.2
    - craype-network-ofi
    - PrgEnv-intel/8.1.0
    - intel/19.1.3.304
    - craype/2.7.10
    - cray-mpich/8.1.12
    environment: {}
    extra_rpaths: []
```
