### ISSUE TITLE
Cannot concretize with `config:install_missing_compilers:true` 

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#43875]
### Steps to reproduce

Trying to concretize a simple environment like:
```yaml
spack:
  specs:
  - zlib-ng %gcc@=13.2.0
  view: true
  config:
    install_missing_compilers: true
  concretizer:
    unify: true
```
fails with a missing compiler error.

### Error message

```console
==> Error: concretization failed for the following reasons:

   1. No valid version for 'zlib-ng' compiler 'gcc' satisfies '@13'
```

### Information on your system

* **Spack:** 0.22.0.dev0 (9d86633fee57eb5c1a3a5921c535ff94bf0c958a)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
