### ISSUE TITLE
How to resolve conflicting compiler entries in packages/compilers config

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#43927]
### Steps to reproduce

(EDIT: it was pointed out in https://github.com/spack/spack/issues/43927#issuecomment-2090448740 that I mixed up the precedence between compilers.yaml and packages.yaml: compilers.yaml overrides; I've swapped everything accordingly but the problem description is nearly identical minus that swap)

Now that compilers can live in `packages.yaml` and `compilers.yaml`, we should think on how to handle cases where users edit `packages.yaml` not knowing that their changes may be ignored (if there is a duplicate compiler ID in `compilers.yaml`)

To replicate:

First, be on a system where `gcc` is available in your PATH (or make that true)

Initial setup (in particular ensuring a clean, fresh config)

```
git clone https://github.com/spack/spack.git
cd spack
mkdir misc-cache
export SPACK_USER_CACHE_PATH=`pwd`/misc-cache
export SPACK_DISABLE_LOCAL_CONFIG=true
. share/spack/setup-env.sh
```

once you have a clean config:

```
spack env create test
spack env activate test
spack spec zlib # this adds the gcc compiler to compilers.yaml
spack external find gcc # this adds a compiler to packages.yaml
```

Now, if you manually edit the packages.yaml entry (e.g. to add flags), it will be ignored.

### Error message

~There is no error message.~ There is a warning: it doesn't explain the precedence or which thing to get rid of to get the flag behavior you want.

This behavior is deliberate (see `compilers/__init__.all_compilers_config()`)

I think it would be worth throwing an error if duplicate ID's have mismatched flags (actually, it's fine if the `compilers.yaml` instance has it, but if the `packages.yaml` instance has them, we ought to fail or warn).

### Information on your system

```
* **Spack:** 0.22.0.dev0 (49d3eb1723a2c7220883acfd2a24860a15ed4ef3)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
@becker33 @alalazo FYI (you each appear in the `git blame` for the relevant function)

**Comment by white238** [comment]
Thanks for looking into this @scheibelp !

**Comment by haampie** [comment]
I suggested to allow `packages:*:extra_attributes:compilers:false`. I think it's better to hold off on autodetecting compilers with `spack external find` until `compilers.yaml` is dropped. Or do it behind a flag `external find --compilers`. Otherwise it's very confusing conceptually, and I've already wasted time troubleshooting issues.

Ping @alalazo

**Comment by alalazo** [comment]
~Right now we prefer compiler definitions in `packages.yaml` to those in `compilers.yaml`:~

https://github.com/spack/spack/blob/2eb7add8c43af833fd665f7b617ae8b6890cebd9/lib/spack/spack/compilers/__init__.py#L339-L348

I think the idea a couple months ago was to arrive at v0.22 with compilers defined in `packages.yaml`, and get rid of `compilers.yaml` alltogether. I'm not sure if we can make it now, ~but in case we can invert the current priority order, and have `compilers.yaml` be the preferred configuration file in case of duplicates.~

EDIT: let me double check, cause I think we already prefer `compilers.yaml` :thinking:

**Comment by alalazo** [comment]
@scheibelp As noted above, I can't reproduce. Following your steps I end up with:
```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: []
  view: true
  concretizer:
    unify: true
  compilers:
  - compiler:
      spec: clang@=12.0.0
      paths:
        cc: /usr/bin/clang-12
        cxx: /usr/bin/clang++-12
        f77: null
        fc: null
      flags: {}
      operating_system: ubuntu20.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=9.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags:
        cflags: "-O3"
      operating_system: ubuntu20.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  packages:
    gcc:
      externals:
      - spec: gcc@9.4.0 languages='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/x86_64-linux-gnu-gcc-9
            cxx: /usr/bin/x86_64-linux-gnu-g++-9
            fortran: /usr/bin/x86_64-linux-gnu-gfortran-9
```
and the entries in `compilers` take precedence. Concretizing the spec, gives:
```console
$ spack spec zlib
==> Warning: duplicate found for gcc@=9.4.0 on ubuntu20.04/x86_64. Edit your compilers.yaml configuration to remove it.
Input spec
--------------------------------
 -   zlib

Concretized
--------------------------------
 -   zlib@1.3.1%gcc@9.4.0 cflags=-O3 +optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-icelake
 -       ^gcc-runtime@9.4.0%gcc@9.4.0 cflags=-O3  build_system=generic arch=linux-ubuntu20.04-icelake
[e]      ^glibc@2.31%gcc@9.4.0 cflags=-O3  build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^gmake@4.4.1%gcc@9.4.0 cflags=-O3 ~guile build_system=generic arch=linux-ubuntu20.04-icelake
```
so there is a warning, though the message can be improved. I am on:

* **Spack:** 0.22.0.dev0 (ecc4336bf97da0072ebb777624097b4deac6da5a)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo
