### ISSUE TITLE
Cannot filter external specs using `reuse:from`

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#44091]
### Steps to reproduce

Originally reported by @pranav-sivaraman on Slack.

The following environment fails to concretize:
```yaml
spack:
  specs:
  - flap
  view: true
  concretizer:
    unify: true
    reuse:
      from:
      - type: external
        include:
        - "cmake"
  packages:
    cmake:
      externals:
      - spec: cmake@3.20.4
        prefix: /usr
```

### Error message

With the environment above active:
```console
$ spack solve
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    flap is unsatisfiable
```

### Information on your system

* **Spack:** 0.22.0.dev0 (05c1e7ecc22b873c3e534aef45774c88521fe7b3)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

The error is due to a logical merge conflict between the reuse PR and the `libc` PR. `libc` providers are not implicitly included in the reuse filter, but they are implicitly added to the external configuration.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
