### ISSUE TITLE
Many packages do not declare correctly a dependency on `gl` 

### ISSUE THREAD

**Issue by kwryankrattiger** [LLNL/spack#44184]
### Steps to reproduce

Using this environment

```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - vtk
  view: true
  concretizer:
    unify: true
  packages:
    vtk:
      require: ['@9.2.6', +osmesa~mpi]
```

Then follow the normal concretization steps for the enviornment

```console
spack env activate vedge_test_env
spack concretize
```

### Error message

The `gl` providers `osmesa` and `glx` are both present in the DAG. VTK is built to support `osmesa`, but the `glew` is using the `glx` version of `gl` which is not compatible.

For some reason, spack seems to be ignoring the `osmesa` provided `gl` completely.

### Information on your system

* **Spack:** 0.23.0.dev0 (7f3dd38ccc106142846f29f76b928fa58e0e3164)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
