### ISSUE TITLE
More specific configuration scopes

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4427]
Right now, we have the following configuration scopes:

* ~/.spack/linux
* ~/.spack
* etc/spack/linux
* etc/spack

I may be biased because I only manage Linux clusters, but I don't find these configuration scopes very useful. I would find the following much more useful:

* ~/.spack/linux-centos7-x86_64
* ~/.spack
* etc/spack/linux-centos7-x86_64
* etc/spack

I manage 2 clusters, one is CentOS 6 and the other is CentOS 7. These clusters provide different versions of the system installed packages. At the moment, it is impossible to use external packages on 2 different OSes without lying. I've tried:
```yaml
packages:
  libtool:
    paths:
      libtool@2.4.2 arch=linux-centos7-x86_64: /usr
      libtool@2.2.6b arch=linux-centos6-x86_64: /usr
    buildable: False
```
but this doesn't work (see #3508). I could lie and say that they are both the same version, but this won't work for packages that require a specific version, or if the packages are in different locations. Having more specific configuration scopes would make life much easier. We can still keep `~/.spack/linux` and `etc/spack/linux` if people really want them.
