### ISSUE TITLE
Support non-virtual dependencies in lmod hierarchy

### ISSUE THREAD

**Issue by lang-m** [LLNL/spack#44559]
### Summary

Support non-virtual dependencies in `lmod:hierarchy` in `modules.yaml`. Some packages optionally come with support for non-virtual dependencies (e.g. CUDA, see below) that would make sense in the lmod hierarchy, e.g. `compiler -> CUDA -> mpi` instead of `compiler -> "special mpi with CUDA support"`.

### Rationale

We use Spack to provide software as modules on our local HPC system. Our users do not directly interact with Spack and instead only use the lmod modules.

One of the packages we provide is Octopus, which can come with and without CUDA support (both of which we need to provide to our users). At the moment we modify the version name of all modules that depend on CUDA to distinguish between the two different variants. In `modules.yaml` we have
```yaml
modules:
  default:
    lmod:
      all:
        suffixes:
            '^cuda@11.4.4': 'cuda-11.4.4'
```
Doing this we get modules like `octopus/14.0-cuda-11.4.4` (similar e.g. for `openmpi` which also is a dependency of octopus).

Users currently need the following command to load `octopus+cuda`:
```
module load gcc/11.3.0 openmpi/4.1.4-cuda-11.4.4 octopus/14.0-cuda-11.4.4
```

### Description

The more natural way for `octopus+cuda` in my opinion would be:
```
module load gcc/11.3.0 cuda/11.4.4 openmpi/4.1.4 octopus/14.0
```
i.e. to add `cuda` as a separate level in the hierarchy in `modules.yaml`:
```yaml
modules:
  default:
    lmod:
      hierarchy:
        - 'cuda'
        - 'mpi'
```

### Additional information

For reference, the command for `octopus~cuda` is (and should be):
```
module load gcc/11.3.0 openmpi/4.1.4 octopus/14.0
```

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
