### ISSUE TITLE
spack suddenly unable to build xSDK on NERSC edison

### ISSUE THREAD

**Issue by amklinv** [LLNL/spack#4502]
@tgamblin @BarrySmith 

I am trying to install xSDK on edison using the amklinv/xsdk-tpetra-fix branch.  The installation goes fine until it gets to PETSc, at which point it produces the error message 

```
      CLINKER /tmp/amklinv/spack-stage/spack-stage-WPM2JX/petsc/arch-linux2-c-opt/lib/libpetsc.so.3.07.5
/usr/bin/ld: /global/u1/a/amklinv/edison/spack/opt/spack/cray-CNL-ivybridge/gcc-6.1.0/trilinos-xsdk-0.2.0-kyct3xwwu6gnmehtbshvsgledvdnunko/lib/libchaco.a(int
erface.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/global/u1/a/amklinv/edison/spack/opt/spack/cray-CNL-ivybridge/gcc-6.1.0/trilinos-xsdk-0.2.0-kyct3xwwu6gnmehtbshvsgledvdnunko/lib/libchaco.a: could not read
symbols: Bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [/tmp/amklinv/spack-stage/spack-stage-WPM2JX/petsc/arch-linux2-c-opt/lib/libpetsc.so.3.07.5] Error 1
gmake[2]: Leaving directory `/tmp/amklinv/spack-stage/spack-stage-WPM2JX/petsc'
gmake[1]: *** [gnumake] Error 2
gmake[1]: Leaving directory `/tmp/amklinv/spack-stage/spack-stage-WPM2JX/petsc'
**************************ERROR*************************************
  Error during compile, check arch-linux2-c-opt/lib/petsc/conf/make.log
  Send it and arch-linux2-c-opt/lib/petsc/conf/configure.log to petsc-maint@mcs.anl.gov
********************************************************************
make: *** [all] Error 1
```

Modules:
```
Currently Loaded Modulefiles:
  1) modules/3.2.10.4                      12) dmapp/7.0.1-1.0502.10246.8.47.ari     23) slurm/edison
  2) nsg/1.2.0                             13) gni-headers/4.0-1.0502.10317.9.2.ari  24) altd/2.0
  3) eswrap/1.3.3-1.020200.1278.0          14) xpmem/0.1-2.0502.57015.1.15.ari       25) darshan/2.3.1
  4) switch/1.0-1.0502.57058.1.58.ari      15) dvs/2.5_0.9.0-1.0502.1958.2.55.ari    26) python_base/2.7.9
  5) craype-network-aries                  16) alps/5.2.3-2.0502.9295.14.14.ari      27) numpy/1.9.2
  6) craype/2.5.5                          17) rca/1.0.0-2.0502.57212.2.56.ari       28) scipy/0.15.1
  7) intel/17.0.1.132                      18) atp/2.0.2                             29) matplotlib/1.4.3
  8) cray-libsci/16.07.1                   19) PrgEnv-intel/5.2.56                   30) ipython/3.1.0
  9) udreg/2.3.2-1.0502.9889.2.20.ari      20) craype-ivybridge                      31) python/2.7.9
 10) ugni/6.0-1.0502.10245.9.9.ari         21) cray-shmem/7.4.1
 11) pmi/5.0.10-1.0000.11050.0.0.ari       22) cray-mpich/7.4.1
```

compilers.yaml:
```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu
    - gcc/6.1.0
    operating_system: CNL
    paths:
      cc: /opt/cray/craype/2.5.5/bin/cc
      cxx: /opt/cray/craype/2.5.5/bin/CC
      f77: /opt/cray/craype/2.5.5/bin/ftn
      fc: /opt/cray/craype/2.5.5/bin/ftn
    spec: gcc@6.1.0
```

packages.yaml:
```
packages:
  mpich:
    modules:
      mpich@7.4.1%gcc@6.1.0 arch=cray-CNL-ivybridge : cray-mpich/7.4.1
    buildable: False
  hdf5:
    modules:
      hdf5@1.8.12%gcc@6.1.0 arch=cray-CNL-ivybridge : cray-hdf5-parallel/1.8.12
    buildable: False
  netcdf:
    modules:
       netcdf@4.3.1%gcc@6.1.0 arch=cray-CNL-ivybridge : cray-netcdf-hdf5parallel/4.3.1
    buildable: False
  zlib:
    modules:
      zlib@1.2.7%gcc@6.1.0 arch=cray-CNL-ivybridge : zlib/1.2.7
    buildable: False
  boost:
    modules:
      boost@1.54%gcc@6.1.0 arch=cray-CNL-ivybridge : boost/1.54
    buildable: False
  cmake:
    modules:
      cmake@2.8.12.2%gcc@6.1.0 arch=cray-CNL-ivybridge : cmake/2.8.12.2
    buildable: False
  python:
    paths:
      python@2.7.9%gcc@6.1.0 arch=cray-CNL-ivybridge : /usr/common/software/python/2.7.9
    buildable: False
  all:
    providers:
      mpi: [mpich]
```

Any idea what this is about?  I'd be happy to provide any additional information you require.
