### ISSUE TITLE
Include Paths are not loaded into C_INCLUDE_PATH and CPP_INCLUDE_PATH when activating an environment

### ISSUE THREAD

**Issue by dmentock** [LLNL/spack#45162]
### Summary

In the [documentation](https://spack-tutorial.readthedocs.io/en/ecp22/tutorial_environments.html#building-in-environments), the program is built with

`$ mpicc ./mpi-hello.c -I$(spack location -i zlib)/include`

I would like to add the `${SPACK_ROOT}/var/spack/environments/${ENV_NAME}/.spack-env/view/include` dir to my `C_INCLUDE_PATH` and `CPP_INCLUDE_PATH` environment variables by default, so I can immediately start building my program without having to worry about the include files after activating my spack environment. My initial attempt was to modify the `spack.yaml` file as following:

```
spack:
  specs:
  - gcc@12.1.0
  - petsc@3.18.6%gcc+fftw+libpng+mumps+ptscotch+scalapack ^hdf5@1.14+fortran+hl
  ...
  view: true
  concretizer:
    unify: true
  config:
    env:
      append_path:
        C_INCLUDE_PATH: '/opt/spack/var/spack/environments/my_env/.spack-env/view/include'
        CPP_INCLUDE_PATH: '/opt/spack/var/spack/environments/my_env/.spack-env/view/include'
```
However, this does not modify `C_INCLUDE_PATH` or `CPP_INCLUDE_PATH` after loading the environment. Is there any clean way to accomplish this? Is there a reason why environments don't automatically load the `INCLUDE` paths into the env variables by default?

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
