### ISSUE TITLE
Problem setting up in a Cray system

### ISSUE THREAD

**Issue by EmreAtes** [LLNL/spack#4553]
I've tried using spack like described in the getting started, and I'm getting the error `configure: error: installation or configuration problem: C compiler cannot create executables.` The full error message I got in `build.out` is:
```
==> '/ufs/home/eates/spack/var/spack/stage/libelf-0.8.13-dabkko6td6l6fr5lzsvyiengzkcsqrfx/libelf-0.8.13/configure' '--prefix=/ufs/home/eates/spack/opt/spack/c
ray-CNL-ivybridge/gcc-4.8.0/libelf-0.8.13-dabkko6td6l6fr5lzsvyiengzkcsqrfx' '--enable-shared' '--disable-dependency-tracking' '--disable-debug'
creating cache ./config.cache
checking whether make sets ${MAKE}... yes
checking for gcc... /ufs/home/eates/spack/lib/spack/env/gcc/gcc
checking whether the C compiler (/ufs/home/eates/spack/lib/spack/env/gcc/gcc  ) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.
```

Afterwards, I tried setting `compilers.yaml` and `packages.yaml` to these:
```
eates@system:~> cat ~/.spack/compilers.yaml 
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: 
        - 'PrgEnv-cray'
        - 'cce/8.5.6'
    operating_system: CNL
    spec: 'cce@8.5.6'
    paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
    target: any
```
```eates@system:~> cat ~/.spack/packages.yaml 
packages:
    mpich:
        modules: 
            cray-mpich@7.5.1%cce@8.5.6 arch=cray-CNL-ivybridge: cray-mpich/7.5.1
        buildable: False
    all:
        compiler: [cce@8.5.6]
        providers:
            mpi: [mpich@7.5.1]
```
and the error I'm getting is very similar:
```
==> '/ufs/home/eates/spack/var/spack/stage/libelf-0.8.13-hmy3w4e2ce5bq64fs2rbdm3cukmoe2mv/libelf-0.8.13/configure' '--prefix=/ufs/home/eates/spack/opt/spack/cray-CNL-ivybridge/cce-8.5.6/libelf-0.8.13-hmy3w4e2ce5bq64fs2rbdm3cukmoe2mv' '--enable-shared' '--disable-dependency-tracking' '--disable-debug'
loading cache ./config.cache
checking whether make sets ${MAKE}... yes
checking for gcc... /ufs/home/eates/spack/lib/spack/env/cc
checking whether the C compiler (/ufs/home/eates/spack/lib/spack/env/cc  ) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.
```
I can run `configure` on some other tarballs that I download when the `$PATH` is correctly set, and I don't really understand what's going wrong with the configure that spack is running. I can't use `~/spack/lib/spack/env/cc` from the terminal, and I ran out of ideas. I've also tried setting `paths` to whole paths as I saw in some other issue here, but that didn't solve the issue.

**Comment by KineticTheory** [comment]
* Did you follow these cray-specific instructions?
  * https://spack.readthedocs.io/en/latest/getting_started.html#spack-on-cray
* Since you modified `compilers.yaml` between the first and second attempt, you might need to run `spack purge -s` to remove build files left over from your first attempt.

**Comment by EmreAtes** [comment]
I've followed the directions. As far as I know, the architecture and the OS for the front end and the back end of my system are the same, and the rest of the instructions in the cray-specific part has resulted in the compilers.yaml and packages.yaml that I attached.

I tried `spack purge -s` but nothing changed.

**Comment by mamelara** [comment]
Wish I could replicate this but everything works fine on Cori. And I might need to update the docs.

How did you get your list of compilers? Through ``spack compiler find``?

**Comment by EmreAtes** [comment]
I actually wrote the yaml file myself by looking at some examples and issues on github, but I did try `spack compiler find` and the `cce@8.5.6` that spack could find was this one:
```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-cray
    - cce/8.5.6
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.5.6
    target: any
```
I kept `.spack/cray/compilers.yaml` as it is, and tried `spack install libelf %cce@8.5.6` and I got the same error. I also tried the pgi compiler and the result was almost the same:
```
==> '/ufs/home/eates/spack/var/spack/stage/libelf-0.8.13-nlgwtua5jlmhbxt2d467l7253nt2pnap/libelf-0.8.13/configure' '--prefix=/ufs/home/eates/spack/opt/spack/c
ray-CNL-ivybridge/pgi-14.2.0/libelf-0.8.13-nlgwtua5jlmhbxt2d467l7253nt2pnap' '--enable-shared' '--disable-dependency-tracking' '--disable-debug'
creating cache ./config.cache
checking whether make sets ${MAKE}... yes
checking for gcc... /ufs/home/eates/spack/lib/spack/env/pgi/pgcc
checking whether the C compiler (/ufs/home/eates/spack/lib/spack/env/pgi/pgcc  ) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.
```
