### ISSUE TITLE
Can I change the "spack arch" ? In order to use buildcache installing packages

### ISSUE THREAD

**Issue by willie0x14** [LLNL/spack#45639]
### Steps to reproduce

I want to use the binary buildcache from "https://binaries.spack.io/v0.22.1/e4s" when installing packages.

```
$ spack mirror list
v0.22.1-e4s      [sb] https://binaries.spack.io/v0.22.1/e4s

$ spack buildcache list
==> 0 cached builds.
==> You can query all available architectures with:
  spack buildcache list --allarch

$ spack arch 
linux-ubuntu20.04-skylake_avx512
```

I suspect this issue might be due to the detected architecture. Is it possible to change it to x86_64?

I found a potential solution that might alter the architecture Spack detects by modifying the concretizer.yaml file:
```
targets:
  granularity: microarchitectures -> generic
```

However, this change didn't seem to work.

Here is the content of my concretizer.yaml file:

$ nano etc/spack/defaults/concretizer.yaml

```
concretizer:
  # Whether to consider installed packages or packages from buildcaches when
  # concretizing specs. If `true`, we'll try to use as many installs/binaries
  # as possible, rather than building. If `false`, we'll always give you a fresh
  # concretization. If `dependencies`, we'll only reuse dependencies but
  # give you a fresh concretization for your root specs.
  reuse: true
  # Options that tune which targets are considered for concretization. The
  # concretization process is very sensitive to the number targets, and the time
  # needed to reach a solution increases noticeably with the number of targets
  # considered.
  targets:
    # Determine whether we want to target specific or generic
    # microarchitectures. Valid values are: "microarchitectures" or "generic".
    # An example of "microarchitectures" would be "skylake" or "bulldozer",
    # while an example of "generic" would be "aarch64" or "x86_64_v4".
    granularity: generic
    # If "false" allow targets that are incompatible with the current host (for
    # instance concretize with target "icelake" while running on "haswell").
    # If "true" only allow targets that are compatible with the host.
    host_compatible: true
```

Despite this, the detected architecture remains unchanged.
Is it possible to change the architecture that Spack detects?
```
$ spack arch 
linux-ubuntu20.04-skylake_avx512
```

### Information on your system

* **Spack:** 0.22.1 (d66dce2d668a6234504594661506cdd1eaca4adc)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
