### ISSUE TITLE
Sample packages.yaml in Cray documentation is broken

### ISSUE THREAD

**Issue by EmreAtes** [LLNL/spack#4566]
I've created a `packages.yaml` based on the example in the [documentation](https://spack.readthedocs.io/en/latest/getting_started.html#setting-defaults-and-using-cray-modules):
```YAML
packages:
    mpi:
        modules: 
            cray-mpich@7.5.1 arch=cray-CNL-ivybridge: cray-mpich/7.5.1
        buildable: False
```
However, when I try to use spack with this file, I get the error
```
==> Error: packages.yaml entries cannot be virtual packages:
  in "/home/eates/.spack/packages.yaml", line 2, column 5: mpi
```
The correct `packages.yaml` file that the latest version of spack accepts is this:
```YAML
packages:
    mpich:
        modules: 
            cray-mpich@7.5.1 arch=cray-CNL-ivybridge: cray-mpich/7.5.1
        buildable: False
    all:
        providers:
            mpi: [mpich]
```
However, I might have constructed the final file incorrectly, since when I try to install kripke that only depends on mpi, it tries to compile other packages (e.g. libpciaccess which is problematic) which it shouldn't compile according to the graph:
```
o  kripke
o  openmpi
o  hwloc
|\
| |\
| o |  libxml2
|/| | 
| |\ \
| o | |  zlib
|  / /
| o |  xz
|  /
| o  libpciaccess
|/| 
| |\
| o |  util-macros
|  /
o |  pkg-config
 /
o  libtool
o  m4
o  libsigsegv
```

**Comment by adamjstewart** [comment]
Can you try changing:
```yaml
cray-mpich@7.5.1 arch=cray-CNL-ivybridge: cray-mpich/7.5.1
```
to:
```yaml
mpich@7.5.1 arch=cray-CNL-ivybridge: cray-mpich/7.5.1
```
and see if that helps? The thing to the left of the colon needs to be a spec for a valid package (the package is called `mpich`, not `cray-mpich`). The thing to the right of the colon needs to be the module name, which can be whatever you want (`cray-mpich` in this case).

**Comment by EmreAtes** [comment]
I did the change and it accepts the file:
```YAML
packages:
    mpich:
        modules: 
            mpich@7.5.1 arch=cray-CNL-ivybridge: cray-mpich/7.5.1
        buildable: False
    all:
        providers:
            mpi: [mpich]
```
However, the documentation still needs to change, because the example file has no `all:` field.
