### ISSUE TITLE
Specified view not used when generating module files and using `view_relative_modules` in a spack environment

### ISSUE THREAD

**Issue by NMannall** [LLNL/spack#45693]
### Steps to reproduce

I am attempting to create lmod module files that contain more user friendly paths by using a view as described in the documentation at the end of this section: https://spack.readthedocs.io/en/latest/module_file_support.html#customize-environment-modifications

Using a minimal spack environment with the following `spack.yaml`

```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: [namd]
  concretizer:
    unify: true
  modules:
    view_relative_modules:
      use_view: my_view
    prefix_inspections:
      ./bin:
        - PATH
  view:
    my_view:
      root: my_view
      projections:
        all:  '{name}-{hash}'
```

And then running:

```console
spack module lmod refresh
```

The module files are created, however, they still use paths from the spack install tree rather than the specified view.

### Information on your system

* **Spack:** 0.21.2
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
