### ISSUE TITLE
Installation issue: elsi

### ISSUE THREAD

**Issue by jscook2345** [LLNL/spack#45697]
### Steps to reproduce the issue

```console
jscook@perlmutter:login29:~/spack-config> spack spec -l elsi fflags="-fallow-argument-mismatch" ^ntpoly fflags="-fallow-argument-mismatch"
Input spec
--------------------------------
 -   elsi fflags=-fallow-argument-mismatch 
 -       ^ntpoly fflags=-fallow-argument-mismatch 

Concretized
--------------------------------
 -   vwapf3s  elsi@2.10.1%gcc@12.3.0 fflags=-fallow-argument-mismatch ~cuda~enable_pexsi~enable_sips~ipo+use_external_elpa+use_external_ntpoly+use_external_omm build_system=cmake build_type=Release elpa2_kernel=none generator=make internal_elpa_version=2024 arch=linux-sles15-zen3
[e]  wvmvk75      ^cmake@3.24.3%gcc@12.3.0~doc+ncurses+ownlibs build_system=generic build_type=Release patches=dbc3892 arch=linux-sles15-zen3
[e]  cauvsd4      ^cray-libsci@23.12.5%gcc@12.3.0~mpi~openmp+shared build_system=generic arch=linux-sles15-zen3
[e]  6r65ex3      ^cray-mpich@8.1.28%gcc@12.3.0+wrappers build_system=generic arch=linux-sles15-zen3
 -   v5uvzbr      ^elpa@2024.03.001%gcc@12.3.0~autotune~cuda+mpi+openmp~rocm build_system=autotools arch=linux-sles15-zen3
[e]  wnw3gxd          ^libtool@2.4.6%gcc@12.3.0 build_system=autotools arch=linux-sles15-zen3
[e]  qaz5bpi          ^python@3.11%gcc@12.3.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=ebdca64,f2fd060 arch=linux-sles15-zen3
 -   qasdmzu      ^gcc-runtime@12.3.0%gcc@12.3.0 build_system=generic arch=linux-sles15-zen3
[e]  ea6wt6w      ^glibc@2.31%gcc@12.3.0 build_system=autotools arch=linux-sles15-zen3
[e]  x3cnlkc      ^gmake@4.2.1%gcc@12.3.0~guile build_system=generic patches=ca60bd9,fe5b60d arch=linux-sles15-zen3
 -   menthhu      ^matrix-switch@1.2.1%gcc@12.3.0~dbcsr~ipo+lapack+mpi+scalapack build_system=cmake build_type=Release generator=ninja arch=linux-sles15-zen3
[e]  t7xusco          ^ninja@1.10.0%gcc@12.3.0+re2c build_system=generic arch=linux-sles15-zen3
 -   ew6oa2o      ^netlib-scalapack@2.2.0%gcc@12.3.0~ipo~pic+shared build_system=cmake build_type=Release generator=make patches=072b006,1c9ce5f,244a9aa arch=linux-sles15-zen3
 -   lbxe4kw      ^ntpoly@3.1.0%gcc@12.3.0 fflags=-fallow-argument-mismatch ~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-sles15-zen3
 -   x7inm6m      ^omm@1.2.1%gcc@12.3.0~dbcsr~ipo+lapack+mpi+scalapack build_system=cmake build_type=Release generator=ninja arch=linux-sles15-zen3
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

10 errors found in build log:
     247    cd /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-build-vwapf3s/src && /opt/cray/pe/mpich/8.1.28/ofi/
            gnu/12.3/bin/mpif90  -I/opt/cray/pe/libsci/23.12.5/GNU/12.3/x86_64/include -I/global/u1/j/jscook/spack-config/vendor/spack/opt/spack/linux-sl
            es15-zen3/gcc-12.3.0/matrix-switch-1.2.1-menthhuglysqqwoymgasysvoreeu5flv/include/matrixswitch/GNU-12.3.0 -I/global/u1/j/jscook/spack-config/
            vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/omm-1.2.1-x7inm6mfs7loj4i4pkob3zbcle2aaxob/include/omm/GNU-12.3.0 -I/global/u1/j/jscook/s
            pack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/ntpoly-3.1.0-lbxe4kw6lbfbza2ocomjizjqbth3ytyc/include -I/global/u1/j/jscook/s
            pack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/elpa-2024.03.001-v5uvzbr4fl2cbp6vybaap6clkfnrov3e/include/elpa_openmp-2024.03
            .001/modules -I/global/u1/j/jscook/spack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/matrix-switch-1.2.1-menthhuglysqqwoymgasy
            svoreeu5flv/include -I/global/u1/j/jscook/spack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/elpa-2024.03.001-v5uvzbr4fl2cbp6vy
            baap6clkfnrov3e/include/elpa_openmp-2024.03.001 -I/global/u1/j/jscook/spack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/omm-1.
            2.1-x7inm6mfs7loj4i4pkob3zbcle2aaxob/include -I/tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-build-v
            wapf3s/include -I/tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/include -O3 -DNDEBUG -O3 -J..
            /include -c /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_occ.f90 -o CMakeFiles/elsi.di
            r/elsi_occ.f90.o
     248    cd /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-build-vwapf3s/src && /opt/cray/pe/mpich/8.1.28/ofi/
            gnu/12.3/bin/mpif90  -I/opt/cray/pe/libsci/23.12.5/GNU/12.3/x86_64/include -I/global/u1/j/jscook/spack-config/vendor/spack/opt/spack/linux-sl
            es15-zen3/gcc-12.3.0/matrix-switch-1.2.1-menthhuglysqqwoymgasysvoreeu5flv/include/matrixswitch/GNU-12.3.0 -I/global/u1/j/jscook/spack-config/
            vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/omm-1.2.1-x7inm6mfs7loj4i4pkob3zbcle2aaxob/include/omm/GNU-12.3.0 -I/global/u1/j/jscook/s
            pack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/ntpoly-3.1.0-lbxe4kw6lbfbza2ocomjizjqbth3ytyc/include -I/global/u1/j/jscook/s
            pack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/elpa-2024.03.001-v5uvzbr4fl2cbp6vybaap6clkfnrov3e/include/elpa_openmp-2024.03
            .001/modules -I/global/u1/j/jscook/spack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/matrix-switch-1.2.1-menthhuglysqqwoymgasy
            svoreeu5flv/include -I/global/u1/j/jscook/spack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/elpa-2024.03.001-v5uvzbr4fl2cbp6vy
            baap6clkfnrov3e/include/elpa_openmp-2024.03.001 -I/global/u1/j/jscook/spack-config/vendor/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/omm-1.
            2.1-x7inm6mfs7loj4i4pkob3zbcle2aaxob/include -I/tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-build-v
            wapf3s/include -I/tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/include -O3 -DNDEBUG -O3 -J..
            /include -c /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_decision.f90 -o CMakeFiles/el
            si.dir/elsi_decision.f90.o
     249    /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_ntpoly.f90:258:23:
     250    
     251      258 |       ph%nt_options = SolverParameters_t(ph%nt_tol,ph%nt_filter,ph%nt_max_iter,&
     252          |                       1
  >> 253    Error: No initializer for component 'step_thresh' given in the structure constructor at (1)
     254    /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_ntpoly.f90:270:66:
     255    
     256      270 |       call PurificationExtrapolate(dm0,ovlp1,ne,dm1,ph%nt_options)
     257          |                                                                  1
  >> 258    Error: Type mismatch in argument 'trace' at (1); passed INTEGER(4) to REAL(8)
     259    /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_ntpoly.f90:141:23:
     260    
     261      141 |       ph%nt_options = SolverParameters_t(ph%nt_tol,ph%nt_filter,ph%nt_max_iter,&
     262          |                       1
  >> 263    Error: No initializer for component 'step_thresh' given in the structure constructor at (1)
     264    /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_ntpoly.f90:167:56:
     265    
     266      167 |       call PM(ham,ovlp,ne,dm,ph%ebs,ph%mu,ph%nt_options)
     267          |                                                        1
  >> 268    Error: Type mismatch in argument 'trace' at (1); passed INTEGER(4) to REAL(8)
     269    /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_ntpoly.f90:169:58:
     270    
     271      169 |       call TRS2(ham,ovlp,ne,dm,ph%ebs,ph%mu,ph%nt_options)
     272          |                                                          1
  >> 273    Error: Type mismatch in argument 'trace' at (1); passed INTEGER(4) to REAL(8)
     274    /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_ntpoly.f90:171:58:
     275    
     276      171 |       call TRS4(ham,ovlp,ne,dm,ph%ebs,ph%mu,ph%nt_options)
     277          |                                                          1
  >> 278    Error: Type mismatch in argument 'trace' at (1); passed INTEGER(4) to REAL(8)
     279    /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_ntpoly.f90:173:58:
     280    
     281      173 |       call HPCP(ham,ovlp,ne,dm,ph%ebs,ph%mu,ph%nt_options)
     282          |                                                          1
  >> 283    Error: Type mismatch in argument 'trace' at (1); passed INTEGER(4) to REAL(8)
  >> 284    make[2]: *** [src/CMakeFiles/elsi.dir/build.make:234: src/CMakeFiles/elsi.dir/elsi_ntpoly.f90.o] Error 1
     285    make[2]: *** Waiting for unfinished jobs....
     286    /tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-src/src/elsi_pexsi.f90:817:31:
     287    
     288      817 |             call MPI_Allreduce(send_buf,inertias,n_shift,MPI_REAL8,MPI_SUM,&
     289          |                               1
     290    ......

     ...

     337          |                                  1
     338    ......
     339     1595 |    call MPI_Allreduce(eval_c,tmp,ph%n_basis_c,MPI_REAL8,MPI_SUM,bh%comm,ierr)
     340          |                             2
     341    Warning: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/REAL(8)).
     342    make[2]: Leaving directory '/tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-build-vwapf3s'
  >> 343    make[1]: *** [CMakeFiles/Makefile2:189: src/CMakeFiles/elsi.dir/all] Error 2
     344    make[1]: Leaving directory '/tmp/jscook/spack-stage/spack-stage-elsi-2.10.1-vwapf3socgk4ocfydtpx5idhqkilkgfj/spack-build-vwapf3s'
  >> 345    make: *** [Makefile:139: all] Error 2
</pre></details>

### Information on your system

Debug report

```
jscook@perlmutter:login29:~/spack-config> spack debug report
* **Spack:** 0.23.0.dev0 (e4869cd5580feef221277cd7cd2217fc3cd2399c)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
```

Packages

```
jscook@perlmutter:login29:~/spack-config> cat config/packages.yaml 
packages:
  all:
    compiler: [gcc@12.3.0]

    providers:
      blas: [cray-libsci]
      mpi: [cray-mpich]
      lapack: [cray-libsci]

  cmake:
    buildable: false
    version: [3.24.3]
    externals:
    - spec: cmake@3.24.3
      prefix: /global/common/software/nersc/pm-2022q4/spack/linux-sles15-zen/cmake-3.24.3-k5msymx

  cray-libsci:
    buildable: false
    version: [23.12.5]
    externals:
    - spec: cray-libsci@23.12.5 %gcc@12.3.0
      prefix: /opt/cray/pe/libsci/23.12.5/GNU/12.3/x86_64

  cray-mpich:
    buildable: false
    version: [8.1.28]
    externals:
    - spec: cray-mpich@8.1.28 %gcc@12.3.0
      modules:
      - cray-mpich/8.1.28
      - libfabric/1.15.2.0
      prefix: /opt/cray/pe/mpich/8.1.28/ofi/gnu/12.3

  cuda:
    buildable: false
    version: [12.2]
    externals:
    - spec: cuda@12.2
      prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/cuda/12.2

  gmake:
    version: [4.2.1]
    externals:
    - spec: gmake@4.2.1
      prefix: /usr

  libfabric:
    buildable: false
    version: [1.15.2.0]
    externals:
    - spec: libfabric@1.15.2.0
      prefix: /opt/cray/libfabric/1.15.2.0

  libtool:
    version: [2.4.6]
    externals:
    - spec: libtool@2.4.6
      prefix: /usr

  mpich:
    buildable: false
    version: [3.1]
    externals:
    - spec: mpich@3.1 %gcc@12.3.0
      modules:
        - cray-mpich/8.1.28
        - libfabric/1.15.2.0
      prefix: /opt/cray/pe/mpich/8.1.28/ofi/gnu/12.3


  ninja:
    version: [1.10.0]
    externals:
    - spec: ninja@1.10.0
      prefix: /usr

  pkg-config:
    version: [0.29.2]
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr

  python:
    buildable: false
    version: [3.11]
    externals:
    - spec: python@3.11
      prefix: /global/common/software/nersc/pe/conda-envs/24.1.0/python-3.11/nersc-python

  py-numpy:
    buildable: false
    version: [1.26.3]
    externals:
    - spec: py-numpy@1.26.3
      prefix: /global/common/software/nersc/pe/conda-envs/24.1.0/python-3.11/nersc-python/lib/python3.11/site-packages/numpy
```

Compilers

```
jscook@perlmutter:login29:~/spack-config> cat config/compilers.yaml 
compilers:
- compiler:
    spec: gcc@12.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Additional information

Content is too big for the body. Let me know what alternatives there are.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
