### ISSUE TITLE
Cannot build clingo on RISC-V

### ISSUE THREAD

**Issue by abiolasams** [LLNL/spack#45724]
### Steps to reproduce

I ran `spack -b find -p clingo-bootstrap` to install clingo 

### Error message

`==> Error: No package matches the query: clingo-bootstrap`

@alalazo Could you take a look at this issue? Thank you. 

### Information on your system

* **Spack:** 0.23.0.dev0 (2dbc5213b02c3c5f2e021a0493e8cf593e7082e3)
* **Python:** 3.11.4
* **Platform:** linux-debian12-riscv64
* **Concretizer:** clingo

```
root@riscv:/opt/spack# spack config get packages
packages:
  all:
    compiler: [gcc, clang, oneapi, xl, nag, fj, aocc]
    providers:
      awk: [gawk]
      armci: [armcimpi]
      blas: [openblas, amdblis]
      cxx: [gcc]
      D: [ldc]
      daal: [intel-oneapi-daal]
      elf: [elfutils]
      fftw-api: [fftw, amdfftw]
      flame: [libflame, amdlibflame]
      fortran-rt: [gcc-runtime, intel-oneapi-runtime]
      fuse: [libfuse]
      gl: [glx, osmesa]
      glu: [mesa-glu, openglu]
      golang: [go, gcc]
      go-or-gccgo-bootstrap: [go-bootstrap, gcc]
      iconv: [libiconv]
      ipp: [intel-oneapi-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas, amdlibflame]
      libc: [glibc, musl]
      libgfortran: [gcc-runtime]
      libglx: [mesa+glx]
      libifcore: [intel-oneapi-runtime]
      libllvm: [llvm]
      lua-lang: [lua, lua-luajit-openresty, lua-luajit]
      luajit: [lua-luajit-openresty, lua-luajit]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-oneapi-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      onedal: [intel-oneapi-dal]
      pbs: [openpbs, torque]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      qmake: [qt-base, qt]
      rpc: [libtirpc]
      scalapack: [netlib-scalapack, amdscalapack]
      sycl: [hipsycl]
      szip: [libaec, libszip]
      tbb: [intel-tbb]
      unwind: [libunwind]
      uuid: [util-linux-uuid, libuuid]
      wasi-sdk: [wasi-sdk-prebuilt]
      xxd: [xxd-standalone, vim]
      yacc: [bison, byacc]
      ziglang: [zig]
      zlib-api: [zlib-ng+compat, zlib]
    permissions:
      read: world
      write: user
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
