### ISSUE TITLE
Allow user-configurable package patching in packages.yaml

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [LLNL/spack#45864]
### Summary

I propose allowing users to patch packages through packages.yaml in order to facilitate site/organization-specific package customization without having to resort to custom repos, which may create a substantial development and maintenance burden even when only small customizations are needed. See the relatively self-explanatory example below under Description. The idea would be for these modifications to be applied at install time when/just after the regular package patching based on the recipe is done.

### Rationale

Currently, users can customize module file logic (set env variables, etc.) on a per-package basis through modules.yaml, but packages themselves, as far as I know, cannot be patched through packages.yaml. This means that even minor modifications that are otherwise orthogonal to the logic in mainline Spack recipes require the use of custom repos, where a user has to copy the entire recipe and maintain it over time by duplicating code into the custom recipe in order to support whatever modifications. Allowing users to access patching functionality through packages.yaml would reduce the development and maintenance burden on users who, say, want to apply one little system-specific patch or remove one file for organization-specific reasons. I also believe it would be aesthetically nice for making package customization logically consistent with module file customization (i.e., currently, users are not forced to create custom recipes with customized `setup_run_environment()` functions in order to customize their module files).

### Description

```yaml
packages:
  foo:
    patch:
      - filter_files:
          pattern: mystring
          replacement: mymodifiedstring
          paths: src/cool_code.f
          when: "@1.2.3"
      - apply_patch:
          patch_file: /path/to/my/file.patch
          when: "%oneapi"
      - rename_file:
          source: src/cool_code.f
          destination: src/awesome_code.f
          when: "@1.2.3"
      - remove_file:
          path: src/bad_file.c
          when: "@1.2.3"
```

One alternative would be to allow users to create 'partial' recipes that could extend the main recipes by allowing users to add extra functions, etc. (e.g., `mycustomrepo/packages/foo/package_extend.py`), but the above solution seems more user friendly and less error prone to me.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate
