### ISSUE TITLE
Installation issue: llvm-amdgpu external

### ISSUE THREAD

**Issue by etiennemlb** [LLNL/spack#45882]
### Steps to reproduce the issue

Build and +rocm product and dump the LD_LIBRARY_PATH.

### Error message

```
    llvm-amdgpu:
      buildable: false
      externals:
      - spec: llvm-amdgpu@6.1.2
        prefix: /opt/rocm-6.1.2/llvm
        extra_attributes:
          compilers:
            c: /opt/rocm-6.1.2/llvm/bin/clang++
            cxx: /opt/rocm-6.1.2/llvm/bin/clang++
```
The above compiler is shown in multiple place as a way to describe an external build of AMD's gpu clang (not aocc).

I believe the prefix is wrong as it leads to the following code:
https://github.com/spack/spack/blob/8e1bd9a40375196972a03530c01be1302693cb2b/var/spack/repos/builtin/packages/llvm-amdgpu/package.py#L272
to produce a LD_LIBRARY_PATH of the form: /opt/rocm-5.7.1/llvm/llvm/lib note the double llvm.

This in turn, leads to libraries not found.

Using `prefix: /opt/rocm-6.1.2 instead works as expected.

### Information on your system

* **Spack:** 0.23.0.dev0 (657cfdc000d6b25506ab8f45e53e5eb14b9efbce)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen4

### Additional information

@haampie  @renjithravindrankannath  @srekolam

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
