### ISSUE TITLE
Buggy behavior with Spack view's "link" option

### ISSUE THREAD

**Issue by rhoneyager-tomorrow** [LLNL/spack#45883]
### Steps to reproduce

Spack's environment views do not properly include dependencies, and the unit test cases aren't catching this bug. Here's a triggering spack.yaml:

```yaml
spack:
  view:
    alldeps:
      root: view_alldeps
      select: [hdf5]
      link: all
    nodeps:
      root: view_nodeps
      select: [hdf5]
      link: roots
  specs:
  - hdf5 ~mpi
```

After building the hdf5 package, then run `spack env view regenerate`.

### Error message

Here's what you get:
```
ls view*/lib

view_alldeps/lib:
libhdf5.310.3.0.dylib       libhdf5.dylib               libhdf5_tools.310.dylib     pkgconfig/
libhdf5.310.dylib           libhdf5.settings            libhdf5_tools.a
libhdf5.a                   libhdf5_tools.310.0.3.dylib libhdf5_tools.dylib

view_nodeps/lib:
libhdf5.310.3.0.dylib       libhdf5.dylib               libhdf5_tools.310.dylib     pkgconfig/
libhdf5.310.dylib           libhdf5.settings            libhdf5_tools.a
libhdf5.a                   libhdf5_tools.310.0.3.dylib libhdf5_tools.dylib
```

The views with `link: all` and `link: roots` are unexpectedly the same. The dependencies (libz, libpkgconf) are missing.

When I look through the code in `lib/spack/spack/environment/environment.py` and `lib/spack/spack/filesystem_view.py`, it looks like those dependencies are never passed into the filesystem view.

### Information on your system

* **Spack:** 0.23.0.dev0 (8e1bd9a40375196972a03530c01be1302693cb2b)
* **Python:** 3.12.5
* **Platform:** darwin-sonoma-skylake

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
