### ISSUE TITLE
spack is not generating glibc module files after package nco installation %intel. spack 0.22.1 (d66dce2d668a6234504594661506cdd1eaca4adc)

### ISSUE THREAD

**Issue by zeekus** [LLNL/spack#45955]
### Steps to reproduce

# Spack Bug Report: spack is not generating glibc module files after package nco installation %intel. spack 0.22.1 (d66dce2d668a6234504594661506cdd1eaca4adc)

## Spack Version
0.22.1 (d66dce2d668a6234504594661506cdd1eaca4adc)

## Description
When installing packages that depend on glibc using the Intel compiler, Spack is not creating the expected symlink for glibc, causing module load failures.

## Steps to Reproduce
1. Install intel@2021.6.0
2. Run the following Spack install commands:

```
spack install -j8 --reuse netcdf-fortran@4.6.0%intel@2021.6.0 ^hdf5+fortran+hl%intel@2021.6.0 ^netcdf-c@4.9.0%intel@2021.6.0 ^hdf5@1.12.2%intel@2021.6.0 ^intel-oneapi-mpi@2021.9.0%intel@2021.6.0+external-libfabric cflags="-O3,-shared,-static"
spack install nco%intel@2021.6.0 ^intel-oneapi-mpi@2021.9.0
```

3. Attempt to load the nco module:

```
module load nco/5.1.9-intel-2021.6.0-szfh4zx
```

## Expected Behavior
The glibc link should be created somewhere allowing the module to load successfully.

## Actual Behavior
The module fails to load with the error:

```
module load nco/5.1.9-intel-2021.6.0-szfh4zx
Loading nco/5.1.9-intel-2021.6.0-szfh4zx
  ERROR: Unable to locate a modulefile for 'glibc/2.28-intel-2021.6.0-ys4i3ss'
  ERROR: Load of requirement 'glibc/2.28-intel-2021.6.0-ys4i3ss' failed
```

## user Workaround

Manually create the symlink in the directory: 

```
cd $SPACK_ROOT/share/spack/modules/linux-rocky8-haswell/glibc
ln -s 2.28-gcc-9.2.0-454nm4j 2.28-intel-2021.6.0-ys4i3ss
```

### glibc Installation Output

```
spack install glibc%intel@2021.6.0
[+] /usr (external glibc-2.28-ys4i3ssoqfn3vnwl6lac3b5y436x6tbc)
```

### Installed glibc Versions

```
spack find -l glibc
-- linux-rocky8-haswell / gcc@8.5.0 -----------------------------
hkya7ps glibc@2.28

-- linux-rocky8-haswell / gcc@9.2.0 -----------------------------
454nm4j glibc@2.28

-- linux-rocky8-haswell / nvhpc@24.7 ----------------------------
s6xmrav glibc@2.28
==> 3 installed packages
```

### compilers 

```
spack compilers
==> Available compilers
-- gcc rocky8-x86_64 --------------------------------------------
gcc@9.2.0  gcc@8.5.0

-- intel rocky8-x86_64 ------------------------------------------
intel@2021.6.0

-- nvhpc rocky8-x86_64 ------------------------------------------
nvhpc@24.7
```

### nco Dependency Tree

```
spack find -d nco%intel
-- linux-rocky8-haswell / intel@2021.6.0 ------------------------
nco@5.1.9
    antlr@2.7.7
        gcc-runtime@8.5.0
        glibc@2.28
    bison@3.0.4
    flex@2.6.1
    glibc@2.28
    gmake@4.2.1
    gsl@2.7.1
    netcdf-c@4.9.0
        bzip2@1.0.6
        c-blosc@1.21.5
            cmake@3.27.9
                curl@7.61.1
                ncurses@6.5
                    pkgconf@1.4.2
            lz4@1.9.4
            snappy@1.1.10
        glibc@2.28
        hdf5@1.12.2
            pkgconf@1.4.2
        intel-oneapi-mpi@2021.9.0
            libfabric@1.21.0
        libaec@1.0.6
            cmake@3.27.9
                curl@7.61.1
                ncurses@6.5
        zlib-ng@2.1.6
        zstd@1.5.6
    udunits@2.2.28
        expat@2.6.2
            libbsd@0.12.1
                libmd@1.0.4
 ```
 

### Information on your system

```
 spack debug report
* **Spack:** 0.22.1 (d66dce2d668a6234504594661506cdd1eaca4adc)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-haswell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by zeekus** [comment]
I am not sure this a bug or just expected behavior. 

I was able to find a workaround in my environment by doing this. 

```
# This is a Spack Environment file for ifort-rocky
#file: /modeling/spack/var/spack/environments/ifort-rocky/spack.yaml
# It describes a set of packages to be installed, along with
# configuration settings.
# description: works around missing glibc from intel. 
spack:
  # add package specs to the `specs` list
  specs:
  - glibc@2.28%gcc@9.2.0
  - hdf5@1.12.2%intel@2021.6.0
  - intel-oneapi-mpi@2021.9.0%intel@2021.6.0
  - libfabric@1.21.0
  - netcdf-c@4.9.0%intel@2021.6.0
  - netcdf-fortran@4.6.0%intel@2021.6.0
  - cmake@3.27.9%intel@2021.6.0
  - curl@7.61.1%intel@2021.6.0
  - ncurses@6.5%intel@2021.6.0
  - nco%intel@2021.6.0 ^glibc@2.28%gcc@9.2.0 ^intel-oneapi-mpi@2021.9.0
  view: true
  concretizer:
    unify: when_possible
    ```
