### ISSUE TITLE
Installation issue: LAMMPS +kokkos+rocm+kspace does not use hipFFT For GPU

### ISSUE THREAD

**Issue by hagertnl** [LLNL/spack#45968]
### Steps to reproduce the issue

We use the ROCm compiler on Frontier to build LAMMPS with the following `spack.yaml` environment:

```
spack:
  specs:
    - lammps@20240417 %rocmcc@5.7.1 ~mpi+kspace+kokkos+molecule~openmp amdgpu_target=gfx90a

  packages:
    all:
      buildable: true
      target: [x86_64]
    cmake:
      buildable: false
      version: [3.23.2]
      externals:
      - spec: cmake@3.23.2
        modules: [cmake/3.23.2]
    fftw:
      buildable: false
      variants: ~mpi
      version: [3.3.10.6]
      externals:
      - spec: fftw@3.3.10.6
        modules: [cray-fftw/3.3.10.6]
    hipcub:
      buildable: false
      version: [5.7.1]
      externals:
      - spec: hipcub@5.7.1
        prefix: /opt/rocm-5.7.1
    hipfft:
      buildable: false
      version: [5.7.1]
      externals:
      - spec: hipfft@5.7.1
        prefix: /opt/rocm-5.7.1
    hip:
      buildable: false
      version: [5.7.1]
      externals:
      - spec: hip@5.7.1
        prefix: /opt/rocm-5.7.1
    hsa-rocr-dev:
      buildable: false
      version: [5.7.1]
      externals:
      - spec: hsa-rocr-dev@5.7.1
        prefix: /opt/rocm-5.7.1
    rocthrust:
      buildable: false
      version: [5.7.1]
      externals:
      - spec: rocthrust@5.7.1
        prefix: /opt/rocm-5.7.1/rocthrust
    llvm-amdgpu:
      buildable: false
      version: [5.7.1]
      externals:
      - spec: llvm-amdgpu@5.7.1
        prefix: /opt/rocm-5.7.1

  view: false

  config:
    install_tree:
      root: /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/opt
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    template_dirs: ['$spack/share/spack/templates']
    build_stage: /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/build
    test_stage: /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/spack-test
    source_cache: /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/scache
    misc_cache: /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/mcache
    extensions: []
    verify_ssl: true
    install_missing_compilers: false
    checksum: true
    dirty: false
    build_language: C
    build_jobs: 8
    ccache: false
    db_lock_timeout: 120
    package_lock_timeout: null
    shared_linking: rpath
    allow_sgid: true
    locks: true
    suppress_gpg_warnings: false
    connect_timeout: 10
  bootstrap:
    enable: true
    root: /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/bootstrap
    sources:
    - name: github-actions-v0.5
      metadata: $spack/share/spack/bootstrap/github-actions-v0.5
    - name: github-actions-v0.4
      metadata: $spack/share/spack/bootstrap/github-actions-v0.4
    - name: spack-install
      metadata: $spack/share/spack/bootstrap/spack-install
    trusted:
      # By default we trust bootstrapping from sources and from binaries
      # produced on Github via the workflow
      github-actions-v0.5: true
      github-actions-v0.4: true
      spack-install: true
  repos: []

  concretizer:
    reuse: false
    unify: false
    targets:
      granularity: generic
    duplicates:
      strategy: minimal

  compilers:
  - compiler:
      spec: rocmcc@5.7.1
      operating_system: sles15
      modules: [amd/5.7.1]
      paths:
        cc: amdclang
        cxx: amdclang++
        f77: amdflang
        fc: amdflang
```
This provides the following concretization:
```
==> Starting concretization
==> Environment concretized in 31.73 seconds
==> Concretized 1 spec:
 -   gur34if  lammps@20240417%rocmcc@5.7.1~adios~amoeba~asphere~atc~awpmd~bocs~body~bpm~brownian~cg-dna~cg-spica~class2~colloid~colvars~compress~coreshell~cuda~cuda_mps~dielectric~diffraction~dipole~dpd-basic~dpd-meso~dpd-react~dpd-smooth~drude~eff~electrode~extra-compute~extra-dump~extra-fix~extra-molecule~extra-pair~fep~ffmpeg~granular~h5md~intel~interlayer~ipo~jpeg~kim+kokkos+kspace~latboltz~lepton+lib~machdyn~manifold+manybody~mc~meam~mesont~mgpt~misc~ml-hdnnp~ml-iap~ml-pod~ml-rann~ml-snap~mofff+molecule~molfile~mpi~netcdf~opencl~openmp~openmp-package~opt~orient~peri~phonon~plugin~plumed~png~poems~ptm~python~qeq~qtb~reaction~reaxff~replica+rigid+rocm~shock~smtbq~sph~spin~srd~tally~tools~uef~voronoi~vtk~yaff amdgpu_target=gfx90a build_system=cmake build_type=Release fftw_precision=double generator=make lammps_sizes=smallbig arch=linux-sles15-x86_64
[e]  dfu4kwi      ^cmake@3.23.2%rocmcc@5.7.1~doc+ncurses+ownlibs build_system=generic build_type=Release patches=dbc3892 arch=linux-sles15-x86_64
[e]  wsx7eny      ^fftw@3.3.10.6%rocmcc@5.7.1~mpi~openmp~pfft_patches+shared build_system=autotools precision=double,float arch=linux-sles15-x86_64
[e]  5xasqhs      ^glibc@2.31%rocmcc@5.7.1 build_system=autotools arch=linux-sles15-x86_64
 -   ooq4ax6      ^gmake@4.4.1%rocmcc@5.7.1~guile build_system=generic arch=linux-sles15-x86_64
[e]  eesxgz4      ^hip@5.7.1%rocmcc@5.7.1~asan~cuda+rocm build_system=cmake build_type=Release generator=make patches=5bb9b0e,7668b2a,aee7249,b589a02,c2ee21c arch=linux-sles15-x86_64
[e]  d3s6xm6      ^hipfft@5.7.1%rocmcc@5.7.1~asan~cuda+rocm amdgpu_target=auto build_system=cmake build_type=Release generator=make arch=linux-sles15-x86_64
[e]  kl4ghae      ^hsa-rocr-dev@5.7.1%rocmcc@5.7.1~asan+image+shared build_system=cmake build_type=Release generator=make arch=linux-sles15-x86_64
 -   ytbamg4      ^kokkos@4.3.01%rocmcc@5.7.1~aggressive_vectorization~compiler_warnings~cuda~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~hpx~hpx_async_dispatch~hwloc~ipo~memkind~numactl~openmp~openmptarget~pic+rocm+serial+shared~sycl~tests~threads~tuning~wrapper amdgpu_target=gfx90a build_system=cmake build_type=Release cxxstd=17 generator=make intel_gpu_arch=none arch=linux-sles15-x86_64
[e]  gm76iu3          ^rocthrust@5.7.1%rocmcc@5.7.1 amdgpu_target=auto build_system=cmake build_type=Release generator=make arch=linux-sles15-x86_64
[e]  njtkomg      ^llvm-amdgpu@5.7.1%rocmcc@5.7.1~link_llvm_dylib~llvm_dylib+rocm-device-libs build_system=cmake build_type=Release generator=ninja patches=53f9500,9a97712,b66529f arch=linux-sles15-x86_64
```

### Error message

<details><summary>Error message</summary>
<pre>
`ldd` of the resulting binary from the current Spack develop does NOT link in hipFFT:
```
$ cat old.ldd.txt
	linux-vdso.so.1 (0x00007ffdb7bfb000)
	liblammps.so.0 => /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/opt/rocmcc-5.7.1/lammps-20240417-gur34ifeh27hm7hleblhlzciscspztel/lib64/liblammps.so.0 (0x00007f375ec41000)
	libamdhip64.so.5 => /opt/rocm-5.7.1/lib/libamdhip64.so.5 (0x00007f375d575000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f375d30c000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f375d1c0000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f375d19c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f375cfa5000)
	libfftw3.so.mpi31.3 => /opt/cray/pe/fftw/3.3.10.6/x86_trento/lib/libfftw3.so.mpi31.3 (0x00007f375cc38000)
	libfftw3_omp.so.mpi31.3 => /opt/cray/pe/fftw/3.3.10.6/x86_trento/lib/libfftw3_omp.so.mpi31.3 (0x00007f375cc2e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f375cc29000)
	libkokkoscontainers.so.4.3 => /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/opt/rocmcc-5.7.1/kokkos-4.3.01-ytbamg4ljp2mnu5fyb223z6k7fq6ma2n/lib64/libkokkoscontainers.so.4.3 (0x00007f375cc19000)
	libkokkoscore.so.4.3 => /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/opt/rocmcc-5.7.1/kokkos-4.3.01-ytbamg4ljp2mnu5fyb223z6k7fq6ma2n/lib64/libkokkoscore.so.4.3 (0x00007f375cae9000)
	libkokkossimd.so.4.3 => /lustre/orion/proj-shared/stf243/hagertnl/Scratch/test_my_spack_fork/opt/rocmcc-5.7.1/kokkos-4.3.01-ytbamg4ljp2mnu5fyb223z6k7fq6ma2n/lib64/libkokkossimd.so.4.3 (0x00007f375cae5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3763b2f000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f375cad9000)
	libamd_comgr.so.2 => /opt/rocm-5.7.1/lib/libamd_comgr.so.2 (0x00007f37546ff000)
	libhsa-runtime64.so.1 => /opt/rocm-5.7.1/lib/libhsa-runtime64.so.1 (0x00007f375445d000)
	libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x00007f3754200000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3754439000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x00007f375441e000)
	libzstd.so.1 => /usr/lib64/libzstd.so.1 (0x00007f37540cf000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f37540a0000)
	libelf.so.1 => /usr/lib64/libelf.so.1 (0x00007f3753e00000)
	libdrm.so.2 => /opt/amdgpu/lib64/libdrm.so.2 (0x00007f3754089000)
	libdrm_amdgpu.so.1 => /opt/amdgpu/lib64/libdrm_amdgpu.so.1 (0x00007f3754410000)
```
And the resulting runs select KISS FFT for FFT's. We use the following command to test this:
```
$ spack load lammps
$ bash -c "cd $(dirname $(dirname $(which lmp)))/share/lammps/bench; lmp -in in.rhodo -k on g 1 -sf kk -pk kokkos neigh half; cd -;"
```
</pre></details>

### Information on your system

```
$ spack debug report
* **Spack:** 0.23.0.dev0 (b8cbbb8e2ecd5c67583f6e45d4b09bf82ee9c844)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
```

### Additional information

@rbberger I have a patch that I am going to put in a PR in the next few minutes that resolves this. You may want to extend it with CUDA, but I don't remember if LAMMPS CMake build system automatically selects the right FFT for CUDA or not.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate
