### ISSUE TITLE
The concretizer is non-deterministic when a few externals have equivalent specs

### ISSUE THREAD

**Issue by jdomke** [LLNL/spack#46058]
### Steps to reproduce

I'm using a private instance with `~/.spack/linux/packages.yaml` as follows:
```
packages:
  all:
    compiler: [clang]
<snip>
  elfutils:
    externals:
      - spec: "elfutils@0.186%clang@19.1.0 arch=linux-rhel8-a64fx"
        prefix: <some sysroot>/aarch64-none-linux-gnu/libc/usr
```

and the private instance is also connected to a public one (not under my control) with the following content:
```
packages:
  all:
    compiler: [fj, gcc]
<snip>
  elfutils:
    externals:
      - spec: "elfutils@0.186 arch=linux-rhel8-a64fx"
        prefix: /usr
```

Executing the same install command results in different outcome:
```
$ spack install libevent@2.1.8%clang@19.1.0
[+] /usr (external libevent-2.1.8-sniw4nb3mem5e7m7rvlcwqrwbvnj2rq6)
$
$ spack uninstall libevent@2.1.8%clang@19.1.0
<snip>
$
$ spack install libevent@2.1.8%clang@19.1.0
[+] <some sysroot>/aarch64-none-linux-gnu/libc/usr (external libevent-2.1.8-fm7yjc6j2uqccyzzjgn5hjaqnn2fdbil)
```

### Information on your system

* **Spack:** 0.21.0 (ddf2fd860945104163ec6676e281251ed643679f)
* **Python:** 3.11.6
* **Platform:** linux-rhel8-a64fx
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Given how we merge scopes, there are two different entries for `elfutils`, and their spec is "equivalent" when you use `clang` as a compiler. This is more or less what Spack will see:
```yaml
packages:
  elfutils:
    externals:
    - spec: elfutils@0.186%clang <- from your config
      prefix: path/a
    - spec: elfutils@0.186 <- from the other scope
      prefix: path/b
```
If you want only your configuration to be considered for `elfutils` you can use the double colon `::` :
```yaml
packages:
  elfutils::
    externals:
    - spec: elfutils@0.186%clang
      prefix: path/a
```
