### ISSUE TITLE
Spack compiler find creates duplicate entries

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#47085]
### Steps to reproduce

I ran `spack compiler find` when I had only gcc-14 and gfortran-14 installed. g++-14 was missing so a compiler entry with `cxx: null` was created. (A warning message indicating if some added compilers are missing language support might be useful in avoiding operator error like this, I didn't realize the mistake until I tried to build something and had to look at a config log to see that it was trying to configure with an absent g++.)

### Error message

I installed g++-14 and ran `spack compiler find` again. Instead of amending or re-creating the previous entry it added a new one, leaving this in my compilers.yaml file:

```
- compiler:
    spec: gcc@=14.2.0
    paths:
      cc: /usr/bin/gcc-14
      cxx: null
      f77: /usr/bin/gfortran-14
      fc: /usr/bin/gfortran-14
    flags: {}
    operating_system: ubuntu24.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=14.2.0
    paths:
      cc: /usr/bin/gcc-14
      cxx: /usr/bin/g++-14
      f77: /usr/bin/gfortran-14
      fc: /usr/bin/gfortran-14
    flags: {}
    operating_system: ubuntu24.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

I don't know how spack prioritizes those but it seems at least ambiguous and unexpected. It would be nice for some cleanup/sanity-checking to happen when compilers.yaml is automatically changed.

### Information on your system

* **Spack:** 0.23.0.dev0 (e1ea9e12a651e8d224c1ed30331f6dbb3f3dbc9f)
* **Python:** 3.12.3
* **Platform:** linux-ubuntu24.04-westmere

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
