### ISSUE TITLE
`extra_rpaths` are passed to static library link line on macos

### ISSUE THREAD

**Issue by Chrismarsh** [LLNL/spack#47570]
### Steps to reproduce

If `extra_rpaths` is defined in `compilers.yaml`, then, on macos, spack does not correctly remove the rpath from the link line when building a static library. 

### Error:
This results in the following error:

```
     1095    libtool: link: /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openmpi-5.0.5-isbiidxt46wqmcsb7webo3tyhkvoz3ce/bin/mpic++ -r -keep_private_externs -
             nostdlib -o .libs/libpnetcdf.4.dylib-master.o   -Wl,-force_load,../dispatchers/.libs/libdispatchers.a -Wl,-force_load,../drivers/common/.libs/libcommon.a -Wl,-force_load,../drivers/ncmpio/
             .libs/libncmpio.a -Wl,-force_load,../binding/cxx/.libs/libcxx.a -Wl,-force_load,../binding/f77/.libs/libf77.a -Wl,-force_load,../binding/f90/.libs/libf90.a
     1096    ld: warning: -ld_classic is deprecated and will be removed in a future release
     1097    ld: -rpath can only be used when creating a dynamic final linked image
```
A full spack log of this error is in the following [spack-build-out.txt](https://github.com/user-attachments/files/17721889/spack-build-out.txt) example.

### To reproduce:

(I have only seen this error on macos)
1.  Use a mixed apple-clang toolchain and specify the gcc fortran lib path as an `extra_rpath` in the `compilers.yaml`

```
compilers:
- compiler:
    spec: apple-clang@=15.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gcc-14.1.0-457tpmpyozjdws6hjoppm7a7tuyixiuj/bin/gfortran
      fc: /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gcc-14.1.0-457tpmpyozjdws6hjoppm7a7tuyixiuj/bin/gfortran
    flags: 
      ldflags: "-ld_classic"
    operating_system: sonoma
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: [/Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gcc-14.1.0-457tpmpyozjdws6hjoppm7a7tuyixiuj/lib]
```
The motivation for this `extra_rpath` is detailed in https://github.com/spack/spack/issues/45479
2. Install `parallel-netcdf@1.12.2`

The above error is then obtained. The   log then shows shows this additional rpath being included in the link line when building the static library.
```
/bin/sh ../../libtool  --tag=CXX   --mode=link /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openmpi-5.0.5-isbiidxt46wqmcsb7webo3tyhkvoz3ce/bin/mpic++  -fPIC -version-info 4:2:0  -o libpnetcdf.la -rpath /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/parallel-netcdf-1.12.2-mhiahwa7qy63ciureimngctkbgbfybfe/lib   ../dispatchers/libdispatchers.la ../drivers/common/libcommon.la ../drivers/ncmpio/libncmpio.la     ../binding/cxx/libcxx.la ../binding/f77/libf77.la ../binding/f90/libf90.la -L/Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openmpi-5.0.5-isbiidxt46wqmcsb7webo3tyhkvoz3ce/lib -L/Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gcc-14.1.0-457tpmpyozjdws6hjoppm7a7tuyixiuj/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0 -L/Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gcc-14.1.0-457tpmpyozjdws6hjoppm7a7tuyixiuj/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0/../../.. -lemutls_w -lheapt_w -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lquadmath -L/Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openmpi-5.0.5-isbiidxt46wqmcsb7webo3tyhkvoz3ce/lib -L/Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gcc-14.1.0-457tpmpyozjdws6hjoppm7a7tuyixiuj/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0 -L/Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gcc-14.1.0-457tpmpyozjdws6hjoppm7a7tuyixiuj/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0/../../.. -lemutls_w -lheapt_w -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lquadmath 

```

This issue has also been reported by @adamjstewart and I here:
https://github.com/spack/spack/issues/45919
https://github.com/spack/spack/pull/46811
https://github.com/spack/spack/pull/45925

My PR here solves the problem (for me)
https://github.com/spack/spack/pull/46264

The (now defunct?) PR of @tgamblin here
https://github.com/spack/spack/pull/46598
also solved it for me

@haampie
