### ISSUE TITLE
spack environment fails to set GCC env paths

### ISSUE THREAD

**Issue by jtipton2** [LLNL/spack#47924]
### Steps to reproduce

This seems to be similar to a previously posted bug, however, that bug was supposedly fixed already:  [41729](https://github.com/spack/spack/pull/41729)

Install local instance of spack:
```
git clone https://github.com/spack/spack.git
source spack/share/spack/setup-env.sh 
echo $SPACK_ROOT
```

Install and add GCC compiler and cleanup:
```
spack compilers
spack install gcc@10.2.0
spack compiler add "$(spack location -i gcc@10.2.0)"
spack compilers
spack find
spack gc
spack find
```

Create spack environment using custom yaml:
```
spack env create sierra_gcc spack2.yaml
spack env activate -p sierra_gcc
spack concretize
spack install -j 16
spack env deactivate
spack env activate -p sierra_gcc 
```

Contents of spack2.yaml file:
```
spack:

  specs: 
    - openmpi@4.0.5
    - python
    - py-numpy
    - py-pandas
    - py-matplotlib
    - py-scikit-learn
    - py-cython
    - py-setuptools
    - py-pip
    - seacas

  view: true
 
  concretizer:
    unify: true
    reuse: false

  packages:
    all:
      require:
      - "%gcc@10.2.0"

  compilers::
    - compiler:
        spec: gcc@=10.2.0
        paths:
          cc: /home/tvj/spack/opt/spack/linux-rhel8-icelake/gcc-8.5.0/gcc-10.2.0-yuoauijcnprt4xusykfshtmsxhd3bpcp/bin/gcc
          cxx: /home/tvj/spack/opt/spack/linux-rhel8-icelake/gcc-8.5.0/gcc-10.2.0-yuoauijcnprt4xusykfshtmsxhd3bpcp/bin/g++
          f77: /home/tvj/spack/opt/spack/linux-rhel8-icelake/gcc-8.5.0/gcc-10.2.0-yuoauijcnprt4xusykfshtmsxhd3bpcp/bin/gfortran
          fc: /home/tvj/spack/opt/spack/linux-rhel8-icelake/gcc-8.5.0/gcc-10.2.0-yuoauijcnprt4xusykfshtmsxhd3bpcp/bin/gfortran
        flags: {}
        operating_system: rhel8
        target: x86_64
        modules: []
        environment: {}
        extra_rpaths: []
```

### Error message

Even though the spack compiler is correct, the environment paths to gcc are not set:
```
$ spack env activate sierra_gcc 

$ spack compilers
==> Available compilers
-- gcc rhel8-x86_64 ---------------------------------------------
gcc@10.2.0

$ which gcc
/bin/gcc
$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Select output from `env` shows that other paths are set, just not `gcc` paths:
```
$ env
LD_LIBRARY_PATH=/opt/thinlinc/lib64:/opt/thinlinc/lib:/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/lib
SPACK_PYTHON=/bin/python3
PATH_modshare=/usr/bin:1:/opt/thinlinc/bin:1:/usr/share/Modules/bin:1:/usr/local/bin:1:/opt/thinlinc/sbin:1:/var/cfengine/bin:1:/data/software/StarCCM/18.04.009/18.04.009-R8/STAR-View+18.04.009/bin:1:/data/software/StarCCM/18.04.009/18.04.009-R8/STAR-CCM+18.04.009-R8/star/bin:1:/bin:1:/usr/bin/X11:1:/sbin:1:/usr/sbin:1:/usr/local/sbin:1
SPACK_ENV=/home/tvj/spack/var/spack/environments/sierra_gcc
LD_LIBRARY_PATH_modshare=/opt/thinlinc/lib:1:/opt/thinlinc/lib64:1
MPIF90=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/bin/mpif90
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MPICXX=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/bin/mpic++
CMAKE_PREFIX_PATH=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view:.
MPICC=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/bin/mpicc
MPIFC=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/bin/mpifort
SPACK_ROOT=/home/tvj/spack
PYTHONPATH=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/lib:/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/lib/python3.13/site-packages:.
MPIF77=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/bin/mpif77
ACLOCAL_PATH=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/share/aclocal:/usr/share/aclocal
MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
PKG_CONFIG_PATH=/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/lib/pkgconfig:/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/share/pkgconfig:/home/tvj/spack/var/spack/environments/sierra_gcc/.spack-env/view/lib64/pkgconfig:/usr/share/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.24.0.dev0 (c037188b59e0a988903bd470efb550422b92731e)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-sapphirerapids
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
