### ISSUE TITLE
openblas@0.3.28 missing patch with correct sha

### ISSUE THREAD

**Issue by kftsehk** [LLNL/spack#48208]
### Steps to reproduce

With this environment spack.yaml
```yaml
spack:
  concretizer:
    targets:
      granularity: generic
      host_compatible: true
  specs:
    - openblas@0.3.28 # arch=linux-rocky9-x86_64_v4, gcc=(redhat's gcc-toolset-14.2.1)
  view: false
```

```
spack concretize -U -f --fresh-root
```

### Error message

```console
==> Error: Couldn't find patch for package builtin.openblas with sha256: d0b9276ac0f5f6f281620aae72c17161eb7baa7b46e66c57b764c0d0d3337944. This usually means the patch was modified or removed. To fix this, either reconcretize or use the original package repository
```

`openblas@0.3.28` is the newest version available, no such issue with `openblas@0.3.27`

### Information on your system

* **Spack:** 0.24.0.dev0 (0850e0bf085fcdf02b1d77f4daefa26e8f0a18f1)
* **Python:** 3.13.0
* **Platform:** linux-rocky9-zen4

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
