### ISSUE TITLE
Spack config add -f does not properly merge configs when using `-:`/`+:`/`::`

### ISSUE THREAD

**Issue by kwryankrattiger** [LLNL/spack#48216]
### Steps to reproduce

Using file `extra-concretizer-configs.yaml`:

```yaml
concretizer:
  reuse:
    from-:
    - type: environment
```

Using base environment config `spack.yaml:

```yaml
spack:
...
  concretizer:
    reuse:
      from-:
      - type: local
      - type: external
```

Steps to reproduce error:

```console
spack config add -f extra-concretizer-configs.yaml
spack config blame concretizer
```

Output:

```console
/.../spack.yaml  concretizer:
/.../spack.yaml      reuse:
/.../spack.yaml        from-:
/.../spack.yaml        - type: environment
/.../spack.yaml        from:
/.../spack.yaml        - type: local
/.../spack.yaml        - type: external
```

### Information on your system

* **Spack:** 0.24.0.dev0 (773f2821044f9acd8daf3bdabeacba1e302e3e85)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake

CC: @chissg 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
