### ISSUE TITLE
Installation issue: dorado

### ISSUE THREAD

**Issue by ChristianKniep** [LLNL/spack#48442]
### Steps to reproduce the issue

```yaml
spack:
  specs:
    - dorado@0.5.3+cuda
  concretizer:
    unify: true
    targets:
    # Determine whether we want to target specific or generic
    # microarchitectures. Valid values are: "microarchitectures" or "generic".
    # An example of "microarchitectures" would be "skylake" or "bulldozer",
    # while an example of "generic" would be "aarch64" or "x86_64_v4".
      granularity: generic
    # If "false" allow targets that are incompatible with the current host (for
    # instance concretize with target "icelake" while running on "haswell").
    # If "true" only allow targets that are compatible with the host.
      host_compatible: true
  container:
    format: docker
    images:
      os: "ubuntu:20.04"
      spack: "latest"
```

### Error message

<details><summary>Error message</summary>

<pre>
2376.1 1 error found in build log:
2376.1      254      CMakeFilters.cmake:176 (find_package)
2376.1      255      CMakeLists.txt:923 (include)
2376.1      256    This warning is for project developers.  Use -Wno-dev to suppress i
2376.1             t.
2376.1      257
2376.1      258    -- Could NOT find libaec: found neither libaecConfig.cmake nor liba
2376.1             ec-config.cmake (found version "1.0.6")
2376.1      259    -- Filter PLUGIN file is /
2376.1   >> 260    CMake Error at CMakeLists.txt:1183 (message):
2376.1      261       **** Parallel and C++ options are mutually exclusive, override w
2376.1             ith HDF5_ALLOW_UNSUPPORTED option ****
2376.1      262
2376.1      263
2376.1      264    -- Configuring incomplete, errors occurred!
</pre></details>

### Information on your system

The box is stopped. Will add later.

### Additional information

c7.4xl instance on AWS. I tried to build it with `ubuntu` and `rockylinux:9` and natively on the instance running Amazon Linux 2. Always with the same outcome. :( 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by wyphan** [comment]
@spackbot maintainers

**Comment by wyphan** [comment]
Pinging @snehring as the Spack maintainer for `dorado`.
I suspect this line needs to be adjusted:
https://github.com/spack/spack/blob/ca8ea63796a645bb00cb0cc6f68a9216891c8fdb/var/spack/repos/builtin/packages/dorado/package.py#L29

**Comment by snehring** [comment]
Without looking I'm guessing this is a behavior change in hdf5, an earlier release may work. It's gonna be a bit before I can sit down and look though. Start of the year is hectic.

**Comment by ChristianKniep** [comment]
How would I need to change the dependency to make this work? Can I tweak the package myself to have a workaround?

**Comment by snehring** [comment]
So there's a few issues. 
1) I believe the version restriction on hdf5 was a typo, given there is no version 1.17 of hdf5 yet, probably should be 1.7 (or omitted entirely given the oldest version in spack is 1.8)
2) I'm guessing in hdf5@1.14.4 or .5  they changed things and now the cxx variant is conflicting with something.

if you modify the package.py for dorado to just be ```hdf5+hl+cxx+szip``` and then  write the spec as ```dorado ^hdf5@1.14.3```  for your install invocation it will try to build with hdf5 version 1.14.3 (which is likely the the last version I built this with).

**Comment by snehring** [comment]
Hmm. No, even 1.14.5 works. Looks like the version restriction typo was resulting in the 2.0 development branch being installed. Seems there's some issues with +cxx and +mpi in that version that will need resolved eventually. I'll put in a pr shortly to remove the erroneous version restriction.

**Comment by ChristianKniep** [comment]
**EDIT**: I changed the specs line to `- dorado@0.5.3+cuda ^hdf5@1.17:+cxx+hl+szip`. Let's see

Hey y'all, still get the same error? even with an updated spack. 
```
1668.0 1 error found in build log:
1668.0      242    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
1668.0      243    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
1668.0      244    -- Found Threads: TRUE
1668.0      245    -- Looking for stdatomic.h
1668.0      246    -- Looking for stdatomic.h - found
1668.0      247    -- Found libaec: /opt/software/linux-ubuntu20.04-x86_64_v4/gcc-9.4.
1668.0             0/libaec-1.0.6-6imbw3d65flrrqsw5zfzb2rs5encfsm2/cmake/libaec-config
1668.0             .cmake (found version "1.0.6")
1668.0   >> 248    CMake Error at CMakeLists.txt:1237 (message):
1668.0      249       **** Parallel and C++ options are mutually exclusive, override w
1668.0             ith HDF5_ALLOW_UNSUPPORTED option ****
1668.0      250
1668.0      251
1668.0      252    -- Configuring incomplete, errors occurred!
```

### environment
```yaml
spack:
  specs:
    - dorado@0.5.3+cuda
  concretizer:
    unify: true
    targets:
    # Determine whether we want to target specific or generic
    # microarchitectures. Valid values are: "microarchitectures" or "generic".
    # An example of "microarchitectures" would be "skylake" or "bulldozer",
    # while an example of "generic" would be "aarch64" or "x86_64_v4".
      granularity: generic
    # If "false" allow targets that are incompatible with the current host (for
    # instance concretize with target "icelake" while running on "haswell").
    # If "true" only allow targets that are compatible with the host.
      host_compatible: true
  container:
    format: docker
    images:
      os: "ubuntu:20.04"
      spack: "latest"
```
Command: 
```
spack containerize > Dockerfile && docker build . -t test
```
