### ISSUE TITLE
Specify a header prefix and a lib prefix for externals in packages.yaml

### ISSUE THREAD

**Issue by cessenat** [LLNL/spack#48886]
### Summary

Specify a header prefix and a lib prefix for externals in packages.yaml for "non standard" package installation.

### Rationale

External dependency for OpenMPI on RedHat 8 sets prefix to  '/usr/lib64/openmpi'
Then using OpenMPI for building another package complains it does not find the MPI header.
OpenMPI headers are located on '/usr/include/openmpi-x86_64'.
I got the issue compiling fftw with spack.

### Description

Such as
```
  openmpi:
    externals:
    - spec: openmpi@4.1.1+atomics~cuda+cxx~cxx_exceptions+java~memchecker+pmi~static~wrapper-rpath fabrics=ofi,psm2,ucx schedulers=slurm
      libprefix: /usr/lib64/openmpi
      includeprefix: /usr/include/openmpi-x86_64
```

### General information

- [x] I have searched the issues of this repo and believe this is not a duplicate
