### ISSUE TITLE
rocm-openmp-extras: impossible to create a view due to clash with `llvm-amdgpu`

### ISSUE THREAD

**Issue by albestro** [LLNL/spack#48941]
### Steps to reproduce

Installation of this environment fails due to a clash during creation of the view

```yaml
spack:
  concretizer:
    unify: true
  specs:
  - llvm-amdgpu
  - rocm-openmp-extras
  packages:
    all:
      variants: ['+rocm', 'amdgpu_target=gfx942']
  view: true
```

From a quick check, it seems that `rocm-openmp-extras` during its spack installation creates symlinks to the `llvm-amdgpu` folder in the install tree, resulting in having potential duplicates in the view, that fails to be created.

I'm not sure if it is either a problem with `rocm-openmp-extras` spack packaging, with spack views or something else.

### Error message

```console
==> Updating view at /dev/shm/ialberto/environments/rocm6.2/myview
==> Error: 1 fatal error(s) when merging prefixes:
    `/user-environment/linux-sles15-zen4/gcc-13.3.0/rocm-openmp-extras-6.3.1-q6aizzuducdwvjplz2kp7ruasgop6lsb/lib/libdevice` and `/user-environment/linux-sles15-zen4/gcc-13.3.0/llvm-amdgpu-6.3.1-jxorxm3h4w5tpqllzapsddpdivzvbcab/lib/libdevice` both project to `lib/libdevice`
```

### Information on your system

* **Spack:** 1.0.0.dev0 (97750189b62660b4132143299d4a6887a09ea62a)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen4

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
