### ISSUE TITLE
Environment issue: spurious cmake warnings related to libgomp.so

### ISSUE THREAD

**Issue by tpadioleau** [LLNL/spack#49050]
I use spack environments and I recently noticed spurious cmake warnings like the following
```
CMake Warning at CMakeLists.txt:8 (add_executable):
  Cannot generate a safe runtime search path for target main because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libgomp.so.1] in /usr/lib/gcc/x86_64-linux-gnu/9 may be hidden by files in:
      /local/home/tpadiole/Codes/omp-reproducer/omp-env/.spack-env/view/lib

  Some of these libraries may not be found correctly.
```
The file `/local/home/tpadiole/Codes/omp-reproducer/omp-env/.spack-env/view/lib/libgomp.so.1` links to `/local/home/tpadiole/spack-0.22.2/opt/spack/linux-ubuntu20.04-icelake/gcc-10.5.0/gcc-runtime-10.5.0-qg536zuhbvx67he6igimmtprurxn3nvy/lib/libgomp.so.1`

I created a reproducer environment for the purpose of this issue:
```yaml
spack:
  specs:
  - cmake
  - openmpi
  view: true
  concretizer:
    unify: true
```

The bug is likely not related to openmpi, the intent is only to link to a library located in the environment.

The `CMakeLists.txt` used is:
```cmake
cmake_minimum_required(VERSION 3.27)

project(omp-reproducer LANGUAGES CXX)

find_package(OpenMP REQUIRED COMPONENTS CXX)
find_package(MPI REQUIRED COMPONENTS CXX)

add_executable(main main.cpp)
target_link_libraries(main PRIVATE OpenMP::OpenMP_CXX MPI::MPI_CXX)
```
and the file `main.cpp` is
```cpp
#include <iostream>

int main(int argc, char** argv)
{
#pragma omp parallel for
  for(int i=0; i<100; ++i)
  {
      std::cout << i << std::endl;
  }

    return 0;
}
```

**Comment by rbberger** [comment]
This has to do with the `gcc-runtime` package that is added by Spack. It'll point to the gcc runtime libraries, including `libgomp.so`. When added to the environment view, CMake will print out these warnings.

You can avoid this by customizing the view and excluding `gcc-runtime` from being added.
```yaml
spack:
  specs:
  - cmake
  - openmpi
  view:
     default:
        root: .spack-env/view
        exclude: ['gcc-runtime']
  concretizer:
    unify: true
```
