### ISSUE TITLE
Allow dependencies between specs in environments

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#49097]
### Summary

This proposal aims at extending the current syntax for specs in environments, by allowing:
1. A specific order of concretization among matrices
2. The possibility of overriding configuration options per-matrix

Together with #45189, these two extensions should make it easier to bootstrap an entire stack in a single environment, starting from minimal requirements on the system.

### Rationale

This extension should simplify a number of use cases, for instance:

1. `aws-pcluster` pipelines, that need to bootstrap compilers in N steps
2. `e4s` can use different matrixes for different compilers / options in a single pipeline. This means we can potentially lump `e4s-rocm`, `e4s-oneapi` etc. in a single pipeline

Ideally, many workflows that are now using multiple environments, and manual boilerplate operations to connect them, can be unified in a single environment.

### Description

From a user perspective, this should just add a few optional fields to matrices:
- The fields `id` and `needs` can be used to specify dependencies among parts of the same environment.
- The `configuration` field can be used to override config option for that matrix only

An example `spack.yaml` might look like:
```yaml
spack:
  specs:
  - group: gcc12
    spec: gcc@12+binutils

  - group: oneapi2024
    needs:
    - gcc12
    spec: intel-oneapi-compilers@2024.1 %gcc@12

  - group stack
    needs:
    - gcc12
    - oneapi2024
    matrix:
    - [ gromacs, lammps]
    - ["%oneapi"]
    configuration:
      packages:
        fortran:
          require: intel-oneapi-compilers@2024.1

  view: true
  concretizer:
    unify: true
```

Roughly, the rules for concretizing it would be as follows:

- If a matrix `id` is *needed* by another matrix, then it will be concretized before that other matrix, and the concretized root specs will be available for "reuse" (regardless of filters that are applied to reuse). In the example above `gcc12` is concretized before `oneapi2024` and the concrete `gcc@12+binutils` spec is available when concretizing `intel-oneapi-compilers@2024.1 %gcc@12`.
- Matrixes / specs without an `id` are considered to be part of a default `id` that has no dependencies
- Configuration overrides per matrix are used only when concretizing that matrix

The syntax used is taken from Github Actions syntax, so users would hopefully be familiar with it.

### Additional information

For debugging purposes, we should be able to easily reproduce intermediate steps of concretization, e.g. try to concretize the `oneapi2024` matrix and be able to inspect its input, output, ASP encoding etc.

### General information

- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Doesn't immediately feel like something that fits Spack. I'd rather say `spack install gromacs %{intel-oneapi-compilers@2024.1 %{gcc@12 +binutils}}` instead of a dozen lines of yaml. DSL > YAML since it can be used on the command line.

**Comment by alalazo** [comment]
The point is when you need to specify more options in the inner deps that gets ugly. For `aws-pcluster-*` it is:
```
gromacs %{intel-oneapi-compilers@2024.1 %{gcc@12 +binutils %gcc@7}}
```
Also the line above specifies a build dep of gromacs only, which is different from saying that each spec in the DAG needs to use `intel` as a compiler. The last part you can only do with requirements.

That said, this doesn't mean that we shouldn't also implement the DSL, as already detailed in #44379

**Comment by alalazo** [comment]
As a detail for future reference, it's very likely that something like:
```
gromacs %{intel-oneapi-compilers@2024.1 %{gcc@12 +binutils %gcc@7}}
```
needs also to be concretized by context, since concretizing together will put clingo on its knees.

**Comment by haampie** [comment]
Discussed on a call, avoid one-dimensional "`matrix`" so people can go from:

```yaml

spack:
  specs:
  - pkg1 +rocm
  - pkg2 +rocm
  - pkg3 +rocm
  - pkg4 +rocm
  - pkg5 +rocm
```
to
```yaml
spack:
  specs:
  - id: compiler
    list:
    - llvm-amdgpu
  - needs: compiler
    list:
    - pkg1 +rocm
    - pkg2 +rocm
    - pkg3 +rocm
    - pkg4 +rocm
    - pkg5 +rocm
```
or this one which enforces a name for each section
```yaml
spack:
  specs:
    bootstrap:
      specs:
      - llvm-amdgpu
    stack:
      needs: bootstrap
      specs:
      - pkg1 +rocm
      - pkg2 +rocm
      - pkg3 +rocm
      - pkg4 +rocm
      - pkg5 +rocm
```

**Comment by tgamblin** [comment]
Minor tweak on the `id:` (which I think is maybe too generic?) -- how about `group:` for groups of specs?

```
spack:
  specs:
  - group: gcc12
    spec: gcc@12+binutils

  - group: oneapi2024
    needs:
    - gcc12
    spec: intel-oneapi-compilers@2024.1 %gcc@12
```
