### ISSUE TITLE
py-torch concretize failed

### ISSUE THREAD

**Issue by EMinsight** [LLNL/spack#49123]
py-torch concretize failed in a new environment
Here is the _spack.yaml_  

```
spack:
  # add package specs to the `specs` list
  specs:
  - py-torch@2.6.0~caffe2+cuda+cudnn~custom-protobuf~debug+distributed+fbgemm+flash_attention+gloo+kineto+magma~metal+mkldnn+mpi+nccl+nnpack+numa+numpy+openmp+qnnpack~rocm+tensorpipe~test~ucc+valgrind+xnnpack build_system=python_pip cuda_arch==80 patches=1d74a11,65f5630
  view: true
  concretizer:
    unify: true
```
