### ISSUE TITLE
Installation issue: libxml2 http variant not found error

### ISSUE THREAD

**Issue by rem1776** [LLNL/spack#49477]
### Steps to reproduce the issue

linking the maintainer: @AlexanderRichert-NOAA 

I'm running into an error during a container build, with the dockerfile created from a spack.yaml config via the `spack containerize` tool. Installing `libxml2+http` works fine from the command line, but during a container build it cant seem to find the variant. I've tried specifying the version as well, but hit the same error. 

```console
$ spack -e ./ containerize > Dockerfile
docker build .
...
```

### Error message

<details><summary>Error message</summary>

<pre>
[1/2] STEP 3/4: RUN cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y
==> Error: No such variant {'http'} for spec: 'libxml2+http'
Error: building at STEP "RUN cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y": while running runtime: exit status 1
</pre></details>

### Information on your system

rhel 8.10 with amd processors.

* **Spack:** 1.0.0.dev0 (97d66b637ffa0605662ff541c5833932016c94e0)
* **Python:** 3.13.0
* **Platform:** linux-rhel8-zen2

### Additional information

spack.yaml contents:
```yaml
spack:
  specs:
  - gcc
  - mpich
  - netcdf-c
  - netcdf-fortran
  - nccmp
  - docbook-xsl^libxml2+http
  concretizer:
    unify: true
  packages:
    all:
      compiler: [ gcc ]
  config:
    template_dirs:
      - ./
  # container specific options
  container:
    format: docker
    template: Dockerfile.template
    images:
      os: "rockylinux:9"
      spack: 0.23.1
    strip: false
    os_packages:
      final:
      - autoconf
      - libtool
      - make
      - bats
      - git
      - libgomp
      - python3
      - python3-numpy
      - python3-pip
      - python3-pytest
      - perl
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
