### ISSUE TITLE
Lmod: Hierarchical module files, add target/march as a possible refinement

### ISSUE THREAD

**Issue by AdelKS** [LLNL/spack#49487]
### Summary

Hello,

I tried to add `target` or `architecture` on the `modules.yaml` file
```
   lmod:
      core_compilers:
      - 'gcc@11'
      hierarchy:
      - mpi
      - target
```

But it seems to not accept it.

### Rationale

Some clusters have several kind of cpu architectures and/or micro-architectures, it would be nice to use the same `spack` home folder for all of them

### General information

- [x] I have searched the issues of this repo and believe this is not a duplicate
