### ISSUE TITLE
spack compiler find aocc result in unusable compiler

### ISSUE THREAD

**Issue by kftsehk** [LLNL/spack#49543]
### Steps to reproduce

1. Install aocc@4.2.0 or 5.0.0 as is.
2. `spack compiler find --scope=site/linux <prefix-to>/aocc-*`
3. Got this in compiler config
    ```yaml
      compilers:
        - compiler:
        environment: {}
        extra_rpaths: []
        flags:
          cflags: null
          cxxflags: null
          fflags: null
        modules: []
        operating_system: rocky9
        paths:
          cc: <prefix>/bin/clang
          cxx: <prefix>/bin/clang++
          f77: <prefix>/bin/flang
          fc: <prefix>/bin/flang
        spec: aocc@=4.2.0
        target: x86_64
    ```
5. Try concretize something with aocc, compiler not recognized
6. Change `cc` to `<prefix>/bin/clang-16` for 4.2.0 or `<prefix>/bin/clang-17` works

But I `spack load aocc@5.0.0` both clang and clang-17 works, clang is a link to clang-17

### Information on your system

* **Spack:** 1.0.0.dev0 (78207027a5f3dc295e3dc40fd4d7cca94ce784d7)
* **Python:** 3.11.7
* **Platform:** linux-rocky9-zen4

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
