### ISSUE TITLE
Install succeeds, but package not found (splicing + buildcache)

### ISSUE THREAD

**Issue by lrbison** [LLNL/spack#49688]
### Steps to reproduce

```
$ spack install wrf
...
==> Installing wrf-4.6.1-vv443z6isin5i4724bi7kkmmffihxfav [59/59]
[+] /home/ubuntu/spack/opt/spack/linux-ubuntu20.04-neoverse_v1/gcc-12.4.0/wrf-4.6.1-vv443z6isin5i4724bi7kkmmffihxfav
$ echo $?
0
$ spack find -l wrf
==> Error: No package matches the query: wrf
```

### Error message

None.

### Information on your system

```
ubuntu@ip-172-31-9-164:~$ spack mirror list
aws-pcluster-legacy [sb] https://binaries.spack.io/v0.23.1/aws-pcluster-neoverse_v1
bootstrap-gcc-cache [sb] https://bootstrap.spack.io/pcluster/amzn2/aarch64
spack-public        [s ] https://mirror.spack.io
ubuntu@ip-172-31-9-164:~$ spack debug report
* **Spack:** 0.23.1 (2bfcc69fa870d3c6919be87593f22647981b648a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-neoverse_v1
ubuntu@ip-172-31-9-164:~$
```

### General information

I suspect the problem is related to splicing in a gcc-runtime.  Namely:
```
   concretizer:
      splice:
         automatic: true
         explicit:
          - target: gcc-runtime
            replacement: gcc-runtime/zeok37ppigh52daa63jnzgzsuo3karlg
            transitive: true
```

Which I did because otherwise I found that I would have to rebuild the following packages because they end up with a different gcc-runtime than the other 51 packages:
```
   wrf
   hdf5
   openmpi
   netcdf-c
   netcdf-fortran
   parallel-netcdf
```

I think what makes packages special is their DAG for gcc-runtime includes 

```
   virtuals:
      - fortran-rt
      - libgfortran
```

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
