### ISSUE TITLE
Regression on compilers `extra_rpaths`

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#49827]
### Steps to reproduce

_Originally reported by @vbrunini in Slack_

I've got an environment that was previously defining:
```yaml
packages:
  llvm-amdgpu:
    externals:
    - spec: llvm-amdgpu@6.1.2
      prefix: /opt/rocm-6.1.2/llvm
      extra_attributes:
        compilers:
          c: /opt/rocm-6.1.2/bin/amdclang
          cxx: /opt/rocm-6.1.2/bin/amdclang++
        flags:
          ldlibs: -lmpi_gtl_hsa
        extra_rpaths:
        - /opt/cray/pe/mpich/8.1.31/gtl/lib
```
and working (i.e. in the build environment for packages I saw /opt/cray/pe/mpich/8.1.31/gtl/lib in the SPACK_COMPILER_EXTRA_RPATHS environment variable and the compiler wrappers added both -Wl,-rpath,... and -L... flags to link lines correspondingly).

### Error message

Testing after the compilers as nodes changes and the `SPACK_COMPILER_EXTRA_RPATHS` env var is empty and links fail due to being unable to find the mpi_gtl_hsa library that is in the directory from the extra_rpaths.

### Information on your system

--

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by rbberger** [comment]
@alalazo I'm also seeing that
```yaml
...
     extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: ...
```
won't have any effect for compilers.
