### ISSUE TITLE
external gcc not being used on mac with new compilers

### ISSUE THREAD

**Issue by jacobmerson** [LLNL/spack#49919]
### Steps to reproduce

```yaml
packages:
  gcc:
    externals:
    - spec: gcc@14.2.0 languages='c,c++,fortran'
      prefix: /opt/homebrew
      extra_attributes:
        compilers:
          c: /opt/homebrew/bin/gcc-14
          cxx: /opt/homebrew/bin/g++-14
          fortran: /opt/homebrew/bin/gfortran-14
        flags: {}
        environment: {}
        extra_rpaths: []
```

```console
$ spack install gcc
$ spack load gcc
```

### Error message

```console
$ g++ --version
Apple clang version 16.0.0 (clang-1600.0.26.6)
Target: arm64-apple-darwin24.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Note, apple-clang is being used instead of g++ when programs are being built as well.

### Information on your system

* **Spack:** 1.0.0.dev0 (e2cbe77f2e1005833af76e727ff8a5989ce74c0d)
* **Python:** 3.11.10
* **Platform:** darwin-sequoia-m1

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
