### ISSUE TITLE
Spack cannot concretize this spack.yaml environment anymore

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#49991]
### Steps to reproduce

Posting as a "Bug" rather than a "Build" issue since (1) it doesn't depend on which package I want to install, and (2) Spack is pretty much non-informative about why it fails.

Here is a script to reproduce:

```
#!/usr/bin/bash

# Make sure we are isolated
export SPACK_DISABLE_LOCAL_CONFIG=true
export SPACK_USER_CACHE_PATH=/tmp/spack

# Clone spack
git clone https://github.com/spack/spack.git

# Source spack
source spack/share/spack/setup-env.sh

# Download the spack.yaml file
wget https://raw.githubusercontent.com/mochi-hpc-experiments/platform-configurations/refs/heads/main/ANL/Polaris/spack.yaml

# Edit the file to remove the constrain on json-c
sed -i '/json-c/{N;N;d;}' spack.yaml

# Create, activate, and concretize an environment
spack env create myenv spack.yaml
spack env activate myenv
spack concretize -f
```

The `spack.yaml` in question is one we've been using on Polaris, keeping it up-to-date with changes to spack over time. However this now fails with the following error:

```
==> Error: failed to concretize `mochi-margo` for the following reasons:
     1. Cannot select a single "version" for package "mochi-margo"
     2. cannot satisfy a requirement for package 'pkgconfig'.
     3. cannot satisfy a requirement for package 'm4'.
     4. cannot satisfy a requirement for package 'libtool'.
     5. cannot satisfy a requirement for package 'gmake'.
     6. cannot satisfy a requirement for package 'automake'.
```

It works fine with Spack v0.23.1. The problem does not depend on the spec I try to build (here mochi-margo for the example).

Note: even though this file is for ANL's Polaris machine, you can use it on your laptop and get a similar outcome (though with more lines listing things that could not be concretized).

### Information on your system

* **Spack:** 1.0.0.dev0 (b6722ce5c94c498426e02324d3c39412a0c0ff41)
* **Python:** 3.12.3
* **Platform:** linux-ubuntu24.04-aarch64

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
(Trying to understand what is the underlying problem) Isn't this the same issue we discussed elsewhere, where we expect a path to the compiler, and instead we got just the commands:
```yaml
paths:
  cc: cc
  cxx: CC
  f77: ftn
  fc: ftn
```
? Do you get this warning at some point:
```
==> Warning: [spack.compilers.config] cannot detect gcc from the following paths: cc, CC, ftn, ftn
```
?

**Comment by mdorier** [comment]
No I don't see this warning. I have tested also with full paths for compilers, it doesn't change the outcome.

**Comment by alalazo** [comment]
> No I don't see this warning. I have tested also with full paths for compilers, it doesn't change the outcome.

Then you must have other compilers defined elsewhere in the config scope (if you don't see the warning, it means there are compilers already in the configuration, and Spack doesn't try to convert the `compilers:` section)

**Comment by mdorier** [comment]
I'm using 
```
export SPACK_DISABLE_LOCAL_CONFIG=true
export SPACK_USER_CACHE_PATH=/tmp/spack
```
So I don't know from where other compilers could come.

I do see this:
```
==> Compilers have been configured automatically from PATH inspection
```

And when I do `spack config edit config` with the environment activated I see this:
```
...
  compilers:
  - compiler:
      spec: gcc@12.3
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-gnu
      - gcc-native/12.3
      - nvhpc-mixed
      - libfabric
      environment: {}
      extra_rpaths: []
  packages:
    gcc:
      externals:
      - spec: gcc@7.5.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran
      - spec: gcc@12.3.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-12
            cxx: /usr/bin/g++-12
            fortran: /usr/bin/gfortran-12
    nvhpc:
      externals:
      - spec: nvhpc@23.9~blas~lapack~mpi
        prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/compilers
        extra_attributes:
          compilers:
            c: /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/compilers/bin/nvc
            cxx: /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/compilers/bin/nvc++
            fortran: /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/compilers/bin/nvfortran
...
```

So spack did add some compilers I did not ask for (while keeping my `compilers` section untouched).

**Comment by alalazo** [comment]
To clarify on the new changes from #45189:
1. `compilers` is not a config section anymore
2. `%` means "direct dependency" and compilers are regular packages, hence they are defined in `packages.yaml` when they are external
3. if something is concretized and spack sees no compilers configured, it tries first to convert old `compilers` entries, then it inspect the PATH

Because of 3 I think you should see a warning before:
```
==> Compilers have been configured automatically from PATH inspection
```
The code that should trigger this is:
https://github.com/spack/spack/blob/fd31f7e01453a0c6a76fc41bfd75ef303e662c45/lib/spack/spack/compilers/config.py#L119-L142

**Comment by mdorier** [comment]
In the case of my environment, though, the compilers aren't defined in a `compilers.yaml`, they are in the environment's `spack.yaml`. Again, no warning. I can show the whole output of the above script:

```
Cloning into 'spack'...
remote: Enumerating objects: 638417, done.
remote: Counting objects: 100% (1210/1210), done.
remote: Compressing objects: 100% (597/597), done.
remote: Total 638417 (delta 929), reused 613 (delta 608), pack-reused 637207 (from 4)
Receiving objects: 100% (638417/638417), 220.28 MiB | 11.04 MiB/s, done.
Resolving deltas: 100% (302405/302405), done.
Updating files: 100% (12256/12256), done.
==> Created environment myenv in: /home/mdorier/inst-pnetcdf/spack/var/spack/environments/myenv
==> Activate with: spack env activate myenv
==> Fetching https://ghcr.io/v2/spack/bootstrap-buildcache-v1/blobs/sha256:232504c082b9badb4b1c2540f36f2e0c28f8f314f742262935e82aef0c049a0c
==> Fetching https://ghcr.io/v2/spack/bootstrap-buildcache-v1/blobs/sha256:90b7cf4dd98e26c58578ad8604738cc32dfbb228cfb981bdfe103c99d0e7b5dd
==> Installing "clingo-bootstrap@=spack~docs+ipo+optimized+python+static_libstdcpp build_system=cmake build_type=Release generator=make patches:=bebb819,ec99431 arch=linux-centos7-x86_64" from a buildcache
==> Compilers have been configured automatically from PATH inspection
==> Error: failed to concretize `mochi-margo` for the following reasons:
     1. Cannot select a single "version" for package "mochi-margo"
     2. cannot satisfy a requirement for package 'pkgconfig'.
     3. cannot satisfy a requirement for package 'm4'.
     4. cannot satisfy a requirement for package 'libtool'.
     5. cannot satisfy a requirement for package 'gmake'.
     6. cannot satisfy a requirement for package 'automake'.
```

**Comment by mdorier** [comment]
Ah I got somewhere, by doing the following to the environment's file (after environment creation, in `spack config edit config`):
- Removed the compilers section
- Removed gcc 7.5.0 and nvhpc, which I don't care about
- Edited the auto-detected paths for gcc 12.3.0 to the correct compiler wrappers
- Removed the "all" section under "packages"
I think the last point was the problem as it required everything to depend on gcc@12.3, but there wasn't any gcc@12.3: spack had detected a gcc@12.3.0.

Side note: the error message is still not informative enough as to why things could not be satisfied, and spack didn't take into account my `compilers` section when adding compilers as packages.

**Comment by zeekus** [comment]
It sounds like you’ve hit a classic Spack configuration conflict. It looks like a "bug" because of the lack of clear error messaging.  But,  this is  likely a metadata collision introduced by stricter schema validation in newer versions.

Spack v0.23 allowed for duplicate entries across packages.yaml and spack.yaml, but Spack v1.x no longer supports this. Additionally, while v0.23 permitted duplicate compiler definitions in both packages.yaml and compilers.yaml, this is strictly prohibited in v1.x.

Here is one example: 

```
 spack concretize -f
==> Error: the spec 'pmix@4.2.8%gcc@8.5.0' depends on 'gcc@8.5.0', but there are multiple external specs that could satisfy the request [candidates are gcc@=8.5.0~binutils+bootstrap~graphite~nvptx~piclibs~profiled~strip build_system=autotools build_type=RelWithDebInfo languages:='c,c++,fortran' platform=linux os=rocky8 target=x86_64, gcc@=8.5.0~binutils+bootstrap~graphite~nvptx~piclibs~profiled~strip build_system=autotools build_type=RelWithDebInfo languages='c,c++,fortran' platform=linux os=rocky8 target=x86_64] [/modeling/spack/etc/spack/site/packages.yaml:36]
```

# works in spack v23
``` 
packages.yaml 
  pmix:
    buildable: false
    externals:
    - spec: pmix@4.2.8%gcc@=8.5.0
      prefix: /opt/amazon/pmix
```
# works in spack v1.1.0
``` 
  pmix:
    buildable: false
    externals:
    - spec: pmix@4.2.8
      prefix: /opt/amazon/pmix
```
