### ISSUE TITLE
Installation issue: `openmpi@4.1.8 %llvm@19`

### ISSUE THREAD

**Issue by fbarbari** [LLNL/spack#50040]
I have installed llvm with `spack install llvm@19+flang` and  with that I tried to install openmpi with the command `spack install openmpi@4.1.8 %llvm@19`. This is the error I received after a lot of output:
```
*** Fortran compiler
checking whether we are using the GNU Fortran compiler... no
checking whether /home/fbarbari/spack/opt/spack/linux-neoverse_n1/compiler-wrapper-1.0-aidoisczdppdfhmnfdcrn5tqnmzf6tl3/libexec/spack/clang/flang accepts -g... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
configure: WARNING: Open MPI now ignores the F77 and FFLAGS environment variables; only the FC and FCFLAGS environment variables are used.
checking whether ln -s works... yes
checking if Fortran compiler works... no
**********************************************************************
* It appears that your Fortran compiler is unable to produce working
* executables.  A simple test application failed to properly
* execute.  Note that this is likely not a problem with Open MPI,
* but a problem with the local compiler installation.  More
* information (including exactly what command was given to the
* compiler and what error resulted when the command was executed) is
* available in the config.log file in the Open MPI build directory.
**********************************************************************
configure: error: Could not run a simple Fortran program.  Aborting.
==> Error: ProcessError: Command exited with status 1:
    '/tmp/fbarbari/spack-stage/spack-stage-openmpi-4.1.8-dwfg5dtim7r27r6rjpqbvmpqoyevkcho/spack-src/configure' '--prefix=/home/fbarbari/spack/opt/spack/linux-neoverse_n1/openmpi-4.1.8-dwfg5dtim7r27r6rjpqbvmpqoyevkcho' '--enable-shared' '--disable-silent-rules' '--disable-sphinx' '--enable-builtin-atomics' '--disable-static' '--enable-mpi1-compatibility' '--without-verbs' '--without-fca' '--without-cma' '--without-mxm' '--without-xpmem' '--without-hcoll' '--without-knem' '--without-psm' '--without-ofi' '--without-ucc' '--without-psm2' '--without-ucx' '--without-cray-xpmem' '--without-sge' '--without-slurm' '--without-alps' '--without-loadleveler' '--without-tm' '--without-lsf' '--disable-memchecker' '--with-libevent=/home/fbarbari/spack/opt/spack/linux-neoverse_n1/libevent-2.1.12-eiwxlodunluetnqtktzrhuvadalaylst' '--with-pmix=/home/fbarbari/spack/opt/spack/linux-neoverse_n1/pmix-5.0.5-h3qmqp5ll3n7w4pzud6osfl5m4t3oiao' '--with-zlib=/home/fbarbari/spack/opt/spack/linux-neoverse_n1/zlib-ng-2.2.3-qjao6kd7f7pkc55dtsxk53uwvnxfr245' '--with-hwloc=/home/fbarbari/spack/opt/spack/linux-neoverse_n1/hwloc-2.11.1-nt5om5vw4ujynfsydsc6ucx6om27qhvr' '--disable-java' '--disable-mpi-java' '--with-gpfs=no' '--without-cuda' '--enable-wrapper-rpath' '--disable-wrapper-runpath' '--disable-mpi-cxx' '--disable-cxx-exceptions' '--disable-debug'

1 error found in build log:
     387    * execute.  Note that this is likely not a problem with Open MPI,
     388    * but a problem with the local compiler installation.  More
     389    * information (including exactly what command was given to the
     390    * compiler and what error resulted when the command was executed) is
     391    * available in the config.log file in the Open MPI build directory.
     392    **********************************************************************
  >> 393    configure: error: Could not run a simple Fortran program.  Aborting.

```

I think the issue is that openmpi is trying to configure the wrong compiler, assuming the wrong name (but I may be wrong). It is looking for `/home/fbarbari/spack/opt/spack/linux-neoverse_n1/compiler-wrapper-1.0-aidoisczdppdfhmnfdcrn5tqnmzf6tl3/libexec/spack/clang/flang` (which is actually a symbolic link to `/home/fbarbari/spack/opt/spack/linux-neoverse_n1/compiler-wrapper-1.0-aidoisczdppdfhmnfdcrn5tqnmzf6tl3/libexec/spack/cc`) while the correct llvm fortran compiler is `flang-new`, as specified both in my `FC` env variable and in my `/home/fbarbari/.spack/packages.yaml` file.
Output of `spack compiler info llvm@19`:
```
llvm@=19.1.7+clang+flang+lld+lldb arch=linux-rhel8-aarch64:
  prefix: /home/fbarbari/spack/opt/spack/linux-neoverse_n1/llvm-19.1.7-dz6v6tnjkwnpfj7lxpm3ifnox3vbxt7v
  compilers:
    c: /home/fbarbari/spack/opt/spack/linux-neoverse_n1/llvm-19.1.7-dz6v6tnjkwnpfj7lxpm3ifnox3vbxt7v/bin/clang
    cxx: /home/fbarbari/spack/opt/spack/linux-neoverse_n1/llvm-19.1.7-dz6v6tnjkwnpfj7lxpm3ifnox3vbxt7v/bin/clang++
    fortran: /home/fbarbari/spack/opt/spack/linux-neoverse_n1/llvm-19.1.7-dz6v6tnjkwnpfj7lxpm3ifnox3vbxt7v/bin/flang-new

```
Could this be an issue in the openmpi recipe?

`spack --version`:
```
1.0.0.dev0 (e45ee9cb92a875db09a48e84d81985894c395722)
```
