### ISSUE TITLE
Building amg2023 with intel MPI

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#50265]
I'm wanting to build AMG2023 with intel MPI. I have the following environment:

```yaml
spack:
  specs:
  - intel-oneapi-compilers
  - flux-sched
  - flux-core
  - pmix@4.2.2
  - flux-pmix
  - amg2023%oneapi +mpi +openmp
  - hypre +int64 +openmp
  concretizer:
    unify: when_possible
...
```
But it tells me it's not possible. 

```
root@761ac2bcbc61:/opt/spack-environment# spack install --reuse --fail-fast     && spack gc -y
 
==> Warning: using "cmake@3.22.1" which is a deprecated version
==> Error: concretization failed for the following reasons:

   1. Cannot set the required compiler: amg2023%oneapi
```

Is that true?

**Comment by hagertnl** [comment]
We just hit this with both OneAPI and LLVM in Spack v0.23.0 and 0.23.1 (but not v0.22.x).

Try making sure that a `gcc` compiler is defined, and does not require a module to be loaded. In our case, this fixed it:
```
  - compiler:
      spec: gcc@8.5.0
      operating_system: rhel8
      modules: []
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
```

Alternatively, you can add a `gcc` module to your OneAPI compiler's `modules` list.
