### ISSUE TITLE
Installation issue: quantum-espresso v6.6 using gmake@4.4.1

### ISSUE THREAD

**Issue by paolotricerri** [LLNL/spack#50323]
### Steps to reproduce the issue

I am trying to install quantum-espresso v6.6.

I am doing my experiments in the docker image:  ghcr.io/spack/pcluster-amazonlinux-2
Once inside the container I run the setup-env.sh script and set up a packages.yaml file as follows:

```
packages:
  gcc:
    externals:
    - spec: gcc@=12.4.0
      prefix: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-aarch64/gcc-7.3.1/gcc-12.4.0-v6wxye6ijzrxnzxftcwnpu3psohsjl2b
      extra_attributes:
        compilers:
          c: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-aarch64/gcc-7.3.1/gcc-12.4.0-v6wxye6ijzrxnzxftcwnpu3psohsjl2b/bin/gcc
          cxx: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-aarch64/gcc-7.3.1/gcc-12.4.0-v6wxye6ijzrxnzxftcwnpu3psohsjl2b/bin/g++
          fortran: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-aarch64/gcc-7.3.1/gcc-12.4.0-v6wxye6ijzrxnzxftcwnpu3psohsjl2b/bin/gfortran
  acfl:
    require:
    - "%gcc"
    - "target=aarch64"
  gromacs:
    require:
    - gromacs@2024.3 ^armpl-gcc ^openmpi
    - "%gcc"
  libfabric:
    buildable: true
    externals:
    - prefix: /opt/amazon/efa/
      spec: libfabric@1.17.0
    require:
    - fabrics=shm,efa
  llvm:
    variants: ~lldb
  mpas-model:
    require:
    - precision=single ^parallelio+pnetcdf
    - "%gcc"
  mpich:
    require:
    - mpich pmi=pmi2 device=ch4 netmod=ofi +slurm
  nvhpc:
    require:
    - "target=aarch64"
  openfoam:
    require:
     - openfoam ^scotch@6.0.9
  openmpi:
    variants: ~atomics ~cuda ~cxx ~cxx_exceptions ~internal-hwloc ~java +legacylaunchers ~lustre ~memchecker +pmi +romio ~singularity +vt +wrapper-rpath fabrics=ofi schedulers=slurm
    require: '@4:'
  # Palace does not build correctly with armpl until https://github.com/awslabs/palace/pull/207 is merged into a version.
  # palace:
  #   require:
  #     - one_of: ["palace cxxflags=\"-include cstdint\" ^fmt@9.1.0"]
  pmix:
    require: "pmix@3:"
  quantum-espresso:
    require:
    - quantum-espresso@6.6 %gcc ^armpl-gcc
  slurm:
    buildable: false
    externals:
    - prefix: /opt/slurm
      spec: slurm@22.05.8 +pmix
    require:
    - "+pmix"
  all:
    require:
    - "%gcc"
    providers:
      blas: [armpl-gcc, openblas]
      fftw-api: [armpl-gcc, fftw]
      lapack: [armpl-gcc, openblas]
      mpi: [openmpi, mpich]
      scalapack: [netlib-scalapack]
    permissions:
      read: world
      write: user

```
I then run `spack install -v quantum-espresso@6.6 %gcc ^armpl-gcc` and, at the last package, when installing quantum-espresso, I get the error:

Maintainers of gmake: @haampie 
Maintainers of quantum-espresso: @bellenlau  @tgorni  @ye-luo

### Error message

<details><summary>Error message</summary>

<pre>

==> [2025-05-04-21:51:08.740085] '/home/software/spack/[padded-to-256-chars]/linux-neoverse_v1/gmake-4.4.1-cdbeeqrqmvemud6jqg4fkxromfmjoo6m/bin/make' '-j1' 'all' 'epw'
Makefile:9: make.inc: No such file or directory
make: *** No rule to make target 'make.inc'.  Stop.

</pre></details>

### Information on your system

* **Spack:** 1.0.0.dev0
* **Python:** 3.7.16
* **Platform:** linux-amzn2-neoverse_v1

### Additional information

As I am working on ArmPL, I initially thought it was a problem with the version of ArmPL so I used two different versions but the same problem appeared.

I have tried to insert in the armpl-gcc/package.py the explicity dependency of armpl-gcc on gmake@4.4 but for some reason the gmake 4.4.1 version was still downloaded and installed.

[spack-build-out.txt](https://github.com/user-attachments/files/20065033/spack-build-out.txt)

[build-env.txt](https://github.com/user-attachments/files/20065039/build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate
