### ISSUE TITLE
openmpi 4.1.6/8 with ucx (1.18)  broken

### ISSUE THREAD

**Issue by prudhomm** [LLNL/spack#50366]
### Steps to reproduce

```console
spack install openmpi@:4 fabrics=cma,ucx
```

compilation is fine

### Error message

when executing a mpi application one gets 

```console
symbol lookup error: /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/ucx-1.18.0-emtjpi3lgzhj5kooqe4onxod5wjk62iv/lib/ucx/libuct_rocm.so.0: undefined symbol: hsa_init
```

`ldd` gives :
```console
ldd  /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/ucx-1.18.0-emtjpi3lgzhj5kooqe4onxod5wjk62iv/lib/ucx/libuct_rocm.so
        linux-vdso.so.1 (0x00007ffe715cb000)
        libuct.so.0 => /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/ucx-1.18.0-emtjpi3lgzhj5kooqe4onxod5wjk62iv/lib/libuct.so.0 (0x00007f7f29f84000)
        libucs.so.0 => /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/ucx-1.18.0-emtjpi3lgzhj5kooqe4onxod5wjk62iv/lib/libucs.so.0 (0x00007f7f29f0f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f29ca2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7f29bb7000)
        libucm.so.0 => /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/ucx-1.18.0-emtjpi3lgzhj5kooqe4onxod5wjk62iv/lib/libucm.so.0 (0x00007f7f29b97000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7f29fe8000)
```

`nm` gives:
```console
nm  /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/ucx-1.18.0-emtjpi3lgzhj5kooqe4onxod5wjk62iv/lib/ucx/libuct_rocm.so | grep hsa
                 U hsa_agent_get_info
                 U hsa_amd_agent_iterate_memory_pools
                 U hsa_amd_agent_memory_pool_get_info
                 U hsa_amd_agents_allow_access
                 U hsa_amd_ipc_memory_attach
                 U hsa_amd_ipc_memory_create
                 U hsa_amd_ipc_memory_detach
                 U hsa_amd_memory_async_copy
                 U hsa_amd_memory_lock
                 U hsa_amd_memory_pool_allocate
                 U hsa_amd_memory_pool_free
                 U hsa_amd_memory_pool_get_info
                 U hsa_amd_memory_unlock
                 U hsa_amd_pointer_info
                 U hsa_init
                 U hsa_iterate_agents
                 U hsa_signal_create
                 U hsa_signal_destroy
                 U hsa_signal_load_scacquire
                 U hsa_signal_store_screlease
                 U hsa_signal_wait_scacquire
0000000000009110 t uct_rocm_hsa_agent_callback
0000000000009080 t uct_rocm_hsa_pool_callback
```

`nm` on `libhsa-runtime` gives
```console
nm /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/hsa-rocr-dev-6.1.2-ulk6r53varidw3hwri4yttx3bi42dkhz/lib/libhsa-runtime64.so | grep hsa_init
```

this makes openmpi with ucx broken

### Information on your system

* **Spack:** 1.0.0.dev0 (97edcb5acc364c8c61936d86ffb63c84c1d56af0)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-zen2

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by prudhomm** [comment]
here is the spec
```
[+]      ^openmpi@4.1.6+atomics~cuda~cxx~cxx_exceptions~debug~gpfs~internal-hwloc~internal-libevent~internal-pmix~ipv6~java~lustre~memchecker~openshmem~orterunprefix+romio+rsh~singularity~static~two_level_namespace+vt+wrapper-rpath build_system=autotools fabrics:=cma,ucx romio-filesystem:=none schedulers:=none arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libevent@2.1.12+openssl build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^numactl@2.0.18 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^openssh@9.9p1+gssapi build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^krb5@1.21.3+shared build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^perl@5.40.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]              ^berkeley-db@18.1.40+cxx~docs+stl build_system=autotools patches:=26090f4,b231fcc arch=linux-ubuntu22.04-x86_64_v3
[+]          ^pmix@5.0.5~munge~python build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^ucx@1.18.0~assertions~backtrace_detail~cma~cuda~dc~debug~dm+examples~gdrcopy~gtest~ib_hw_tm~java~knem~logging~mlx5_dv+openmp+optimizations~parameter_checking+pic~rc~rdmacm+rocm+thread_multiple~ucg~ud~verbs~vfs~xpmem build_system=autotools libs:=shared,static opt=3 simd:=auto arch=linux-ubuntu22.04-x86_64_v3
[+]              ^hip@6.1.2~asan~cuda~ipo+rocm build_system=cmake build_type=Release generator=make patches:=1f65dfe,6bbe83b arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^comgr@6.1.2~asan~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^rocm-cmake@6.1.2~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^hipcc@6.1.2~ipo build_system=cmake build_type=Release generator=make patches:=f9d4d87 arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^hipify-clang@6.1.2~asan~ipo build_system=cmake build_type=Release generator=make patches:=3ad49b7 arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^hsakmt-roct@6.1.2~asan~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^libdrm@2.4.124~docs~strip build_system=meson buildtype=release default_library:=shared arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^perl-file-which@1.27 build_system=perl arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^perl-uri-encode@1.1.1 build_system=perl arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^perl-module-build@0.4234 build_system=perl arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^py-cppheaderparser@2.7.4 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^rocm-core@6.1.2~asan~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^rocminfo@6.1.2~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^roctracer-dev-api@6.1.2 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]              ^hsa-rocr-dev@6.1.2~asan+image~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^elfutils@0.192~debuginfod+exeprefix+nls build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^xxd-standalone@8.2.1201 build_system=makefile arch=linux-ubuntu22.04-x86_64_v3

```

@hppritcha what do you think ?

**Comment by prudhomm** [comment]
same problem with openmpi 5

```console
> mpirun -np 4 ./hello
./hello: symbol lookup error: /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/ucx-1.18.0-zrlmvxu2r2aoiqoyf3i4mmeol5mtnid3/lib/ucx/libuct_rocm.so.0: undefined symbol: hsa_init
./hello: symbol lookup error: /nvme0/prudhomm/Devel/feelpp.spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-x86_64_v3/ucx-1.18.0-zrlmvxu2r2aoiqoyf3i4mmeol5mtnid3/lib/ucx/libuct_rocm.so.0: undefined symbol: hsa_init
--------------------------------------------------------------------------
prterun detected that one or more processes exited with non-zero status,
thus causing the job to be terminated. The first process to do so was:

   Process name: [prterun-gaya-3242561@1,0]
   Exit code:    127
--------------------------------------------------------------------------
```

here is the environment to reproduce
```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  config:
    target: x86_64_v3
    install_tree:
      padded_length: 128
  packages:
    gcc:
      externals:
      - spec: gcc@9.5.0 languages=c,fortran
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-9
            fortran: /usr/bin/gfortran-9
      - spec: gcc@11.4.0 languages='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran
      - spec: gcc@12.3.0 languages='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-12
            cxx: /usr/bin/g++-12
            fortran: /usr/bin/gfortran-12
    llvm:
      externals:
      - spec: llvm@14.0.0+clang~lld+lldb
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/clang
            cxx: /usr/bin/clang++
    mpi:
      require: ['openmpi fabrics=cma,ucx']
  definitions:
  - targets: [target=x86_64_v3]
  - compilers: ['gcc@11:']
  - mpis: [mpi]
  specs:
  - matrix:
    - [$compilers]
    - [$targets]
  - matrix:
    - [$mpis]
    - [^ucx +rocm +cma +thread_multiple]
    - [$%compilers]
    - [$targets]
  view: true
  concretizer:
    targets:
      granularity: generic
      host_compatible: true
    unify: true
```

**Comment by prudhomm** [comment]
same thing with ucx 1.17

**Comment by prudhomm** [comment]
everything is fine with `ucx~rocm`

here is a working environment.

```
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  config:
    target: x86_64_v3
    install_tree:
      padded_length: 128
  packages:
    gcc:
      externals:
      - spec: gcc@9.5.0 languages=c,fortran
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-9
            fortran: /usr/bin/gfortran-9
      - spec: gcc@11.4.0 languages='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran
      - spec: gcc@12.3.0 languages='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-12
            cxx: /usr/bin/g++-12
            fortran: /usr/bin/gfortran-12
    llvm:
      externals:
      - spec: llvm@14.0.0+clang~lld+lldb
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/clang
            cxx: /usr/bin/clang++
    mpi:
      require: ['openmpi fabrics=cma,ucx']
  definitions:
  - targets: [target=x86_64_v3]
  - compilers: ['gcc@11']
  - mpis: [mpi]
  specs:
  - matrix:
    - [$compilers]
    - [$targets]
  - matrix:
    - [$mpis]
    - [^ucx@1.18 ~rocm +cma +thread_multiple]
    - [$%compilers]
#    - [$targets]
  view: true
  concretizer:
    targets:
      granularity: generic
      host_compatible: true
    unify: true
```
