### ISSUE TITLE
Definition being evaluated before merging scopes/includes

### ISSUE THREAD

**Issue by kftsehk** [LLNL/spack#50422]
### Steps to reproduce

site scope: `includes.yaml` to include a yaml

```yaml
definitions:
  - a:
    - key=value
```

env scope: `spack.yaml`

```yaml
spack:
  definitions:
    - b:
      - matrix:
        - - key2=value2
          - key3=value3 
        - - $a
```

However ref to `a` works if directly used in `spack::spec`, not via definition.

### Error message

Error: SpecList 'b' refers to named list 'a' which does not appear in its reference dict.

### Information on your system

* **Spack:** 1.0.0.dev0 (6d181b733084e9f7931566da8ae005e9a54724d7)
* **Python:** 3.11.7
* **Platform:** linux-rocky9-zen4

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
