### ISSUE TITLE
`spack install` intermittently disables `tty` echo

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#50842]
### Steps to reproduce

`spack install` after #47590 intermittently causes the terminal to detach, requiring the user to run `reset` on their CLI.

This can happen on success and on failure, according to @haampie and @alalazo.

### Information on your system

Linux and macos machines

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I can reproduce this one almost reliably on:

* **Spack:** 1.0.0.dev0 (c0a9cde834a52f603efcd0fcb588266d3f766888)
* **Builtin repo:** d0f19f1cfca29b7fae679da18b740d8c0f2e1771
* **Python:** 3.13.0
* **Platform:** linux-ubuntu20.04-icelake

If I use the following environment:
```yaml
spack:
  specs:
  - gcc@14+binutils
  - gcc@15+binutils
  - intel-oneapi-compilers
  concretizer:
    unify: false
    reuse: true
  config:
    install_tree:
      root: ./store

    ccache: true
  view: ./view

  mirrors:
    develop-2025-05-25-developer-tools-x86_64_v3-linux-gnu: https://binaries.spack.io/develop-2025-05-25/developer-tools-x86_64_v3-linux-gnu
    local: file:///home/culpo/opt/compilers/mirror
  packages:
    c:
      require: gcc@10
    cxx:
      require: gcc@10
    'gcc:':
      externals:
      - spec: gcc@10.5.0 languages='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-10
            cxx: /usr/bin/g++-10
            fortran: /usr/bin/gfortran-10
```
and try to:
```console
$ spack concretize -f --fresh
$ spack -v install -p 4 -j 4
```
