### ISSUE TITLE
Improving composability of package `require` and `prefer`

### ISSUE THREAD

**Issue by vbrunini** [LLNL/spack#50879]
Currently any default package requirements specified via the `packages: all: require:` configuration are discarded for individual packages that have any requirements as described in the documentation ( https://spack.readthedocs.io/en/latest/packages_yaml.html#setting-default-requirements ). This makes it extremely error-prone (and IMO counterintuitive) to try and apply requirements across all packages in an environment, which is a common need particularly for variants like `target`, `cuda`, `cuda_arch`, `rocm`, `amdgpu_target`. For example consider an environment where you need to require `target=x86_64` for a build that works across a variety of machines, and also want to require specific versions of several packages.
```
packages:
  all:
    require:
    - target=x86_64
    foo:
      require: foo@1.0
    bar:
      require: bar@2.0
    baz:
      require: baz@3.0
```
would be very convenient, but doesn't work. Instead you must:
```
packages:
  all:
    require:
    - target=x86_64
    foo:
      require: foo@1.0  target=x86_64
    bar:
      require: bar@2.0 target=x86_64
    baz:
      require: baz@3.0 target=x86_64
```

This is an even larger obstacle when trying to use include files to manage multiple environments where some package settings are common to all and others are environment specific. For example consider an application wanting to specify a common set of versions of certain dependencies across multiple environments, and then each individual environment specifying the CPU & GPU targets corresponding to a particular platform. Ideally we could have a `base/packages.yaml` containing:
```
packages:
    foo:
      require: foo@1.0
    bar:
      require: bar@2.0
    baz:
      require: baz@3.0
```
and then individual platform environments could do things like:
```
include:
  base/packages.yaml
packages:
  all:
    require:
    - target=x86_64
```
for an x86_64 build
```
include:
  base/packages.yaml
packages:
  all:
    require:
    - +cuda cuda_arch=90
```
for a Cuda H100 build,
```
include:
  base/packages.yaml
packages:
  all:
    require:
    - +rocm amdgpu_target=gfx942
```
for an MI300 build, etc. However this is not possible since the default requirements in the individual environment builds don't apply to any of the packages with requirements in the `base/packages.yaml`.

A proposed solution would be for default requirements to also apply to packages with their own requirements unless the package specific requirements are for the same variants as the default.

**Comment by vanderwb** [comment]
I would really appreciate this functionality as well, though it would still be nice to completely throw out the global requirements if desired - maybe as another use of the `::` override syntax.

**Comment by psakievich** [comment]
Discussed in the TSC today. We are going to put this as a stretch goal for 1.2. 1.2 is already looking crowded though so we might need to bump to 1.3. Note this also applies to `prefer`.

@alalazo proposed a new config key something like

```yaml
packages:
  all:
    # overide/default
    require: []
    prefer: []
  always:
    # composes with packages
    require: []
    prefer: []
```

**Comment by sebrowne** [comment]
@alalazo @psakievich to be clear the intended behavior is for a `package`-level require/prefer to take precedence over the `all` in its complete form (current behavior), and for it to compose with the values in `always`, but with the `package`-level values taking precedence for a conflicting variant/version/etc in that `always` case?  Or do I have it backwards?

**Comment by psakievich** [comment]
@sebrowne yes `all` would remain unmodified as a "default" that gets over-ridden by per package. `always` would be the composable. I think we'd want a conflict between a package specific config and `always` to error and not take precedent? Or maybe warn and take precedent? That part has not been determined. My thought is make it an error, and give the per package a way to override always for an intentional conflict.  A counter argument could be a 3 tier system that mirrors other patterns we have in config:
 
1. default: starting point for unspecified packages (`all`)
2. prefer: always apply each term unless a direct conflict exists with the package
3. require: always apply, hard error on conflict
 
I'd love to remap/rename and do something like this but it would be very breaking throughout the code base. The `always` idea came up because it could be added by extension.

**Comment by sebrowne** [comment]
@psakievich  I was speaking with @becker33 today and his preference is to go with the following approach:

`all` value is composed with package-specific by default
`::` on the `require` or `prefer` in the package-specific section would explicitly override (current behavior) instead of composing.  Both approaches appear to be relatively simple to implement (I have a working prototype of Greg's proposal currently).

Benefit of doing it Greg's way is that it probably makes the most sense long-term (IMO), but does change behavior right now in a way that may negatively impact users relying on the existing override behavior.

If the requirements conflict, the concretizer will error appropriately (tested), and that should work with either approach.

**Comment by psakievich** [comment]
Sounds really good to me. I think we floated something similar to this in stand up one time but there was a concern about it being a breaking change to config. I agree this is a better form factor. We might need to discuss at stand up and/or the TSC.

**Comment by alalazo** [comment]
> :: on the require or prefer in the package-specific section would explicitly override (current behavior) instead of composing. 

I think it's worse:
1. No other configuration scope works like that, so we are giving `packages:<pkg>:` its own special merge semantics that involves `packages:all`
2. It's breaking over current behavior, which is probably established at this point
3. We can't `::` in two different scopes for a package-specific section and expect the result to be merged, since that `::` means override from this scope

I have to say that thinking about the proposed semantics it's not clear to me what e.g. is the result if I have:
```yaml
packages:
 all:
    require: [<1>]
 pkg::
    require: [<2>]
```
in a lower priority scope and:
```yaml
packages:
 all:
    require: [<3>]
 pkg:
    require: [<4>]
```
in a higher priority scope.
