### ISSUE TITLE
Cannot concretize a matrix using the `xl` compiler

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#50916]
### Steps to reproduce

Trying to concretize an environment with new toolchain feature, I am getting some unexpected behavior:
```yaml
  definitions:
  - compilers:
    - '%clang-16'
  - radiuss-projects:
    - umpire +cuda ^cuda@11.8.0+allow-unsupported-compilers

  specs:
  - matrix:
    - [$radiuss-projects]
    - [$compilers]
```
gives
```console
==> Error: failed to concretize `umpire+cuda %[when='%c'] c=clang@16.0.6+clang~lld~lldb %[when='%cxx'] cxx=clang@16.0.6+clang~lld~lldb %[when='%fortran'] fortran=xl@16.1.1.14+r ^cuda@11.8.0+allow-unsupported-compilers` for the following reasons:
     1. Cannot select a single "version" for package "xl"
     2. Attempted to use external for 'xl' which does not satisfy any configured external spec version
     3. Attempted to use external for 'xl' which does not satisfy any configured external spec
     4. Cannot satisfy 'xl@16.1.1.14'
```
and for more context, the toolchain is defined as follows:
```yaml
  toolchains:
    clang-16:
    - spec: '%[virtuals=c]llvm@16.0.6+clang~lld~lldb'
      when: '%c'
    - spec: '%[virtuals=cxx]llvm@16.0.6+clang~lld~lldb'
      when: '%cxx'
    - spec: '%[virtuals=fortran]xl@16.1.1.14+r'
      when: '%fortran'
```

### Error message

Minimal reproducer on Livermore Computing `lassen` system with spack@develop
```yaml
spack:
  concretizer:
    reuse: false
    unify: false
  view: false

  packages:
    all:
      require:
      - target=power9le
      - spec: ^blt%clang
        when: '%clang ^blt'
    xl:
      externals:
      - spec: xl@16.1.1.14+r
        prefix: /usr/tce/packages/xl/xl-2023.06.28
        extra_attributes:
          compilers:
            fortran: /usr/tce/packages/xl/xl-2023.06.28/bin/xlf_r
          flags: {}
          environment: {}
          extra_rpaths: []
    llvm:
      externals:
      - spec: llvm@16.0.6+clang~lld~lldb
        prefix: /usr/tce/packages/clang/clang-16.0.6
        extra_attributes:
          compilers:
            c: /usr/tce/packages/clang/clang-16.0.6/bin/clang
            cxx: /usr/tce/packages/clang/clang-16.0.6/bin/clang++
          flags: {}
          environment: {}
          extra_rpaths: []
    cmake:
      version: [3.23.1]
      buildable: false
      externals:
      - spec: cmake@3.23.1
        prefix: /usr/tce/packages/cmake/cmake-3.23.1
    cuda:
      version: [11.8.0]
      buildable: false
      externals:
      - spec: cuda@11.8.0+allow-unsupported-compilers
        prefix: /usr/tce/packages/cuda/cuda-11.8.0

  toolchains:
    clang-16:
    - spec: '%[virtuals=c]llvm@16.0.6+clang~lld~lldb'
      when: '%c'
    - spec: '%[virtuals=cxx]llvm@16.0.6+clang~lld~lldb'
      when: '%cxx'
    - spec: '%[virtuals=fortran]xl@16.1.1.14+r'
      when: '%fortran'

  config:
    install_tree:
      root: /usr/workspace/bernede1/install-v1/test
      padded_length: 128
      projections:
        all: '{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    'build_stage:':
    - $user_cache_path/stage
    test_stage: $user_cache_path/test
    misc_cache: $user_cache_path/misc
    flags:
      keep_werror: all

  # Does not work
  definitions:
  - compilers:
    - '%clang-16'
      #- '%clang-16-ibm'
  - radiuss-projects:
    - umpire +cuda ^cuda@11.8.0+allow-unsupported-compilers
      #- raja +cuda ^cuda@11.8.0+allow-unsupported-compilers

  specs:
  - matrix:
    - [$radiuss-projects]
    - [$compilers]

  # Works
  #  specs:
  #    - umpire +cuda ^cuda@11.8.0+allow-unsupported-compilers %clang-16
```

### Information on your system

* **Spack:** 1.0.0.dev0 (59009109c6cad03c8269b4552a2e413d2bbfcf66)
* **Builtin repo:** 0ddfd9aa5ea7ae720d3744b5e010928ff3a21eaa
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adrienbernede** [comment]
@alalazo here is the issue, I can provide a full debug report tomorrow.

**Comment by alalazo** [comment]
Thanks for the issue. As already reported in Slack, the claim that the first spec:
```
umpire +cuda ^cuda@11.8.0+allow-unsupported-compilers %clang-16
```
is equivalent to the matrix is wrong, so I'll be editing the issue in that respect. 

The matrix should expand to:
```
umpire +cuda %clang-16 ^cuda@11.8.0+allow-unsupported-compilers 
```
cause we reduce by the `Spec.constrain` operation.

**Comment by alalazo** [comment]
If you run:
```console
$ spack -d concretize -f
```
do you have a line similar to:
```
==> [2025-06-20-10:53:10.277449] [spack.solver.asp]: not considering xl@=16.1.1.14+r as external, since it's a non-working compiler
```
in your output?

**Comment by adrienbernede** [comment]
Re: matrix and spec not equivalent.
I understand your statement and the underlying reason. Now, it is made clear in the high impact changes notice that we should put the compiler at the end of the spec to avoid potential issues.
My question then is: How can I ensure equivalence between a list of specs and a matrix taking the above into consideration ?

Re: "not considering compiler..."
I noticed it in both the failing and the passing debug logs, indeed. I thought it was just related to the other line:
`==> [2025-06-20-06:32:33.543782] the spec xl@16.1.1.14/veq35f425gvovikoitsprxp7ndyw6zwh does not provide a C compiler.`

**Comment by alalazo** [comment]
> Now, it is made clear in the high impact changes notice that we should put the compiler at the end of the spec to avoid potential issues.

The way we reduce specs in matrices didn't change. Even in v0.23 (with compiler being node attributes) that would have been the case. So, not a high-impact change for v1.0 I guess.

---

The underlying problem here is that `xl` was probed and not considered to be "functional", therefore it was not used during concretization. I still need to check whether we probe `xl` correctly, but in any case the error message is way off in telling users what is the real cause of the unsat concretization. 

Still trying to think how to deal with this and produce a sane error message for users who care about those compilers, without annoying users that happen to have non-working compilers in their configs, but don't use them. Best idea I got so far is to emit a fact into the solve, to signal that the compiler is non-functional, and have a more targeted error message.

**Comment by adrienbernede** [comment]
> The way we reduce specs in matrices didn't change. Even in v0.23 (with compiler being node attributes) that would have been the case. So, not a high-impact change for v1.0 I guess.

My bad: I was extending `High-impact changes for v1.0 point 1.i. to dependencies while it applies to variants only`. No problem specifying the spec `umpire +cuda %clang-16 ^cuda@11.8.0+allow-unsupported-compilers` (I was wrongfully anticipating an error).

Now I see that I can reproduce the failure with the matrix equivalent spec and I understand the error better: since cuda does not require a fortran compiler, the concretizer alleviates the constraint on using 'xl'.

With that in mind, the main issue I have is that the concretizer "hallucinates" fortran support by the clang compiler,

```console
 -   xkva44l  umpire@2025.03.0~asan~backtrace+c+cuda~dev_benchmarks~device_alloc~deviceconst~examples+fmt_header_only~fortran~ipc_shmem~ipo~mpi~mpi3_shmem~numa~omptarget~openmp~rocm~sanitizer_tests~shared~sqlite_experimental~tools~werror build_system=cmake build_type=Release commit=1ed0669c57f041baa1f1070693991c3a7a43e7ee cuda_arch:=none generator=make tests=none arch=linux-rhel7-power9le %c,cxx,fortran=clang@16.0.6
```

while my config is, I think, clear about that not being the case:

```yaml
       externals:
       - spec: llvm@16.0.6+clang~lld~lldb
         prefix: /usr/tce/packages/clang/clang-16.0.6
         extra_attributes:
           compilers:
             c: /usr/tce/packages/clang/clang-16.0.6/bin/clang
             cxx: /usr/tce/packages/clang/clang-16.0.6/bin/clang++
           flags: {}
           environment: {}
           extra_rpaths: []
```

Regarding XL probing:
If I were to specify a full XL compiler, with c and cxx support, Spack would fail earlier complaining that libcxx was not found for XL compiler.
I suspect that by only creating a fortran compiler, I worked around that, but still fail at "probing".

Is probing assessing the compiler capability for all languages or only C ? Can I prevent probing on languages I don’t want to support with a given compiler ?

**Comment by adrienbernede** [comment]
For the records, here is a working pre-v1 compiler compiler config that I am trying to port over to v1:
```yaml
 - compiler:
     spec: clang@=16.0.6
     paths:
       cc: /usr/tce/packages/clang/clang-16.0.6/bin/clang
       cxx: /usr/tce/packages/clang/clang-16.0.6/bin/clang++
       fc: /usr/tce/packages/xl/xl-2023.06.28/bin/xlf2003_r
       f77: /usr/tce/packages/xl/xl-2023.06.28/bin/xlf_r
     flags: {}
     operating_system: rhel7
     target: ppc64le
     modules: []
     environment: {}
     extra_rpaths: []
```
hence the configuration in the reproducer above.
