### ISSUE TITLE
How do I set extra_rpaths for MPI compile wrappers?

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#5137]
I'm trying to build parmetis%intel@17.0.1 ^openmpi@2.1.1.  The compiler and MPI are external packages.

`compiler.yaml` uses `extra_rpaths` to allow Intel/17.0.1 to work:

```
compilers:
- compiler:
    environment: {}
    extra_rpaths: [/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/lib/intel64]
    flags: {}
    modules:
      - intel/17.0.1
    operating_system: rhel7
    paths:
      cc: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/icc
      cxx: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/icpc
      f77: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/ifort
      fc: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/ifort
    spec: intel@17.0.1
    target: x86_64
```

`packages.yaml` specifies MPI as an external package:

```
packages:
  openmpi:
    version: [2.1.1]
    paths:
       openmpi@2.1.1%intel@17.0.1 arch=linux-rhel7-x86_64: /usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1
    buildable: False
```

Setting the `extra_rpaths` in `compiler.yaml` allows me to build metis, but parmetis fails with: `The C compiler "/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1/bin/mpicc" is not able to compile a simple test program.`

Adding `--dirty` to the spack install command allows the build to work.  The only significance between the clean and dirty build is the removal of `LD_LIBRARY_PATH` for the clean build, Is there a way to tell spack to use `extra_rpaths` when the compiler is an MPI compiler wrapper?  Or is there a way to set extra environment/rpath information in `packages.yaml`?  

Any suggestions (other than always using `--dirty`) for solving this?

**Comment by skosukhin** [comment]
Your external openmpi has a set of its own wrappers. Those wrappers are configured to run one of the compilers on your system. Among other things those wrappers should add all necessary -L flags when they call the real compiler. Now, when you build a package that needs openmpi (it does not matter if it's external or not) with Spack, it calls 'setup_dependent_environment' from openmpi package. The method sets OMPI_CC and OMPI_CXX environment variables to override openmpi wrapper's configuration to make the wrappers call Spack's wrapper (./lib/spack/env/cc). The latter should convert all -L flags that openmpi wrappers set to rpaths and pass them to the actual compiler.

That's how I understand this at least. The first step to solve your problem could be to check if everything really works like I described =)
The second step is to make sure that openmpi compiler wrappers really add all necessary -L flags because it's basically a matter of correct openmpi installation.

**Comment by KineticTheory** [comment]
@skosukhin Thank you for the description of spack's logic for mpi compile wrappers.

Our MPI compiler wrappers include the OpenMPI library paths, but do not provide paths for the Intel compiler.

```
$ mpicc --showme
/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/icc \
-I/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1/include \
-pthread -Wl,-rpath -Wl,/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1/lib \
-L/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1/lib -lmpi
```

However, the Intel compiler will only work if `-Xlinker -rpath=/usr/projects/hpcsoft/toss3/common/gcc/5.3.0/lib64:/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/lib/intel64` is also included on the link line.  For non-mpi packages, spack adds this option via the `extra_rpaths` option specified in `compilers.yaml`.

Any thoughts on how to insert those extra rpaths when using `mpicc`?

**Comment by skosukhin** [comment]
@KineticTheory if your external openmpi takes into account OMPI_CC and OMPI_CXX environment variables, which Spack sets, Spack's wrapper is called instead of the real compiler. And the wrapper should add the extra_rpaths if they are specified in compilers.yaml. I mean, if everything is configured correctly, spack's wrapper is called, whether the package you build depends on mpi or not. And the wrapper adds rpath flags.

Keep in mind that if some of the packages that parmetis depends on were built before you added rpaths to compiler.yaml (with --dirty, for example) you have to reinstall them, because they don't contain rpaths, which prevents linker from finding the necessary libraries

**Comment by KineticTheory** [comment]
@skosukhin  I am using openmpi-2.1.1 and `mpicc` respects the variables `OMPI_CC`.  This means

`/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1/bin/mpicc` is translated as

```
/usr/projects/jayenne/devs/kellyt/build/spack.llnl/lib/spack/env/intel/icc \
-I/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1/include \
-pthread \
-Wl,-rpath -Wl,/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1/lib \
-L/usr/projects/hpcsoft/toss3/snow/openmpi/2.1.1-intel-17.0.1/lib \
-lmpi
```

I guess I don't understand why cmake claims that the compiler `is not able to compile a simple test program.`  My best guess is that `extra_rpaths` set in my `compilers.yaml` isn't processed when `CMAKE_C_COMPILER` is `mpicc`,  

Do you know how to tell spack or cmake to dump more information about the flags used when CMake tests for a working compiler?

**Comment by KineticTheory** [comment]
The following *hack* to add `LD_LIBRARY_PATH` back into the environment seems to allow `mpicc` to work:

`compilers.yaml`

```
compilers:
- compiler:
    environment:
      set:
        LD_LIBRARY_PATH : /usr/projects/hpcsoft/toss3/common/gcc/5.3.0/lib64:/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/lib/intel64
    extra_rpaths:
      - /usr/projects/hpcsoft/toss3/common/gcc/5.3.0/lib64
      - /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/lib/intel64
    flags: {}
    modules:
      - intel/17.0.1
    operating_system: rhel7
    paths:
      cc: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/icc
      cxx: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/icpc
      f77: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/ifort
      fc: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/bin/intel64/ifort
    spec: intel@17.0.1
    target: x86_64
```

Does this look reasonable?  Should this be required?
