### ISSUE TITLE
boost fails to compile on OS-X

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#570]
```
Usage: /Users/davydden/spack/opt/spack/darwin-x86_64/clang-7.0.2-apple/libtool-2.4.6-ycntnovcsaknvnlqht5nhtpwlwbj5rxw/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
```
That could be related to libtool compiled by spack.

**Comment by eschnett** [comment]
See <https://github.com/LLNL/spack/pull/563>. Look for `boost/package.py` there.

Yes, the problem is that one of Boost's dependencies pulls in GNU libtool, whereas Boost expects to find the Darwin libtool on OS X. Both libtools are incompatible (of course!). My pull request above has a solution.

There is another problem with Boost, since it doesn't properly set the `install_name_path`. My patch addresses this as well.

**Comment by davydden** [comment]
cool! thanks for the prompt reply.

**Comment by davydden** [comment]
this fixed it for me 
```
packages:
  all:
    compiler: [clang, gcc]
  libtool:
    paths:
      libtool@2.4.6%clang@7.0.2-apple: /usr/ # libtool is in /usr/bin/
    buildable: False # never build libtool
```
I then reinstalled `OpenMPI` with its dependencies and now `./spack install boost +mpi` builds fine.
