### ISSUE TITLE
external packages for virtual dependencies (blas/mpi)

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#571]
The documentation of external packages has an example
```
packages:
   openmpi:
      paths:
         openmpi@1.4.3%gcc@4.4.7=chaos_5_x86_64_ib: /opt/openmpi-1.4.3
```
For the life of mine I could not make it work to set up system's blas/lapack and avoid Spack trying to install `openblas` as a dependency for `hypre`. I tried something along these lines
```
packages:
  blas:
    paths:
      blas: <system>
    buildable: False
  lapack:
    paths:
      lapack: <system>
    buildable: False
```
which would be my naïve interpretation of the documentation.

~~Btw, the `hypre`'s blas-related configure is not correct as it assumes blas-lapack names as `blas` and `lapack`~~
```
configure_args = [
                "--prefix=%s" % prefix,
                "--with-lapack-libs=lapack",
                "--with-lapack-lib-dirs=%s/lib" % lapack_dir,
                "--with-blas-libs=blas",
                "--with-blas-lib-dirs=%s/lib" % blas_dir]
```
~~which is certainly not the case for `openblas`.~~
I see that you symlink `libbas` and `liblapack` when installing openblas. However, this is not a flexible enough solution for things like MKL.  It goes back to the issue https://github.com/LLNL/spack/issues/234 .

**Comment by davydden** [comment]
p.s. on `osx` `libblas` and `liblapack` can be found in `/usr/lib`.

**Comment by citibeth** [comment]
I use the following in my ``packages.yaml``.  The place you tell it for system-installed stuff doesn't (usually) have to be correct, since builds will find it anyway.  Hope this helps.

```
    openssl:
        paths:
            openssl@system: /usr
        buildable: False
```

**Comment by davydden** [comment]
@citibeth do you do that for MPI or blas/lapack? I was not able to figure it out for these two.

**Comment by citibeth** [comment]
How about:
```
    openblas:
        paths:
            openblas@system: /usr
        buildable: False
    openmpi:
        paths:
            openmpi@system: /usr
        buildable: False
    all:
        compiler: [gcc@4.9.3]
        providers:
            mpi: [openmpi]
            blas: [openblas]
            lapack: [openblas]

```

**Comment by davydden** [comment]
@citibeth thanks! I will give this a try, looks reasonable. In my original attempts I was missing `providers` section and a couple of other details.

**Comment by alalazo** [comment]
@davydden Just a wild guess, but I think the problem is that you are using a `virtual ` package as it was a concrete one:
```
blas:
    paths:
      blas: <system>
    buildable: False
```
should read : 
```
<concrete-package>:
    paths:
      <concrete-package>@<version>: <system>
    buildable: False
```
where `concrete-package` means that a `package.py` for that name exists in a repo. For instance it could be `openblas` or `netlib-lapack` depending on what you have installed.

**Comment by tgamblin** [comment]
The syntax is a bit more complicated as a result, but note that it lets you pick providers per package if you want to.  e.g. you can say this:

```
all:
    providers:
        mpi: [openmpi]
```

Or you can separate your preferences for different dependents:

```
concrete-app1:
    providers:
        mpi: [openmpi]
concrete-app2:
    providers:
        mpi: [mpich]
```

Maybe not useful all the time, but that's why this goes under `all` and not just under an `mpi` entry in the file.
