### ISSUE TITLE
gcc 7.2.0 version is not detected correctly on Ubuntu 16.04

### ISSUE THREAD

**Issue by RezaLTM** [LLNL/spack#5778]
`spack compiler find` does not pick the GCC7.2.0 version correctly:
```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu16.04
    paths:
      cc: /usr/bin/gcc-7
      cxx: /usr/bin/g++-7
      f77: null
      fc: null
    spec: gcc@7
    target: x86_64
```
however
```
$ gcc-7 --version
gcc-7 (Ubuntu 7.2.0-1ubuntu1~16.04) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Spack picked up gcc 5 and 6 perfectly fine though:
```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu16.04
    paths:
      cc: /usr/bin/gcc-6
      cxx: /usr/bin/g++-6
      f77: /usr/bin/gfortran-6
      fc: /usr/bin/gfortran-6
    spec: gcc@6.3.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu16.04
    paths:
      cc: /usr/bin/gcc-5
      cxx: /usr/bin/g++-5
      f77: /usr/bin/gfortran-5
      fc: /usr/bin/gfortran-5
    spec: gcc@5.4.1
    target: x86_64g
```
