### ISSUE TITLE
ld not checked for compatibility before use

### ISSUE THREAD

**Issue by wrwilliams** [LLNL/spack#5794]
There are two sources for this issue I've uncovered:

1) The gcc package will use the system ld even when that ld is incompatible. Found with gcc 5.4.0 and the RHEL6 system ld on cab.
2) elfutils provides an ld which is incompatible with the binutils ld. Definitely triggers when elfutils is a build dependency; there may be other ways to get that ld to be used inappropriately.

As an added note, using the +binutils variant on gcc does resolve this, but it was far from obvious from the documentation that that was the solution.

**Comment by tgamblin** [comment]
Is this something we need to fix in the compiler wrappers or something that we should fix in the `gcc` package?

I think having more intelligence around compiler detection would be extremely useful.  Is there an automated check we can do to test whether `ld` is compatible?

**Comment by wrwilliams** [comment]
I'm not sure whether the proper fix is in the wrappers or the package. The baseline configure/cmake tests of "build a simple executable" were failing for me, and I was also able to reproduce with a trivial gcc test.c -o test using the wrapped environment (main that returns zero).

**Comment by mplegendre** [comment]
I don't know of an automated check for ld/gcc compatibility.  A subset of compatible versions can be found here: http://wiki.osdev.org/Cross-Compiler_Successful_Builds . We could encode this table into the gcc package.

Right now a spack-built gcc can float between different linkers depending on the environment.  This floating is what caused @wrwilliams dyninst builds to start picking up the ld in elfutils and break. We could look into binding a spack-built gcc with the linker when gcc is built with via modifying its spec file.

We should also look into breaking up the ld package.  Perhaps put the elfutils ld utility into a default-off variant.

**Comment by wrwilliams** [comment]
Having thought about this more, I'm afraid the answer to "where should this get checked"? is both.

The package should pass the "does this compile a trivial executable?" test in the environment used by `module load`. The spack wrapper should pass the same test in the wrapped environment (which as I understand it may not be the same). The first test should be something that runs as part of any compiler package, either as part of that compiler's `make check` or as a separate step. The second test should be run as a precondition for adding something to the spack compilers list via `spack compiler find`.

Does this make sense? Package tests for external/module usability, wrapper tests for internal usability.

**Comment by ajw1980** [comment]
This is an old bug, but still problematic in other ways, too. For software that tries to use CPU optimized instructions available in a newer gcc but uses an old binutils, you get errors about no such instruction:

  >> 5822    ../kernel/x86_64/dgemm_kernel_4x8_haswell.S:1759: Error: no such instruction: `vpermpd $ 0xb1,%ymm0,%ymm0'

That is compiling openblas on centos 6x with gcc 7.3.0. There is no specific binutils dependency, so it just uses the system binutils.

**Comment by ajw1980** [comment]
Building binutils and the bin directory from it to the path in compilers.yaml seems to work around this problem without having to add binutils to a bunch of package dependencies:

```
- compiler:
    environment:
      prepend-path:
        PATH: /shared/spack/opt/spack/linux-centos6-x86_64/gcc-8.3.0/binutils-2.31.1-4vewtvcy67dqkbyfjwpj5zqs5zw7aqnj/bin
    extra_rpaths: []
    flags:
      cflags: -O2 -s
      cxxflags: -O2 -s
      cppflags: -O2 -s
    modules: []
    operating_system: centos6
    paths:
      cc: /shared/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/gcc-8.3.0-prs437plxlysdwly4mwrsq5alzpdfwe4/bin/gcc
      cxx: /shared/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/gcc-8.3.0-prs437plxlysdwly4mwrsq5alzpdfwe4/bin/g++
      f77: /shared/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/gcc-8.3.0-prs437plxlysdwly4mwrsq5alzpdfwe4/bin/gfortran
      fc: /shared/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/gcc-8.3.0-prs437plxlysdwly4mwrsq5alzpdfwe4/bin/gfortran
    spec: gcc@8.3.0
    target: x86_64
```
I tried adding binutils in the modules section, but that seemed to break compiling. 

It seems like gcc and binutils should somehow be tightly coupled for compiler selection. For packages without an explicit binutils dependency, you are just relying on whatever linker is in your path (probably the OS version).
