### ISSUE TITLE
spack package (regcm) is 4 times slower than the hand-built one

### ISSUE THREAD

**Issue by bebosudo** [LLNL/spack#9957]
I'm using spack to build regcm (f602fd8ea4ee5f4e759e15627a67468294cc11e5).
Comparing the spack-built with the hand-built version, the spack one is more than 4 times slower.

### Steps to reproduce the issue

I've installed regcm with spack with the following dependencies:
```console
# spack spec -Il regcm  ^hdf5/nbrjtor ^zlib/vonxam4 ^netcdf/7th67uc ^netcdf-fortran/vmbrd6f
Input spec
--------------------------------
...

Concretized
--------------------------------
[+]  6oggmvo  regcm@4.7.1-SVN6884%intel@18.0.3~debug extension= ~profile~singleprecision arch=linux-centos7-x86_64 
[+]  nbrjtor      ^hdf5@1.10.3%intel@18.0.3~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-centos7-x86_64 
[+]  35ityo3          ^intel-parallel-studio@cluster.2018.3%intel@18.0.3~advisor~clck+daal~gdb~ilp64~inspector+ipp~itac+mkl+mpi~newdtags+rpath+shared+tbb threads=none ~vtune arch=linux-centos7-x86_64 
[+]  vonxam4          ^zlib@1.2.11%intel@18.0.3+optimize+pic+shared arch=linux-centos7-x86_64 
[+]  7th67uc      ^netcdf@4.6.1%intel@18.0.3~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+pic+shared arch=linux-centos7-x86_64 
[+]  vmbrd6f      ^netcdf-fortran@4.4.4%intel@18.0.3+pic arch=linux-centos7-x86_64 
```

Then I've taken the same dependencies to manually build the package, using also the same configure line (I've only added those CC and FC flags because the configure was choosing the system versions; maybe sourcing the intel shell setup script could help):
```console
$ module load intel-parallel-studio/cluster.2018.3/intel-18.0.3-35ityo3 \
              hdf5/1.10.3/intel-18.0.3-nbrjtor \
              netcdf/4.6.1/intel-18.0.3-7th67uc \
              netcdf-fortran/4.4.4/intel-18.0.3-vmbrd6f \
              zlib/1.2.11/intel-18.0.3-vonxam4

$ './configure' 'LDLIBS=-lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lz' \
    '--prefix=/path/to/dir/regcm-4.7.1-SVN6884-intel-parallel-studio'  \
    '--enable-shared' \
    'MPIFC=/opt/cluster/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-parallel-studio-cluster.2018.3-35ityo3mbfsfhgvtlodnkslmaryj5ezp/compilers_and_libraries_2018.3.222/linux/mpi/intel64/bin/mpiifort' \
    CC=icc FC=ifort
```

Running the application causes the time difference in the output files:
```console
$ diff runs_regcm-4.7.1-SVN6884_intel-by_hand_again_1d/submit.o205 runs_regcm-4.7.1-SVN6884_intel-parallel-studio_again_1d/submit.o203

<  : Total elapsed seconds of run :    96.5349999959545     
---
>  : Total elapsed seconds of run :    401.504635012146     
```
The computation performed is the same, because the output files are the same.

I can provide you some input files to regcm, to test this behavior.
The RegCM version used isn't released yet, but it can be obtained as specified in #9934.

### Information on your system

Centos 7, spack git-version 3557b6e14903c02bcc0a19b34c8b4c64f3d05ca3 (but I can update it anytime)

`compilers.yaml`:
```yaml
compilers:
... other compilers

- compiler:
    target:     x86_64
    operating_system:   centos7
    modules:    []
    spec:       intel@18.0.3
    paths:
      cc: /opt/cluster/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-parallel-studio-cluster.2018.3-35ityo3mbfsfhgvtlodnkslmaryj5ezp/compilers_and_libraries_2018.3.222/linux/bin/intel64/icc
      cxx: /opt/cluster/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-parallel-studio-cluster.2018.3-35ityo3mbfsfhgvtlodnkslmaryj5ezp/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc
      f77: /opt/cluster/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-parallel-studio-cluster.2018.3-35ityo3mbfsfhgvtlodnkslmaryj5ezp/compilers_and_libraries_2018.3.222/linux/bin/intel64/ifort
      fc: /opt/cluster/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-parallel-studio-cluster.2018.3-35ityo3mbfsfhgvtlodnkslmaryj5ezp/compilers_and_libraries_2018.3.222/linux/bin/intel64/ifort
    extra_rpaths:
      - /opt/cluster/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/intel-parallel-studio-cluster.2018.3-35ityo3mbfsfhgvtlodnkslmaryj5ezp/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64/
```

This seems to be related to #6712, even though the performance drop is greater than those 30% reported.

Any idea why are spack executables so slow?

**Comment by jrood-nrel** [comment]
Have you tried adding something like this to `compilers.yaml`?
```
    flags:
      cflags: -O2 -mtune=native -march=native
      cxxflags: -O2 -mtune=native -march=native
      fflags: -O2 -mtune=native -march=native
```

**Comment by bebosudo** [comment]
Hi @jrood-nrel, thanks for your reply.

I discovered that somehow the intel module inserts a `-O3` at compilation time.

I added a:
```yaml
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
```
to `compilers.yaml`, as suggested by Jon, and now the application compiled with spack matches the performance of the application compiled without spack.

Could it be worthwhile to add a line in the docs?
https://spack.readthedocs.io/en/latest/tutorial_configuration.html?highlight=compilers.yaml#compiler-flags
